---
permalink: audit/accessing-audit-log-file.html 
sidebar: sidebar 
keywords: storagegrid, audit, log, log file, access, accessing 
summary: Die Revisionsfreigabe enthält die aktive audit.log-Datei und alle komprimierten Audit-Log-Dateien. Sie können über die Befehlszeile des Admin-Knotens direkt auf Audit-Log-Dateien zugreifen. 
---
= Zugriff auf die Audit-Log-Datei
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Audit-Freigabe enthält die aktive `audit.log` Datei und alle komprimierten Audit-Log-Dateien. Sie können über die Befehlszeile des Admin-Knotens direkt auf Audit-Log-Dateien zugreifen.

Der `audit.log` Die Datei bleibt leer, es sei denn, Sie konfigurieren StorageGRID für *Admin-Knoten/lokale Knoten* oder *Admin-Knoten und externen Syslog-Server*. Weitere Informationen finden Sie unter link:../monitor/configure-log-management.html#select-log-location["Protokollspeicherort auswählen"] .

.Bevor Sie beginnen
* Sie haben link:../admin/admin-group-permissions.html["Bestimmte Zugriffsberechtigungen"].
* Sie müssen über die `Passwords.txt` Datei verfügen.
* Sie müssen die IP-Adresse eines Admin-Knotens kennen.


.Schritte
. Melden Sie sich bei einem Admin-Knoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.



. Gehen Sie zu dem Verzeichnis, das die Audit-Log-Dateien enthält:
+
`cd  /var/local/audit/export/`

. Sehen Sie sich die aktuelle oder gespeicherte Audit-Protokolldatei nach Bedarf an.

