---
permalink: audit/client-write-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client write, OVWR, SDEL, SPOS, SPUT, SUPD, WDEL, WPUT, S3 
summary: Audit-Meldungen für den Client-Schreibvorgang werden protokolliert, wenn eine S3-Client-Anwendung eine Anforderung zum Erstellen oder Ändern eines Objekts stellt. 
---
= Audit-Meldungen des Clients schreiben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Audit-Meldungen für den Client-Schreibvorgang werden protokolliert, wenn eine S3-Client-Anwendung eine Anforderung zum Erstellen oder Ändern eines Objekts stellt.

[cols="1a,3a,1a,1a"]
|===
| Codieren | Beschreibung | Verwendet von | Siehe 


 a| 
OVWR
 a| 
Objekt-Überschreiben: Protokolliert eine Transaktion, um ein Objekt mit einem anderen Objekt zu überschreiben.
 a| 
S3-Client
 a| 
link:ovwr-object-overwrite.html["OVWR: Objektüberschreibung"]



 a| 
SDEL
 a| 
S3 DELETE: Protokolliert eine erfolgreiche Transaktion zum Löschen eines Objekts oder Buckets.

*Hinweis:* Wenn die Transaktion auf einer Unterressource ausgeführt wird, enthält die Audit-Nachricht das Feld S3SR.
 a| 
S3-Client
 a| 
link:sdel-s3-delete.html["SDEL: S3 LÖSCHEN"]



 a| 
SPOS
 a| 
S3 POST: Protokolliert eine erfolgreiche Transaktion zur Wiederherstellung eines Objekts aus AWS Glacier Storage in einem Cloud Storage Pool.
 a| 
S3-Client
 a| 
link:spos-s3-post.html["SPOS: S3-BEITRAG"]



 a| 
SPUT
 a| 
S3 PUT: Protokolliert eine erfolgreiche Transaktion, um ein neues Objekt oder einen neuen Bucket zu erstellen.

*Hinweis:* Wenn die Transaktion auf einer Unterressource ausgeführt wird, enthält die Audit-Nachricht das Feld S3SR.
 a| 
S3-Client
 a| 
link:sput-s3-put.html["SPUT: S3 PUT"]



 a| 
SUPD
 a| 
Aktualisierte S3 Metadaten: Protokolliert eine erfolgreiche Transaktion zur Aktualisierung der Metadaten für ein vorhandenes Objekt oder Bucket.
 a| 
S3-Client
 a| 
link:supd-s3-metadata-updated.html["SUPD: S3-Metadaten wurden aktualisiert"]

|===