---
permalink: audit/ebdl-empty-bucket-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, EBDL, Empty Bucket Delete 
summary: 'Der ILM-Scanner hat ein Objekt in einem Bucket gelöscht, das alle Objekte löscht (und einen leeren Bucket-Vorgang durchgeführt).' 
---
= EBDL: Leerer Bucket löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der ILM-Scanner hat ein Objekt in einem Bucket gelöscht, das alle Objekte löscht (und einen leeren Bucket-Vorgang durchgeführt).

[cols="1a,1a,4a"]
|===
| Codieren | Feld | Beschreibung 


 a| 
CSIZ
 a| 
Objektgröße
 a| 
Die Größe des Objekts in Byte.



 a| 
PFAD
 a| 
S3-Bucket/Key
 a| 
Der S3-Bucket-Name und der S3-Schlüsselname.



 a| 
SEGC
 a| 
Container-UUID
 a| 
UUID des Containers für das segmentierte Objekt. Dieser Wert ist nur verfügbar, wenn das Objekt segmentiert ist.



 a| 
UUID
 a| 
Universell Eindeutige Kennung
 a| 
Die Kennung des Objekts im StorageGRID System.



 a| 
RSLT
 a| 
Ergebnis des Löschvorgangs
 a| 
Das Ergebnis eines Ereignisses, Prozesses oder einer Transaktion. Wenn für eine Nachricht nicht relevant ist, WIRD KEINE verwendet, sondern SUCS, damit die Nachricht nicht versehentlich gefiltert wird.

|===