---
permalink: audit/sadd-security-audit-disable.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SADD, Security Audit Disable 
summary: 'Diese Meldung gibt an, dass der ursprüngliche Dienst \(Node ID\) die Protokollierung von Überwachungsmeldungen deaktiviert hat; Audit-Meldungen werden nicht mehr erfasst oder geliefert.' 
---
= SADD: Security Audit deaktiviert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Meldung gibt an, dass der ursprüngliche Dienst (Node-ID) die Protokollierung der Überwachungsmeldungen deaktiviert hat; Audit-Meldungen werden nicht mehr erfasst oder geliefert.

[cols="1a,1a,4a"]
|===
| Codieren | Feld | Beschreibung 


 a| 
AETM
 a| 
Methode Aktivieren
 a| 
Die Methode, mit der das Audit deaktiviert wird.



 a| 
AEUN
 a| 
Benutzername
 a| 
Der Benutzername, der den Befehl zum Deaktivieren der Revisionsprotokollierung ausgeführt hat.



 a| 
RSLT
 a| 
Ergebnis
 a| 
Dieses Feld hat den Wert NONE. RSLT ist ein Pflichtfeld, ist aber für diese Nachricht nicht relevant. KEINE wird verwendet, anstatt SUCS, damit diese Meldung nicht gefiltert wird.

|===
Die Meldung besagt, dass die Protokollierung zuvor aktiviert, aber jetzt deaktiviert wurde. Dies wird normalerweise nur während der Massenaufnahme verwendet, um die Systemperformance zu verbessern. Nach der Massenaktivität ist das Auditing wiederhergestellt (SADE) und die Möglichkeit, das Auditing zu deaktivieren, wird dann dauerhaft gesperrt.
