---
permalink: audit/sade-security-audit-enable.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SADE, Security Audit Enable 
summary: 'Diese Meldung signalisiert, dass der Ursprungsdienst (Knoten-ID) die Protokollierung von Audit-Meldungen wiederhergestellt hat. StorageGRID erfasst und übermittelt wieder Audit-Meldungen.' 
---
= SADE-Revisionsprotokollmeldung zur Aktivierung der Sicherheitsüberwachung in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Meldung signalisiert, dass der Ursprungsdienst (Knoten-ID) die Protokollierung von Audit-Meldungen wiederhergestellt hat. StorageGRID erfasst und übermittelt wieder Audit-Meldungen.

[cols="1a,1a,4a"]
|===
| Codieren | Feld | Beschreibung 


 a| 
AETM
 a| 
Methode Aktivieren
 a| 
Die Methode, die zum Aktivieren des Audits verwendet wird.



 a| 
AEUN
 a| 
Benutzername
 a| 
Der Benutzername, der den Befehl zum Aktivieren der Audit-Protokollierung ausgeführt hat.



 a| 
RSLT
 a| 
Ergebnis
 a| 
Dieses Feld hat den Wert NONE. RSLT ist ein Pflichtfeld, ist aber für diese Nachricht nicht relevant. KEINE wird verwendet, anstatt SUCS, damit diese Meldung nicht gefiltert wird.

|===
Die Nachricht bedeutet, dass die Protokollierung vorher deaktiviert (SADD) war, aber jetzt wiederhergestellt wurde. Dies wird in der Regel nur während der Massenaufnahme verwendet, um die Systemperformance zu verbessern. Nach der Massenaktivität ist das Auditing wiederhergestellt und die Möglichkeit, das Auditing zu deaktivieren, wird dann dauerhaft gesperrt.
