---
permalink: audit/scmt-object-store-commit.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SCMT, Object Store Commit 
summary: 'Grid-Inhalte werden erst bereitgestellt oder als gespeichert erkannt, nachdem sie bereitgestellt wurden \ (was bedeutet, dass sie dauerhaft gespeichert wurden\). Dauerhaft gespeicherte Inhalte wurden vollständig auf Festplatte geschrieben und haben entsprechende Integritätsprüfungen bestanden. Diese Meldung wird ausgegeben, wenn ein Inhaltsblock auf den Speicher gesetzt wird.' 
---
= SCMT: Objekt Store Commit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid-Inhalte werden erst dann zur Verfügung gestellt oder als gespeichert erkannt, wenn sie bereitgestellt wurden (was bedeutet, dass sie dauerhaft gespeichert wurden). Dauerhaft gespeicherte Inhalte wurden vollständig auf Festplatte geschrieben und haben entsprechende Integritätsprüfungen bestanden. Diese Meldung wird ausgegeben, wenn ein Inhaltsblock auf den Speicher gesetzt wird.

[cols="1a,1a,4a"]
|===
| Codieren | Feld | Beschreibung 


 a| 
CBID
 a| 
Kennung Für Inhaltsblock
 a| 
Die eindeutige Kennung des Inhaltsblocks, der zu permanentem Speicher verpflichtet ist.



 a| 
RSLT
 a| 
Ergebniscode
 a| 
Status zum Zeitpunkt, zu dem das Objekt auf Festplatte gespeichert wurde:

SUCS: Objekt erfolgreich gespeichert.

|===
Diese Meldung bedeutet, dass ein bestimmter Inhaltsblock vollständig gespeichert und überprüft wurde und nun angefordert werden kann. Er kann zur Nachverfolgung des Datenflusses im System eingesetzt werden.
