---
permalink: audit/svru-object-store-verify-unknown.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SVRU, Object Store Verify Unknown 
summary: Die Speicherkomponente des LDR-Dienstes scannt kontinuierlich alle Kopien replizierter Objektdaten im Objektspeicher. Diese Meldung wird ausgegeben, wenn eine unbekannte oder unerwartete Kopie replizierter Objektdaten im Objektspeicher erkannt und in das Quarantäneverzeichnis verschoben wird. 
---
= SVRU: Objektspeicher überprüfen Unbekannt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Storage-Komponente des LDR-Service scannt kontinuierlich alle Kopien replizierter Objektdaten im Objektspeicher. Diese Meldung wird ausgegeben, wenn eine unbekannte oder unerwartete Kopie replizierter Objektdaten im Objektspeicher erkannt und in das Quarantäneverzeichnis verschoben wird.

[cols="1a,1a,4a"]
|===
| Codieren | Feld | Beschreibung 


 a| 
FPTH
 a| 
Dateipfad
 a| 
Dateipfad der unerwarteten Objektkopie.



 a| 
RSLT
 a| 
Ergebnis
 a| 
Dieses Feld hat den Wert 'NEIN'. RSLT ist ein Pflichtfeld, ist aber für diese Nachricht nicht relevant. „KEINE“ wird anstelle von „UCS“ verwendet, damit diese Meldung nicht gefiltert wird.

|===

NOTE: Die Meldung SVRU: Object Store Verify Unknown Audit sollte genau überwacht werden. Es bedeutet, dass im Objektspeicher unerwartete Kopien von Objektdaten erkannt wurden. Diese Situation sollte sofort untersucht werden, um festzustellen, wie diese Kopien erstellt wurden, da sie auf drohende Hardwareausfälle hinweisen können.
