---
permalink: audit/syst-node-stopping.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYST, Node Stopping 
summary: 'Wird ein Dienst ordnungsgemäß beendet, wird diese Meldung generiert, um anzuzeigen, dass die Beendigung angefordert wurde und der Dienst seine Beendigungssequenz eingeleitet hat. Mit SYST kann festgestellt werden, ob die Beendigung angefordert wurde, bevor der Dienst neu gestartet wird (im Gegensatz zu SYSD, das typischerweise nach dem Neustart des Dienstes gesendet wird).' 
---
= SYST-Revisionsprotokollmeldung für das Anhalten eines Knotens in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wird ein Dienst ordnungsgemäß beendet, wird diese Meldung generiert, um anzuzeigen, dass die Beendigung angefordert wurde und der Dienst seine Beendigungssequenz eingeleitet hat. Mit SYST kann festgestellt werden, ob die Beendigung angefordert wurde, bevor der Dienst neu gestartet wird (im Gegensatz zu SYSD, das typischerweise nach dem Neustart des Dienstes gesendet wird).

[cols="1a,1a,4a"]
|===
| Codieren | Feld | Beschreibung 


 a| 
RSLT
 a| 
Herunterfahren Reinigen
 a| 
Die Art des Herunterfahrens:

SAUCS: Das System wurde sauber abgeschaltet.

|===
Die Meldung gibt nicht an, ob der Host-Server angehalten wird, sondern nur der Reporting-Service. Der RSLT-Code einer SYST-Meldung kann nicht auf ein „schmutziges“ Herunterfahren hinweisen, da die Meldung nur durch „sauberes“ Herunterfahren generiert wird.
