---
permalink: audit/syst-node-stopping.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYST, Node Stopping 
summary: 'Wenn ein Dienst ordnungsgemäß angehalten wird, wird diese Meldung generiert, um anzugeben, dass das Herunterfahren angefordert wurde und dass der Dienst seine Abschaltsequenz initiiert hat. SYST kann verwendet werden, um festzustellen, ob das Herunterfahren angefordert wurde, bevor der Dienst neu gestartet wird \ (im Gegensatz zu SYSD, die normalerweise nach dem Neustart des Dienstes gesendet wird.\)' 
---
= SYST: Knoten wird angehalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Dienst ordnungsgemäß angehalten wird, wird diese Meldung generiert, um anzugeben, dass das Herunterfahren angefordert wurde und dass der Dienst seine Abschaltsequenz initiiert hat. SYST kann verwendet werden, um festzustellen, ob das Herunterfahren angefordert wurde, bevor der Dienst neu gestartet wird (im Gegensatz zu SYSD, das normalerweise nach dem Neustart des Dienstes gesendet wird).

[cols="1a,1a,4a"]
|===
| Codieren | Feld | Beschreibung 


 a| 
RSLT
 a| 
Herunterfahren Reinigen
 a| 
Die Art des Herunterfahrens:

SAUCS: Das System wurde sauber abgeschaltet.

|===
Die Meldung gibt nicht an, ob der Host-Server angehalten wird, sondern nur der Reporting-Service. Der RSLT-Code einer SYST-Meldung kann nicht auf ein „schmutziges“ Herunterfahren hinweisen, da die Meldung nur durch „sauberes“ Herunterfahren generiert wird.
