---
permalink: swnodes/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create rhel ubuntu or debian node configuration files, port, remap, port remap 
summary: Konfigurationsdateien für die Nodes sind kleine Textdateien, die die Informationen liefern, die der StorageGRID-Host-Service benötigt, um einen Node zu starten und eine Verbindung zu den entsprechenden Netzwerk- und Block-Storage-Ressourcen herzustellen. Die Node-Konfigurationsdateien werden für virtuelle Nodes verwendet und nicht für Appliance-Nodes verwendet. 
---
= Erstellen von Knotenkonfigurationsdateien für Linux-Bereitstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Konfigurationsdateien für die Nodes sind kleine Textdateien, die die Informationen liefern, die der StorageGRID-Host-Service benötigt, um einen Node zu starten und eine Verbindung zu den entsprechenden Netzwerk- und Block-Storage-Ressourcen herzustellen. Node-Konfigurationsdateien werden für virtuelle Nodes verwendet und nicht für Appliance-Nodes verwendet.


NOTE: „Linux“ bezieht sich auf eine RHEL-, Ubuntu- oder Debian-Bereitstellung.  Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool (IMT)"^] .



== Speicherort für Node-Konfigurationsdateien

Platzieren Sie die Konfigurationsdatei für jeden StorageGRID-Knoten im `/etc/storagegrid/nodes` Verzeichnis auf dem Host, auf dem der Node ausgeführt werden soll. Wenn Sie beispielsweise einen Admin-Knoten, einen Gateway-Knoten und einen Storage-Knoten auf Hosta ausführen möchten, müssen Sie drei Knoten-Konfigurationsdateien in auf Hosta platzieren `/etc/storagegrid/nodes`.

Sie können die Konfigurationsdateien direkt auf jedem Host mit einem Texteditor, wie z. B. vim oder nano, erstellen oder sie an einem anderen Ort erstellen und auf jeden Host verschieben.



== Benennung von Node-Konfigurationsdateien

Die Namen der Konfigurationsdateien sind erheblich. Das Format ist `node-name.conf`, wobei `node-name` es sich um einen Namen handelt, den Sie dem Knoten zuweisen. Dieser Name wird im StorageGRID Installer angezeigt und wird für Knotenwartungsvorgänge, z. B. für Node-Migration, verwendet.

Node-Namen müssen folgende Bedingungen erfüllen:

* Muss eindeutig sein
* Nur mit einem Buchstaben beginnen
* Kann die Zeichen A bis Z und a bis z enthalten
* Kann die Zahlen 0 bis 9 enthalten
* Kann eine oder mehrere Bindestriche enthalten (-)
* Darf nicht mehr als 32 Zeichen enthalten, ohne die `.conf` Erweiterung


Alle Dateien, `/etc/storagegrid/nodes` die diese Namenskonventionen nicht befolgen, werden vom Host-Service nicht geparst.

Wenn das Grid eine Topologie mit mehreren Standorten geplant ist, ist unter Umständen ein typisches Benennungsschema für Node möglich:

`site-nodetype-nodenumber.conf`

Sie können beispielsweise für den ersten Admin-Node in Data Center 1 und `dc2-sn3.conf` für den dritten Storage-Node in Data Center 2 verwenden `dc1-adm1.conf`. Sie können jedoch ein beliebiges Schema verwenden, das Sie mögen, solange alle Knotennamen den Benennungsregeln folgen.



== Inhalt einer Node-Konfigurationsdatei

Eine Konfigurationsdatei enthält Schlüssel-/Wertpaare mit einem Schlüssel und einem Wert pro Zeile. Befolgen Sie für jedes Schlüssel-/Wertepaar die folgenden Regeln:

* Der Schlüssel und der Wert müssen durch ein Gleichheitszeichen (`=`und ein optionales Leerzeichen getrennt werden.
* Die Schlüssel können keine Leerzeichen enthalten.
* Die Werte können eingebettete Leerzeichen enthalten.
* Führende oder nachgestellte Leerzeichen werden ignoriert.


Die folgende Tabelle definiert die Werte für alle unterstützten Schlüssel. Jeder Schlüssel hat eine der folgenden Bezeichnungen:

* *Erforderlich*: Erforderlich für jeden Knoten oder für die angegebenen Knotentypen
* *Best Practice*: Optional, obwohl empfohlen
* *Optional*: Optional für alle Knoten




=== Admin-Netzwerkschlüssel



==== ADMIN_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Grid-Netzwerk-IPv4-Adresse des Admin-Knotens, den Sie zum Installieren des Linux-basierten Knotens verwenden möchten.  Verwenden Sie zur Wiederherstellung die IP des primären Admin-Knotens, falls verfügbar. Andernfalls verwenden Sie die IP eines nicht primären Admin-Knotens.  Wenn Sie diesen Parameter weglassen, versucht der Knoten, mithilfe von mDNS einen primären Admin-Knoten zu ermitteln.

link:how-grid-nodes-discover-primary-admin-node.html["Ermitteln der primären Admin-Node durch Grid-Nodes"]

*Hinweis*: Dieser Wert wird auf dem primären Admin-Node ignoriert und kann möglicherweise nicht verwendet werden.
 a| 
Best Practices in sich

|===


==== ADMIN_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
DHCP, STATISCH ODER DEAKTIVIERT
 a| 
Optional

|===


==== ADMIN_NETWORK_ESL

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Kommagetrennte Liste von Subnetzen in CIDR-Notation, mit denen dieser Knoten über das Admin-Netzwerk-Gateway kommunizieren soll.

Beispiel: `172.16.0.0/21,172.17.0.0/21`
 a| 
Optional

|===


==== ADMIN_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse des lokalen Admin-Netzwerk-Gateways für diesen Node. Muss sich im Subnetz befinden, das von ADMIN_NETWORK_IP und ADMIN_NETWORK_MASKE definiert ist. Dieser Wert wird bei DHCP-konfigurierten Netzwerken ignoriert.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn `ADMIN_NETWORK_ESL` angegeben ist. Andernfalls optional.

|===


==== ADMIN_NETWORK_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse dieses Knotens im Admin-Netzwerk. Dieser Schlüssel ist nur erforderlich, wenn ADMIN_NETWORK_CONFIG = STATIC; geben Sie ihn nicht für andere Werte an.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn ADMIN_NETWORK_CONFIG = STATISCH.

Andernfalls optional.

|===


==== ADMIN_NETWORK_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die MAC-Adresse für die Admin-Netzwerkschnittstelle im Container.

Dieses Feld ist optional. Wenn keine Angabe erfolgt, wird automatisch eine MAC-Adresse generiert.

Muss aus 6 Hexadezimalziffern bestehen, die durch Doppelpunkte getrennt werden.

Beispiel: `b2:9c:02:c2:27:10`
 a| 
Optional

|===


==== ADMIN_NETWORK_MASKE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Netmask für diesen Node im Admin-Netzwerk. Geben Sie diesen Schlüssel an, wenn ADMIN_NETWORK_CONFIG = STATISCH ist; geben Sie ihn nicht für andere Werte an.

Beispiele:

`255.255.255.0`

`255.255.248.0`
 a| 
Erforderlich, wenn ADMIN_NETWORK_IP angegeben und ADMIN_NETWORK_CONFIG = STATISCH ist.

Andernfalls optional.

|===


==== ADMIN_NETWORK_MTU

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die maximale Übertragungseinheit (MTU) für diesen Knoten im Admin-Netzwerk. Geben Sie nicht an, ob ADMIN_NETWORK_CONFIG = DHCP. Wenn angegeben, muss der Wert zwischen 1280 und 9216 liegen. Wenn weggelassen, wird 1500 verwendet.

Wenn Sie Jumbo Frames verwenden möchten, setzen Sie die MTU auf einen für Jumbo Frames geeigneten Wert, z. B. 9000. Behalten Sie andernfalls den Standardwert bei.

*WICHTIG*: Der MTU-Wert des Netzwerks muss mit dem Wert übereinstimmen, der auf dem Switch-Port konfiguriert ist, an den der Knoten angeschlossen ist. Andernfalls können Probleme mit der Netzwerkleistung oder Paketverluste auftreten.

Beispiele:

`1500`

`8192`
 a| 
Optional

|===


==== ADMIN_NETWORK_TARGET

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name des Host-Geräts, das Sie für den Administratornetzwerkzugriff durch den StorageGRID-Knoten verwenden werden. Es werden nur Namen von Netzwerkschnittstellen unterstützt. Normalerweise verwenden Sie einen anderen Schnittstellennamen als den für GRID_NETWORK_TARGET oder CLIENT_NETWORK_TARGET angegebenen Namen.

*Hinweis*: Verwenden Sie keine Bond- oder Bridge-Geräte als Netzwerkziel. Konfigurieren Sie entweder ein VLAN (oder eine andere virtuelle Schnittstelle) auf dem Bond-Gerät oder verwenden Sie ein Bridge- und virtuelles Ethernet-Paar (veth).

*Best Practice*:Geben Sie einen Wert an, selbst wenn dieser Knoten zunächst keine Admin-Netzwerk-IP-Adresse hat. Anschließend können Sie später eine Admin-Netzwerk-IP-Adresse hinzufügen, ohne den Node auf dem Host neu konfigurieren zu müssen.

Beispiele:

`bond0.1002`

`ens256`
 a| 
Best Practices in sich

|===


==== ADMIN_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Schnittstelle (Dies ist der einzige unterstützte Wert.)
 a| 
Optional

|===


==== ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Richtig oder falsch

Setzen Sie den Schlüssel auf „true“, damit der StorageGRID-Container die MAC-Adresse der Host-Zielschnittstelle im Admin-Netzwerk verwendet.

*Best Practice:* in Netzwerken, in denen der promiskuious-Modus erforderlich wäre, verwenden Sie stattdessen DEN ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC-Schlüssel.

Weitere Informationen zum MAC-Klonen für Linux finden Sie unterlink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen"]
 a| 
Best Practices in sich

|===


==== ADMIN_ROLLE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Primär oder nicht primär

Dieser Schlüssel ist nur erforderlich, wenn NODE_TYPE = VM_Admin_Node; geben Sie ihn nicht für andere Node-Typen an.
 a| 
Erforderlich, wenn NODE_TYPE = VM_Admin_Node

Andernfalls optional.

|===


=== Sperren von Geräteschlüsseln



==== BLOCK_DEVICE_AUDIT_LOGS

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der Sonderdatei für Blockgeräte, die dieser Node für die persistente Speicherung von Prüfprotokollen verwendet.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
Erforderlich für Nodes mit NODE_TYPE = VM_Admin_Node. Geben Sie sie nicht für andere Node-Typen an.

|===


==== BLOCK_DEVICE_RANGEDB_NNN

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der Sonderdatei für das Blockgerät wird dieser Node für den persistenten Objekt-Storage verwenden. Dieser Schlüssel ist nur für Knoten mit NODE_TYPE = VM_Storage_Node erforderlich; geben Sie ihn nicht für andere Knotentypen an.

Es ist nur BLOCK_DEVICE_RANGEDB_000 erforderlich; der Rest ist optional. Das für BLOCK_DEVICE_RANGEDB_000 angegebene Blockgerät muss mindestens 4 TB betragen; die anderen können kleiner sein.

Lassen Sie keine Lücken. Wenn Sie BLOCK_DEVICE_RANGEDB_005 angeben, müssen Sie auch BLOCK_DEVICE_RANGEDB_004 angeben.

*Hinweis*: Zur Kompatibilität mit bestehenden Bereitstellungen werden zweistellige Schlüssel für aktualisierte Knoten unterstützt.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
Erforderlich:

BLOCK_DEVICE_RANGEDB_000

Optional:

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== BLOCK_DEVICE_TABLES

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der Sonderdatei des Blockgerätes, die dieser Knoten für die dauerhafte Speicherung von Datenbanktabellen verwendet. Dieser Schlüssel ist nur für Nodes mit NODE_TYPE = VM_Admin_Node erforderlich; geben Sie ihn nicht für andere Node-Typen an.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
Erforderlich

|===


==== BLOCK_DEVICE_VAR_LOCAL

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Pfad und Name der speziellen Datei des Blockgeräts, die dieser Knoten für seinen persistenten Speicher verwendet `/var/local`.

Beispiele:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
Erforderlich

|===


=== Netzwerkschlüssel des Clients



==== CLIENT_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
DHCP, STATISCH ODER DEAKTIVIERT
 a| 
Optional

|===


==== CLIENT_NETWORK_GATEWAY

[cols="4a,2a"]
|===


 a| 
Wert
 a| 
Bezeichnung



 a| 
IPv4-Adresse des lokalen Client-Netzwerk-Gateways für diesen Node, der sich im Subnetz befinden muss, das durch CLIENT_NETWORK_IP und CLIENT_NETWORK_MASK definiert ist. Dieser Wert wird bei DHCP-konfigurierten Netzwerken ignoriert.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Optional

|===


==== CLIENT_NETWORK_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse dieses Knotens im Client-Netzwerk.

Dieser Schlüssel ist nur erforderlich, wenn CLIENT_NETWORK_CONFIG = STATIC; geben Sie ihn nicht für andere Werte an.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn CLIENT_NETWORK_CONFIG = STATISCH

Andernfalls optional.

|===


==== CLIENT_NETWORK_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die MAC-Adresse für die Client-Netzwerkschnittstelle im Container.

Dieses Feld ist optional. Wenn keine Angabe erfolgt, wird automatisch eine MAC-Adresse generiert.

Muss aus 6 Hexadezimalziffern bestehen, die durch Doppelpunkte getrennt werden.

Beispiel: `b2:9c:02:c2:27:20`
 a| 
Optional

|===


==== CLIENT_NETWORK_MASK

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Netzmaske für diesen Knoten im Client-Netzwerk.

Geben Sie diesen Schlüssel an, wenn CLIENT_NETWORK_CONFIG = STATISCH ist; geben Sie ihn nicht für andere Werte an.

Beispiele:

`255.255.255.0`

`255.255.248.0`
 a| 
Erforderlich, wenn CLIENT_NETWORK_IP angegeben und CLIENT_NETWORK_CONFIG = STATISCH ist

Andernfalls optional.

|===


==== CLIENT_NETWORK_MTU

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die maximale Übertragungseinheit (MTU) für diesen Knoten im Client-Netzwerk. Geben Sie nicht an, ob CLIENT_NETWORK_CONFIG = DHCP. Wenn angegeben, muss der Wert zwischen 1280 und 9216 liegen. Wenn weggelassen, wird 1500 verwendet.

Wenn Sie Jumbo Frames verwenden möchten, setzen Sie die MTU auf einen für Jumbo Frames geeigneten Wert, z. B. 9000. Behalten Sie andernfalls den Standardwert bei.

*WICHTIG*: Der MTU-Wert des Netzwerks muss mit dem Wert übereinstimmen, der auf dem Switch-Port konfiguriert ist, an den der Knoten angeschlossen ist. Andernfalls können Probleme mit der Netzwerkleistung oder Paketverluste auftreten.

Beispiele:

`1500`

`8192`
 a| 
Optional

|===


==== CLIENT_NETWORK_TARGET

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name des Host-Geräts, das Sie für den Zugriff auf das Client-Netzwerk durch den StorageGRID-Knoten verwenden werden. Es werden nur Namen von Netzwerkschnittstellen unterstützt. Normalerweise verwenden Sie einen anderen Schnittstellennamen als der für GRID_NETWORK_TARGET oder ADMIN_NETWORK_TARGET angegeben wurde.

*Hinweis*: Verwenden Sie keine Bond- oder Bridge-Geräte als Netzwerkziel. Konfigurieren Sie entweder ein VLAN (oder eine andere virtuelle Schnittstelle) auf dem Bond-Gerät oder verwenden Sie ein Bridge- und virtuelles Ethernet-Paar (veth).

*Best Practice:* Geben Sie einen Wert an, auch wenn dieser Knoten zunächst keine Client Network IP Adresse hat. Anschließend können Sie später eine Client-Netzwerk-IP-Adresse hinzufügen, ohne den Node auf dem Host neu konfigurieren zu müssen.

Beispiele:

`bond0.1003`

`ens423`
 a| 
Best Practices in sich

|===


==== CLIENT_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Schnittstelle (dieser Wert wird nur unterstützt.)
 a| 
Optional

|===


==== CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Richtig oder falsch

Setzen Sie den Schlüssel auf „true“, damit der StorageGRID-Container die MAC-Adresse der Host-Zielschnittstelle im Client-Netzwerk verwenden kann.

*Best Practice:* in Netzwerken, in denen der promiskuious-Modus erforderlich wäre, verwenden Sie stattdessen DEN CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC-Schlüssel.

Weitere Informationen zum MAC-Klonen für Linux finden Sie unterlink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen"]
 a| 
Best Practices in sich

|===


=== Schlüssel für das Grid-Netzwerk



==== GRID_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
STATISCH oder DHCP

Wenn nicht angegeben, wird standardmäßig auf STATISCH gesetzt.
 a| 
Best Practices in sich

|===


==== GRID_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse des lokalen Grid-Netzwerk-Gateways für diesen Node, der sich im Subnetz befinden muss, das durch GRID_NETWORK_IP und GRID_NETWORK_MASKE definiert ist. Dieser Wert wird bei DHCP-konfigurierten Netzwerken ignoriert.

Wenn das Grid-Netzwerk ein einzelnes Subnetz ohne Gateway ist, verwenden Sie entweder die Standard-Gateway-Adresse für das Subnetz (X.Z.1) oder den GRID_NETWORK_IP-Wert dieses Knotens; jeder Wert wird mögliche zukünftige Grid-Netzwerk-Erweiterungen vereinfachen.
 a| 
Erforderlich

|===


==== GRID_NETWORK_IP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Adresse dieses Knotens im Grid-Netzwerk. Dieser Schlüssel ist nur erforderlich, wenn GRID_NETWORK_CONFIG = STATIC; geben Sie ihn nicht für andere Werte an.

Beispiele:

`1.1.1.1`

`10.224.4.81`
 a| 
Erforderlich, wenn GRID_NETWORK_CONFIG = STATISCH

Andernfalls optional.

|===


==== GRID_NETWORK_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die MAC-Adresse für die Grid-Netzwerkschnittstelle im Container.

Muss aus 6 Hexadezimalziffern bestehen, die durch Doppelpunkte getrennt werden.

Beispiel: `b2:9c:02:c2:27:30`
 a| 
Optional

Wenn keine Angabe erfolgt, wird automatisch eine MAC-Adresse generiert.

|===


==== GRID_NETWORK_MASKE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
IPv4-Netzmaske für diesen Knoten im Grid-Netzwerk. Geben Sie diesen Schlüssel an, wenn GRID_NETWORK_CONFIG = STATISCH ist; geben Sie ihn nicht für andere Werte an.

Beispiele:

`255.255.255.0`

`255.255.248.0`
 a| 
Erforderlich, wenn GRID_NETWORK_IP angegeben und GRID_NETWORK_CONFIG = STATISCH ist.

Andernfalls optional.

|===


==== GRID_NETWORK_MTU

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Die maximale Übertragungseinheit (MTU) für diesen Knoten im Grid-Netzwerk. Geben Sie nicht an, ob GRID_NETWORK_CONFIG = DHCP ist. Wenn angegeben, muss der Wert zwischen 1280 und 9216 liegen. Wenn weggelassen, wird 1500 verwendet.

Wenn Sie Jumbo Frames verwenden möchten, setzen Sie die MTU auf einen für Jumbo Frames geeigneten Wert, z. B. 9000. Behalten Sie andernfalls den Standardwert bei.

*WICHTIG*: Der MTU-Wert des Netzwerks muss mit dem Wert übereinstimmen, der auf dem Switch-Port konfiguriert ist, an den der Knoten angeschlossen ist. Andernfalls können Probleme mit der Netzwerkleistung oder Paketverluste auftreten.

*WICHTIG*: Für die beste Netzwerkleistung sollten alle Knoten auf ihren Grid Network Interfaces mit ähnlichen MTU-Werten konfiguriert werden. Die Warnung *Grid Network MTU mismatch* wird ausgelöst, wenn sich die MTU-Einstellungen für das Grid Network auf einzelnen Knoten erheblich unterscheiden. Die MTU-Werte müssen nicht für alle Netzwerktypen gleich sein.

Beispiele:

`1500`

`8192`
 a| 
Optional

|===


==== GRID_NETWORK_TARGET

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name des Hostgeräts, das Sie für den Netzzugang über den StorageGRID-Knoten verwenden werden. Es werden nur Namen von Netzwerkschnittstellen unterstützt. Normalerweise verwenden Sie einen anderen Schnittstellennamen als den für ADMIN_NETWORK_TARGET oder CLIENT_NETWORK_TARGET angegebenen.

*Hinweis*: Verwenden Sie keine Bond- oder Bridge-Geräte als Netzwerkziel. Konfigurieren Sie entweder ein VLAN (oder eine andere virtuelle Schnittstelle) auf dem Bond-Gerät oder verwenden Sie ein Bridge- und virtuelles Ethernet-Paar (veth).

Beispiele:

`bond0.1001`

`ens192`
 a| 
Erforderlich

|===


==== GRID_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Schnittstelle (Dies ist der einzige unterstützte Wert.)
 a| 
Optional

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Richtig oder falsch

Setzen Sie den Wert des Schlüssels auf „true“, um den StorageGRID-Container dazu zu bringen, die MAC-Adresse der Host-Zielschnittstelle im Grid-Netzwerk zu verwenden.

*Best Practice:* in Netzwerken, in denen der promiskuious-Modus erforderlich wäre, verwenden Sie stattdessen DEN GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC-Schlüssel.

Weitere Informationen zum MAC-Klonen für Linux finden Sie unterlink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Überlegungen und Empfehlungen zum Klonen von MAC-Adressen"]
 a| 
Best Practices in sich

|===


=== Schlüssel für Installationspasswort (temporär)



==== CUSTOM_TEMPORARY_PASSWORD_HASH

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Legen Sie für den primären Administratorknoten während der Installation ein temporäres Standardpasswort für die StorageGRID Installations-API fest.

*Hinweis*: Legen Sie nur auf dem primären Admin-Knoten ein Installationspasswort fest. Wenn Sie versuchen, ein Passwort für einen anderen Node-Typ festzulegen, schlägt die Validierung der Node-Konfigurationsdatei fehl.

Die Einstellung dieses Wertes hat keine Auswirkung, wenn die Installation abgeschlossen ist.

Wenn dieser Schlüssel weggelassen wird, wird standardmäßig kein temporäres Passwort festgelegt. Alternativ können Sie über die StorageGRID Installations-API ein temporäres Passwort festlegen.

Muss ein SHA-512-Passwort-Hash mit einem Format `$6$<salt>$<password hash>` für ein Passwort von mindestens 8 und nicht mehr als 32 Zeichen sein `crypt()`.

Dieser Hash kann mit CLI-Tools, wie dem Befehl im SHA-512-Modus, generiert `openssl passwd` werden.
 a| 
Best Practices in sich

|===


=== Schnittstellenschlüssel



==== INTERFACE_TARGET_nnnn

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Name und optionale Beschreibung für eine zusätzliche Schnittstelle, die Sie diesem Node hinzufügen möchten. Jeder Node kann mehrere zusätzliche Schnittstellen hinzugefügt werden.

Geben Sie für _nnnn_ eine eindeutige Nummer für jeden Eintrag INTERFACE_TARGET an, den Sie hinzufügen.

Geben Sie für den Wert den Namen der physischen Schnittstelle auf dem Bare-Metal-Host an. Fügen Sie dann optional ein Komma hinzu und geben Sie eine Beschreibung der Schnittstelle an, die auf der Seite VLAN-Schnittstellen und der Seite HA-Gruppen angezeigt wird.

Beispiel: `INTERFACE_TARGET_0001=ens256, Trunk`

Wenn Sie eine Trunk-Schnittstelle hinzufügen, müssen Sie eine VLAN-Schnittstelle in StorageGRID konfigurieren. Wenn Sie eine Zugriffsschnittstelle hinzufügen, können Sie die Schnittstelle direkt einer HA-Gruppe hinzufügen. Sie müssen keine VLAN-Schnittstelle konfigurieren.
 a| 
Optional

|===


=== Maximaler RAM-Schlüssel



==== MAXIMUM_RAM

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Der maximale RAM-Umfang, den dieser Node nutzen darf. Wenn dieser Schlüssel nicht angegeben ist, gelten für den Node keine Speicherbeschränkungen. Wenn Sie dieses Feld für einen Knoten auf Produktionsebene festlegen, geben Sie einen Wert an, der mindestens 24 GB und 16 bis 32 GB kleiner als der gesamte RAM des Systems ist.

*Hinweis*: Der RAM-Wert wirkt sich auf den tatsächlich reservierten Metadatenspeicherplatz eines Knotens aus. Siehe link:../admin/managing-object-metadata-storage.html["beschreibung des reservierten Speicherplatzes für Metadaten"].

Das Format für dieses Feld ist `_numberunit_`, wo kann `b` , `_unit_` , `k`, `m` oder `g`.

Beispiele:

`24g`

`38654705664b`

*Hinweis*: Wenn Sie diese Option verwenden möchten, müssen Sie Kernel-Unterstützung für Speicher-cgroups aktivieren.
 a| 
Optional

|===


=== Schlüssel vom Knotentyp



==== NODE_TYPE

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Node-Typ:

* VM_Admin_Node
* VM_Storage_Node
* VM_Archive_Node
* VM_API_Gateway

 a| 
Erforderlich

|===


==== SPEICHERTYP

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Definiert den Objekttyp, den ein Storage Node enthält. Weitere Informationen finden Sie unter link:../primer/what-storage-node-is.html#types-of-storage-nodes["Typen von Storage-Nodes"]. Dieser Schlüssel ist nur für Knoten mit NODE_TYPE = VM_Storage_Node erforderlich; geben Sie ihn nicht für andere Knotentypen an. Speichertypen:

* Kombiniert
* Daten
* Metadaten


*Hinweis*: Wenn der STORAGE_TYPE nicht angegeben ist, wird der Storage Node-Typ standardmäßig auf kombiniert (Daten und Metadaten) gesetzt.
 a| 
Optional

|===


=== Schlüssel für die Portzuordnung neu zuweisen


NOTE: Die Unterstützung für die Neuzuordnung von Ports ist veraltet und wird in einer zukünftigen Version entfernt. Informationen zum Entfernen neu zugeordneter Ports finden Sie unterlink:../maintain/removing-port-remaps-on-bare-metal-hosts.html["Entfernen Sie die Port-Remaps auf Bare-Metal-Hosts"] .



==== PORT_NEU ZUORDNEN

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Ordnet alle von einem Node verwendeten Ports für interne Grid Node-Kommunikation oder externe Kommunikation neu zu. Neuzuordnungen von Ports sind erforderlich, wenn die Netzwerkrichtlinien des Unternehmens einen oder mehrere von StorageGRID verwendete Ports einschränken, wie in  oder beschriebenlink:../network/internal-grid-node-communications.html["Interne Kommunikation mit Grid-Nodes"]link:../network/external-communications.html["Externe Kommunikation"].

*WICHTIG*: Weisen Sie die Ports, die Sie für die Konfiguration von Load Balancer Endpunkten verwenden möchten, nicht neu zu.

*Hinweis*: Wenn nur PORT_REMAP eingestellt ist, wird die von Ihnen angegebene Zuordnung sowohl für eingehende als auch für ausgehende Kommunikation verwendet. Wenn AUCH PORT_REMAP_INBOUND angegeben wird, gilt PORT_REMAP nur für ausgehende Kommunikation.

Das verwendete Format ist: `_network type_/_protocol_/_default port used by grid node_/_new port_`, Wobei `_network type_` Grid, admin oder Client und tcp oder `_protocol_` udp ist.

Beispiel: `PORT_REMAP = client/tcp/18082/443`

Sie können auch mehrere Ports mithilfe einer kommagetrennten Liste neu zuordnen.

Beispiel: `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
Optional

|===


==== PORT_REMAP_INBOUND

[cols="4a,2a"]
|===
| Wert | Bezeichnung 


 a| 
Ordnet die eingehende Kommunikation dem angegebenen Port erneut zu. Wenn SIE PORT_REMAP_INBOUND angeben, aber keinen Wert für PORT_REMAP angeben, bleiben die ausgehenden Kommunikationen für den Port unverändert.

*WICHTIG*: Weisen Sie die Ports, die Sie für die Konfiguration von Load Balancer Endpunkten verwenden möchten, nicht neu zu.

Das verwendete Format ist: `_network type_/_protocol_/_remapped port_/_default port used by grid node_`, Wobei `_network type_` Grid, admin oder Client und tcp oder `_protocol_` udp ist.

Beispiel: `PORT_REMAP_INBOUND = grid/tcp/3022/22`

Sie können auch mehrere eingehende Ports mithilfe einer kommagetrennten Liste neu zuordnen.

Beispiel: `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
Optional

|===