---
permalink: swnodes/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: StorageGRID stellt die StorageGRID Installations-API für die Durchführung von Installationsaufgaben bereit. 
---
= Erfahren Sie mehr über die StorageGRID Installation REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID stellt die StorageGRID Installations-API für die Durchführung von Installationsaufgaben bereit.

Die API verwendet die Swagger Open Source API-Plattform, um die API-Dokumentation bereitzustellen. Swagger ermöglicht Entwicklern und nicht-Entwicklern die Interaktion mit der API in einer Benutzeroberfläche, die zeigt, wie die API auf Parameter und Optionen reagiert. Diese Dokumentation setzt voraus, dass Sie mit Standard-Webtechnologien und dem JSON-Datenformat vertraut sind.


CAUTION: Alle API-Operationen, die Sie mit der API-Dokumentations-Webseite durchführen, sind Live-Operationen. Achten Sie darauf, dass Konfigurationsdaten oder andere Daten nicht versehentlich erstellt, aktualisiert oder gelöscht werden.

Jeder REST-API-Befehl umfasst die URL der API, eine HTTP-Aktion, alle erforderlichen oder optionalen URL-Parameter sowie eine erwartete API-Antwort.



[[storagegrid-installation-api]]
== StorageGRID Installations-API

Die StorageGRID Installations-API ist nur verfügbar, wenn Sie das StorageGRID-System zu Beginn konfigurieren und eine primäre Wiederherstellung des Admin-Knotens durchführen müssen. Der Zugriff auf die Installations-API erfolgt über HTTPS vom Grid Manager.

Um auf die API-Dokumentation zuzugreifen, gehen Sie auf die Installations-Webseite des primären Admin-Knotens und wählen Sie in der Menüleiste *Hilfe* > *API-Dokumentation* aus.

Die StorageGRID Installations-API umfasst die folgenden Abschnitte:

* *config*: Operationen im Zusammenhang mit der Produkteinführung und den Versionen der API. Es ist möglich, die Produkt-Release-Version und die von dieser Version unterstützten Hauptversionen der API aufzulisten.
* *grid*: Konfigurationsvorgänge auf Grid-Ebene. Es besteht die Möglichkeit, Grid-Einstellungen abzurufen und zu aktualisieren, einschließlich Grid-Details, Grid Network Subnetzen, Grid-Passwörtern sowie NTP- und DNS-Server-IP-Adressen.
* *Knoten*: Konfigurationsvorgänge auf Knotenebene. Es besteht die Möglichkeit, eine Liste der Grid-Knoten abzurufen, einen Grid-Knoten zu löschen, einen Grid-Knoten zu konfigurieren, einen Grid-Knoten anzuzeigen und die Konfiguration eines Grid-Knotens zurückzusetzen.
* *Bereitstellung*: Bereitstellungsvorgänge. Der Bereitstellungsvorgang kann gestartet und der Status des Bereitstellungsvorgangs angezeigt werden.
* *Wiederherstellung*: Wiederherstellungsvorgänge des primären Admin-Knotens. Es besteht die Möglichkeit, Informationen zurückzusetzen, das Recovery Package hochzuladen, die Wiederherstellung zu starten und den Status des Wiederherstellungsvorgangs anzuzeigen.
* *recovery-package*: Vorgänge zum Herunterladen des Recovery Package.
* *sites*: Konfigurationsvorgänge auf Site-Ebene. Es besteht die Möglichkeit, eine Site zu erstellen, anzuzeigen, zu löschen und zu bearbeiten.
* *temporary-password*: Vorgänge mit dem temporären Passwort zur Absicherung der mgmt-api während der Installation.

