---
permalink: swnodes/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Sie können eine virtuelle Maschine zum Hosten eines beliebigen Typs von StorageGRID-Knoten verwenden. Für jeden Grid-Node benötigen Sie eine virtuelle Maschine. 
---
= Softwareanforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine virtuelle Maschine zum Hosten eines beliebigen Typs von StorageGRID-Knoten verwenden. Für jeden Grid-Node benötigen Sie eine virtuelle Maschine.

[role="tabbed-block"]
====
.RHEL
--
Um StorageGRID auf RHEL zu installieren, müssen Sie einige Softwarepakete von Drittanbietern installieren.  Einige unterstützte Linux-Distributionen enthalten diese Pakete nicht standardmäßig.  Zu den Softwarepaketversionen, auf denen StorageGRID Installationen getestet werden, gehören die auf dieser Seite aufgeführten.

Wenn Sie eine Linux-Distribution und eine Container-Laufzeitinstallation auswählen, für die eines dieser Pakete erforderlich ist und die nicht automatisch von der Linux-Distribution installiert werden, installieren Sie eine der hier aufgeführten Versionen, wenn diese bei Ihrem Provider oder dem Support-Anbieter für Ihre Linux-Distribution verfügbar sind. Verwenden Sie andernfalls die Standardpaketversionen, die Sie von Ihrem Hersteller erhalten.

Für alle Installationsoptionen ist Podman oder Docker erforderlich. Installieren Sie nicht beide Pakete. Installieren Sie nur das für Ihre Installationsoption erforderliche Paket.


NOTE: Die Unterstützung für Docker als Container-Engine für rein softwarebasierte Implementierungen ist veraltet. Docker wird in einer zukünftigen Version durch eine weitere Container-Engine ersetzt.

*Getestete Python-Versionen*

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6


*Getestete Podman-Versionen*

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12


*Getestete Docker-Versionen*


IMPORTANT: Die Docker-Unterstützung ist veraltet und wird in einer zukünftigen Version entfernt.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23.0.6-1
* Docker-CE 24.0.2-1
* Docker-CE 24.0.4-1
* Docker-CE 24.0.5-1
* Docker-CE 24.0.7-1
* 1,5-2


--
.Ubuntu und Debian
--
Um StorageGRID auf Ubuntu oder Debian zu installieren, müssen Sie einige Softwarepakete von Drittanbietern installieren. Einige unterstützte Linux-Distributionen enthalten diese Pakete standardmäßig nicht. Die Software-Paketversionen, auf denen StorageGRID-Installationen getestet werden, enthalten die auf dieser Seite aufgeführten.

Wenn Sie eine Linux-Distribution und eine Container-Laufzeitinstallation auswählen, für die eines dieser Pakete erforderlich ist und die nicht automatisch von der Linux-Distribution installiert werden, installieren Sie eine der hier aufgeführten Versionen, wenn diese bei Ihrem Provider oder dem Support-Anbieter für Ihre Linux-Distribution verfügbar sind. Verwenden Sie andernfalls die Standardpaketversionen, die Sie von Ihrem Hersteller erhalten.

Für alle Installationsoptionen ist Podman oder Docker erforderlich. Installieren Sie nicht beide Pakete. Installieren Sie nur das für Ihre Installationsoption erforderliche Paket.


NOTE: Die Unterstützung für Docker als Container-Engine für rein softwarebasierte Implementierungen ist veraltet. Docker wird in einer zukünftigen Version durch eine weitere Container-Engine ersetzt.

*Getestete Python-Versionen*

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6


*Getestete Podman-Versionen*

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12


*Getestete Docker-Versionen*


IMPORTANT: Die Docker-Unterstützung ist veraltet und wird in einer zukünftigen Version entfernt.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23.0.6-1
* Docker-CE 24.0.2-1
* Docker-CE 24.0.4-1
* Docker-CE 24.0.5-1
* Docker-CE 24.0.7-1
* 1,5-2


--
.VMware
--
*VMware vSphere Hypervisor*

Sie müssen VMware vSphere Hypervisor auf einem vorbereiteten physischen Server installieren. Die Hardware muss vor der Installation der VMware Software korrekt konfiguriert sein (einschließlich Firmware-Versionen und BIOS-Einstellungen).

* Zur Unterstützung des Netzwerkes für das zu installierende StorageGRID-System konfigurieren Sie das Netzwerk im Hypervisor nach Bedarf.
+
link:../network/index.html["Netzwerkrichtlinien"]

* Stellen Sie sicher, dass der Datastore groß genug für die virtuellen Maschinen und virtuellen Festplatten ist, die zum Hosten der Grid-Nodes benötigt werden.
* Wenn Sie mehr als einen Datenspeicher erstellen, benennen Sie jeden Datenspeicher. So können Sie bei der Erstellung von Virtual Machines leicht ermitteln, welchen Datenspeicher für die einzelnen Grid-Nodes verwendet werden soll.


*Konfigurationsanforderungen für ESX-Hosts*


CAUTION: Sie müssen das Network Time Protocol (NTP) auf jedem ESX-Host ordnungsgemäß konfigurieren. Wenn die Host-Zeit falsch ist, können negative Auswirkungen, einschließlich Datenverlust, auftreten.

*VMware-Konfigurationsanforderungen*

Sie müssen VMware vSphere und vCenter vor der Bereitstellung von StorageGRID-Knoten installieren und konfigurieren.

Informationen zu unterstützten Versionen von VMware vSphere Hypervisor und VMware vCenter Server-Software finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^].

Die Schritte zur Installation dieser VMware-Produkte finden Sie in der VMware-Dokumentation.

--
====