---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.0 verwendet Version 4 der Grid-Management-API. Version 4 verfällt Version 3; allerdings werden die Versionen 1, 2 und 3 weiterhin unterstützt. 
---
= Änderungen an der Grid-Management-API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 verwendet Version 4 der Grid-Management-API. Version 4 verfällt Version 3; allerdings werden die Versionen 1, 2 und 3 weiterhin unterstützt.


NOTE: Sie können mit StorageGRID 12.0 weiterhin veraltete Versionen der Management-API verwenden. Die Unterstützung für diese Versionen der API wird jedoch in einem zukünftigen Release von StorageGRID entfernt. Nach dem Upgrade auf StorageGRID 12.0 können Sie die veralteten APIs mithilfe der API deaktivieren `PUT /grid/config/management`.

Weitere Informationen finden Sie unter link:../admin/using-grid-management-api.html["Verwenden Sie die Grid-Management-API"].



== Neue private Endpunkte für ADC verschieben

Die folgenden privaten Endpunkte wurden hinzugefügt, um Ihnen die Möglichkeit zu geben, link:../maintain/move-adc-service.html["Den ADC-Dienst verschieben"]von einem Storage Node zu einem anderen am selben Standort zu wechseln:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`
