---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 12.0 verwendet Version 4 der Tenant Management API.  Version 4 macht Version 3 veraltet; die Versionen 1, 2 und 3 werden jedoch weiterhin unterstützt. 
---
= Änderungen an der Mandantenmanagement-API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 verwendet Version 4 der Tenant Management API.  Version 4 macht Version 3 veraltet; die Versionen 1, 2 und 3 werden jedoch weiterhin unterstützt.


NOTE: Sie können veraltete Versionen der Tenant Management API weiterhin mit StorageGRID 12.0 verwenden. Die Unterstützung für diese Versionen der API wird jedoch in einer zukünftigen Version von StorageGRID entfernt.  Nach dem Upgrade auf StorageGRID 12.0 können Sie die veralteten APIs deaktivieren, indem Sie die `PUT /grid/config/management` API.

Weitere Informationen finden Sie unter link:../tenant/understanding-tenant-management-api.html["Mandantenmanagement-API verstehen"].



== Neue API für die Objektreplikation

Sie können die `/org/cross-grid-replication/{versionId}/replicate` API zum manuellen Replizieren von Objekten in einem vorhandenen Bucket, für den die Cross-Grid-Replikation neu konfiguriert wurde.
