---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.0 verwendet Version 4 der Grid Management API.  Version 4 macht Version 3 veraltet; die Versionen 1, 2 und 3 werden jedoch weiterhin unterstützt. 
---
= Änderungen an der Grid-Management-API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 verwendet Version 4 der Grid Management API.  Version 4 macht Version 3 veraltet; die Versionen 1, 2 und 3 werden jedoch weiterhin unterstützt.


NOTE: Sie können veraltete Versionen der Verwaltungs-API weiterhin mit StorageGRID 12.0 verwenden. Die Unterstützung für diese Versionen der API wird jedoch in einer zukünftigen Version von StorageGRID entfernt.  Nach dem Upgrade auf StorageGRID 12.0 können Sie die veralteten APIs deaktivieren, indem Sie die `PUT /grid/config/management` API.

Weitere Informationen finden Sie unter link:../admin/using-grid-management-api.html["Verwenden Sie die Grid-Management-API"].



== Neue Endpunkte für Branch-Buckets

Die folgenden Endpunkte wurden hinzugefügt, um Ihnen zu ermöglichen,link:../tenant/what-is-branch-bucket.html["Branch-Buckets verwalten"] :

`GET /org/containers/{branchBucketName}/branch`

`PUT /org/containers/{branchBucketName}/branch`



== Neue private Endpunkte für Move ADC

Die folgenden privaten Endpunkte wurden hinzugefügt, damit Sielink:../maintain/move-adc-service.html["Verschieben Sie den ADC-Dienst"] von einem Speicherknoten zu einem anderen am selben Standort:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`



== Neue private Endpunkte für die Konvertierung in einen Nur-Daten-Knoten

Die folgenden privaten Endpunkte wurden hinzugefügt, damit Sielink:../maintain/convert-to-data-only-node.html["Konvertieren Sie einen oder mehrere kombinierte Speicherknoten"] die den ADC-Dienst nicht enthalten, in reine Datenknoten.

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`
