---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Überprüfen Sie vor dem Upgrade eines StorageGRID-Systems, ob das System für das Upgrade bereit ist. Stellen Sie sicher, dass das System ordnungsgemäß ausgeführt wird und dass alle Grid-Nodes funktionsfähig sind. 
---
= Überprüfen Sie den Zustand des Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie vor dem Upgrade eines StorageGRID-Systems, ob das System für das Upgrade bereit ist. Stellen Sie sicher, dass das System ordnungsgemäß ausgeführt wird und dass alle Grid-Nodes funktionsfähig sind.

.Schritte
. Melden Sie sich mit einem beim Grid-Manager anlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
. Aktive Warnmeldungen prüfen und beheben.
. Bestätigen Sie, dass keine in Konflikt stehenden Grid-Aufgaben aktiv oder ausstehend sind.
+
.. Wählen Sie *SUPPORT* > *Tools* > *Grid-Topologie* aus.
.. Wählen Sie *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Konfiguration* aus.
+
ILME-Tasks (Information Lifecycle Management Evaluation) sind die einzigen Grid-Aufgaben, die gleichzeitig mit dem Software-Upgrade ausgeführt werden können.

.. Wenn andere Grid-Aufgaben aktiv oder ausstehend sind, warten Sie, bis sie abgeschlossen sind oder lassen Sie ihre Sperre los.
+

NOTE: Wenden Sie sich an den technischen Support, wenn eine Aufgabe nicht beendet ist oder ihre Sperre nicht freigegeben wird.



. Lesen Sie link:../network/internal-grid-node-communications.html["Interne Kommunikation mit Grid-Nodes"]undlink:../network/external-communications.html["Externe Kommunikation"], um sicherzustellen, dass alle erforderlichen Ports für StorageGRID 11.9 geöffnet sind, bevor Sie ein Upgrade durchführen.
+

NOTE: Beim Upgrade auf StorageGRID 12.0 sind keine zusätzlichen Ports erforderlich.


