---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Überprüfen Sie vor dem Upgrade eines StorageGRID-Systems, ob das System für das Upgrade bereit ist. Stellen Sie sicher, dass das System ordnungsgemäß ausgeführt wird und dass alle Grid-Nodes funktionsfähig sind. 
---
= Überprüfen Sie den Zustand des Systems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie vor dem Upgrade eines StorageGRID-Systems, ob das System für das Upgrade bereit ist. Stellen Sie sicher, dass das System ordnungsgemäß ausgeführt wird und dass alle Grid-Nodes funktionsfähig sind.

.Schritte
. Melden Sie sich mit einem beim Grid-Manager anlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
. Aktive Warnmeldungen prüfen und beheben.
. Siehelink:../network/internal-grid-node-communications.html["Interne Kommunikation mit Grid-Nodes"] Undlink:../network/external-communications.html["Externe Kommunikation"] um sicherzustellen, dass alle erforderlichen Ports für StorageGRID 12.0 geöffnet sind, bevor Sie ein Upgrade durchführen.
+

NOTE: Beim Upgrade auf StorageGRID 12.0 sind keine zusätzlichen Ports erforderlich.


