---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Erfahren Sie, wie Ihr StorageGRID-System bei einem Upgrade beeinträchtigt wird. 
---
= Auswirkungen des Upgrades auf Ihr System
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie Ihr StorageGRID-System bei einem Upgrade beeinträchtigt wird.



== Externer SSH-Zugriff ist bis zum Abschluss des Upgrades zulässig.

Während des Upgrades ist externer SSH-Zugriff zulässig.  Wenn das Upgrade abgeschlossen ist, wird der externe SSH-Zugriff standardmäßig blockiert.  Nach dem Upgrade können Sie die Registerkarte *SSH blockieren* auf der Seite *Grid Manager* > *Sicherheitseinstellungen* verwenden, umlink:../admin/manage-external-ssh-access.html["externen SSH-Zugriff verwalten"] .  Der SSH-Zugriff zwischen Grid-Knoten ist nicht betroffen.



== StorageGRID Upgrades sind unterbrechungsfrei

Das StorageGRID System ist in der Lage, während des Upgrades Daten von Client-Applikationen aufzunehmen und abzurufen. Wenn Sie alle Nodes desselben Typs für das Upgrade genehmigen (z. B. Storage Nodes), werden die Nodes nacheinander heruntergefahren. Es ist also keine Zeit, wenn alle Grid-Nodes oder alle Grid-Nodes eines bestimmten Typs nicht verfügbar sind.

Um die kontinuierliche Verfügbarkeit zu gewährleisten, stellen Sie sicher, dass Ihre ILM-Richtlinie Regeln enthält, die das Speichern mehrerer Kopien jedes Objekts festlegen. Außerdem müssen Sie sicherstellen, dass alle externen S3-Clients so konfiguriert sind, dass sie Anforderungen an einen der folgenden senden:

* Eine virtuelle IP-Adresse einer HA-Gruppe (High Availability, Hochverfügbarkeit)
* Einen hochverfügbaren Drittanbieter-Load Balancer
* Mehrere Gateway-Nodes für jeden Client
* Mehrere Storage-Nodes für jeden Client




== Bei Client-Applikationen kommt es unter Umständen zu kurzfristigen Unterbrechungen

Das StorageGRID System kann Daten aus Client-Applikationen während des Upgrades aufnehmen und abrufen. Es kann jedoch vorübergehend zu Client-Verbindungen zu einzelnen Gateway Nodes oder Storage Nodes unterbrochen werden, wenn das Upgrade die Services auf diesen Nodes neu starten muss. Die Konnektivität wird nach Abschluss des Upgrade-Vorgangs wiederhergestellt und die Services auf den einzelnen Nodes wieder aufgenommen.

Möglicherweise müssen Sie Ausfallzeiten planen, um ein Upgrade durchzuführen, wenn der Verbindungsverlust für einen kurzen Zeitraum nicht akzeptabel ist. Sie können eine selektive Genehmigung verwenden, um die Planung für die Aktualisierung bestimmter Knoten zu planen.


NOTE: Mehrere Gateways und Hochverfügbarkeitsgruppen (High Availability, HA) ermöglichen automatisches Failover während des Upgrades. Siehe die Anleitung für link:../admin/configure-high-availability-group.html["Konfigurieren von Hochverfügbarkeitsgruppen"].



== Hintergrundreparaturen werden auf Grids mit Knoten unterschiedlicher Versionen nicht ausgeführt

Wenn das Grid Knoten mit unterschiedlichen Versionen enthält, werden während des Upgrades keine Hintergrundreparaturen ausgeführt.  Etwaige Inkonsistenzen, die während eines Site-Ausfalls auftreten, werden erst behoben, wenn das Upgrade abgeschlossen ist.



== Die Appliance-Firmware wird aktualisiert

Während des StorageGRID 12.0-Upgrades:

* Alle StorageGRID Appliance-Knoten werden automatisch auf die StorageGRID Appliance Installer-Firmwareversion 12.0 aktualisiert.
* SG6060- und SGF6024-Geräte werden automatisch auf die BIOS-Firmware-Version 3B08.EX und die BMC -Firmware-Version 4.01.07 aktualisiert.
* SG100- und SG1000-Geräte werden automatisch auf die BIOS-Firmware-Version 3B13.EC und die BMC -Firmware-Version 4.75.07 aktualisiert.
* Die Geräte SGF6112, SG6160, SG110 und SG1100 werden automatisch auf die BIOS-Firmware-Version 3A14.QD und die BMC -Firmware-Version 3.19.07 aktualisiert.




== ILM-Richtlinien werden je nach Status unterschiedlich gehandhabt

* Die aktive Richtlinie bleibt nach dem Upgrade unverändert.
* Nur die letzten 10 historischen Richtlinien bleiben bei der Aktualisierung erhalten.
* Wenn eine vorgeschlagene Richtlinie vorhanden ist, wird sie während des Upgrades gelöscht.




== Möglicherweise werden Benachrichtigungen ausgelöst

Warnmeldungen können ausgelöst werden, wenn Services gestartet und beendet werden und wenn das StorageGRID System als Umgebung mit gemischten Versionen funktioniert (einige Grid-Nodes mit einer früheren Version, während andere auf eine neuere Version aktualisiert wurden). Nach Abschluss des Upgrades können weitere Warnmeldungen ausgelöst werden.

Beispielsweise wird möglicherweise die Warnung *Kommunikation mit Knoten nicht möglich* angezeigt, wenn Dienste gestoppt werden, oder die Warnung *Cassandra-Kommunikationsfehler*, wenn einige Knoten auf StorageGRID 12.0 aktualisiert wurden, auf anderen Knoten jedoch noch StorageGRID 11.9 ausgeführt wird.  Im Allgemeinen werden diese Warnungen gelöscht, wenn das Upgrade abgeschlossen ist.

Die Warnung *ILM-Platzierung nicht erreichbar* kann ausgelöst werden, wenn Speicherknoten während des Upgrades auf StorageGRID 12.0 angehalten werden.  Diese Warnung bleibt möglicherweise noch einen Tag nach Abschluss des Upgrades bestehen.

Nachdem das Upgrade abgeschlossen ist, können Sie alle Upgrade-bezogenen Warnmeldungen überprüfen, indem Sie im Grid Manager-Dashboard *Kürzlich aufgelöste Warnmeldungen* oder *Aktuelle Warnmeldungen* auswählen.



== Konfigurationsänderungen sind eingeschränkt


NOTE: Diese Liste gilt speziell für Upgrades von StorageGRID 11.9 auf StorageGRID 12.0.  Wenn Sie auf eine andere StorageGRID Version aktualisieren, lesen Sie die Liste der eingeschränkten Änderungen in den Upgrade-Anweisungen für diese Version.

Bis die Aufgabe *Neues Feature* aktivieren abgeschlossen ist:

* Nehmen Sie keine Änderungen an der Grid-Konfiguration vor.
* Aktivieren oder deaktivieren Sie keine neuen Funktionen.
* Aktualisieren Sie nicht die ILM-Konfiguration. Andernfalls kann es zu inkonsistenten und unerwarteten ILM-Verhaltensweisen kommen.
* Wenden Sie keinen Hotfix an, und stellen Sie keinen Grid-Knoten wieder her.
+

NOTE: Wenden Sie sich an den technischen Support, wenn Sie einen Node während des Upgrades wiederherstellen müssen.

* Sie sollten während des Upgrades auf StorageGRID 12.0 keine HA-Gruppen, VLAN-Schnittstellen oder Load Balancer-Endpunkte verwalten.
* Löschen Sie keine HA-Gruppen, bis das Upgrade auf StorageGRID 12.0 abgeschlossen ist.  Auf virtuelle IP-Adressen in anderen HA-Gruppen kann möglicherweise nicht mehr zugegriffen werden.


Bis die Aufgabe * Final Upgrade Steps* abgeschlossen ist:

* Führen Sie keine Erweiterungsschritte durch.
* Führen Sie keine Stilllegungsverfahren durch.

