---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: storagegrid software upgrade 
summary: Verwenden Sie diese Anweisungen, um ein StorageGRID System auf eine neue Version zu aktualisieren. 
---
= Upgrade der StorageGRID Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie diese Anweisungen, um ein StorageGRID System auf eine neue Version zu aktualisieren.

Wenn Sie das Upgrade durchführen, werden alle Knoten in Ihrem StorageGRID-System aktualisiert.



== Bevor Sie beginnen

In diesen Themen erfahren Sie mehr über die neuen Funktionen und Verbesserungen in StorageGRID 11.9, können feststellen, ob Funktionen veraltet oder entfernt wurden, und Informationen zu Änderungen an StorageGRID APIs finden Sie unter.

* link:whats-new.html["Was ist neu in StorageGRID 11.9"]
* link:removed-or-deprecated-features.html["Funktionen entfernt oder veraltet"]
* link:changes-to-grid-management-api.html["Änderungen an der Grid-Management-API"]
* link:changes-to-tenant-management-api.html["Änderungen an der Mandantenmanagement-API"]

