---
permalink: upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html 
sidebar: sidebar 
keywords: upgrade, linux, rpm, deb, 
summary: Wenn StorageGRID-Knoten auf Linux-Hosts bereitgestellt werden, installieren Sie auf jedem dieser Hosts ein zusätzliches RPM- oder DEB-Paket, bevor Sie mit dem Upgrade beginnen. 
---
= Linux: Laden Sie das RPM- oder DEB-Paket herunter und installieren Sie es auf allen Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn StorageGRID-Knoten auf Linux-Hosts bereitgestellt werden, laden Sie ein zusätzliches RPM- oder DEB-Paket herunter, und installieren Sie es auf jedem dieser Hosts, bevor Sie mit dem Upgrade beginnen.



== Laden Sie Upgrade-, Linux- und Hotfix-Dateien herunter

Wenn Sie ein StorageGRID-Upgrade über den Grid-Manager durchführen, werden Sie aufgefordert, das Upgrade-Archiv und den erforderlichen Hotfix als ersten Schritt herunterzuladen. Wenn Sie jedoch Dateien herunterladen müssen, um Linux-Hosts zu aktualisieren, können Sie Zeit sparen, indem Sie alle erforderlichen Dateien im Voraus herunterladen.

.Schritte
. Gehen Sie zu https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^].
. Wählen Sie die Schaltfläche zum Herunterladen der neuesten Version, oder wählen Sie eine andere Version aus dem Dropdown-Menü aus und wählen Sie *Go*.
+
Die StorageGRID-Softwareversionen haben dieses Format: 11._x.y_. StorageGRID-Hotfixes haben dieses Format: 11._x. y.y.z_.

. Melden Sie sich mit Ihrem Benutzernamen und Passwort für Ihr NetApp Konto an.
. Wenn ein Warnhinweis/MustRead angezeigt wird, notieren Sie sich die Hotfix-Nummer, und aktivieren Sie das Kontrollkästchen.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung (EULA), aktivieren Sie das Kontrollkästchen und wählen Sie dann *Accept & Continue* aus.
+
Die Download-Seite für die ausgewählte Version wird angezeigt. Die Seite enthält drei Spalten.

. Laden Sie in der zweiten Spalte (*Upgrade StorageGRID*) zwei Dateien herunter:
+
** Das Upgrade-Archiv für die neueste Version (dies ist die Datei im Abschnitt *VMware, SG1000 oder SG100 Primary Admin Node*). Diese Datei wird zwar erst benötigt, wenn Sie das Upgrade durchführen, aber das Herunterladen spart jetzt Zeit.
** Ein RPM- oder DEB-Archiv im `.tgz` oder `.zip`-Format. Wählen Sie die Datei aus `.zip`, wenn Sie Windows auf dem Service-Laptop ausführen.
+
*** Red Hat Enterprise Linux + +
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip`
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz`
*** Ubuntu oder Debian +
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` +
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz`




. Wenn Sie aufgrund eines erforderlichen Hotfix einem Warnhinweis/MustRead zustimmen müssen, laden Sie den Hotfix herunter:
+
.. Zurück zu https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^].
.. Wählen Sie die Hotfix-Nummer aus der Dropdown-Liste aus.
.. Stimmen Sie den Vorsichtshinweis und EULA erneut zu.
.. Laden Sie den Hotfix und dessen README herunter und speichern Sie ihn.
+
Sie werden aufgefordert, die Hotfix-Datei auf der StorageGRID-Upgrade-Seite hochzuladen, wenn Sie mit dem Upgrade beginnen.







== Installieren Sie Archive auf allen Linux-Hosts

Führen Sie diese Schritte aus, bevor Sie die StorageGRID Software aktualisieren.

.Schritte
. Extrahieren Sie die RPM- oder DEB-Pakete aus der Installationsdatei.
. Installieren Sie die RPM- oder DEB-Pakete auf allen Linux-Hosts.
+
Siehe die Schritte zum Installieren von StorageGRID-Hostdiensten in der Installationsanleitung:

+
** link:../rhel/installing-storagegrid-webscale-host-service.html["Red hat Enterprise Linux: Installieren Sie StorageGRID-Hostservices"]
** link:../ubuntu/installing-storagegrid-webscale-host-services.html["Ubuntu oder Debian: Installieren Sie StorageGRID-Hostdienste"]


+
Die neuen Pakete werden als zusätzliche Pakete installiert.





== Entfernen Sie Installationsarchive für frühere Versionen

Um Speicherplatz auf Linux-Hosts freizugeben, können Sie die Installationsarchive für frühere StorageGRID-Versionen entfernen, die Sie nicht mehr benötigen.

.Schritte
. Entfernen Sie die alten StorageGRID-Installationsarchive.


[role="tabbed-block"]
====
.Red Hat
--
. Erfassen Sie die Liste der installierten StorageGRID-Pakete: `dnf list | grep -i storagegrid`.
+
Beispiel:

+
[listing]
----
[root@rhel-example ~]# dnf list | grep -i storagegrid
StorageGRID-Webscale-Images-11-6-0.x86_64 11.6.0-20220210.0232.8d56cfe @System
StorageGRID-Webscale-Images-11-7-0.x86_64 11.7.0-20230424.2238.1a2cf8c @System
StorageGRID-Webscale-Images-11-8-0.x86_64 11.8.0-20240131.0139.e3e0c87 @System
StorageGRID-Webscale-Images-11-9-0.x86_64 11.9.0-20240826.1753.4aeeb70 @System
StorageGRID-Webscale-Service-11-6-0.x86_64 11.6.0-20220210.0232.8d56cfe @System
StorageGRID-Webscale-Service-11-7-0.x86_64 11.7.0-20230424.2238.1a2cf8c @System
StorageGRID-Webscale-Service-11-8-0.x86_64 11.8.0-20240131.0139.e3e0c87 @System
StorageGRID-Webscale-Service-11-9-0.x86_64 11.9.0-20240826.1753.4aeeb70 @System
[root@rhel-example ~]#
----
. Frühere StorageGRID-Pakete entfernen: `dnf remove _images-package_ _service-package_`
+

CAUTION: Entfernen Sie nicht die Installationsarchive für die Version von StorageGRID, die Sie derzeit ausführen, oder die Versionen von StorageGRID, auf die Sie aktualisieren möchten.

+
Sie können die angezeigten Warnungen ohne Bedenken ignorieren. Sie beziehen sich auf Dateien, die bei der Installation neuerer StorageGRID-Pakete ersetzt wurden.

+
Beispiel:

+
[listing]
----
[root@rhel-example ~]# dnf remove StorageGRID-Webscale-Images-11-6-0.x86_64 StorageGRID-Webscale-Service-11-6-0.x86_64
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Dependencies resolved.
============================================================================
Package            Architecture      Version           Repository  Size
============================================================================
Removing:
StorageGRID-Webscale-Images-11-6-0 x86_64 11.6.0-20220210.0232.8d56cfe @System 2.7 G
StorageGRID-Webscale-Service-11-6-0 x86_64 11.6.0-20220210.0232.8d56cfe @System 7.5 M

Transaction Summary
============================================================================
Remove 2 Packages

Freed space: 2.8 G
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing: 1/1
  Running scriptlet: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
  Erasing: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/ipv6.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/ipv4.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/eui64.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/eui48.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/sets.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/rfc1924.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/nmap.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/iana.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/glob.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/fbsocket.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/eui/ieee.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/eui/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/core.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/contrib/subnet_splitter.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/contrib/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/compat.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/__init__.pyc: remove failed: No such file or directory

  Erasing: StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64   2/2
  Verifying: StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
  Verifying: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  2/2
Installed products updated.

Removed:
  StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64
  StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64

Complete!
[root@rhel-example ~]#
----


--
.Ubuntu und Debian
--
. Erfassen Sie die Liste der installierten StorageGRID-Pakete: `dpkg -l | grep storagegrid`
+
Beispiel:

+
[listing]
----
root@debian-example:~# dpkg -l | grep storagegrid
ii  storagegrid-webscale-images-11-6-0  11.6.0-20220210.0232.8d56cfe amd64 StorageGRID Webscale docker images for 11.6.0
ii  storagegrid-webscale-images-11-7-0  11.7.0-20230424.2238.1a2cf8c.dev-signed amd64 StorageGRID Webscale docker images for 11.7.0
ii  storagegrid-webscale-images-11-8-0  11.8.0-20240131.0139.e3e0c87 amd64 StorageGRID Webscale docker images for 11.8.0
ii  storagegrid-webscale-images-11-9-0  11.9.0-20240826.1753.4aeeb70 amd64 StorageGRID Webscale docker images for 11.9.0
ii  storagegrid-webscale-service-11-6-0 11.6.0-20220210.0232.8d56cfe amd64 StorageGRID Webscale host services for 11.6.0
ii  storagegrid-webscale-service-11-7-0 11.7.0-20230424.2238.1a2cf8c amd64 StorageGRID Webscale host services for 11.7.0
ii  storagegrid-webscale-service-11-8-0 11.8.0-20240131.0139.e3e0c87 amd64 StorageGRID Webscale host services for 11.8.0
ii  storagegrid-webscale-service-11-9-0 11.9.0-20240826.1753.4aeeb70 amd64 StorageGRID Webscale host services for 11.9.0
root@debian-example:~#
----
. Frühere StorageGRID-Pakete entfernen: `dpkg -r _images-package_ _service-package_`
+

CAUTION: Entfernen Sie nicht die Installationsarchive für die Version von StorageGRID, die Sie derzeit ausführen, oder die Versionen von StorageGRID, auf die Sie aktualisieren möchten.

+
Beispiel:

+
[listing]
----
root@debian-example:~# dpkg -r storagegrid-webscale-service-11-6-0 storagegrid-webscale-images-11-6-0
(Reading database ... 38190 files and directories currently installed.)
Removing storagegrid-webscale-service-11-6-0 (11.6.0-20220210.0232.8d56cfe) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
dpkg: warning: while removing storagegrid-webscale-service-11-6-0, directory '/usr/lib/python2.7/dist-packages/netapp/storagegrid/vendor/latest' not empty so not removed
Removing storagegrid-webscale-images-11-6-0 (11.6.0-20220210.0232.8d56cfe) ...
root@debian-example:~#
----


--
====
. Entfernen Sie StorageGRID-Container-Images.


[role="tabbed-block"]
====
.Docker
--
. Erfassen Sie die Liste der installierten Container-Images: `docker images`
+
Beispiel:

+
[listing]
----
[root@docker-example ~]# docker images
REPOSITORY           TAG            IMAGE ID       CREATED         SIZE
storagegrid-11.9.0   Admin_Node     610f2595bcb4   2 days ago      2.77GB
storagegrid-11.9.0   Storage_Node   7f73d33eb880   2 days ago      2.65GB
storagegrid-11.9.0   API_Gateway    2f0bb79526e9   2 days ago      1.82GB
storagegrid-11.8.0   Storage_Node   7125480de71b   7 months ago    2.54GB
storagegrid-11.8.0   Admin_Node     404e9f1bd173   7 months ago    2.63GB
storagegrid-11.8.0   Archive_Node   c3294a29697c   7 months ago    2.39GB
storagegrid-11.8.0   API_Gateway    1f88f24b9098   7 months ago    1.74GB
storagegrid-11.7.0   Storage_Node   1655350eff6f   16 months ago   2.51GB
storagegrid-11.7.0   Admin_Node     872258dd0dc8   16 months ago   2.48GB
storagegrid-11.7.0   Archive_Node   121e7c8b6d3b   16 months ago   2.41GB
storagegrid-11.7.0   API_Gateway    5b7a26e382de   16 months ago   1.77GB
storagegrid-11.6.0   Admin_Node     ee39f71a73e1   2 years ago     2.38GB
storagegrid-11.6.0   Storage_Node   f5ef895dcad0   2 years ago     2.08GB
storagegrid-11.6.0   Archive_Node   5782de552db0   2 years ago     1.95GB
storagegrid-11.6.0   API_Gateway    cb480ed37eea   2 years ago     1.35GB
[root@docker-example ~]#
----
. Entfernen Sie die Container-Images für frühere StorageGRID-Versionen: `docker rmi _image id_`
+

CAUTION: Entfernen Sie nicht die Container-Images für die derzeit ausgeführte StorageGRID-Version oder die Versionen von StorageGRID, auf die Sie aktualisieren möchten.

+
Beispiel:

+
[listing]
----
[root@docker-example ~]# docker rmi cb480ed37eea
Untagged: storagegrid-11.6.0:API_Gateway
Deleted: sha256:cb480ed37eea0ae9cf3522de1dadfbff0075010d89c1c0a2337a3178051ddf02
Deleted: sha256:5f269aabf15c32c1fe6f36329c304b6c6ecb563d973794b9b59e8e5ab8cccafa
Deleted: sha256:47c2b2c295a77b312b8db69db58a02d8e09e929e121352bec713fa12dae66bde
[root@docker-example ~]#
----


--
.Podman
--
. Erfassen Sie die Liste der installierten Container-Images: `podman images`
+
Beispiel:

+
[listing]
----
[root@podman-example ~]# podman images
REPOSITORY                    TAG           IMAGE ID      CREATED        SIZE
localhost/storagegrid-11.8.0  Storage_Node  7125480de71b  7 months ago   2.57 GB
localhost/storagegrid-11.8.0  Admin_Node    404e9f1bd173  7 months ago   2.67 GB
localhost/storagegrid-11.8.0  Archive_Node  c3294a29697c  7 months ago   2.42 GB
localhost/storagegrid-11.8.0  API_Gateway   1f88f24b9098  7 months ago   1.77 GB
localhost/storagegrid-11.7.0  Storage_Node  1655350eff6f  16 months ago  2.54 GB
localhost/storagegrid-11.7.0  Admin_Node    872258dd0dc8  16 months ago  2.51 GB
localhost/storagegrid-11.7.0  Archive_Node  121e7c8b6d3b  16 months ago  2.44 GB
localhost/storagegrid-11.7.0  API_Gateway   5b7a26e382de  16 months ago  1.8 GB
localhost/storagegrid-11.6.0  Admin_Node    ee39f71a73e1  2 years ago    2.42 GB
localhost/storagegrid-11.6.0  Storage_Node  f5ef895dcad0  2 years ago    2.11 GB
localhost/storagegrid-11.6.0  Archive_Node  5782de552db0  2 years ago    1.98 GB
localhost/storagegrid-11.6.0  API_Gateway   cb480ed37eea  2 years ago    1.38 GB
[root@podman-example ~]#
----
. Entfernen Sie die Container-Images für frühere StorageGRID-Versionen: `podman rmi _image id_`
+

CAUTION: Entfernen Sie nicht die Container-Images für die derzeit ausgeführte StorageGRID-Version oder die Versionen von StorageGRID, auf die Sie aktualisieren möchten.

+
Beispiel:

+
[listing]
----
[root@podman-example ~]# podman rmi f5ef895dcad0
Untagged: localhost/storagegrid-11.6.0:Storage_Node
Deleted: f5ef895dcad0d78d0fd21a07dd132d7c7f65f45d80ee7205a4d615494e44cbb7
[root@podman-example ~]#
----


--
====