---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Bevor Sie mit dem Upgrade beginnen, überprüfen Sie, ob die vorherige Version von StorageGRID derzeit mit dem neuesten verfügbaren Hotfix installiert ist. 
---
= Überprüfen Sie die installierte StorageGRID-Version
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit dem Upgrade beginnen, überprüfen Sie, ob die vorherige Version von StorageGRID derzeit mit dem neuesten verfügbaren Hotfix installiert ist.

.Über diese Aufgabe
Bevor Sie auf StorageGRID 12.0 aktualisieren, muss auf Ihrem Grid StorageGRID 11.9.0.8 oder höher installiert sein.  Wenn Sie derzeit eine frühere Version von StorageGRID verwenden, müssen Sie alle vorherigen Upgrade-Dateien zusammen mit den neuesten Hotfixes installieren (dringend empfohlen), bis die aktuelle Version Ihres Grids mindestens StorageGRID 11.9.0.8 ist.

Ein möglicher Upgrade-Pfad wird im angezeigt<<example-upgrade-path,Beispiel>>.


CAUTION: NetApp empfiehlt dringend, dass Sie vor dem Upgrade auf die nächste Version den neuesten Hotfix für jede StorageGRID Version anwenden und dass Sie auch für jede neue Version, die Sie installieren, den neuesten Hotfix anwenden.  In einigen Fällen müssen Sie einen Hotfix anwenden, um das Risiko eines Datenverlusts zu vermeiden.  Siehe https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] und die Versionshinweise zu jedem Hotfix, um mehr zu erfahren.



== Überprüfen der installierten Version

.Schritte
. Melden Sie sich mit einem beim Grid-Manager anlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
. Wählen Sie oben im Grid Manager die Option *Hilfe* > *Info*.
. Stellen Sie sicher, dass die *Version* 11.9.0.8 oder höher ist.
. Wenn *Version* nicht 11.9.0.8 oder höher ist, gehen Sie zu https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] um die benötigten Upgrade- und Hotfix-Dateien herunterzuladen.
. link:../upgrade/index.html["Befolgen Sie die Upgrade-Anweisungen"]für jede Version, die Sie heruntergeladen haben. link:../maintain/storagegrid-hotfix-procedure.html["Wenden Sie den neuesten Hotfix an"] für jede Version (dringend empfohlen).


Siehe das folgende Upgrade-Beispiel.



== [[example-upgrade-path]]Beispiel: Upgrade auf StorageGRID 12.0 von Version 11.8

Das folgende Beispiel zeigt die Schritte zum Upgrade von StorageGRID Version 11.8 auf Version 11.9 als Vorbereitung für ein StorageGRID 12.0-Upgrade.

Laden Sie die Software in der folgenden Reihenfolge herunter und installieren Sie sie, um Ihr System auf die Aktualisierung vorzubereiten:

. Upgrade auf die Hauptversion von StorageGRID 11.8.0.
. Wenden Sie den aktuellen StorageGRID 11.8.0._y_ Hotfix an.
. Aktualisieren Sie auf die Hauptversion von StorageGRID 11.9.0.
. Wenden Sie den Hotfix StorageGRID 11.9.0.8 oder höher an.

