---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Diese Version von StorageGRID stellt die folgenden Funktionen und Funktionsänderungen vor. 
---
= Neuerungen bei StorageGRID 12.0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Version von StorageGRID stellt die folgenden Funktionen und Funktionsänderungen vor.



== Grid-übergreifende Replizierung mit S3 Object Lock

Sie können die Grid-übergreifende Replizierung zwischen Buckets konfigurieren, wenn S3 Object Lock aktiviert ist. Siehe link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Grid-übergreifende Replizierung mit S3 Object Lock"].

NetApp empfiehlt, diese Funktion nur zwischen StorageGRID 12.0 Quell- und Ziel-Buckets zu verwenden. Diese Funktion wird jedoch zwischen StorageGRID 11.9-Quell-Buckets mit deaktivierter S3-Objektsperrung und StorageGRID 12.0-Ziel-Buckets mit aktivierter S3-Objektsperrung unterstützt.



== Sicherheit



=== Verbesserte Sicherheit für verschlüsselte Passwörter auf der Festplatte

Verbesserte Passwortsicherheit, einschließlich einer stark erhöhten Hash-Round-Anzahl für SHA512-Passwort-Hashes.



== S3 Buckets



=== Eimer verzweigen

Sie können jetzt link:../tenant/manage-branch-bucket-html["Erstellen Sie Zweige-Buckets"] für einen S3-Bucket zugreifen. Ein Branch Bucket bietet Zugriff auf S3-Bucket-Objekte, wie sie zu einem bestimmten Zeitpunkt existierten. Ein Branch Bucket ist nicht dasselbe wie ein Backup.



== Benutzeroberfläche



=== Dunkles Design

Dunkle Themen- und Systemthemeneinstellungen sind im Menü „Benutzer“ des Grid-Managers und des Tenant-Managers verfügbar.



== Verbesserungen von Grid Manager



=== Konfigurieren der Bereichserweiterung

Die Seite Regionen im Grid Manager enthält jetzt eine Registerkarte *Default Region*. Mit dieser Registerkarte können Sie die definierte Standardregion für S3-Buckets ändern. link:../ilm/configuring-regions-optional-and-s3-only.html["Weitere Informationen ."].
