---
permalink: ubuntu/automating-installation.html 
sidebar: sidebar 
keywords: how to automate ubuntu or debian installation 
summary: Die Installation des StorageGRID Host Service und die Konfiguration der Grid-Nodes können automatisiert werden. 
---
= Automatisieren der Installation (Ubuntu oder Debian)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation des StorageGRID Host Service und die Konfiguration der Grid-Nodes können automatisiert werden.

.Über diese Aufgabe
Eine Automatisierung der Implementierung kann in einem der folgenden Fälle von Nutzen sein:

* Sie verwenden bereits ein Standard-Orchestrierungs-Framework wie Ansible, Puppet oder Chef für die Implementierung und Konfiguration physischer oder virtueller Hosts.
* Sie beabsichtigen, mehrere StorageGRID Instanzen zu implementieren.
* Sie implementieren eine große, komplexe StorageGRID Instanz.


Der StorageGRID Host Service wird durch ein Paket installiert und unterstützt durch Konfigurationsdateien, die während einer manuellen Installation interaktiv erstellt oder vorab (oder programmgesteuert) vorbereitet werden können, um eine automatisierte Installation mithilfe von Standard-Orchestrierungs-Frameworks zu ermöglichen. StorageGRID bietet optionale Python-Skripte zur Automatisierung der Konfiguration von StorageGRID Appliances und des gesamten StorageGRID Systems (das „Grid“). Sie können diese Skripte direkt verwenden oder sie informieren, wie Sie die StorageGRID Installations-REST-API bei den von Ihnen selbst entwickelten Grid-Implementierungs- und Konfigurations-Tools verwenden.



== Automatisieren Sie die Installation und Konfiguration des StorageGRID-Host-Service

Die Installation des StorageGRID-Host-Service kann mithilfe von Standard-Orchestrierungs-Frameworks wie Ansible, Puppet, Chef, Fabric oder SaltStack automatisiert werden.

Der StorageGRID-Host-Service befindet sich in einer DEB-Paket und wird durch Konfigurationsdateien bestimmt, die vorab (oder programmgesteuert) für eine automatisierte Installation vorbereitet werden können. Wenn Sie bereits ein Standard-Orchestrierungs-Framework zur Installation und Konfiguration von Ubuntu oder Debian verwenden, sollte das Hinzufügen von StorageGRID zu Playbooks oder Rezepten einfach sein.

Sie können diese Aufgaben automatisieren:

. Linux Wird Installiert
. Linux Wird Konfiguriert
. Konfiguration von Host-Netzwerkschnittstellen zur Erfüllung der StorageGRID Anforderungen
. Konfiguration von Host-Storage zur Erfüllung von StorageGRID-Anforderungen
. Installation Von Docker
. Installation des StorageGRID-Hostservice
. Erstellen von StorageGRID-Knoten-Konfigurationsdateien in `/etc/storagegrid/nodes`
. Validieren der StorageGRID-Node-Konfigurationsdateien
. Starten des StorageGRID Host Service




=== Beispiel: Ansible-Rolle und Playbook

Eine Beispiel-Rolle und ein Playbook für Ansible werden dem Installationsarchiv im Ordner beigestellt `/extras`. Das Ansible Playbook zeigt, wie die `storagegrid` Rolle die Hosts vorbereitet und StorageGRID auf den Zielservern installiert. Die Rolle oder das Playbook können Sie nach Bedarf anpassen.



== Automatisieren Sie die Konfiguration von StorageGRID

Nach der Implementierung der Grid-Nodes können Sie die Konfiguration des StorageGRID Systems automatisieren.

.Bevor Sie beginnen
* Sie kennen den Speicherort der folgenden Dateien aus dem Installationsarchiv.
+
[cols="1a,1a"]
|===
| Dateiname | Beschreibung 


| configure-storagegrid.py  a| 
Python-Skript zur Automatisierung der Konfiguration



| Configure-storagegrid.sample.json  a| 
Beispielkonfigurationsdatei für die Verwendung mit dem Skript



| Configure-storagegrid.blank.json  a| 
Leere Konfigurationsdatei für die Verwendung mit dem Skript

|===
* Sie haben eine Konfigurationsdatei erstellt `configure-storagegrid.json`. Um diese Datei zu erstellen, können Sie die Beispiel-Konfigurationsdatei ändern (`configure-storagegrid.sample.json`) oder die leere Konfigurationsdatei (`configure-storagegrid.blank.json`).


.Über diese Aufgabe
Sie können das Python-Skript und die `configure-storagegrid.json` Konfigurationsdatei verwenden `configure-storagegrid.py`, um die Konfiguration Ihres StorageGRID-Systems zu automatisieren.


NOTE: Sie können das System auch mit dem Grid Manager oder der Installations-API konfigurieren.

.Schritte
. Melden Sie sich an der Linux-Maschine an, die Sie verwenden, um das Python-Skript auszuführen.
. Wechseln Sie in das Verzeichnis, in dem Sie das Installationsarchiv extrahiert haben.
+
Beispiel:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
Wo `platform` ist `debs`, `rpms` oder `vsphere`.

. Führen Sie das Python-Skript aus und verwenden Sie die von Ihnen erstellte Konfigurationsdatei.
+
Beispiel:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Ergebnis
Eine Wiederherstellungspaket- `.zip`Datei wird während des Konfigurationsprozesses generiert und in das Verzeichnis heruntergeladen, in dem Sie den Installations- und Konfigurationsprozess ausführen. Sie müssen die Recovery-Paket-Datei sichern, damit Sie das StorageGRID-System wiederherstellen können, wenn ein oder mehrere Grid-Knoten ausfallen. Zum Beispiel kopieren Sie den Text auf einen sicheren, gesicherten Netzwerkstandort und an einen sicheren Cloud-Storage-Standort.


CAUTION: Die Recovery Package-Datei muss gesichert sein, weil sie Verschlüsselungsschlüssel und Passwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.

Wenn Sie angegeben haben, dass zufällige Passwörter generiert werden sollen, öffnen Sie die `Passwords.txt` Datei und suchen Sie nach den Kennwörtern, die für den Zugriff auf Ihr StorageGRID-System erforderlich sind.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Das StorageGRID System wird installiert und konfiguriert, wenn eine Bestätigungsmeldung angezeigt wird.

[listing]
----
StorageGRID has been configured and installed.
----
.Verwandte Informationen
link:overview-of-installation-rest-api.html["REST-API für die Installation"]
