---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download ubuntu or debian installation files 
summary: Sie müssen das StorageGRID-Installationsarchiv herunterladen und die erforderlichen Dateien extrahieren. Optional können Sie die Dateien im Installationspaket manuell überprüfen. 
---
= Laden Sie die StorageGRID Installationsdateien herunter und extrahieren Sie sie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das StorageGRID-Installationsarchiv herunterladen und die erforderlichen Dateien extrahieren. Optional können Sie die Dateien im Installationspaket manuell überprüfen.

.Schritte
. Gehen Sie zum https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Download-Seite für StorageGRID"^].
. Wählen Sie die Schaltfläche zum Herunterladen der neuesten Version, oder wählen Sie eine andere Version aus dem Dropdown-Menü aus und wählen Sie *Go*.
. Melden Sie sich mit Ihrem Benutzernamen und Passwort für Ihr NetApp Konto an.
. Wenn eine Vorsichtshinweis/MustRead-Anweisung angezeigt wird, lesen Sie sie und aktivieren Sie das Kontrollkästchen.
+

CAUTION: Nachdem Sie die StorageGRID Version installiert haben, müssen Sie alle erforderlichen Hotfixes anwenden. Weitere Informationen finden Sie im link:../maintain/storagegrid-hotfix-procedure.html["Hotfix-Verfahren in der Recovery- und Wartungsanleitung"]

. Lesen Sie die Endbenutzer-Lizenzvereinbarung, aktivieren Sie das Kontrollkästchen und wählen Sie dann *Akzeptieren und fortfahren* aus.
. Wählen Sie in der Spalte *Install StorageGRID* das .tgz- oder .zip-Installationsarchiv für Ubuntu oder Debian aus.
+

NOTE: Wählen Sie die Datei aus `.zip`, wenn Sie Windows auf dem Service-Laptop ausführen.

. Speichern Sie das Installationsarchiv.
. [[ubuntu-download-verification-package]]Wenn Sie das Installationsarchiv überprüfen müssen:
+
.. Laden Sie das Paket zur Überprüfung der StorageGRID-Code-Signatur herunter. Der Dateiname für dieses Paket verwendet das Format `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`, wobei `<version-number>` die StorageGRID-Softwareversion ist.
.. Befolgen Sie die Schritte bis link:../ubuntu/download-files-verify.html["Überprüfen Sie die Installationsdateien manuell"].


. Extrahieren Sie die Dateien aus dem Installationsarchiv.
. Wählen Sie die gewünschten Dateien aus.
+
Die benötigten Dateien hängen von der geplanten Grid-Topologie und der Bereitstellung des StorageGRID Systems ab.

+

NOTE: Die in der Tabelle aufgeführten Pfade beziehen sich auf das Verzeichnis der obersten Ebene, das vom extrahierten Installationsarchiv installiert wird.



[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./DES/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./Debs/NLF000000.txt  a| 
Eine NetApp Lizenzdatei, die nicht in der Produktionsumgebung enthalten ist und für Tests und Proof of Concept-Implementierungen genutzt werden kann



| ./Debs/storagegrid-webscale-images-version-SHA.deb  a| 
DEB-Paket zum Installieren der StorageGRID-Knoten-Images auf Ubuntu oder Debian-Hosts.



| ./Debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5-Prüfsumme für die Datei `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./Debs/storagegrid-webscale-service-version-SHA.deb  a| 
DEB-Paket zur Installation des StorageGRID-Hostdienstes auf Ubuntu oder Debian-Hosts.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./Debs/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./Debs/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./Debs/storagegrid-ssoauth.py  a| 
Ein Beispiel-Python-Skript, mit dem Sie sich bei aktivierter Single-Sign-On-Funktion bei der Grid-Management-API anmelden können. Sie können dieses Skript auch für die Ping Federate-Integration verwenden.



| ./debs/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript.



| ./debs/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei zur Verwendung mit dem `configure-storagegrid.py` Skript.



| ./Debs/Extras/ansible  a| 
Beispiel-Rolle und Playbook für Ansible zur Konfiguration von Ubuntu oder Debian-Hosts für die Implementierung von StorageGRID-Containern Die Rolle oder das Playbook können Sie nach Bedarf anpassen.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) mithilfe von Active Directory oder Ping Federate aktiviert ist.



| ./debs/storagegrid-ssoauth-Azure.js  a| 
Ein Hilfsskript, das vom zugehörigen Python-Skript aufgerufen `storagegrid-ssoauth-azure.py` wird, um SSO-Interaktionen mit Azure durchzuführen.



| ./debs/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie diese Schemas verwenden, um zu bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung für Upgrade-Kompatibilitätstests haben.

|===