---
permalink: ubuntu/installing-storagegrid-webscale-host-services.html 
sidebar: sidebar 
keywords: how to install StorageGRID host services 
summary: Sie verwenden das StorageGRID DEB-Paket, um die StorageGRID-Hostdienste zu installieren. 
---
= Installation der StorageGRID Host Services
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden das StorageGRID DEB-Paket, um die StorageGRID-Hostdienste zu installieren.

.Über diese Aufgabe
In dieser Anleitung wird beschrieben, wie die Hostdienste von den DEB-Paketen installiert werden. Alternativ können Sie die im Installationarchiv enthaltenen APT-Repository-Metadaten verwenden, um die DEB-Pakete Remote zu installieren. Lesen Sie die APT-Repository-Anweisungen für Ihr Linux-Betriebssystem.

.Schritte
. Kopieren Sie die StorageGRID DEB-Pakete auf jeden Ihrer Hosts, oder stellen Sie sie auf Shared Storage zur Verfügung.
+
Legen Sie sie beispielsweise in das Verzeichnis, damit Sie im `/tmp` nächsten Schritt den Beispielbefehl verwenden können.

. Melden Sie sich bei jedem Host als Root an oder verwenden Sie ein Konto mit sudo-Berechtigung, und führen Sie die folgenden Befehle aus.
+
Sie müssen zuerst das Paket und anschließend das `service` Paket installieren `images`. Wenn Sie die Pakete in ein anderes Verzeichnis als gesetzt `/tmp` haben, ändern Sie den Befehl, um den Pfad, den Sie verwendet haben, wiederzugeben.

+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+

NOTE: Python 2.7 muss bereits installiert sein, bevor die StorageGRID-Pakete installiert werden können. Der `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb` Befehl schlägt fehl, bis Sie dies getan haben.


