---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: StorageGRID, hardening guidelines, upgrades 
summary: Sie müssen Ihr StorageGRID-System und die zugehörigen Services immer auf dem neuesten Stand halten, um sich gegen Angriffe zu wehren. 
---
= Härtungsrichtlinien für StorageGRID-Software-Upgrades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Ihr StorageGRID-System und die zugehörigen Services immer auf dem neuesten Stand halten, um sich gegen Angriffe zu wehren.



== Upgrades auf StorageGRID Software

Sofern möglich, sollten Sie ein Upgrade der StorageGRID Software auf das neueste Hauptversion oder auf das vorherige Hauptversion durchführen. Durch die aktuelle Nutzung von StorageGRID lässt sich die Zeit bis zur aktiven Nutzung bekannter Schwachstellen reduzieren und gleichzeitig die Angriffsfläche insgesamt verringern. Darüber hinaus enthalten die neuesten StorageGRID Versionen häufig Funktionen zur Erhöhung der Sicherheit, die in früheren Versionen nicht enthalten sind.

Informationen zur Verwendung der StorageGRID-Software finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^] (IMT). Wenn ein Hotfix erforderlich ist, priorisiert NetApp die Erstellung von Updates der letzten Versionen. Einige Patches sind möglicherweise nicht mit früheren Versionen kompatibel.

* Die neuesten StorageGRID-Versionen und Hotfixes können Sie unter herunterladen https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^].
* Informationen zum Upgrade der StorageGRID-Software finden Sie im link:../upgrade/performing-upgrade.html["Upgrade-Anweisungen"].
* Informationen zum Anwenden eines Hotfix finden Sie im link:../maintain/storagegrid-hotfix-procedure.html["StorageGRID Hotfix Verfahren"].




== Upgrades auf externe Dienste

Externe Dienste können Schwachstellen aufweisen, die StorageGRID indirekt betreffen.  Stellen Sie sicher, dass die Dienste, von denen StorageGRID abhängt, auf dem neuesten Stand gehalten werden.  Zu diesen Diensten gehören LDAP, KMS (oder KMIP-Server), DNS und NTP.

Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^].



== Upgrades auf Hypervisoren

Wenn die StorageGRID-Nodes auf VMware oder einem anderen Hypervisor ausgeführt werden, müssen Sie sicherstellen, dass die Hypervisor-Software und die Firmware auf dem neuesten Stand sind.

Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^].



== *Upgrades auf Linux-Knoten*

Wenn Ihre StorageGRID-Knoten Linux-Hostplattformen verwenden, müssen Sie sicherstellen, dass Sicherheitsupdates und Kernel-Updates auf das Host-Betriebssystem angewendet werden. Darüber hinaus müssen Sie Firmware-Updates auf anfällige Hardware anwenden, wenn diese Updates verfügbar sind.

Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^].
