---
permalink: harden/hardening-guidelines-for-storagegrid-nodes.html 
sidebar: sidebar 
keywords: hardening guidelines, nodes, security 
summary: StorageGRID Nodes können auf VMware Virtual Machines innerhalb einer Container-Engine auf Linux-Hosts oder als dedizierte Hardware-Appliances implementiert werden. Jeder Plattformtyp und jeder Node-Typ verfügt über eigene Best Practices zur Härtung. 
---
= Hardening-Richtlinien für StorageGRID-Knoten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID Nodes können auf VMware Virtual Machines innerhalb einer Container-Engine auf Linux-Hosts oder als dedizierte Hardware-Appliances implementiert werden. Jeder Plattformtyp und jeder Node-Typ verfügt über eigene Best Practices zur Härtung.



== [[block-remote-ipmi]]Steuern Sie den Remote-IPMI-Zugriff auf BMC

Sie können den Remote-IPMI-Zugriff für alle Appliances aktivieren oder deaktivieren, die einen BMC enthalten. Die Remote-IPMI-Schnittstelle ermöglicht jedem Benutzer mit einem BMC-Konto und Passwort den Zugriff auf Ihre StorageGRID-Geräte auf niedriger Ebene. Wenn Sie keinen Remote-IPMI-Zugriff auf den BMC benötigen, deaktivieren Sie diese Option.

* Um den Remote-IPMI-Zugriff auf den BMC im Grid Manager zu steuern, gehen Sie zu *Konfiguration* > *Sicherheit* > *Sicherheitseinstellungen* > *Geräte*:
+
** Deaktivieren Sie das Kontrollkästchen *Remote-IPMI-Zugriff aktivieren*, um den IPMI-Zugriff auf den BMC zu deaktivieren.
** Aktivieren Sie das Kontrollkästchen *Remote-IPMI-Zugriff aktivieren*, um IPMI-Zugriff auf den BMC zu aktivieren.




Weitere Informationen zur BMC Härtung finden Sie im https://media.defense.gov/2023/Jun/14/2003241405/-1/-1/0/CSI_HARDEN_BMCS.PDF["Baseboard-Management-Controller härten"^] Informationsblatt zur Cybersicherheit der https://www.nsa.gov/["Nationale Sicherheitsagentur (NSA)"^] Und https://www.cisa.gov/["Agentur für Cybersicherheit und Infrastruktursicherheit (CISA)"^] .



== Firewall-Konfiguration

Im Rahmen des System-Hardening-Prozesses müssen Sie externe Firewall-Konfigurationen überprüfen und ändern, damit der Datenverkehr nur von den IP-Adressen und den Ports akzeptiert wird, von denen er unbedingt benötigt wird.

StorageGRID verfügt über eine interne Firewall auf jedem Node, die die Sicherheit Ihres Grids erhöht, indem Sie den Netzwerkzugriff auf den Node kontrollieren können. Sie sollten link:../admin/manage-firewall-controls.html["Interne Firewall-Kontrollen verwalten"] den Netzwerkzugriff auf allen Ports verhindern, mit Ausnahme der Ports, die für Ihre spezifische Grid-Bereitstellung erforderlich sind. Die Konfigurationsänderungen, die Sie auf der Seite Firewall-Steuerung vornehmen, werden für jeden Knoten bereitgestellt.

Sie können insbesondere diese Bereiche managen:

* *Privilegierte Adressen*: Sie können ausgewählten IP-Adressen oder Subnetzen erlauben, auf Ports zuzugreifen, die durch Einstellungen auf der Registerkarte externen Zugriff verwalten geschlossen werden.
* *Externen Zugriff verwalten*: Sie können Ports schließen, die standardmäßig geöffnet sind, oder zuvor geschlossene Ports wieder öffnen.
* *Nicht vertrauenswürdiges Client-Netzwerk*: Sie können angeben, ob ein Knoten eingehenden Datenverkehr vom Client-Netzwerk sowie die zusätzlichen Ports, die geöffnet werden sollen, wenn nicht vertrauenswürdiges Client-Netzwerk konfiguriert ist, anvertraut.


Diese interne Firewall bietet zwar eine zusätzliche Schutzschicht gegen häufig vorgängige Bedrohungen, sie macht aber keine externe Firewall erforderlich.

Eine Liste aller von StorageGRID verwendeten internen und externen Ports finden Sie unterlink:../network/internal-grid-node-communications.html#storagegrid-internal-ports["Interne StorageGRID-Ports"] Undlink:../network/external-communications.html#ports-used-for-external-communications["Anschlüsse für externe Kommunikation"] .



== Deaktivieren Sie nicht verwendete Dienste

Für alle StorageGRID -Knoten sollten Sie den Zugriff auf nicht verwendete Dienste deaktivieren oder blockieren.  Wenn Sie beispielsweise DHCP nicht verwenden möchten, schließen Sie Port 68 mit dem Grid Manager.  Wählen Sie *Konfiguration* > *Firewall-Steuerung* > *Externen Zugriff verwalten*.  Ändern Sie dann den Statusschalter für Port 68 von *Offen* auf *Geschlossen*.



== Virtualisierung, Container und gemeinsam genutzte Hardware

Vermeiden Sie bei allen StorageGRID Nodes die Ausführung von StorageGRID auf derselben physischen Hardware wie die nicht vertrauenswürdige Software. Setzen Sie nicht voraus, dass ein Hypervisor-Schutz Malware den Zugriff auf StorageGRID geschützte Daten verhindert, wenn sich sowohl StorageGRID als auch Malware auf derselben physischen Hardware befinden. So nutzen beispielsweise die Meltdown- und Specter-Angriffe kritische Schwachstellen in modernen Prozessoren und ermöglichen Programmen, Daten im Arbeitsspeicher auf demselben Computer zu stehlen.



== Schutz von Nodes während der Installation

Erlauben Sie nicht vertrauenswürdigen Benutzern den Zugriff auf StorageGRID-Knoten über das Netzwerk, wenn die Knoten installiert werden. Nodes sind erst dann vollständig sicher, wenn sie sich dem Grid angeschlossen haben.



== Beschränken Sie den physischen Zugriff auf die Hardware

Sie müssen den physischen Zugriff auf StorageGRID -Hardware-Appliance-Knoten sowie auf VMware-Hosts für virtuelle Maschinen und Linux-Hosts, auf denen StorageGRID ausgeführt wird, auf autorisierte Administratoren beschränken.  Beispiele für physische Zugangskontrollen sind Schlösser, Wachen, physische Barrieren und Videoüberwachung.

Hardware-Appliance-Knoten dürfen nur von autorisierten Administratoren installiert und betrieben werden.  Erlauben Sie nicht autorisierten Administratoren keinen Zugriff auf Hardware-Appliance-Knoten.



== Richtlinien für Admin-Nodes

Admin Nodes stellen Managementservices wie Systemkonfiguration, Monitoring und Protokollierung bereit. Wenn Sie sich beim Grid Manager oder dem Tenant Manager anmelden, stellen Sie eine Verbindung zu einem Admin-Node her.

Befolgen Sie diese Richtlinien, um die Admin-Knoten in Ihrem StorageGRID-System zu sichern:

* Sichern Sie alle Admin-Knoten von nicht vertrauenswürdigen Clients, wie denen im offenen Internet. Stellen Sie sicher, dass kein nicht vertrauenswürdiger Client auf einen beliebigen Admin-Node im Grid-Netzwerk, auf das Admin-Netzwerk oder auf das Client-Netzwerk zugreifen kann.
* StorageGRID-Gruppen steuern den Zugriff auf Grid Manager- und Mandantenmanager-Funktionen. Gewähren Sie jeder Gruppe von Benutzern die erforderlichen Mindestberechtigungen für ihre Rolle, und verwenden Sie den schreibgeschützten Zugriffsmodus, um zu verhindern, dass Benutzer die Konfiguration ändern.
* Verwenden Sie bei der Verwendung von StorageGRID Load Balancer-Endpunkten Gateway-Nodes anstelle von Admin-Nodes für nicht vertrauenswürdigen Client-Datenverkehr.
* Wenn Sie nicht vertrauenswürdige Mandanten haben, erlauben Sie ihnen keinen direkten Zugriff auf den Mandantenmanager oder die Mandantenmanagement-API. Verwenden Sie stattdessen ein Mandantenportal oder ein externes Mandantenmanagement-System, das mit der Mandantenmanagement-API interagiert.
* Optional können Sie einen Administrator-Proxy verwenden, um die AutoSupport-Kommunikation zwischen Admin-Nodes und der NetApp-Unterstützung besser zu steuern. Siehe die Schritte für link:../admin/configuring-admin-proxy-settings.html["Erstellen eines Admin-Proxy"].
* Verwenden Sie optional die eingeschränkten 8443- und 9443-Ports, um die Kommunikation zwischen Grid Manager und Tenant Manager voneinander zu trennen. Blockieren Sie den gemeinsam genutzten Port 443 und beschränken Sie Mandantenanforderungen auf Port 9443, um zusätzlichen Schutz zu bieten.
* Verwenden Sie optional separate Admin-Nodes für Grid-Administratoren und Mandantenbenutzer.


Weitere Informationen finden Sie in den Anweisungen für link:../admin/index.html["Administration von StorageGRID"].



== Richtlinien für Storage-Nodes

Storage-Nodes managen und speichern Objektdaten und Metadaten. Befolgen Sie diese Richtlinien, um die Speicherknoten in Ihrem StorageGRID System zu sichern.

* Nicht vertrauenswürdige Clients dürfen keine direkte Verbindung zu Storage-Nodes herstellen. Verwenden Sie einen Load Balancer-Endpunkt, der von einem Gateway-Node oder einem Load Balancer eines Drittanbieters bereitgestellt wird.
* Aktivieren Sie keine ausgehenden Dienste für nicht vertrauenswürdige Mandanten. Wenn Sie beispielsweise das Konto für einen nicht vertrauenswürdigen Mandanten erstellen, erlauben Sie dem Mandanten nicht, seine eigene Identitätsquelle zu verwenden, und erlauben Sie nicht die Nutzung von Plattformdiensten. Siehe die Schritte für link:../admin/creating-tenant-account.html["Erstellen eines Mandantenkontos"].
* Verwenden Sie einen Drittanbieter-Load-Balancer für nicht vertrauenswürdigen Client-Datenverkehr. Der Lastausgleich von Drittanbietern bietet mehr Kontrolle und zusätzlichen Schutz vor Angriffen.
* Verwenden Sie optional einen Storage Proxy, um mehr Kontrolle über Cloud-Storage-Pools und die Kommunikation der Plattformservices von Storage Nodes zu externen Services zu erhalten. Siehe die Schritte für link:../admin/configuring-storage-proxy-settings.html["Erstellen eines Speicherproxys"].
* Optional können Sie über das Client-Netzwerk eine Verbindung zu externen Diensten herstellen.  Wählen Sie dann *Konfiguration* > *Sicherheit* > *Firewall-Steuerung* > *Nicht vertrauenswürdige Client-Netzwerke* und geben Sie an, dass das Client-Netzwerk auf dem Speicherknoten nicht vertrauenswürdig ist.  Der Speicherknoten akzeptiert keinen eingehenden Datenverkehr mehr im Client-Netzwerk, lässt jedoch weiterhin ausgehende Anfragen für Plattformdienste zu.




== Richtlinien für Gateway-Nodes

Gateway-Knoten stellen eine optionale Schnittstelle zum Lastausgleich bereit, über die Client-Anwendungen eine Verbindung zu StorageGRID herstellen können. Befolgen Sie die folgenden Richtlinien zum Sichern aller Gateway-Knoten in Ihrem StorageGRID System:

* Konfigurieren und verwenden Sie Load Balancer-Endpunkte. Siehe link:../admin/managing-load-balancing.html["Überlegungen zum Lastausgleich"].
* Verwenden Sie für nicht vertrauenswürdigen Client-Datenverkehr einen Drittanbieter-Load-Balancer zwischen Client und Gateway-Node oder Storage-Nodes. Der Lastausgleich von Drittanbietern bietet mehr Kontrolle und zusätzlichen Schutz vor Angriffen. Wenn Sie einen Load Balancer eines Drittanbieters verwenden, kann der Netzwerk-Traffic optional auch so konfiguriert werden, dass er über einen internen Load Balancer-Endpunkt geleitet oder direkt an Storage Nodes gesendet wird.
* Wenn Sie Load Balancer-Endpunkte verwenden, können Sie Clients optional über das Client-Netzwerk verbinden.  Wählen Sie dann *Konfiguration* > *Sicherheit* > *Firewall-Steuerung* > *Nicht vertrauenswürdige Client-Netzwerke* und geben Sie an, dass das Client-Netzwerk auf dem Gateway-Knoten nicht vertrauenswürdig ist.  Der Gateway-Knoten akzeptiert eingehenden Datenverkehr nur auf den Ports, die explizit als Endpunkte des Lastenausgleichs konfiguriert sind.




== Richtlinien für die Nodes von Hardware-Appliances

StorageGRID Hardware-Appliances wurden speziell für den Einsatz in einem StorageGRID System entwickelt. Einige Geräte können als Storage-Nodes verwendet werden. Andere Appliances können als Admin-Nodes oder Gateway-Nodes verwendet werden. Appliance-Nodes können mit softwarebasierten Nodes kombiniert oder voll entwickelten All-Appliance-Grids implementiert werden.

Beachten Sie diese Richtlinien zum Schutz aller Hardware-Appliance-Nodes in Ihrem StorageGRID System:

* Wenn die Appliance SANtricity System Manager zum Management des Storage Controllers verwendet, verhindern Sie, dass nicht vertrauenswürdige Clients über das Netzwerk auf SANtricity System Manager zugreifen.
* Wenn das Gerät über einen Baseboard Management Controller (BMC) verfügt, beachten Sie, dass der BMC Verwaltungsport einen Low-Level-Hardwarezugriff ermöglicht.  Verbinden Sie den BMC Verwaltungsport nur mit einem sicheren, vertrauenswürdigen internen Verwaltungsnetzwerk.
+
Sie können ein VLAN einrichten, um BMC Netzwerkverbindungen zu isolieren und den BMC Internetzugriff auf vertrauenswürdige Netzwerke zu beschränken.  Weitere Informationen zum Erzwingen der VLAN-Trennung finden Sie im https://media.defense.gov/2023/Jun/14/2003241405/-1/-1/0/CSI_HARDEN_BMCS.PDF["Baseboard-Management-Controller härten"^] Informationsblatt zur Cybersicherheit der https://www.nsa.gov/["Nationale Sicherheitsagentur (NSA)"^] Und https://www.cisa.gov/["Agentur für Cybersicherheit und Infrastruktursicherheit (CISA)"^] .

+
Wenn kein sicheres, vertrauenswürdiges internes Verwaltungsnetzwerk verfügbar ist, lassen Sie den BMC Verwaltungsport unverbunden oder blockiert.  Der technische Support kann während eines Supportfalls vorübergehenden Zugriff anfordern.

* Wenn die Appliance die Remote-Verwaltung der Controller-Hardware über Ethernet mit dem IPMI-Standard (Intelligent Platform Management Interface) unterstützt, blockieren Sie den nicht vertrauenswürdigen Datenverkehr auf Port 623.



NOTE: Sie können den Remote-IPMI-Zugriff für alle Appliances mit einem BMC aktivieren oder deaktivieren.  Die Remote-IPMI-Schnittstelle ermöglicht jedem mit einem BMC -Konto und Kennwort den Low-Level-Hardwarezugriff auf Ihre StorageGRID -Geräte.  Wenn Sie keinen Remote-IPMI-Zugriff auf den BMC benötigen, deaktivieren Sie diese Option mit einer der folgenden Methoden: + Gehen Sie im Grid Manager zu *Konfiguration* > *Sicherheit* > *Sicherheitseinstellungen* > *Geräte* und deaktivieren Sie das Kontrollkästchen *Remote-IPMI-Zugriff aktivieren*.  + Verwenden Sie in der Grid-Management-API den privaten Endpunkt: `PUT /private/bmc` .

+ Sie können auch<<block-remote-ipmi,Deaktivieren des Remote-IPMI-Zugriffs>> .

* Für Appliance-Modelle mit SED-, FDE- oder FIPS-NL-SAS-Laufwerken, die Sie mit SANtricity System Manager managen, https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/accessing-and-configuring-santricity-system-manager.html["Aktivieren und konfigurieren Sie die SANtricity-Laufwerksicherheit"^].
* Für Appliance-Modelle mit SED- oder FIPS-NVMe-SSDs, die Sie mit dem StorageGRID Appliance Installer und Grid Manager verwalten, https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#enable-drive-encryption["Aktivieren und konfigurieren Sie die StorageGRID-Laufwerkverschlüsselung"^] .
* Für Geräte ohne SED-, FDE- oder FIPS-Laufwerke verwenden Sie einen Key Management Server (KMS), um https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#enable-node-encryption["Aktivieren und Konfigurieren der StorageGRID -Softwareknotenverschlüsselung"^] .


.Verwandte Informationen
https://docs.netapp.com/us-en/e-series-santricity/sm-settings/overview-drive-security.html["Erfahren Sie mehr über die Laufwerkssicherheit im SANtricity System Manager"^]
