---
permalink: network/grid-network-requirements.html 
sidebar: sidebar 
keywords: grid network requirements 
summary: Befolgen Sie die folgenden Anforderungen und Richtlinien für das Grid-Netzwerk. 
---
= Anforderungen an das Grid-Netzwerk
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Befolgen Sie die folgenden Anforderungen und Richtlinien für das Grid-Netzwerk.

* Bei der Bereitstellung muss jeder Grid-Node mit dem Grid-Netzwerk verbunden sein und mit dem primären Admin-Node über die bei der Bereitstellung des Node angegebene Netzwerkkonfiguration kommunizieren können.
* Während normaler Grid-Vorgänge muss jeder Grid-Node in der Lage sein, über das Grid-Netzwerk mit allen anderen Grid-Nodes zu kommunizieren.
+

NOTE: Das Grid-Netzwerk muss direkt zwischen jedem Knoten routingfähig sein. Network Address Translation (NAT) zwischen Knoten wird nicht unterstützt.

* Wenn das Grid-Netzwerk aus mehreren Subnetzen besteht, fügen Sie sie der Grid Network Subnet List (GNSL) hinzu. Für jedes Subnetz in der GNSL werden auf allen Knoten statische Routen erstellt.

