---
permalink: tenant/deleting-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to delete tenant platform services endpoint 
summary: Sie können einen Endpunkt löschen, wenn Sie den zugeordneten Plattformdienst nicht mehr verwenden möchten. 
---
= Endpunkt für Plattformservices löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Endpunkt löschen, wenn Sie den zugeordneten Plattformdienst nicht mehr verwenden möchten.

.Bevor Sie beginnen
* Sie sind beim Tenant Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie gehören zu einer Benutzergruppe mit dem link:tenant-management-permissions.html["Verwalten von Endpunkten oder Root-Zugriffsberechtigungen"].


.Schritte
. Wählen Sie *STORAGE (S3)* > *Plattform-Services-Endpunkte* aus.
+
Die Seite Endpunkte der Plattformservices wird angezeigt und zeigt die Liste der bereits konfigurierten Endpunkte der Plattformservices an.

. Aktivieren Sie das Kontrollkästchen für jeden Endpunkt, den Sie löschen möchten.
+

NOTE: Wenn Sie einen Endpunkt für Plattformservices löschen, der verwendet wird, wird der zugehörige Plattformdienst für alle Buckets deaktiviert, die den Endpunkt verwenden. Alle noch nicht abgeschlossenen Anfragen werden gelöscht. Neue Anfragen werden weiterhin generiert, bis Sie Ihre Bucket-Konfiguration so ändern, dass Sie nicht mehr auf den gelöschten URN verweisen. StorageGRID meldet diese Anfragen als nicht behebbare Fehler.

. Wählen Sie *Aktionen* > *Endpunkt löschen*.
+
Eine Bestätigungsmeldung wird angezeigt.

. Wählen Sie *Endpunkt löschen*.

