---
permalink: tenant/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: 'Sie können die Cross-Origin Resource Sharing (CORS) für Management-API-Anfragen an StorageGRID aktivieren, wenn Sie möchten, dass Daten in StorageGRID über Management-APIs einer anderen Domäne zugänglich sind.' 
---
= Aktivieren Sie StorageGRID CORS für eine Managementoberfläche
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Cross-Origin Resource Sharing (CORS) für Management-API-Anfragen an StorageGRID aktivieren, wenn Sie möchten, dass Daten in StorageGRID über Management-APIs einer anderen Domäne zugänglich sind.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Der link:tenant-management-permissions.html["Root-Zugriffsberechtigung"] bietet Zugriff auf alle CORS-Konfigurationsanforderungen.


.Über diese Aufgabe
CORS ist ein Sicherheitsmechanismus, mit dem Client-Webanwendungen in einer Domäne auf Ressourcen in einer anderen Domäne zugreifen können. Angenommen, Sie möchten ein Monitoring-Dashboard für StorageGRID in Domain erstellen `\http://www.example.com`. Durch die Aktivierung von CORS in StorageGRID for `\http://www.example.com` und „Grid Manager“ reagiert die StorageGRID-Domäne auf Anforderungen der Grid-Management-API von `\http://www.example.com`.

Management-API-Anforderungen (Mgmt-API) mit `application/json` oder- `multipart/formdata`Anforderungen für `Content-Type` werden für CORS unterstützt.

.Schritte
. Wählen Sie unter *Netzwerk* auf der StorageGRID-Konfigurationsseite *Managementschnittstelle CORS-Einstellungen* aus.
. Wählen Sie *Grid Manager*, *Tenant Manager* oder beide Optionen aus.
+
** *Grid Manager*: Aktiviert CORS für domänenübergreifende Grid Management API-Anforderungen.
** *Tenant Manager*: Aktiviert CORS für domänenübergreifende Tenant Management API-Anforderungen.


. Geben Sie die URL für die andere Domain in das Feld *Domains* ein.
+
Wählen Sie *Add another Domain* aus, wenn Sie CORS in StorageGRID für mehr als eine Domäne aktivieren möchten.

. Wählen Sie *Speichern*.


.Verwandte Informationen
link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["Konfigurieren Sie StorageGRID-CORS für Buckets und Objekte"]
