---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: Bevor Sie eine Mandantengruppe erstellen, überlegen Sie, welche Berechtigungen Sie dieser Gruppe zuweisen möchten. Über die Mandantenmanagement-Berechtigungen wird festgelegt, welche Aufgaben Benutzer mit dem Tenant Manager oder der Mandantenmanagement-API durchführen können. Ein Benutzer kann einer oder mehreren Gruppen angehören. Berechtigungen werden kumulativ, wenn ein Benutzer zu mehreren Gruppen gehört. 
---
= Mandantenmanagement-Berechtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine Mandantengruppe erstellen, überlegen Sie, welche Berechtigungen Sie dieser Gruppe zuweisen möchten. Über die Mandantenmanagement-Berechtigungen wird festgelegt, welche Aufgaben Benutzer mit dem Tenant Manager oder der Mandantenmanagement-API durchführen können. Ein Benutzer kann einer oder mehreren Gruppen angehören. Berechtigungen werden kumulativ, wenn ein Benutzer zu mehreren Gruppen gehört.

Um sich beim Tenant Manager anzumelden oder die Mandantenmanagement-API zu verwenden, müssen Benutzer einer Gruppe mit mindestens einer Berechtigung angehören. Alle Benutzer, die sich anmelden können, können die folgenden Aufgaben ausführen:

* Dashboard anzeigen
* Eigenes Kennwort ändern (für lokale Benutzer)


Für alle Berechtigungen legt die Einstellung Zugriffsmodus der Gruppe fest, ob Benutzer Einstellungen ändern und Vorgänge ausführen können oder ob sie nur die zugehörigen Einstellungen und Funktionen anzeigen können.


NOTE: Wenn ein Benutzer zu mehreren Gruppen gehört und eine beliebige Gruppe auf schreibgeschützt eingestellt ist, hat der Benutzer schreibgeschützten Zugriff auf alle ausgewählten Einstellungen und Funktionen.

Sie können einer Gruppe die folgenden Berechtigungen zuweisen.

[cols="1a,3a,3a"]
|===
| Berechtigung | Beschreibung | Details 


 a| 
Root-Zugriff
 a| 
Bietet vollständigen Zugriff auf den Tenant Manager und die Mandanten-Management-API.
 a| 



 a| 
Management Ihrer eigenen S3 Zugangsdaten
 a| 
Benutzer können ihre eigenen S3-Zugriffsschlüssel erstellen und entfernen.
 a| 
Benutzer, die diese Berechtigung nicht besitzen, sehen die Menüoption *STORAGE (S3)* > *Meine S3-Zugriffstasten* nicht.



 a| 
Alle Buckets anzeigen
 a| 
Ermöglicht Benutzern, alle Buckets und Bucket-Konfigurationen anzuzeigen.
 a| 
Benutzer, die weder die Berechtigung Alle Buckets anzeigen noch die Berechtigung Alle Buckets verwalten haben, sehen die Menüoption *Buckets* nicht.

Diese Berechtigung wird durch die Berechtigung „Alle Buckets verwalten“ ersetzt.  Es hat keine Auswirkungen auf S3-Bucket- oder Gruppenrichtlinien, die von S3-Clients oder der S3-Konsole verwendet werden.



 a| 
Managen aller Buckets
 a| 
Ermöglicht Benutzern die Verwendung des Tenant Managers und der Tenant Management API zum Erstellen und Löschen von S3-Buckets und zum Verwalten der Einstellungen für alle S3-Buckets im Tenant-Konto, unabhängig von S3-Bucket- oder Gruppenrichtlinien.
 a| 
Benutzer, die weder die Berechtigung Alle Buckets anzeigen noch die Berechtigung Alle Buckets verwalten haben, sehen die Menüoption *Buckets* nicht.

Diese Berechtigung ersetzt die Berechtigung „Alle Buckets anzeigen“.  Es hat keine Auswirkungen auf S3-Bucket- oder Gruppenrichtlinien, die von S3-Clients oder der S3-Konsole verwendet werden.



 a| 
Verwalten von Endpunkten
 a| 
Ermöglicht Benutzern die Verwendung des Tenant Managers oder der Mandanten-Management-API zum Erstellen oder Bearbeiten von Plattformdienstendpunkten, die als Ziel für StorageGRID-Plattformdienste verwendet werden.
 a| 
Benutzer, die diese Berechtigung nicht besitzen, sehen die Menüoption *Plattform-Dienste-Endpunkte* nicht.



 a| 
Verwenden Sie die Registerkarte S3 Console
 a| 
In Kombination mit der Berechtigung Alle Buckets anzeigen oder alle Buckets verwalten können Benutzer Objekte über die Registerkarte S3 Console auf der Detailseite für einen Bucket anzeigen und managen.
 a| 

|===