---
permalink: tenant/understanding-notifications-for-buckets.html 
sidebar: sidebar 
keywords: s3 bucket event notification, sequencer key 
summary: Sie können die Ereignisbenachrichtigung für einen S3-Bucket aktivieren, wenn StorageGRID Benachrichtigungen über angegebene Ereignisse an ein Kafka-Zielcluster oder Amazon Simple Notification Service senden soll. 
---
= Informieren Sie sich über Benachrichtigungen für Buckets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Ereignisbenachrichtigung für einen S3-Bucket aktivieren, wenn StorageGRID Benachrichtigungen über bestimmte Ereignisse an einen Kafka-Zielcluster, einen Webhook-Endpunkt oder den Amazon Simple Notification Service senden soll.

Beispielsweise können Sie Warnmeldungen so konfigurieren, dass sie an Administratoren über jedes Objekt, das einem Bucket hinzugefügt wurde, gesendet werden, wo die Objekte Protokolldateien darstellen, die mit einem kritischen Systemereignis verbunden sind.

Ereignisbenachrichtigungen werden auf dem Quell-Bucket erstellt, wie in der Benachrichtigungskonfiguration angegeben, und werden an das Ziel übergeben. Wenn ein Ereignis, das einem Objekt zugeordnet ist, erfolgreich ist, wird eine Benachrichtigung über dieses Ereignis erstellt und für die Bereitstellung in die Warteschlange verschoben.

Die Eindeutigkeit und Bestellung von Benachrichtigungen ist nicht garantiert. Möglicherweise werden mehrere Benachrichtigungen zu einem Ereignis an das Ziel übermittelt, da die Maßnahmen zur Sicherstellung des Liefererfolgs durchgeführt werden. Da die Bereitstellung asynchron ist, entspricht die Reihenfolge der Benachrichtigungen am Ziel nicht der Reihenfolge der Ereignisse auf dem Quell-Bucket. Dies gilt insbesondere für Vorgänge, die von unterschiedlichen StorageGRID-Standorten stammen. Sie können den Schlüssel in der Ereignismeldung verwenden `sequencer`, um die Reihenfolge der Ereignisse für ein bestimmtes Objekt zu bestimmen, wie in der Amazon S3-Dokumentation beschrieben.

StorageGRID-Ereignisbenachrichtigungen folgen mit einigen Einschränkungen der Amazon S3-API.

* Die folgenden Ereignistypen werden unterstützt:
+
** s3:ObjectCreated:
** s3:ObjectCreated:Put
** s3:ObjectCreated:Post
** s3:ObjectCreated:Copy
** s3:ObjectCreated:CompleteMultipartUpload
** s3:ObjectRemoved:
** s3:ObjectRemoved:Löschen
** s3:ObjectRemoved:DeleteMarkerCreated
** s3:ObjectRestore:Post


* Aus StorageGRID gesendete Ereignisbenachrichtigungen verwenden das Standard-JSON-Format, enthalten aber keine Schlüssel und verwenden bestimmte Werte für andere, wie in der Tabelle gezeigt:


[cols="1a,2a"]
|===
| Schlüsselname | Wert von StorageGRID 


 a| 
EventSource
 a| 
`sgws:s3`



 a| 
AwsRegion
 a| 
_Nicht enthalten_



 a| 
X-amz-id-2
 a| 
_Nicht enthalten_



 a| 
arn
 a| 
`urn:sgws:s3:::bucket_name`

|===