---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Wenn Sie beim Erstellen des Buckets die S3-Objektsperre aktiviert haben, können Sie den Bucket bearbeiten, um die Standardeinstellungen für die Aufbewahrung zu ändern. Sie können die Standardaufbewahrung aktivieren (oder deaktivieren) und einen Standardaufbewahrungsmodus und eine Standardaufbewahrungsdauer festlegen.' 
---
= Aktualisieren Sie die S3 Object Lock-Standardaufbewahrung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie beim Erstellen des Buckets die S3-Objektsperre aktiviert haben, können Sie den Bucket bearbeiten, um die Standardeinstellungen für die Aufbewahrung zu ändern. Sie können die Standardaufbewahrung aktivieren (oder deaktivieren) und einen Standardaufbewahrungsmodus und eine Standardaufbewahrungsdauer festlegen.

.Bevor Sie beginnen
* Sie sind beim Tenant Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie gehören zu einer Benutzergruppe mit dem link:tenant-management-permissions.html["Managen aller Buckets oder Root-Zugriffsberechtigungen"]. Diese Berechtigungen überschreiben die Berechtigungseinstellungen in Gruppen- oder Bucket-Richtlinien.
* S3 Objektsperre ist global für Ihr StorageGRID-System aktiviert; Sie haben S3 Objektsperre bei Erstellung des Buckets aktiviert. Siehe link:using-s3-object-lock.html["Verwenden Sie S3 Objektsperre, um Objekte beizubehalten"].


.Schritte
. Wählen Sie *View Buckets* aus dem Dashboard, oder wählen Sie *STORAGE (S3)* > *Buckets*.
. Wählen Sie den Bucket-Namen aus der Tabelle aus.
+
Die Seite mit den Bucket-Details wird angezeigt.

. Wählen Sie auf der Registerkarte *Bucket options* das Akkordeon *S3 Object Lock* aus.
. Aktivieren oder deaktivieren Sie optional *Default Retention* für diesen Bucket.
+
Änderungen an dieser Einstellung gelten nicht für Objekte, die bereits im Bucket vorhanden sind, oder für Objekte, die möglicherweise eigene Aufbewahrungsfristen haben.

. Wenn *Default Retention* aktiviert ist, geben Sie einen *Default Retention Mode* für den Bucket an.
+
[cols="1a,2a"]
|===
| Standardaufbewahrungsmodus | Beschreibung 


 a| 
Governance
 a| 
** Benutzer mit der `s3:BypassGovernanceRetention` Berechtigung können den Anforderungskopf verwenden `x-amz-bypass-governance-retention: true`, um die Aufbewahrungseinstellungen zu umgehen.
** Diese Benutzer können eine Objektversion löschen, bevor das Aufbewahrungsdatum erreicht ist.
** Diese Benutzer können das Aufbewahrungsdatum eines Objekts erhöhen, verringern oder entfernen.




 a| 
Compliance
 a| 
** Das Objekt kann erst gelöscht werden, wenn das Aufbewahrungsdatum erreicht ist.
** Das Aufbewahrungsdatum des Objekts kann erhöht, aber nicht verringert werden.
** Das Aufbewahrungsdatum des Objekts kann erst entfernt werden, wenn dieses Datum erreicht ist.


*Hinweis*: Ihr Grid-Administrator muss Ihnen erlauben, den Compliance-Modus zu verwenden.

|===
. Wenn *Default Retention* aktiviert ist, geben Sie die *Default Retention Period* für den Bucket an.
+
Die *Default Retention Period* gibt an, wie lange neue Objekte zu diesem Bucket hinzugefügt werden sollen, beginnend mit dem Zeitpunkt, zu dem sie aufgenommen werden. Geben Sie einen Wert an, der kleiner oder gleich der maximalen Aufbewahrungsfrist für den Mandanten ist, wie vom Grid-Administrator festgelegt.

+
Eine _maximale_ Aufbewahrungsfrist, die ein Wert von 1 Tag bis 100 Jahre sein kann, wird festgelegt, wenn der Grid-Administrator den Mandanten erstellt. Wenn Sie eine _default_ Aufbewahrungsfrist festlegen, darf sie den für die maximale Aufbewahrungsfrist festgelegten Wert nicht überschreiten. Bitten Sie bei Bedarf Ihren Grid-Administrator, die maximale Aufbewahrungsfrist zu verlängern oder zu verkürzen.

. Wählen Sie *Änderungen speichern*.

