---
permalink: tenant/viewing-s3-bucket-details.html 
sidebar: sidebar 
keywords: how to view bucket details 
summary: Sie können die Buckets in Ihrem Mandantenkonto anzeigen. 
---
= Bucket-Details anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Buckets in Ihrem Mandantenkonto anzeigen.

.Bevor Sie beginnen
* Sie sind beim Tenant Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie gehören zu einer Benutzergruppe mit dem link:tenant-management-permissions.html["Root-Zugriff, Alle Buckets verwalten oder Alle Buckets anzeigen"]. Diese Berechtigungen überschreiben die Berechtigungseinstellungen in Gruppen- oder Bucket-Richtlinien.


.Schritte
. Wählen Sie *View Buckets* aus dem Dashboard, oder wählen Sie *STORAGE (S3)* > *Buckets*.
+
Die Seite „Buckets“ wird angezeigt.

. Überprüfen Sie die Übersichtstabelle für jeden Bucket.
+
Bei Bedarf können Sie die Informationen nach einer beliebigen Spalte sortieren oder Sie können die Seite vorwärts und zurück durch die Liste blättern.

+

NOTE: Bei den angezeigten Werten für Objektanzahl, belegter Speicherplatz und Nutzung handelt es sich um Schätzwerte. Diese Schätzungen sind vom Zeitpunkt der Aufnahme, der Netzwerkverbindung und des Node-Status betroffen. Wenn Buckets die Versionierung aktiviert ist, sind gelöschte Objektversionen in der Objektanzahl enthalten.

+
Name:: Der eindeutige Name des Buckets, der nicht geändert werden kann.
Aktivierte Funktionen:: Die Liste der Funktionen, die für den Bucket aktiviert sind.
S3-Objektsperre:: Gibt an, ob S3 Object Lock für den Bucket aktiviert ist.
+
--
Diese Spalte wird nur angezeigt, wenn die S3-Objektsperre für das Raster aktiviert ist. In dieser Spalte werden außerdem Informationen für alle Buckets angezeigt, die für die Konformität mit älteren Daten verwendet wurden.

--
Region:: Der Bereich des Eimers, der nicht geändert werden kann. Diese Spalte ist standardmäßig ausgeblendet.
Objektanzahl:: Die Anzahl der Objekte in diesem Bucket. Wenn für Buckets die Versionierung aktiviert ist, sind nicht aktuelle Objektversionen in diesem Wert enthalten.
+
--
Wenn Objekte hinzugefügt oder gelöscht werden, wird dieser Wert möglicherweise nicht sofort aktualisiert.

--
Belegten Speicherplatz:: Die logische Größe aller Objekte im Bucket Die logische Größe umfasst nicht den tatsächlich benötigten Speicherplatz für replizierte oder Erasure Coding-Kopien oder für Objekt-Metadaten.
+
--
Die Aktualisierung dieses Werts kann bis zu 10 Minuten dauern.

--
Zu Verwenden:: Der Prozentsatz, der vom Kapazitätslimit des Buckets verwendet wird, sofern ein Wert festgelegt wurde.
+
--
Der Nutzungswert basiert auf internen Schätzungen und kann in einigen Fällen überschritten werden. StorageGRID überprüft beispielsweise das Kapazitätslimit (sofern festgelegt), wenn ein Mandant beginnt, Objekte hochzuladen, und lehnt neue Ingest für diesen Bucket ab, wenn der Mandant das Kapazitätslimit überschritten hat. StorageGRID berücksichtigt jedoch nicht die Größe des aktuellen Uploads, wenn festgestellt wird, ob das Kapazitätslimit überschritten wurde. Wenn Objekte gelöscht werden, kann es vorkommen, dass ein Mandant vorübergehend verhindert wird, neue Objekte in diesen Bucket hochzuladen, bis die Auslastung der Kapazitätsgrenze neu berechnet wird. Die Berechnungen können 10 Minuten oder länger dauern.

Dieser Wert gibt die logische Größe und nicht die physische Größe an, die zum Speichern der Objekte und ihrer Metadaten erforderlich ist.

--
Kapazität:: Wenn festgelegt, wird das Kapazitätslimit des Buckets festgelegt.
Erstellungsdatum:: Datum und Uhrzeit der Erstellung des Buckets. Diese Spalte ist standardmäßig ausgeblendet.


. Um Details für einen bestimmten Bucket anzuzeigen, wählen Sie den Bucket-Namen aus der Tabelle aus.
+
.. Zeigen Sie die zusammenfassenden Informationen oben auf der Webseite an, um die Details für den Bucket zu bestätigen, z. B. Region und Objektanzahl.
.. Zeigen Sie die Balken für die Kapazitätslimitnutzung und die Objektanzahllimitnutzung an.  Wenn die Nutzung 100 % oder nahe 100 % beträgt, sollten Sie eine Erhöhung des Limits oder das Löschen einiger Objekte in Erwägung ziehen.
.. Wählen Sie bei Bedarf *Objekte im Bucket löschen* und *Bucket löschen* aus.
+
[CAUTION]
====
Achten Sie bei der Auswahl dieser Optionen genau auf die Warnhinweise. Weitere Informationen finden Sie unter:

*** link:deleting-s3-bucket-objects.html["Löschen aller Objekte in einem Bucket"]
*** link:deleting-s3-bucket.html["Löschen eines Buckets"] (Bucket muss leer sein)


====
.. Zeigen Sie die Einstellungen für den Bucket auf den einzelnen Registerkarten nach Bedarf an, oder ändern Sie sie.
+
*** *S3 Console*: Zeigt die Objekte für den Bucket an. Weitere Informationen finden Sie unter link:use-s3-console.html["Verwenden Sie die S3-Konsole"].
*** *Bucket-Optionen*: Optionen anzeigen oder ändern. Einige Einstellungen, wie z. B. S3 Object Lock, können nach dem Erstellen des Buckets nicht geändert werden.
+
**** link:manage-bucket-consistency.html["Management der Bucket-Konsistenz"]
**** link:enabling-or-disabling-last-access-time-updates.html["Aktualisierung der Uhrzeit des letzten Zugriffs"]
**** link:../tenant/creating-s3-bucket.html#capacity-limit["Kapazitätsgrenze"]
**** link:../tenant/creating-s3-bucket.html#object-count-limit["Objektanzahllimit"]
**** link:changing-bucket-versioning.html["Objektversionierung"]
**** link:using-s3-object-lock.html["S3-Objektsperre"]
**** link:update-default-retention-settings.html["Standardmäßige Bucket-Aufbewahrung"]
**** link:grid-federation-manage-cross-grid-replication.html["Grid-übergreifende Replizierung managen"] (Falls für den Mieter zulässig)


*** *Plattform-Services*: link:considerations-for-platform-services.html["Management von Plattform-Services"] (Wenn für den Mieter erlaubt)
*** *Bucket Access*: Optionen anzeigen oder ändern. Sie müssen über spezifische Zugriffsberechtigungen verfügen.
+
**** Konfigurierenlink:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["CORS für Buckets und Objekte"] sodass der Bucket und die Objekte im Bucket für Webanwendungen in anderen Domänen zugänglich sind.
**** link:../tenant/manage-bucket-policy.html["Kontrolle des Benutzerzugriffs"] Für einen S3-Bucket und Objekte in diesem Bucket.


*** *Branches*: Zeigen Sie die Liste der Branch-Buckets für den Bucket an. link:../tenant/manage-branch-buckets.html["Erstellen Sie einen neuen Branch-Bucket oder verwalten Sie Branch-Buckets"] .





