---
permalink: vmware/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Sie können eine virtuelle Maschine zum Hosten eines beliebigen Typs von StorageGRID-Knoten verwenden. Für jeden Grid-Node benötigen Sie eine virtuelle Maschine. 
---
= Softwareanforderungen für VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine virtuelle Maschine zum Hosten eines beliebigen Typs von StorageGRID-Knoten verwenden. Für jeden Grid-Node benötigen Sie eine virtuelle Maschine.



== VMware vSphere Hypervisor

Sie müssen VMware vSphere Hypervisor auf einem vorbereiteten physischen Server installieren. Die Hardware muss vor der Installation der VMware Software korrekt konfiguriert sein (einschließlich Firmware-Versionen und BIOS-Einstellungen).

* Zur Unterstützung des Netzwerkes für das zu installierende StorageGRID-System konfigurieren Sie das Netzwerk im Hypervisor nach Bedarf.
+
link:../network/index.html["Netzwerkrichtlinien"]

* Stellen Sie sicher, dass der Datastore groß genug für die virtuellen Maschinen und virtuellen Festplatten ist, die zum Hosten der Grid-Nodes benötigt werden.
* Wenn Sie mehr als einen Datenspeicher erstellen, benennen Sie jeden Datenspeicher. So können Sie bei der Erstellung von Virtual Machines leicht ermitteln, welchen Datenspeicher für die einzelnen Grid-Nodes verwendet werden soll.




== Konfigurationsanforderungen für den ESX Host


CAUTION: Sie müssen das Network Time Protocol (NTP) auf jedem ESX-Host ordnungsgemäß konfigurieren. Wenn die Host-Zeit falsch ist, können negative Auswirkungen, einschließlich Datenverlust, auftreten.



== Konfigurationsanforderungen für VMware

Sie müssen VMware vSphere und vCenter vor der Bereitstellung von StorageGRID-Knoten installieren und konfigurieren.

Informationen zu unterstützten Versionen von VMware vSphere Hypervisor und VMware vCenter Server-Software finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^].

Die Schritte zur Installation dieser VMware-Produkte finden Sie in der VMware-Dokumentation.
