---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: how to automate red hat linux installation 
summary: Die Installation des StorageGRID Host Service und die Konfiguration der Grid-Nodes können automatisiert werden. 
---
= Automatisieren Sie die StorageGRID-Installation auf Red hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation des StorageGRID Host Service und die Konfiguration der Grid-Nodes können automatisiert werden.

Eine Automatisierung der Implementierung kann in einem der folgenden Fälle von Nutzen sein:

* Sie verwenden bereits ein Standard-Orchestrierungs-Framework wie Ansible, Puppet oder Chef für die Implementierung und Konfiguration physischer oder virtueller Hosts.
* Sie beabsichtigen, mehrere StorageGRID Instanzen zu implementieren.
* Sie implementieren eine große, komplexe StorageGRID Instanz.


Der StorageGRID-Host-Service wird von einem Paket installiert und durch Konfigurationsdateien gesteuert. Sie können die Konfigurationsdateien mit einer der folgenden Methoden erstellen:

* link:creating-node-configuration-files.html["Erstellen Sie die Konfigurationsdateien"] Interaktiv während einer manuellen Installation.
* Bereiten Sie die Konfigurationsdateien vorab (oder programmatisch) auf die automatisierte Installation mithilfe von Standard-Orchestrierungs-Frameworks vor, wie in diesem Artikel beschrieben.
+
StorageGRID bietet optionale Python-Skripte zur Automatisierung der Konfiguration von StorageGRID Appliances und des gesamten StorageGRID-Systems (das „Grid“). Sie können diese Skripte direkt verwenden oder sie überprüfen, um zu erfahren, wie Sie die  in Grid Deployment und Konfigurationstools verwendenlink:overview-of-installation-rest-api.html["REST-API für die StorageGRID Installation"], die Sie selbst entwickeln.





== Automatisieren Sie die Installation und Konfiguration des StorageGRID-Host-Service

Die Installation des StorageGRID-Host-Service kann mithilfe von Standard-Orchestrierungs-Frameworks wie Ansible, Puppet, Chef, Fabric oder SaltStack automatisiert werden.

Der StorageGRID-Host-Service ist eine RPM und orientiert sich an Konfigurationsdateien, die Sie für die automatisierte Installation vorab (oder programmgesteuert) vorbereiten können. Wenn Sie bereits ein Standard-Orchestrierungs-Framework für die Installation und Konfiguration von RHEL verwenden, wäre es ganz einfach, StorageGRID in Ihre Playbooks oder Rezepte hinzuzufügen.

Sehen Sie sich die Beispiel-Rolle und das Playbook „Ansible“ in dem `/extras` Ordner an, der dem Installationsarchiv beiliegt. Das Ansible Playbook zeigt, wie die `storagegrid` Rolle den Host vorbereitet und StorageGRID auf den Zielservern installiert. Die Rolle oder das Playbook können Sie nach Bedarf anpassen.


NOTE: Das Beispiel-Playbook enthält nicht die Schritte, die zum Erstellen von Netzwerkgeräten vor dem Start des StorageGRID-Hostdienstes erforderlich sind. Fügen Sie diese Schritte vor der Fertigstellung und Verwendung des Playbook ein.

Sie können alle Schritte zur Vorbereitung der Hosts automatisieren und virtuelle Grid-Nodes implementieren.



=== Beispiel: Ansible-Rolle und Playbook

Eine Beispiel-Rolle und ein Playbook für Ansible werden dem Installationsarchiv im Ordner beigestellt `/extras`. Das Ansible Playbook zeigt, wie die `storagegrid` Rolle die Hosts vorbereitet und StorageGRID auf den Zielservern installiert. Die Rolle oder das Playbook können Sie nach Bedarf anpassen.

Die Installationsaufgaben im angegebenen `storagegrid` Rollenbeispiel verwenden das `ansible.builtin.dnf` Modul, um die Installation aus den lokalen RPM-Dateien oder einem externen Yum-Repository durchzuführen. Wenn das Modul nicht verfügbar ist oder nicht unterstützt wird, müssen Sie möglicherweise die entsprechenden Ansible-Aufgaben in den folgenden Dateien bearbeiten, um das Modul oder `ansible.builtin.yum` zu verwenden `yum`:

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`




== Automatisieren Sie die Konfiguration von StorageGRID

Nach der Implementierung der Grid-Nodes können Sie die Konfiguration des StorageGRID Systems automatisieren.

.Bevor Sie beginnen
* Sie kennen den Speicherort der folgenden Dateien aus dem Installationsarchiv.
+
[cols="1a,1a"]
|===
| Dateiname | Beschreibung 


| configure-storagegrid.py  a| 
Python-Skript zur Automatisierung der Konfiguration



| Configure-storagegrid.sample.json  a| 
Beispielkonfigurationsdatei für die Verwendung mit dem Skript



| Configure-storagegrid.blank.json  a| 
Leere Konfigurationsdatei für die Verwendung mit dem Skript

|===
* Sie haben eine Konfigurationsdatei erstellt `configure-storagegrid.json`. Um diese Datei zu erstellen, können Sie die Beispiel-Konfigurationsdatei ändern (`configure-storagegrid.sample.json`) oder die leere Konfigurationsdatei (`configure-storagegrid.blank.json`).


.Über diese Aufgabe
Sie können das Python-Skript und die `configure-storagegrid.json` Konfigurationsdatei verwenden `configure-storagegrid.py`, um die Konfiguration Ihres StorageGRID-Systems zu automatisieren.


NOTE: Sie können das System auch mit dem Grid Manager oder der Installations-API konfigurieren.

.Schritte
. Melden Sie sich an der Linux-Maschine an, die Sie verwenden, um das Python-Skript auszuführen.
. Wechseln Sie in das Verzeichnis, in dem Sie das Installationsarchiv extrahiert haben.
+
Beispiel:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
Wo `platform` ist `debs`, `rpms` oder `vsphere`.

. Führen Sie das Python-Skript aus und verwenden Sie die von Ihnen erstellte Konfigurationsdatei.
+
Beispiel:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Ergebnis
Eine Wiederherstellungspaket- `.zip`Datei wird während des Konfigurationsprozesses generiert und in das Verzeichnis heruntergeladen, in dem Sie den Installations- und Konfigurationsprozess ausführen. Sie müssen die Recovery-Paket-Datei sichern, damit Sie das StorageGRID-System wiederherstellen können, wenn ein oder mehrere Grid-Knoten ausfallen. Zum Beispiel kopieren Sie den Text auf einen sicheren, gesicherten Netzwerkstandort und an einen sicheren Cloud-Storage-Standort.


CAUTION: Die Recovery Package-Datei muss gesichert sein, weil sie Verschlüsselungsschlüssel und Passwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.

Wenn Sie angegeben haben, dass zufällige Passwörter generiert werden, öffnen Sie die `Passwords.txt` Datei und suchen Sie nach den Kennwörtern, die für den Zugriff auf Ihr StorageGRID-System erforderlich sind.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Das StorageGRID System wird installiert und konfiguriert, wenn eine Bestätigungsmeldung angezeigt wird.

[listing]
----
StorageGRID has been configured and installed.
----
.Verwandte Informationen
link:overview-of-installation-rest-api.html["REST-API für die Installation"]
