---
permalink: rhel/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure container engine storage volume, Docker, Podman 
summary: 'Vor der Installation der Container-Engine (Docker oder Podman) müssen Sie möglicherweise das Storage-Volume formatieren und mounten.' 
---
= Konfigurieren des Container Engine Storage Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation der Container-Engine (Docker oder Podman) müssen Sie möglicherweise das Storage-Volume formatieren und mounten.


NOTE: Die Unterstützung für Docker als Container-Engine für rein softwarebasierte Implementierungen ist veraltet. Docker wird in einer zukünftigen Version durch eine weitere Container-Engine ersetzt.

.Über diese Aufgabe
Sie können diese Schritte überspringen, wenn Sie den lokalen Speicher für das Docker- oder Podman-Speichervolume verwenden möchten und auf der Host-Partition, die Docker und `/var/lib/containers` Podman enthält, ausreichend Speicherplatz zur Verfügung steht `/var/lib/docker`.


NOTE: Podman wird nur auf Red hat Enterprise Linux (RHEL) unterstützt.

.Schritte
. Dateisystem auf dem Container-Engine-Storage-Volume erstellen:
+
[listing]
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
. Mounten des Container-Engine-Storage-Volumes:
+
** Für Docker:
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
** Für Podman:
+
[listing]
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----


. Fügen Sie einen Eintrag für Container-Storage-Volume-Device zu /etc/fstab hinzu.
+
Mit diesem Schritt wird sichergestellt, dass das Storage Volume nach einem Neustart des Hosts automatisch neu eingebunden wird.





== Installation Von Docker

Das StorageGRID-System läuft unter Red hat Enterprise Linux als eine Sammlung von Containern. Wenn Sie sich für die Verwendung der Docker Container-Engine entschieden haben, führen Sie die folgenden Schritte aus, um Docker zu installieren. Andernfalls <<Installieren Sie Podman,Installieren Sie Podman>>.

.Schritte
. Installieren Sie Docker gemäß den Anweisungen für Ihre Linux-Distribution.
+

NOTE: Wenn Docker nicht in Ihrer Linux Distribution enthalten ist, können Sie sie über die Docker Website herunterladen.

. Vergewissern Sie sich, dass Docker aktiviert und gestartet wurde, indem Sie die folgenden beiden Befehle ausführen:
+
[listing]
----
sudo systemctl enable docker
----
+
[listing]
----
sudo systemctl start docker
----
. Vergewissern Sie sich, dass Sie die erwartete Version von Docker installiert haben, indem Sie Folgendes eingeben:
+
[listing]
----
sudo docker version
----
+
Die Client- und Server-Versionen müssen 1.11.0 oder höher sein.





== Installieren Sie Podman

Das StorageGRID-System läuft unter Red hat Enterprise Linux als eine Sammlung von Containern. Wenn Sie sich für die Verwendung der Podman Container-Engine entschieden haben, befolgen Sie diese Schritte, um Podman zu installieren. Andernfalls <<Installation Von Docker,Installation von Docker>>.


NOTE: Podman wird nur auf Red hat Enterprise Linux (RHEL) unterstützt.

.Schritte
. Installieren Sie Podman und Podman-Docker, indem Sie den Anweisungen für Ihre Linux-Distribution folgen.
+

NOTE: Bei der Installation von Podman müssen Sie auch das Podman-Docker-Paket installieren.

. Vergewissern Sie sich, dass Sie die erwartete Version von Podman und Podman-Docker installiert haben, indem Sie Folgendes eingeben:
+
[listing]
----
sudo docker version
----
+

NOTE: Das Podman-Docker Paket ermöglicht die Verwendung von Docker Befehlen.

+
Die Client- und Server-Versionen müssen 3.2.3 oder höher sein.

+
[listing]
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----

