---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: Sie müssen StorageGRID auf allen Red hat Enterprise Linux Grid-Hosts installieren. Eine Liste der unterstützten Versionen finden Sie im NetApp Interoperabilitäts-Matrix-Tool. 
---
= Installieren Sie Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen StorageGRID auf allen Red hat Enterprise Linux Grid-Hosts installieren. Eine Liste der unterstützten Versionen finden Sie im NetApp Interoperabilitäts-Matrix-Tool.

.Bevor Sie beginnen
Stellen Sie sicher, dass Ihr Betriebssystem die Mindestanforderungen für die Kernel-Version von StorageGRID erfüllt, wie unten aufgeführt. Verwenden Sie den Befehl `uname -r`, um die Kernel-Version Ihres Betriebssystems zu erhalten, oder wenden Sie sich an den Hersteller Ihres Betriebssystems.

[cols="1a,2a,2a"]
|===
| Red hat Enterprise Linux-Version | Minimale Kernel-Version | Name des Kernel-Pakets 


 a| 
8.8 (veraltet)
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
Kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8.10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
Kernel-4.18.0-553.el8_10.x86_64



 a| 
9.0 (veraltet)
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
Kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9.2 (veraltet)
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
Kernel-5.14.0-284.11.1.el9_2.x86_64



 a| 
9,4
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
Kernel-5.14.0-427.18.1.el9_4.x86_64

|===
.Schritte
. Installieren Sie Linux auf allen physischen oder virtuellen Grid-Hosts gemäß den Anweisungen des Distributors oder dem Standardverfahren.
+

NOTE: Wenn Sie das Standard-Linux-Installationsprogramm verwenden, wählen Sie die Softwarekonfiguration „Compute Node“, falls verfügbar, oder die Basisumgebung „Minimal Install“ aus. Installieren Sie keine grafischen Desktop-Umgebungen.

. Stellen Sie sicher, dass alle Hosts Zugriff auf Paket-Repositorys haben, einschließlich des Extras-Kanals.
+
Möglicherweise benötigen Sie diese zusätzlichen Pakete später in diesem Installationsvorgang.

. Wenn Swap aktiviert ist:
+
.. Führen Sie den folgenden Befehl aus: `$ sudo swapoff --all`
.. Entfernen Sie alle Swap-Einträge aus `/etc/fstab`, um die Einstellungen beizubehalten.


+

NOTE: Wenn Sie den Auslagerungsaustausch nicht vollständig deaktivieren, kann die Leistung erheblich gesenkt werden.


