---
permalink: rhel/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Sie können eine virtuelle Maschine zum Hosten eines beliebigen Typs von StorageGRID-Knoten verwenden. Für jeden Grid-Node benötigen Sie eine virtuelle Maschine. 
---
= Softwareanforderungen für Red hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine virtuelle Maschine zum Hosten eines beliebigen Typs von StorageGRID-Knoten verwenden. Für jeden Grid-Node benötigen Sie eine virtuelle Maschine.

Um StorageGRID auf Red hat Enterprise Linux (RHEL) zu installieren, müssen Sie einige Softwarepakete von Drittanbietern installieren. Einige unterstützte Linux-Distributionen enthalten diese Pakete standardmäßig nicht. Die Software-Paketversionen, auf denen StorageGRID-Installationen getestet werden, enthalten die auf dieser Seite aufgeführten.

Wenn Sie eine Linux-Distribution und eine Container-Laufzeitinstallation auswählen, für die eines dieser Pakete erforderlich ist und die nicht automatisch von der Linux-Distribution installiert werden, installieren Sie eine der hier aufgeführten Versionen, wenn diese bei Ihrem Provider oder dem Support-Anbieter für Ihre Linux-Distribution verfügbar sind. Verwenden Sie andernfalls die Standardpaketversionen, die Sie von Ihrem Hersteller erhalten.

Für alle Installationsoptionen ist Podman oder Docker erforderlich. Installieren Sie nicht beide Pakete. Installieren Sie nur das für Ihre Installationsoption erforderliche Paket.


NOTE: Die Unterstützung für Docker als Container-Engine für rein softwarebasierte Implementierungen ist veraltet. Docker wird in einer zukünftigen Version durch eine weitere Container-Engine ersetzt.



== Python-Versionen getestet

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== Podman-Versionen getestet

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12




== Getestete Docker-Versionen


IMPORTANT: Die Docker-Unterstützung ist veraltet und wird in einer zukünftigen Version entfernt.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23.0.6-1
* Docker-CE 24.0.2-1
* Docker-CE 24.0.4-1
* Docker-CE 24.0.5-1
* Docker-CE 24.0.7-1
* 1,5-2

