---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: Wenn Sie die SSH-Zugriffskennwörter für Admin-Nodes ändern, werden auch die eindeutigen Sätze interner SSH-Schlüssel für jeden Node im Grid aktualisiert. Der primäre Admin-Node verwendet diese SSH-Schlüssel, um mit einer sicheren Authentifizierung ohne Kennwort auf Knoten zuzugreifen. 
---
= Ändern Sie die SSH-Zugriffskennwörter für Admin-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die SSH-Zugriffskennwörter für Admin-Nodes ändern, werden auch die eindeutigen Sätze interner SSH-Schlüssel für jeden Node im Grid aktualisiert. Der primäre Admin-Node verwendet diese SSH-Schlüssel, um mit einer sicheren Authentifizierung ohne Kennwort auf Knoten zuzugreifen.

Verwenden Sie einen SSH-Schlüssel, um sich bei einem Node als `admin` oder beim Root-Benutzer auf einer VM- oder physischen Konsolenverbindung anzumelden.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Sie haben die aktuelle Provisionierungs-Passphrase.


.Über diese Aufgabe
Die neuen Zugriffskennwörter für Admin-Knoten und die neuen internen Schlüssel für jeden Knoten werden in der Datei im Wiederherstellungspaket gespeichert `Passwords.txt`. Die Schlüssel werden in der Spalte Kennwort in dieser Datei aufgeführt.

Separate SSH-Zugriffskennwörter für die SSH-Schlüssel, die für die Kommunikation zwischen den Nodes verwendet werden. Diese werden durch dieses Verfahren nicht geändert.



== Greifen Sie auf den Assistenten zu

.Schritte
. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Grid-Passwörter*.
. Wählen Sie unter *SSH-Schlüssel ändern* *Änderung vornehmen*.




== [[download-current]]Laden Sie das aktuelle Wiederherstellungspaket herunter

Laden Sie vor dem Ändern der SSH-Zugriffsschlüssel das aktuelle Wiederherstellungspaket herunter. Sie können die Schlüssel in dieser Datei verwenden, wenn die Schlüsseländerung für einen Node fehlschlägt.

.Schritte
. Geben Sie die Provisionierungs-Passphrase für Ihr Grid ein.
. Wählen Sie *Wiederherstellungspaket herunterladen*.
. Kopieren Sie die Wiederherstellungspaket-Datei (`.zip`) in zwei sichere und separate Speicherorte.
+

CAUTION: Die Recovery Package-Datei muss gesichert sein, weil sie Verschlüsselungsschlüssel und Passwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.

. Wählen Sie *Weiter*.
. Wenn das Bestätigungsdialogfeld angezeigt wird, wählen Sie *Yes* aus, wenn Sie bereit sind, die SSH-Zugriffsschlüssel zu ändern.
+

CAUTION: Sie können diesen Vorgang nach dem Start nicht abbrechen.





== Ändern Sie die SSH-Zugriffsschlüssel

Wenn der SSH-Zugriffsschlüssel-Änderungsprozess startet, wird ein neues Wiederherstellungspaket mit den neuen Schlüsseln generiert. Anschließend werden die Schlüssel auf jedem Node aktualisiert.

.Schritte
. Warten Sie, bis das neue Wiederherstellungspaket erstellt wurde. Dies kann einige Minuten dauern.
. Wenn die Schaltfläche Neues Wiederherstellungspaket herunterladen aktiviert ist, wählen Sie *Neues Wiederherstellungspaket herunterladen* und speichern Sie die neue Wiederherstellungspaket-Datei (`.zip`) an zwei sicheren, sicheren und separaten Speicherorten.
. Wenn der Download abgeschlossen ist:
+
.. Öffnen Sie die `.zip` Datei.
.. Bestätigen Sie, dass Sie auf den Inhalt zugreifen können, einschließlich der `Passwords.txt` Datei, die die neuen SSH-Zugriffsschlüssel enthält.
.. Kopieren Sie die neue Recovery Package-Datei (`.zip`) in zwei sichere und separate Speicherorte.
+

CAUTION: Überschreiben Sie das alte Wiederherstellungspaket nicht.

+
Die Recovery Package-Datei muss gesichert sein, weil sie Verschlüsselungsschlüssel und Passwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.



. Warten Sie, bis die Schlüssel auf jedem Node aktualisiert werden. Dies kann einige Minuten dauern.
+
Wenn die Schlüssel für alle Nodes geändert werden, wird ein grünes Success-Banner angezeigt.

+
Wenn während des Aktualisierungsvorgangs ein Fehler auftritt, wird in einer Banner-Meldung die Anzahl der Knoten aufgeführt, bei denen die Schlüssel nicht geändert wurden. Das System wiederholt den Prozess automatisch auf jedem Node, bei dem der Schlüssel nicht geändert wurde. Wenn der Prozess mit einigen Knoten endet, die noch keinen geänderten Schlüssel haben, wird die Schaltfläche *Wiederholen* angezeigt.

+
Wenn das Schlüsselupdate für einen oder mehrere Nodes fehlgeschlagen ist:

+
.. Überprüfen Sie die in der Tabelle aufgeführten Fehlermeldungen.
.. Beheben Sie die Probleme.
.. Wählen Sie *Wiederholen*.
+
Durch die erneute Versuche werden nur die SSH-Zugriffsschlüssel auf den Nodes geändert, die bei vorherigen Versuchen mit Schlüsseländerungen fehlgeschlagen sind.



. Nachdem SSH-Zugriffsschlüssel für alle Nodes geändert wurden, löschen Sie die <<download-current,Erstes heruntergeladenes Wiederherstellungspaket>>.
. Optional wählen Sie *MAINTENANCE* > *System* > *Recovery Package*, um eine zusätzliche Kopie des neuen Wiederherstellungspakets herunterzuladen.

