---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: Wenn Sie die SSH-Zugriffskennwörter für Admin-Nodes ändern, werden auch die eindeutigen Sätze interner SSH-Schlüssel für jeden Node im Grid aktualisiert. Der primäre Admin-Node verwendet diese SSH-Schlüssel, um mit einer sicheren Authentifizierung ohne Kennwort auf Knoten zuzugreifen. 
---
= Ändern Sie die SSH-Zugriffskennwörter für Admin-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die SSH-Zugriffskennwörter für Admin-Nodes ändern, werden auch die eindeutigen Sätze interner SSH-Schlüssel für jeden Node im Grid aktualisiert. Der primäre Admin-Node verwendet diese SSH-Schlüssel, um mit einer sicheren Authentifizierung ohne Kennwort auf Knoten zuzugreifen.

Verwenden Sie einen SSH-Schlüssel, um sich bei einem Node als `admin` oder beim Root-Benutzer auf einer VM- oder physischen Konsolenverbindung anzumelden.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Sie haben die aktuelle Provisionierungs-Passphrase.


.Über diese Aufgabe
Die neuen Zugangspasswörter für Admin-Knoten und die neuen internen Schlüssel für jeden Knoten werden im `Passwords.txt` Datei im Wiederherstellungspaket.  Die Schlüssel sind in der Spalte „Passwort“ dieser Datei aufgeführt.

Separate SSH-Zugriffskennwörter für die SSH-Schlüssel, die für die Kommunikation zwischen den Nodes verwendet werden. Diese werden durch dieses Verfahren nicht geändert.



== Greifen Sie auf den Assistenten zu

.Schritte
. Wählen Sie *Konfiguration* > *Zugriffskontrolle* > *Grid-Passwörter*.
. Wählen Sie unter *SSH-Schlüssel ändern* *Änderung vornehmen*.




== [[download-current]]Laden Sie das aktuelle Wiederherstellungspaket herunter

Laden Sie vor dem Ändern der SSH-Zugriffsschlüssel das aktuelle Wiederherstellungspaket herunter.  Sie können die Schlüssel in dieser Datei verwenden, wenn der Schlüsseländerungsprozess für einen beliebigen Knoten fehlschlägt.

.Schritte
. Geben Sie die Provisionierungs-Passphrase für Ihr Grid ein.
. Wählen Sie *Wiederherstellungspaket herunterladen*.
. Kopieren Sie die Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Die Wiederherstellungspaketdatei muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.

. Wählen Sie *Weiter*.
. Wenn das Bestätigungsdialogfeld angezeigt wird, wählen Sie *Yes* aus, wenn Sie bereit sind, die SSH-Zugriffsschlüssel zu ändern.
+

CAUTION: Sie können diesen Vorgang nach dem Start nicht abbrechen.





== Ändern Sie die SSH-Zugriffsschlüssel

Wenn der Prozess zum Ändern der SSH-Zugriffsschlüssel beginnt, wird ein neues Wiederherstellungspaket generiert, das die neuen Schlüssel enthält.  Anschließend werden die Schlüssel auf jedem Knoten aktualisiert.

.Schritte
. Warten Sie, bis das neue Wiederherstellungspaket generiert wurde. Dies kann einige Minuten dauern.
. Wenn die Schaltfläche „Neues Wiederherstellungspaket herunterladen“ aktiviert ist, wählen Sie „Neues Wiederherstellungspaket herunterladen“ und speichern Sie die neue Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
. Wenn der Download abgeschlossen ist:
+
.. Öffnen Sie die `.zip` Datei.
.. Bestätigen Sie, dass Sie auf den Inhalt zugreifen können, einschließlich der `Passwords.txt` Datei, die die neuen SSH-Zugriffsschlüssel enthält.
.. Kopieren Sie die neue Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Überschreiben Sie nicht das alte Wiederherstellungspaket.

+
Die Wiederherstellungspaketdatei muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.



. Warten Sie, bis die Schlüssel auf jedem Node aktualisiert werden. Dies kann einige Minuten dauern.
+
Wenn die Schlüssel für alle Nodes geändert werden, wird ein grünes Success-Banner angezeigt.

+
Wenn während des Aktualisierungsvorgangs ein Fehler auftritt, wird in einer Banner-Meldung die Anzahl der Knoten aufgeführt, bei denen die Schlüssel nicht geändert wurden. Das System wiederholt den Prozess automatisch auf jedem Node, bei dem der Schlüssel nicht geändert wurde. Wenn der Prozess mit einigen Knoten endet, die noch keinen geänderten Schlüssel haben, wird die Schaltfläche *Wiederholen* angezeigt.

+
Wenn das Schlüsselupdate für einen oder mehrere Nodes fehlgeschlagen ist:

+
.. Überprüfen Sie die in der Tabelle aufgeführten Fehlermeldungen.
.. Beheben Sie die Probleme.
.. Wählen Sie *Wiederholen*.
+
Durch die erneute Versuche werden nur die SSH-Zugriffsschlüssel auf den Nodes geändert, die bei vorherigen Versuchen mit Schlüsseländerungen fehlgeschlagen sind.



. Nachdem die SSH-Zugriffsschlüssel für alle Knoten geändert wurden, löschen Sie die<<download-current,das erste Wiederherstellungspaket, das Sie heruntergeladen haben>> .
. Wählen Sie optional *Wartung* > *System* > *Wiederherstellungspaket*, um eine zusätzliche Kopie des neuen Wiederherstellungspakets herunterzuladen.

