---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Jeder Node im Grid verfügt über ein Passwort für die Node-Konsole, mit dem Sie sich beim Node anmelden. Standardmäßig verfügt jeder Knoten über ein eindeutiges Passwort. Sie können jedes Kennwort in ein neues eindeutiges Kennwort ändern oder das Kennwort für jeden Knoten ändern, um ein globales Kennwort zu verwenden. Die Passwörter werden im Wiederherstellungspaket gespeichert. 
---
= Ändern der Passwörter für die Node-Konsole
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jeder Node im Grid verfügt über ein Passwort für die Node-Konsole, mit dem Sie sich beim Node anmelden. Standardmäßig verfügt jeder Knoten über ein eindeutiges Passwort. Sie können jedes Kennwort in ein neues eindeutiges Kennwort ändern oder das Kennwort für jeden Knoten ändern, um ein globales Kennwort zu verwenden. Die Passwörter werden im Wiederherstellungspaket gespeichert.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Sie haben die aktuelle Provisionierungs-Passphrase.


.Über diese Aufgabe
Sie verwenden ein Passwort für die Node-Konsole, um sich mit SSH bei einem Node als „admin“ oder bei dem Root-Benutzer über eine VM/physische Konsolenverbindung anzumelden. Sie können die Kennwörter der Node-Konsole mit einer der folgenden Optionen ändern:

* Automatisches Anwenden zufälliger Passwörter auf jeden Knoten
* Geben Sie ein globales Kennwort an, und wenden Sie es auf alle Knoten an
* Geben Sie ein eindeutiges Passwort an und wenden Sie es auf einen oder mehrere Nodes an


Die Passwörter werden in einer aktualisierten Datei im Wiederherstellungspaket gespeichert `Passwords.txt`. Die Passwörter sind in der Spalte Passwort in der Datei aufgeführt.


NOTE: Die  für die SSH-Schlüssel, die für die Kommunikation zwischen den Nodes verwendet werden, sind von den Kennwörtern der link:../admin/change-ssh-access-passwords.html["SSH-Zugriffspasswörter"]Node-Konsole getrennt. Dieses Verfahren ändert nicht die SSH-Zugangskennwörter.



== Greifen Sie auf den Assistenten zu

.Schritte
. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Grid-Passwörter*.
. Wählen Sie unter *Change Node Console passwords* die Option *make a change* aus.




== [[download-current]]Laden Sie das aktuelle Wiederherstellungspaket herunter

Laden Sie das aktuelle Wiederherstellungspaket herunter, bevor Sie die Kennwörter der Node-Konsole ändern. Sie können die Passwörter in dieser Datei verwenden, wenn die Passwortänderung für einen beliebigen Knoten fehlschlägt.

.Schritte
. Geben Sie die Provisionierungs-Passphrase für Ihr Grid ein.
. Wählen Sie *Wiederherstellungspaket herunterladen*.
. Kopieren Sie die Wiederherstellungspaket-Datei (`.zip`) in zwei sichere und separate Speicherorte.
+

CAUTION: Die Wiederherstellungspaket-Datei muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, die verwendet werden können, um Daten vom StorageGRID-System zu erhalten.

. Wählen Sie *Weiter*.




== Geben Sie neue Kennwörter ein

. Wählen Sie die Methode zur Kennwortänderung aus, die Sie verwenden möchten.
+
** *Automatisch*: StorageGRID weist allen Knoten automatisch ein neues zufälliges Konsolenpasswort zu.
** *Custom*: Sie geben Konsole-Passwörter.




[role="tabbed-block"]
====
.Automatisch
--
. Wählen Sie *Weiter*.


--
.Individuell
--
. Wählen Sie eine der folgenden Optionen:
+
** *Globales Konsolenpasswort*: Wenden Sie das gleiche Konsolenpasswort auf alle Knoten an.
** *Unique Console Passwords*: Ein anderes Passwort auf einen oder mehrere Knoten anwenden.


. Wenn Sie *Globales Konsolenpasswort* ausgewählt haben, geben Sie das Passwort ein, das Sie für alle Knoten verwenden möchten.
. Wenn Sie *Unique Console passwords* ausgewählt haben, geben Sie ein eindeutiges Passwort für einen oder mehrere Knoten ein.
. Wählen Sie *Weiter*.


--
====


== Schließen Sie die Passwortänderung ab

. Wenn das Bestätigungsdialogfeld angezeigt wird, wählen Sie *Yes* aus, wenn StorageGRID bereit ist, die Passwörter der Knotenkonsole zu ändern.
+

NOTE: Sie können diesen Vorgang nach dem Start nicht abbrechen.

+
StorageGRID generiert ein neues Wiederherstellungspaket mit dem neuen Passwort.

. Wenn das neue Wiederherstellungspaket fertig ist, wählen Sie *Neues Wiederherstellungspaket herunterladen* und speichern Sie das Wiederherstellungspaket.
. Öffnen Sie die `.zip` Datei.
. Vergewissern Sie sich, dass Sie auf den Inhalt zugreifen können, einschließlich der `Passwords.txt` Datei, die die neuen Kennwörter der Node-Konsole enthält.
. Kopieren Sie die neue Wiederherstellungspaket-Datei (`.zip`) in zwei sichere und separate Speicherorte.
+

CAUTION: Überschreiben Sie das alte Wiederherstellungspaket nicht.

+
Sie müssen die Wiederherstellungsdatei sichern, da sie Verschlüsselungsschlüssel und Kennwörter enthält, die zum Abrufen von Daten vom StorageGRID-System verwendet werden können.

. Aktivieren Sie das Kontrollkästchen, um anzugeben, dass Sie das neue Wiederherstellungspaket heruntergeladen und den Inhalt überprüft haben.
. Wählen Sie *Weiter*.
+
StorageGRID aktualisiert das Passwort für jeden Node.

+
Wenn während des Aktualisierungsvorgangs ein Fehler auftritt, wird in der Statusleiste die Anzahl der Knoten aufgeführt, bei denen die Passwörter nicht geändert wurden. Das System wiederholt den Prozess automatisch auf jedem Knoten, bei dem das Kennwort nicht geändert wurde. Wenn der Prozess endet, wenn einige Knoten noch kein geändertes Kennwort haben, wird die Schaltfläche *Wiederholen* angezeigt.

. Wenn die Kennwortaktualisierung für einen oder mehrere Knoten fehlgeschlagen ist:
+
.. Überprüfen Sie die in der Tabelle aufgeführten Fehlermeldungen.
.. Beheben Sie die Probleme.
.. Wählen Sie *Wiederholen*.
+

NOTE: Beim erneuten Versuch werden nur die Kennwörter der Knotenkonsole auf den Knoten geändert, die bei früheren Kennwortänderungsversuchen fehlgeschlagen sind.



. Wenn der Fortschrittsbalken anzeigt, dass keine Updates mehr vorhanden sind, wählen Sie *Fertig stellen*.
. Nachdem die Kennwörter der Knotenkonsole für alle Knoten geändert wurden, löschen Sie die <<download-current,Erstes heruntergeladenes Wiederherstellungspaket>>.

