---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Jeder Knoten in Ihrem Grid verfügt über ein Knotenkonsolenkennwort, mit dem Sie sich beim Knoten anmelden.  Standardmäßig hat jeder Knoten ein eindeutiges Passwort.  Sie können jedes Kennwort in ein neues, eindeutiges Kennwort ändern oder das Kennwort für jeden Knoten ändern, um ein globales Kennwort zu verwenden.  Die Passwörter werden im Wiederherstellungspaket gespeichert. 
---
= Ändern der Passwörter für die Node-Konsole
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jeder Knoten in Ihrem Grid verfügt über ein Knotenkonsolenkennwort, mit dem Sie sich beim Knoten anmelden.  Standardmäßig hat jeder Knoten ein eindeutiges Passwort.  Sie können jedes Kennwort in ein neues, eindeutiges Kennwort ändern oder das Kennwort für jeden Knoten ändern, um ein globales Kennwort zu verwenden.  Die Passwörter werden im Wiederherstellungspaket gespeichert.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Sie haben die aktuelle Provisionierungs-Passphrase.


.Über diese Aufgabe
Sie verwenden ein Knotenkonsolenkennwort, um sich per SSH als „Administrator“ bei einem Knoten oder als Root-Benutzer bei einer VM-/physischen Konsolenverbindung anzumelden.  Sie können die Passwörter der Knotenkonsole mit einer der folgenden Optionen ändern:

* Wenden Sie automatisch zufällige Passwörter auf jeden Knoten an
* Ein globales Passwort für alle Knoten festlegen und anwenden
* Geben Sie ein eindeutiges Kennwort an und wenden Sie es auf einen oder mehrere Knoten an.


Die Passwörter werden in einer aktualisierten `Passwords.txt` Datei im Wiederherstellungspaket.  Die Passwörter sind in der Spalte „Passwort“ der Datei aufgeführt.


NOTE: Derlink:../admin/change-ssh-access-passwords.html["SSH-Zugriffspasswörter"] denn die für die Kommunikation zwischen Knoten verwendeten SSH-Schlüssel sind von den Passwörtern der Knotenkonsole getrennt.  Dieses Verfahren ändert die SSH-Zugriffskennwörter nicht.



== Greifen Sie auf den Assistenten zu

.Schritte
. Wählen Sie *Konfiguration* > *Zugriffskontrolle* > *Grid-Passwörter*.
. Wählen Sie unter *Change Node Console passwords* die Option *make a change* aus.




== [[download-current]]Laden Sie das aktuelle Wiederherstellungspaket herunter

Laden Sie das aktuelle Wiederherstellungspaket herunter, bevor Sie die Passwörter der Knotenkonsole ändern.  Sie können die Passwörter in dieser Datei verwenden, wenn der Passwortänderungsprozess für einen beliebigen Knoten fehlschlägt.

.Schritte
. Geben Sie die Provisionierungs-Passphrase für Ihr Grid ein.
. Wählen Sie *Wiederherstellungspaket herunterladen*.
. Kopieren Sie die Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Die Wiederherstellungspaketdatei muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.

. Wählen Sie *Weiter*.




== Neue Passwörter bereitstellen

. Wählen Sie die gewünschte Methode zum Ändern des Kennworts aus.
+
** *Automatisch*: StorageGRID weist allen Knoten automatisch ein neues zufälliges Konsolenkennwort zu.
** *Benutzerdefiniert*: Sie geben Konsolenkennwörter an.




[role="tabbed-block"]
====
.Automatisch
--
. Wählen Sie *Weiter*.


--
.Individuell
--
. Wählen Sie eine der folgenden Optionen:
+
** *Globales Konsolenkennwort*: Wenden Sie auf allen Knoten dasselbe Konsolenkennwort an.
** *Eindeutige Konsolenkennwörter*: Wenden Sie auf einem oder mehreren Knoten ein anderes Kennwort an.


. Wenn Sie *Globales Konsolenkennwort* ausgewählt haben, geben Sie das Kennwort ein, das Sie für alle Knoten verwenden möchten.
. Wenn Sie *Eindeutige Konsolenkennwörter* ausgewählt haben, geben Sie ein eindeutiges Kennwort für einen oder mehrere Knoten ein.
. Wählen Sie *Weiter*.


--
====


== Schließen Sie die Passwortänderung ab

. Wenn das Bestätigungsdialogfeld angezeigt wird, wählen Sie *Ja*, wenn Sie bereit sind, dass StorageGRID mit der Änderung der Knotenkonsolenkennwörter beginnt.
+

NOTE: Sie können diesen Vorgang nach dem Start nicht abbrechen.

+
StorageGRID generiert ein neues Wiederherstellungspaket, das das neue Passwort enthält.

. Wenn das neue Wiederherstellungspaket fertig ist, wählen Sie *Neues Wiederherstellungspaket herunterladen* und speichern Sie das Wiederherstellungspaket.
. Öffnen Sie die `.zip` Datei.
. Vergewissern Sie sich, dass Sie auf den Inhalt zugreifen können, einschließlich der `Passwords.txt` Datei, die die neuen Kennwörter der Node-Konsole enthält.
. Kopieren Sie die neue Wiederherstellungspaketdatei(`.zip` ) an zwei sichere und getrennte Orte.
+

CAUTION: Überschreiben Sie nicht das alte Wiederherstellungspaket.

+
Sie müssen die Wiederherstellungsdatei sichern, da sie Verschlüsselungsschlüssel und Passwörter enthält, mit denen Daten aus dem StorageGRID -System abgerufen werden können.

. Aktivieren Sie das Kontrollkästchen, um anzugeben, dass Sie das neue Wiederherstellungspaket heruntergeladen und den Inhalt überprüft haben.
. Wählen Sie *Weiter*.
+
StorageGRID aktualisiert das Passwort für jeden Knoten.

+
Wenn während des Aktualisierungsvorgangs ein Fehler auftritt, wird in der Fortschrittsleiste die Anzahl der Knoten aufgeführt, deren Passwörter nicht geändert werden konnten.  Das System wiederholt den Vorgang automatisch auf jedem Knoten, dessen Kennwort nicht geändert werden konnte.  Wenn der Vorgang endet und einige Knoten immer noch kein geändertes Kennwort haben, wird die Schaltfläche *Wiederholen* angezeigt.

. Wenn die Kennwortaktualisierung für einen oder mehrere Knoten fehlgeschlagen ist:
+
.. Überprüfen Sie die in der Tabelle aufgeführten Fehlermeldungen.
.. Beheben Sie die Probleme.
.. Wählen Sie *Wiederholen*.
+

NOTE: Beim erneuten Versuch werden nur die Kennwörter der Knotenkonsole auf den Knoten geändert, die bei früheren Kennwortänderungsversuchen fehlgeschlagen sind.



. Wenn der Fortschrittsbalken anzeigt, dass keine Updates mehr verfügbar sind, wählen Sie *Fertig*.
. Nachdem die Passwörter der Knotenkonsole für alle Knoten geändert wurden, löschen Sie die<<download-current,das erste Wiederherstellungspaket, das Sie heruntergeladen haben>> .

