---
permalink: admin/configure-sso.html 
sidebar: sidebar 
keywords: use sandbox mode for sso, how to test single sign-on 
summary: 'Sie können den SSO-Assistenten konfigurieren befolgen und in den Sandbox-Modus wechseln, um Single Sign-On\(SSO \) zu konfigurieren und zu testen, bevor Sie es für alle StorageGRID-Benutzer aktivieren. Nachdem SSO aktiviert wurde, können Sie bei Bedarf zum Ändern oder erneuten Testen der Konfiguration in den Sandbox-Modus zurückkehren.' 
---
= SSO konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den SSO-Assistenten konfigurieren befolgen und in den Sandbox-Modus wechseln, um Single Sign-On (SSO) zu konfigurieren und zu testen, bevor es für alle StorageGRID-Benutzer aktiviert wird. Nachdem SSO aktiviert wurde, können Sie bei Bedarf in den Sandbox-Modus zurückkehren, um die Konfiguration zu ändern oder erneut zu testen.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:admin-group-permissions.html["Root-Zugriffsberechtigung"].
* Sie haben eine Identitätsföderation für Ihr StorageGRID System konfiguriert.
* Für den Identity Federation *LDAP-Diensttyp* haben Sie entweder Active Directory oder Entra-ID ausgewählt, basierend auf dem SSO-Identitätsanbieter, den Sie verwenden möchten.
+
[cols="1a,1a"]
|===
| Konfigurierter LDAP-Servicetyp | Optionen für SSO-Identitätsanbieter 


 a| 
Active Directory Federation Service (AD FS)
 a| 
** Active Directory
** Eintragungs-ID
** PingFederate




 a| 
Eintragungs-ID
 a| 
Eintragungs-ID

|===


.Über diese Aufgabe
Wenn SSO aktiviert ist und ein Benutzer versucht, sich bei einem Admin-Node anzumelden, sendet StorageGRID eine Authentifizierungsanforderung an den SSO-Identitäts-Provider. Der SSO-Identitäts-Provider sendet wiederum eine Authentifizierungsantwort zurück an StorageGRID, die angibt, ob die Authentifizierungsanforderung erfolgreich war. Für erfolgreiche Anfragen:

* Die Antwort von Active Directory oder PingFederate enthält eine Universally Unique Identifier (UUID) für den Benutzer.
* Die Antwort von der Entra-ID enthält einen UPN (User Principal Name).


Damit StorageGRID (der Dienstanbieter) und der SSO-Identitätsanbieter sicher über Authentifizierungsanforderungen von Benutzern kommunizieren können, führen Sie die folgenden Aufgaben aus:

. Konfigurieren Sie die Einstellungen in StorageGRID.
. Verwenden Sie die Software des SSO-Identitätsanbieters, um für jeden Admin-Node eine Vertrauensstellung (AD FS), eine Enterprise-Anwendung (Entra-ID) oder einen Service-Provider (PingFederate) zu erstellen.
. Kehren Sie zur StorageGRID zurück, um SSO zu aktivieren.


Im Sandbox-Modus ist es einfach, diese Rückkehrkonfiguration durchzuführen und alle Einstellungen zu testen, bevor Sie SSO aktivieren. Wenn Sie den Sandbox-Modus verwenden, können sich Benutzer nicht mit SSO anmelden.



== Greifen Sie auf den Assistenten zu

.Schritte
. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Single Sign-On*. Die Seite Single Sign-On wird angezeigt.
+

NOTE: Wenn die Schaltfläche SSO-Einstellungen konfigurieren deaktiviert ist, bestätigen Sie, dass Sie den Identitätsanbieter als föderierte Identitätsquelle konfiguriert haben. Siehe link:requirements-for-sso.html["Voraussetzungen und Überlegungen für Single Sign-On"].

. Wählen Sie *SSO-Einstellungen konfigurieren*. Die Seite Details zum Identitätsanbieter angeben wird angezeigt.




== Angaben zum Identitätsanbieter

.Schritte
. Wählen Sie aus der Dropdown-Liste den *SSO-Typ* aus.
. Wenn Sie Active Directory als SSO-Typ ausgewählt haben, geben Sie den Namen des *Verbunddiensts* für den Identitätsanbieter genau so ein, wie er im Active Directory-Verbunddienst (AD FS) angezeigt wird.
+

NOTE: Um den Namen des Föderationsdienstes zu finden, gehen Sie zu Windows Server Manager. Wählen Sie *Tools* > *AD FS Management*. Wählen Sie im Menü Aktion die Option *Eigenschaften des Föderationsdienstes bearbeiten* aus. Der Name des Föderationsdienstes wird im zweiten Feld angezeigt.

. Geben Sie an, welches TLS-Zertifikat zur Sicherung der Verbindung verwendet wird, wenn der Identitäts-Provider SSO-Konfigurationsinformationen als Antwort auf StorageGRID-Anforderungen sendet.
+
** *Verwenden Sie das Betriebssystem CA-Zertifikat*: Verwenden Sie das auf dem Betriebssystem installierte Standard-CA-Zertifikat, um die Verbindung zu sichern.
** *Benutzerdefiniertes CA-Zertifikat verwenden*: Verwenden Sie ein benutzerdefiniertes CA-Zertifikat, um die Verbindung zu sichern.
+
Wenn Sie diese Einstellung auswählen, kopieren Sie den Text des benutzerdefinierten Zertifikats und fügen Sie ihn in das Textfeld *CA-Zertifikat* ein.

** *Verwenden Sie keine TLS*: Verwenden Sie kein TLS-Zertifikat, um die Verbindung zu sichern.
+

CAUTION: Wenn Sie das Zertifizierungsstellenzertifikat ändern, führen Sie sofort link:../maintain/starting-or-restarting-service.html["Starten Sie den Management-API-Service auf den Admin-Nodes neu"]eine erfolgreiche SSO-Prüfung im Grid Manager durch.



. Wählen Sie *Weiter*. Die Seite ID des betreffenden Anbieters angeben wird angezeigt.




== [[Enter-Sandbox-Mode]]Geben Sie die ID des Drittanbieters an

. Füllen Sie die Felder auf der Seite Geben Sie die ID des auswählenden Anbieters basierend auf dem von Ihnen ausgewählten SSO-Typ aus.
+
[role="tabbed-block"]
====
.Active Directory
--
.. Geben Sie für StorageGRID die Kennung der * ausvertrauenden Partei* an. Dieser Wert steuert den Namen, den Sie für jedes Vertrauen der betreffenden Partei in AD FS verwenden.
+
*** Wenn Ihr Grid beispielsweise nur über einen Admin-Knoten verfügt und Sie in Zukunft nicht mehr Admin-Knoten hinzufügen möchten, geben Sie `SG` oder `StorageGRID`ein.
*** Wenn Ihr Raster mehr als einen Admin-Knoten enthält, fügen Sie die Zeichenfolge `[HOSTNAME]` in die Kennung ein.  `SG-[HOSTNAME]`Beispiel: . Durch die Einbindung dieser Zeichenfolge wird eine Tabelle erstellt, in der die ID der zugreifenden Partei für jeden Admin-Node im Raster auf der Grundlage des Hostnamens des Node angezeigt wird.
+

NOTE: Sie müssen für jeden Admin-Knoten in Ihrem StorageGRID-System ein Vertrauensverhältnis aufbauen. Mit einer Vertrauensbasis für jeden Admin-Knoten wird sichergestellt, dass Benutzer sich sicher bei und aus jedem Admin-Knoten anmelden können.



.. Wählen Sie *Speichern und wechseln Sie in den Sandbox-Modus*.


--
.Eintragungs-ID
--
.. Geben Sie im Abschnitt Enterprise-Anwendung den *Enterprise-Anwendungsnamen* für StorageGRID an. Dieser Wert steuert den Namen, den Sie für jede Unternehmensanwendung in der Entra-ID verwenden.
+
*** Wenn Ihr Grid beispielsweise nur über einen Admin-Knoten verfügt und Sie in Zukunft nicht mehr Admin-Knoten hinzufügen möchten, geben Sie `SG` oder `StorageGRID`ein.
*** Wenn Ihr Raster mehr als einen Admin-Knoten enthält, fügen Sie die Zeichenfolge `[HOSTNAME]` in die Kennung ein.  `SG-[HOSTNAME]`Beispiel: . Durch die Einbindung dieser Zeichenfolge wird eine Tabelle erstellt, die auf der Grundlage des Hostnamens des Node für jeden Admin-Node im System einen Anwendungsnamen des Unternehmens anzeigt.
+

NOTE: Sie müssen eine Enterprise-Anwendung für jeden Admin-Knoten in Ihrem StorageGRID-System erstellen. Mit einer Enterprise-Anwendung für jeden Admin-Node wird sichergestellt, dass Benutzer sich sicher bei und aus jedem Admin-Node anmelden können.



.. Führen Sie die Schritte unter link:../admin/creating-enterprise-application-entra-id.html["Erstellen Sie Unternehmensanwendungen in Entra ID"]aus, um für jeden in der Tabelle aufgeführten Admin-Node eine Unternehmensanwendungen zu erstellen.
.. Kopieren Sie aus der Entra-ID die Metadaten-URL für jede Unternehmensanwendung. Fügen Sie dann diese URL in das entsprechende Feld *Federation Metadaten URL* in StorageGRID ein.
.. Nachdem Sie eine Föderation Metadaten-URL für alle Admin-Knoten kopiert und eingefügt haben, wählen Sie *Speichern und starten Sie den Sandbox-Modus*.


--
.PingFederate
--
.. Geben Sie im Abschnitt Dienstanbieter (SP) die *SP-Verbindungs-ID* für StorageGRID an. Dieser Wert steuert den Namen, den Sie für jede SP-Verbindung in PingFederate verwenden.
+
*** Wenn Ihr Grid beispielsweise nur über einen Admin-Knoten verfügt und Sie in Zukunft nicht mehr Admin-Knoten hinzufügen möchten, geben Sie `SG` oder `StorageGRID`ein.
*** Wenn Ihr Raster mehr als einen Admin-Knoten enthält, fügen Sie die Zeichenfolge `[HOSTNAME]` in die Kennung ein.  `SG-[HOSTNAME]`Beispiel: . Durch Einbindung dieser Zeichenfolge wird eine Tabelle erstellt, die basierend auf dem Hostnamen des Node die SP-Verbindungs-ID für jeden Admin-Node im System anzeigt.
+

NOTE: Sie müssen für jeden Admin-Knoten in Ihrem StorageGRID-System eine SP-Verbindung erstellen. Durch eine SP-Verbindung für jeden Admin-Node wird sichergestellt, dass Benutzer sich sicher bei und aus jedem Admin-Node anmelden können.



.. Geben Sie im Feld *Federation Metadaten-URL* die URL der Federation Metadaten für jeden Admin-Node an.
+
Verwenden Sie das folgende Format:

+
[listing]
----
https://<Federation Service Name>:<port>/pf/federation_metadata.ping?PartnerSpId=<SP Connection ID>
----
.. Wählen Sie *Speichern und wechseln Sie in den Sandbox-Modus*.


--
====




== Konfigurieren Sie Vertrauensstellungen von Drittanbietern, Unternehmensanwendungen oder SP-Verbindungen

Nachdem Sie die Konfiguration gespeichert und in den Sandbox-Modus gewechselt haben, können Sie die Konfiguration für den ausgewählten SSO-Typ abschließen und testen.

StorageGRID kann so lange wie erforderlich im Sandbox-Modus verbleiben. Allerdings können sich nur föderierte Benutzer und lokale Benutzer anmelden.

[role="tabbed-block"]
====
.Active Directory
--
.Schritte
. Wechseln Sie zu Active Directory Federation Services (AD FS).
. Erstellen Sie eine oder mehrere Vertrauensstellungen für StorageGRID, indem Sie die in der Tabelle auf der Seite SSO konfigurieren in der Tabelle aufgeführten IDs der vertrauenswürdigen Parteien verwenden.
+
Sie müssen für jeden in der Tabelle aufgeführten Admin-Node ein Vertrauen erstellen.

+
Anweisungen hierzu finden Sie unter link:../admin/creating-relying-party-trusts-in-ad-fs.html["Erstellen Sie Vertrauensstellungen von vertrauenswürdigen Parteien in AD FS"].



--
.Eintragungs-ID
--
.Schritte
. Wählen Sie auf der Seite Single Sign-On für den Admin-Node, bei dem Sie sich aktuell angemeldet haben, die Schaltfläche zum Herunterladen und Speichern der SAML-Metadaten aus.
. Wiederholen Sie dann für alle anderen Admin-Knoten in Ihrem Raster die folgenden Schritte:
+
.. Melden Sie sich beim Knoten an.
.. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Single Sign-On*.
.. Laden Sie die SAML-Metadaten für diesen Node herunter, und speichern Sie sie.


. Rufen Sie das Azure-Portal auf.
. Befolgen Sie die Schritte unterlink:../admin/creating-enterprise-application-entra-id.html["Erstellen Sie Unternehmensanwendungen in Entra ID"], um die SAML-Metadatendatei für jeden Admin-Node in die entsprechende Enterprise-Anwendung Entra ID hochzuladen.


--
.PingFederate
--
.Schritte
. Wählen Sie auf der Seite Single Sign-On für den Admin-Node, bei dem Sie sich aktuell angemeldet haben, die Schaltfläche zum Herunterladen und Speichern der SAML-Metadaten aus.
. Wiederholen Sie dann für alle anderen Admin-Knoten in Ihrem Raster die folgenden Schritte:
+
.. Melden Sie sich beim Knoten an.
.. Wählen Sie *KONFIGURATION* > *Zugriffskontrolle* > *Single Sign-On*.
.. Laden Sie die SAML-Metadaten für diesen Node herunter, und speichern Sie sie.


. Fahren Sie zur PingFederate.
. link:../admin/creating-sp-connection-ping.html["Erstellen Sie eine oder mehrere SP-Verbindungen (Service-Provider) für StorageGRID"]. Verwenden Sie die SP-Verbindungs-ID für jeden Administratorknoten (in der Tabelle auf der Seite SSO konfigurieren) und die SAML-Metadaten, die Sie für diesen Administratorknoten heruntergeladen haben.
+
Für jeden in der Tabelle aufgeführten Admin-Node müssen Sie eine SP-Verbindung erstellen.



--
====


== [[Test-sso]]Konfiguration testen

Bevor Sie die Verwendung von Single Sign-On für Ihr gesamtes StorageGRID-System erzwingen, vergewissern Sie sich, dass Single Sign-On und Single Logout für jeden Admin-Knoten korrekt konfiguriert sind.

[role="tabbed-block"]
====
.Active Directory
--
.Schritte
. Suchen Sie auf der Seite SSO konfigurieren den Link im Schritt Testkonfiguration des Assistenten.
+
Die URL wird aus dem Wert abgeleitet, den Sie im Feld *Federation Service Name* eingegeben haben.

. Wählen Sie den Link aus, oder kopieren Sie die URL in einen Browser, um auf die Anmeldeseite Ihres Identitätsanbieters zuzugreifen.
. Um zu bestätigen, dass Sie SSO zur Anmeldung bei StorageGRID verwenden können, wählen Sie *Anmelden bei einer der folgenden Sites*, wählen Sie die bevertrauenden Partei-ID für Ihren primären Admin-Knoten und wählen Sie *Anmelden*.
. Geben Sie Ihren föderierten Benutzernamen und Ihr Kennwort ein.
+
** Wenn die SSO-Anmelde- und -Abmeldevorgänge erfolgreich sind, wird eine Erfolgsmeldung angezeigt.
** Wenn der SSO-Vorgang nicht erfolgreich ist, wird eine Fehlermeldung angezeigt. Beheben Sie das Problem, löschen Sie die Cookies des Browsers, und versuchen Sie es erneut.


. Wiederholen Sie diese Schritte, um die SSO-Verbindung für jeden Admin-Node in Ihrem Raster zu überprüfen.


--
.Eintragungs-ID
--
.Schritte
. Wechseln Sie im Azure-Portal zur Seite Single Sign On.
. Wählen Sie *Diese Anwendung testen*.
. Geben Sie die Anmeldeinformationen eines föderierten Benutzers ein.
+
** Wenn die SSO-Anmelde- und -Abmeldevorgänge erfolgreich sind, wird eine Erfolgsmeldung angezeigt.
** Wenn der SSO-Vorgang nicht erfolgreich ist, wird eine Fehlermeldung angezeigt. Beheben Sie das Problem, löschen Sie die Cookies des Browsers, und versuchen Sie es erneut.


. Wiederholen Sie diese Schritte, um die SSO-Verbindung für jeden Admin-Node in Ihrem Raster zu überprüfen.


--
.PingFederate
--
.Schritte
. Wählen Sie auf der Seite SSO konfigurieren den ersten Link in der Meldung Sandbox-Modus aus.
+
Wählen Sie jeweils einen Link aus, und testen Sie ihn.

. Geben Sie die Anmeldeinformationen eines föderierten Benutzers ein.
+
** Wenn die SSO-Anmelde- und -Abmeldevorgänge erfolgreich sind, wird eine Erfolgsmeldung angezeigt.
** Wenn der SSO-Vorgang nicht erfolgreich ist, wird eine Fehlermeldung angezeigt. Beheben Sie das Problem, löschen Sie die Cookies des Browsers, und versuchen Sie es erneut.


. Wählen Sie den nächsten Link aus, um die SSO-Verbindung für jeden Admin-Node in Ihrem Raster zu überprüfen.
+
Wenn eine Nachricht mit abgelaufener Seite angezeigt wird, wählen Sie in Ihrem Browser die Schaltfläche *Zurück* aus, und senden Sie Ihre Anmeldedaten erneut.



--
====


== Aktivieren Sie Single Sign On

Wenn Sie bestätigt haben, dass Sie sich mit SSO bei jedem Admin-Node anmelden können, können Sie SSO für Ihr gesamtes StorageGRID System aktivieren.


TIP: Wenn SSO aktiviert ist, müssen alle Benutzer SSO verwenden, um auf den Grid Manager, den Mandanten-Manager, die Grid-Management-API und die Mandanten-Management-API zuzugreifen. Lokale Benutzer können nicht mehr auf StorageGRID zugreifen.

.Schritte
. Wählen Sie im Konfigurationsschritt Test des Assistenten SSO konfigurieren *SSO aktivieren* aus.
. Überprüfen Sie die Warnmeldung, und wählen Sie *SSO aktivieren*.
+
Single Sign-On ist jetzt aktiviert. Die Seite Single Sign-On wird angezeigt und enthält nun die Details für das soeben konfigurierte SSO.

. Um die Konfiguration zu bearbeiten, wählen Sie *Bearbeiten*.
. Um die einmalige Anmeldung zu deaktivieren, wählen Sie *SSO deaktivieren*.



TIP: Wenn Sie das Azure-Portal verwenden und von demselben Computer aus auf StorageGRID zugreifen, mit dem Sie auf die Entra-ID zugreifen, stellen Sie sicher, dass der Benutzer des Azure-Portals auch ein autorisierter StorageGRID-Benutzer ist (ein Benutzer in einer föderierten Gruppe, der in StorageGRID importiert wurde, oder melden Sie sich beim Azure-Portal ab, bevor Sie versuchen, sich bei StorageGRID anzumelden.
