---
permalink: admin/controlling-storagegrid-access.html 
sidebar: sidebar 
keywords: administrator access, single sign on, sso, users, groups, client certificates, passwords, passphrase 
summary: 'Sie steuern, wer auf StorageGRID zugreifen kann und welche Aufgaben Benutzer ausführen können, indem Sie Gruppen und Benutzer erstellen oder importieren und jeder Gruppe Berechtigungen zuweisen. Optional können Sie Single Sign On (SSO) aktivieren, Client-Zertifikate erstellen und Grid-Passwörter ändern.' 
---
= Kontrolle über den StorageGRID-Zugriff
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie steuern, wer auf StorageGRID zugreifen kann und welche Aufgaben Benutzer ausführen dürfen, indem Sie Gruppen und Benutzer erstellen oder importieren und den einzelnen Gruppen Berechtigungen zuweisen. Optional besteht die Möglichkeit, Single Sign-On (SSO) zu aktivieren, Clientzertifikate zu erstellen, Grid-Passwörter zu ändern und die Multi-Admin-Verifizierung zu verwenden.



[[control-access-to-the-grid-manager]]
== Den Zugriff auf den Grid Manager steuern

Sie bestimmen, wer auf den Grid Manager und die Grid Management API zugreifen kann, indem Sie Gruppen und Benutzer von einem Identitätsverbundservice aus importieren oder lokale Gruppen und lokale Benutzer einrichten.

Mit link:using-identity-federation.html["Identitätsföderation"] wird die Einrichtung link:managing-admin-groups.html["Gruppen"]beschleunigt und link:managing-users.html["Benutzer"]Benutzer können sich mit vertrauten Anmeldeinformationen bei StorageGRID anmelden. Sie können die Identitätsföderation konfigurieren, wenn Sie Active Directory, OpenLDAP oder Oracle Directory Server verwenden.


NOTE: Wenden Sie sich an den technischen Support, wenn Sie einen anderen LDAP v3-Dienst verwenden möchten.

Sie legen fest, welche Aufgaben jeder Benutzer durchführen kann, indem Sie jeder Gruppe unterschiedliche Aufgaben zuweisenlink:admin-group-permissions.html["Berechtigungen"]. Beispielsweise können Benutzer in einer Gruppe in der Lage sein, ILM-Regeln und Benutzer in einer anderen Gruppe zu verwalten, um Wartungsaufgaben durchzuführen. Ein Benutzer muss mindestens einer Gruppe angehören, um auf das System zuzugreifen.

Optional können Sie eine Gruppe als schreibgeschützt konfigurieren. Benutzer in einer schreibgeschützten Gruppe können nur Einstellungen und Funktionen anzeigen. Sie können keine Änderungen an der Grid Manager- oder Grid-Management-API vornehmen oder Vorgänge ausführen.



[[enable-single-sign-on]]
== Aktivieren Sie Single Sign On

Das StorageGRID System unterstützt Single Sign-On (SSO) mithilfe des Security Assertion Markup Language 2.0 (SAML 2.0) oder OpenID Connect (OIDC) Standards. Nachdem Sie link:how-sso-works.html["Konfigurieren und aktivieren Sie SSO"] haben, müssen alle Benutzer von einem externen Identitätsanbieter authentifiziert werden, bevor sie auf den Grid Manager, den Tenant Manager, die Grid Management API oder die Tenant Management API zugreifen können. Lokale Benutzer können sich nicht bei StorageGRID anmelden.



[[change-provisioning-passphrase]]
== Provisionierungs-Passphrase ändern

Die Bereitstellungspassphrase wird für viele Installations- und Wartungsverfahren sowie zum Herunterladen des StorageGRID -Wiederherstellungspakets benötigt.  Die Passphrase ist auch zum Herunterladen von Backups der Grid-Topologieinformationen und Verschlüsselungsschlüssel für das StorageGRID -System erforderlich.  Du kannstlink:changing-provisioning-passphrase.html["Ändern Sie die Passphrase"] nach Bedarf.



[[change-node-console-passwords]]
== Ändern der Passwörter für die Node-Konsole

Jeder Knoten in Ihrem Grid verfügt über ein Knotenkonsolenkennwort, das Sie benötigen, um sich per SSH als „Admin“ beim Knoten oder bei einer VM-/physischen Konsolenverbindung als Root-Benutzer anzumelden.  Bei Bedarf können Sielink:change-node-console-password.html["Ändern Sie das Passwort für die Node-Konsole"] für jeden Knoten.



[[use-multi-admin-verification]]
== Multi-Admin-Verifizierung

Mithilfe der Multi-Admin-Verifizierung (MAV) kann sichergestellt werden, dass bestimmte StorageGRID Operationen nur nach Genehmigung durch die zuständigen Administratoren durchgeführt werden. MAV verhindert, dass kompromittierte, böswillige oder unerfahrene Administratoren unerwünschte Änderungen vornehmen oder Daten löschen.
