---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: Sie verwenden die Entra-ID, um für jeden Admin-Knoten in Ihrem System eine Unternehmensanwendung zu erstellen. 
---
= Erstellen Sie Unternehmensanwendungen in Entra ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie verwenden die Entra-ID, um für jeden Admin-Knoten in Ihrem System eine Unternehmensanwendung zu erstellen.

.Bevor Sie beginnen
* Sie haben mit der Konfiguration der einmaligen Anmeldung für StorageGRID begonnen und *Entra ID* als SSO-Typ ausgewählt.
* Du hastlink:../admin/configure-sso.html#enter-sandbox-mode["Sandbox-Modus aufgerufen"] im Grid Manager.
* Sie haben den *Namen der Unternehmensanwendung* für jeden Admin-Knoten in Ihrem System.  Sie können diese Werte aus der Detailtabelle des Admin-Knotens auf der Seite „SSO konfigurieren“ kopieren.
+

NOTE: Sie müssen eine Enterprise-Anwendung für jeden Admin-Knoten in Ihrem StorageGRID-System erstellen. Mit einer Enterprise-Anwendung für jeden Admin-Node wird sichergestellt, dass Benutzer sich sicher bei und aus jedem Admin-Node anmelden können.

* Sie haben Erfahrung mit der Erstellung von Unternehmensanwendungen in Entra ID.
* Sie haben ein Entra-ID-Konto mit einem aktiven Abonnement.
* Sie haben eine der folgenden Rollen im Entra ID-Konto: Globaler Administrator, Cloud-Anwendungsadministrator, Anwendungsadministrator oder Besitzer des Dienstprinzipals.




== Zugang zur Entra-ID

.Schritte
. Melden Sie sich beim an https://portal.azure.com["Azure-Portal"^].
. Navigieren Sie zu https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["Entra-ID"^] .
. Wählen Sie https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Enterprise-Applikationen"^].




== Erstellen von Enterprise-Applikationen und Speichern von StorageGRID SSO-Konfiguration

Um die SSO-Konfiguration für Entra ID in StorageGRID zu speichern, müssen Sie Entra ID verwenden, um für jeden Admin-Knoten eine Unternehmensanwendung zu erstellen.  Sie kopieren die URLs der Föderationsmetadaten von Entra ID und fügen sie in die entsprechenden Felder *Föderationsmetadaten-URL* auf der Seite „SSO konfigurieren“ ein.

.Schritte
. Wiederholen Sie die folgenden Schritte für jeden Admin-Node.
+
.. Wählen Sie im Bereich „Entra ID Enterprise-Anwendungen“ *Neue Anwendung* aus.
.. Wählen Sie *Erstellen Sie Ihre eigene Anwendung*.
.. Geben Sie als Namen den *Namen der Unternehmensanwendung* ein, den Sie aus der Tabelle mit den Admin-Knotendetails auf der Seite „SSO konfigurieren“ kopiert haben.
.. Lassen Sie das * eine andere Anwendung integrieren, die Sie nicht in der Galerie finden (nicht-Galerie)* Optionsfeld ausgewählt.
.. Wählen Sie *Erstellen*.
.. Wählen Sie im *2 den Link *Get Started* aus. Aktivieren Sie das Feld Single Sign On*, oder wählen Sie den Link *Single Sign-On* im linken Rand.
.. Wählen Sie das Feld *SAML* aus.
.. Kopieren Sie die *App Federation Metadaten-URL*, die Sie unter *Step 3 SAML-Signierungszertifikat* finden können.
.. Gehen Sie zur Seite „SSO konfigurieren“ und fügen Sie die URL in das Feld „URL der Verbundmetadaten“ ein, die dem von Ihnen verwendeten „Namen der Unternehmensanwendung“ entspricht.


. Nachdem Sie für jeden Admin-Knoten eine URL mit Verbundmetadaten eingefügt und alle anderen erforderlichen Änderungen an der SSO-Konfiguration vorgenommen haben, wählen Sie auf der Seite „SSO konfigurieren“ *Speichern* aus.




== Laden Sie für jeden Admin-Node SAML-Metadaten herunter

Nachdem die SSO-Konfiguration gespeichert ist, können Sie für jeden Admin-Node in Ihrem StorageGRID-System eine SAML-Metadatendatei herunterladen.

.Schritte
. Wiederholen Sie diese Schritte für jeden Admin-Node.
+
.. Melden Sie sich über den Admin-Node bei StorageGRID an.
.. Wählen Sie *Konfiguration* > *Zugriffskontrolle* > *Einmaliges Anmelden*.
.. Wählen Sie die Schaltfläche, um die SAML-Metadaten für diesen Admin-Node herunterzuladen.
.. Speichern Sie die Datei, die Sie in Entra ID hochladen.






== Hochladen von SAML-Metadaten in jede Enterprise-Applikation

Nachdem Sie für jeden StorageGRID Admin-Knoten eine SAML-Metadatendatei heruntergeladen haben, führen Sie in Entra ID die folgenden Schritte aus:

.Schritte
. Zurück zum Azure-Portal.
. Wiederholen Sie diese Schritte für jede Enterprise-Applikation:
+

NOTE: Möglicherweise müssen Sie die Seite Enterprise-Applikationen aktualisieren, um Anwendungen anzuzeigen, die Sie zuvor in der Liste hinzugefügt haben.

+
.. Gehen Sie zur Seite Eigenschaften für die Enterprise-Anwendung.
.. Legen Sie *Zuweisung erforderlich* auf *Nein* fest (es sei denn, Sie möchten Aufgaben separat konfigurieren).
.. Rufen Sie die Seite Single Sign-On auf.
.. Schließen Sie die SAML-Konfiguration ab.
.. Wählen Sie die Schaltfläche *Metadatendatei hochladen* aus, und wählen Sie die SAML-Metadatendatei aus, die Sie für den entsprechenden Admin-Node heruntergeladen haben.
.. Nachdem die Datei geladen wurde, wählen Sie *Speichern* und dann *X* aus, um das Fenster zu schließen. Sie gelangen zurück zur Seite Single Sign-On mit SAML einrichten.


. link:../admin/configure-sso.html#test-sso["Testen Sie jede Anwendung"] .

