---
permalink: admin/managing-full-storage-nodes.html 
sidebar: sidebar 
keywords: storage node is full 
summary: 'Wenn Storage-Nodes die Kapazität erreichen, müssen Sie das StorageGRID System durch Hinzufügen eines neuen Storage erweitern. Es sind drei Optionen verfügbar: Das Hinzufügen von Storage Volumes, das Hinzufügen von Shelfs zur Storage-Erweiterung und das Hinzufügen von Storage-Nodes.' 
---
= Management vollständiger Storage-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Storage-Nodes die Kapazität erreichen, müssen Sie das StorageGRID System durch Hinzufügen eines neuen Storage erweitern. Es sind drei Optionen verfügbar: Das Hinzufügen von Storage Volumes, das Hinzufügen von Shelfs zur Storage-Erweiterung und das Hinzufügen von Storage-Nodes.



== Hinzufügen von Storage-Volumes

Jeder Storage-Node unterstützt eine maximale Anzahl an Storage-Volumes. Der definierte Höchstwert variiert je nach Plattform. Wenn ein Storage-Node weniger als die maximale Anzahl an Storage-Volumes enthält, können Sie Volumes hinzufügen, um seine Kapazität zu erhöhen. Siehe die Anleitung für link:../expand/index.html["Erweitern eines StorageGRID Systems"].



== Hinzufügen von Shelfs zur Storage-Erweiterung

Einige Storage-Nodes der StorageGRID Appliance, z. B. SG6060 oder SG6160, können zusätzliche Storage-Shelfs unterstützen. Bei StorageGRID Appliances mit Erweiterungsfunktionen, die nicht bereits auf die maximale Kapazität erweitert wurden, können Sie Storage-Shelfs zur Steigerung der Kapazität hinzufügen. Siehe die Anleitung für link:../expand/index.html["Erweitern eines StorageGRID Systems"].



== Storage-Nodes Hinzufügen

Sie können die Storage-Kapazität durch Hinzufügen von Storage-Nodes erhöhen. Beim Hinzufügen von Storage müssen die aktuell aktiven ILM-Regeln und Kapazitätsanforderungen sorgfältig berücksichtigt werden. Siehe die Anleitung für link:../expand/index.html["Erweitern eines StorageGRID Systems"].
