---
permalink: admin/signing-in-to-grid-manager.html 
sidebar: sidebar 
keywords: grid manager, sign in, log in 
summary: 'Sie greifen auf die Anmeldeseite des Grid Manager zu, indem Sie den vollständig qualifizierten Domänennamen \(FQDN\) oder die IP-Adresse eines Admin-Knotens in die Adressleiste eines unterstützten Webbrowsers eingeben.' 
---
= Melden Sie sich beim Grid Manager an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie greifen auf die Anmeldeseite des Grid Manager zu, indem Sie den vollständig qualifizierten Domänennamen (FQDN) oder die IP-Adresse eines Admin-Knotens in die Adressleiste eines unterstützten Webbrowsers eingeben.

Jedes StorageGRID System umfasst einen primären Admin-Node und eine beliebige Anzahl nicht primärer Admin-Nodes. Sie können sich bei einem beliebigen Admin-Knoten beim Grid-Manager anmelden, um das StorageGRID-System zu verwalten. Einige Wartungsverfahren können jedoch nur über den primären Admin-Node durchgeführt werden.



=== Stellen Sie eine Verbindung mit der HA-Gruppe her

Wenn Admin-Nodes in einer HA-Gruppe (High Availability, Hochverfügbarkeit) enthalten sind, stellen Sie eine Verbindung über die virtuelle IP-Adresse der HA-Gruppe oder einen vollständig qualifizierten Domänennamen her, der der der virtuellen IP-Adresse zugeordnet ist. Der primäre Admin-Node sollte als primäre Schnittstelle der Gruppe ausgewählt werden, sodass Sie beim Zugriff auf den Grid Manager auf den primären Admin-Knoten zugreifen, wenn der primäre Admin-Node nicht verfügbar ist. Siehe link:managing-high-availability-groups.html["Management von Hochverfügbarkeitsgruppen"].



=== Verwenden Sie SSO

Die Anmeldeschritte sind etwas anders, wennlink:how-sso-works.html["Single Sign-On (SSO) wurde konfiguriert"] .



== Melden Sie sich beim Grid-Manager beim ersten Admin-Node an

.Bevor Sie beginnen
* Sie haben Ihre Anmeldedaten.
* Sie verwenden einen link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Cookies sind in Ihrem Webbrowser aktiviert.
* Sie gehören einer Benutzergruppe an, die über mindestens eine Berechtigung verfügt.
* Sie haben die URL für den Grid-Manager:
+
`https://_FQDN_or_Admin_Node_IP_/`

+
Sie können den vollständig qualifizierten Domänennamen, die IP-Adresse eines Admin-Node oder die virtuelle IP-Adresse einer HA-Gruppe von Admin-Nodes verwenden.

+
Um auf einen anderen Port als den Standardport für HTTPS (443) auf den Grid-Manager zuzugreifen, geben Sie die Portnummer in die URL ein:

+
`https://_FQDN_or_Admin_Node_IP:port_/`

+

NOTE: SSO ist auf dem eingeschränkten Grid Manager-Port nicht verfügbar. Sie müssen Port 443 verwenden.



.Schritte
. Starten Sie einen unterstützten Webbrowser.
. Geben Sie in der Adressleiste des Browsers die URL für den Grid Manager ein.
. Wenn Sie aufgefordert werden, eine Sicherheitswarnung zu erhalten, installieren Sie das Zertifikat mithilfe des Browser-Installationsassistenten. Siehe link:using-storagegrid-security-certificates.html["Verwalten von Sicherheitszertifikaten"].
. Melden Sie sich beim Grid Manager an.
+
Der angezeigte Anmeldebildschirm hängt davon ab, ob Single Sign-On (SSO) für StorageGRID konfiguriert wurde.

+
[role="tabbed-block"]
====
.SSO wird nicht verwendet
--
.. Geben Sie Ihren Benutzernamen und Ihr Kennwort für den Grid Manager ein.
.. Wählen Sie *Anmelden*.


--
.SSO wird verwendet
--
** Wenn StorageGRID SSO verwendet und Sie zum ersten Mal auf die URL in diesem Browser zugreifen:
+
... Wählen Sie *Anmelden*. Sie können die 0 im Feld „Konto“ belassen.
... Geben Sie Ihre Standard-SSO-Anmeldeinformationen auf der SSO-Anmeldeseite Ihrer Organisation ein.
+
Wenn StorageGRID beispielsweise SSO verwendet und Sie zuvor auf den Grid Manager oder ein Mandantenkonto zugegriffen haben:

+
.... Geben Sie *0* (die Konto-ID für den Grid-Manager) ein oder wählen Sie *Grid-Manager* aus, wenn er in der Liste der letzten Konten angezeigt wird.
.... Wählen Sie *Anmelden*.
.... Melden Sie sich mit Ihren Standard-SSO-Anmeldedaten auf der SSO-Anmeldeseite Ihres Unternehmens an.






--
====


Wenn Sie angemeldet sind, wird die Startseite des Grid-Managers angezeigt, die das Dashboard enthält. Informationen zu den bereitgestellten Informationen finden Sie unter link:../monitor/viewing-dashboard.html["Das Dashboard anzeigen und verwalten"].



== Melden Sie sich bei einem anderen Admin-Node an

Führen Sie die folgenden Schritte aus, um sich bei einem anderen Admin-Node anzumelden.

[role="tabbed-block"]
====
.SSO wird nicht verwendet
--
.Schritte
. Geben Sie in der Adressleiste des Browsers den vollständig qualifizierten Domänennamen oder die IP-Adresse des anderen Admin-Knotens ein. Geben Sie die Portnummer nach Bedarf an.
. Geben Sie Ihren Benutzernamen und Ihr Kennwort für den Grid Manager ein.
. Wählen Sie *Anmelden*.


--
.SSO wird verwendet
--
Wenn StorageGRID SSO verwendet und Sie sich bei einem Admin-Knoten angemeldet haben, können Sie auf andere Admin-Knoten zugreifen, ohne sich erneut anmelden zu müssen.

.Schritte
. Geben Sie den vollständig qualifizierten Domänennamen oder die IP-Adresse des anderen Admin-Knotens in die Adressleiste des Browsers ein.
. Wenn Ihre SSO-Sitzung abgelaufen ist, geben Sie Ihre Anmeldedaten erneut ein.


--
====