---
permalink: s3/get-bucket-metadata-notification-configuration-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket metadata notification configuration 
summary: Die Konfigurationsanforderung FÜR GET Bucket-Metadaten-Benachrichtigungen ermöglicht es Ihnen, die Konfigurations-XML abzurufen, die zur Konfiguration der Suchintegration für einzelne Buckets verwendet wird. 
---
= Konfiguration der Bucket-Metadaten-Benachrichtigungen ABRUFEN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Konfigurationsanforderung FÜR GET Bucket-Metadaten-Benachrichtigungen ermöglicht es Ihnen, die Konfigurations-XML abzurufen, die zur Konfiguration der Suchintegration für einzelne Buckets verwendet wird.

Sie müssen über die berechtigung s3:GetBucketMetadataNotification verfügen oder als Kontowurzel dienen, um diesen Vorgang abzuschließen.



== Anforderungsbeispiel

Diese Anforderung ruft die Metadaten-Benachrichtigungskonfiguration für den Bucket namens `bucket`ab.

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Antwort

Der Response Body umfasst die Konfiguration der Metadaten-Benachrichtigung für den Bucket. Anhand der Konfiguration der Metadatenbenachrichtigung können Sie festlegen, wie der Bucket für die Suchintegration konfiguriert ist. So können Unternehmen ermitteln, welche Objekte indiziert sind und an welche Endpunkte ihre Objektmetadaten gesendet werden.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
Jede Konfiguration für die Metadatenbenachrichtigung enthält mindestens ein Regeln. Jede Regel gibt die Objekte an, die auf sie angewendet werden, und das Ziel, an dem StorageGRID Objekt-Metadaten senden soll. Ziele müssen mit dem URN eines StorageGRID-Endpunkts angegeben werden.

[cols="1a,2a,1a"]
|===
| Name | Beschreibung | Erforderlich 


 a| 
MetadataNotificationKonfiguration
 a| 
Container-Tag für Regeln zur Angabe von Objekten und Zielen für Metadatenbenachrichtigungen

Enthält mindestens ein Regelelement.
 a| 
Ja.



 a| 
Regel
 a| 
Container-Tag für eine Regel, die die Objekte identifiziert, deren Metadaten zu einem bestimmten Index hinzugefügt werden sollen.

Regeln mit überlappenden Präfixen werden abgelehnt.

Im MetadataNotificationConfiguration Element enthalten.
 a| 
Ja.



 a| 
ID
 a| 
Eindeutige Kennung für die Regel.

In das Element Regel aufgenommen.
 a| 
Nein



 a| 
Status
 a| 
Der Status kann „aktiviert“ oder „deaktiviert“ sein. Für deaktivierte Regeln wird keine Aktion durchgeführt.

In das Element Regel aufgenommen.
 a| 
Ja.



 a| 
Präfix
 a| 
Objekte, die mit dem Präfix übereinstimmen, werden von der Regel beeinflusst und ihre Metadaten werden an das angegebene Ziel gesendet.

Geben Sie ein leeres Präfix an, um alle Objekte zu entsprechen.

In das Element Regel aufgenommen.
 a| 
Ja.



 a| 
Ziel
 a| 
Container-Tag für das Ziel einer Regel.

In das Element Regel aufgenommen.
 a| 
Ja.



 a| 
Urne
 a| 
URNE des Ziels, an dem Objektmetadaten gesendet werden. Muss der URN eines StorageGRID-Endpunkts mit den folgenden Eigenschaften sein:

* `es` Muss das dritte Element sein.
* Die URN muss mit dem Index und dem Typ enden, in dem die Metadaten gespeichert sind, in der Form `domain-name/myindex/mytype`.


Endpunkte werden mithilfe der Mandanten-Manager oder der Mandanten-Management-API konfiguriert. Sie nehmen folgende Form:

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


Der Endpunkt muss konfiguriert werden, bevor die Konfigurations-XML gesendet wird, oder die Konfiguration schlägt mit einem Fehler 404 fehl.

Urne ist im Element Ziel enthalten.
 a| 
Ja.

|===


== Antwortbeispiel

Die XML-Datei zwischen den  `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>` Tags zeigt, wie die Integration mit einem Endpunkt für die Suchintegration für den Bucket konfiguriert ist. In diesem Beispiel werden Objektmetadaten an einen Elasticsearch-Index mit dem Namen und dem Typ `2017` gesendet `current`, der in einer AWS-Domäne mit dem Namen gehostet wird `records`.

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Verwandte Informationen
link:../tenant/index.html["Verwenden Sie ein Mandantenkonto"]
