---
permalink: s3/index.html 
sidebar: sidebar 
keywords: about s3, s3 rest api, s3 overview 
summary: 'StorageGRID unterstützt die Simple Storage Service \ (S3\) API, die als Satz von Representational State Transfer \(REST\) Web Services implementiert wird.' 
---
= Von S3 REST API unterstützte Versionen und Updates
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID unterstützt die S3-API (Simple Storage Service), die als Satz Rest-Web-Services (Representational State Transfer) implementiert wird.

Dank der Unterstützung für die S3-REST-API können serviceorientierte Applikationen, die für S3-Web-Services entwickelt wurden, mit On-Premises-Objekt-Storage verbunden werden, der das StorageGRID-System verwendet. Es sind minimale Änderungen an der aktuellen Nutzung von S3-REST-API-Aufrufen einer Client-Applikation erforderlich.



== Unterstützte Versionen

StorageGRID unterstützt die folgenden spezifischen Versionen von STS, S3 und HTTP:

[cols="1a,1a"]
|===
| Element | Version 


 a| 
STS AssumeRole-API-Spezifikation
 a| 
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html["Amazon Web Services (AWS)-Dokumentation: Amazon Assumerole API-Referenz"^]

Weitere Informationen zu AssumeRole finden Sie unterlink:../tenant/manage-groups.html#set-up-assumerole["Einrichten von AssumeRole"] .



 a| 
S3-API-Spezifikation
 a| 
http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["AWS-Dokumentation: Amazon Simple Storage Service API-Referenz"^]



 a| 
HTTP
 a| 
1,1

Weitere Informationen zu HTTP finden Sie unter HTTP/1.1 (RFCs 7230-35).

https://datatracker.ietf.org/doc/html/rfc2616["IETF RFC 2616: Hypertext Transfer Protocol (HTTP/1.1)"^]

*Hinweis*: StorageGRID unterstützt HTTP/1.1-Pipelining nicht.

|===


== Updates für die S3-REST-API-Unterstützung

[cols="1a,4a"]
|===
| Freigabe | Kommentare 


 a| 
12,0
 a| 
* Unterstützung für Cross-Origin Resource Sharing (CORS) für eine Verwaltungsschnittstelle hinzugefügt, die es einer anderen Domäne ermöglicht, mithilfe von Verwaltungs-APIs auf Daten in StorageGRID zuzugreifen. link:../admin/enable-cross-origin-resource-sharing-for-management-interface.html["Weitere Informationen ."] .
* Unterstützung für STS AssumeRole und Sitzungsrichtlinie hinzugefügt. Sehen link:example-session-policies.html["ein Beispiel für eine Sitzungsrichtlinie"] .  Sie können AssumeRole unter Mandantengruppen einrichten.




 a| 
11,9
 a| 
* Unterstützung für vorberechnete SHA-256-Prüfsummenwerte für die folgenden Anforderungen und unterstützten Header wurde hinzugefügt. Mit dieser Funktion können Sie die Integrität hochgeladener Objekte überprüfen:
+
** CompleteMultipartUpload: `x-amz-checksum-sha256`
** CreateMultipartUpload: `x-amz-checksum-algorithm`
** GetObject: `x-amz-checksum-mode`
** Kopfobjekt: `x-amz-checksum-mode`
** ListenTeile
** PutObject: `x-amz-checksum-sha256`
** UploadPart: `x-amz-checksum-sha256`


* Der Grid-Administrator kann die Aufbewahrungs- und Compliance-Einstellungen auf Mandantenebene kontrollieren. Diese Einstellungen wirken sich auf die Einstellungen der S3-Objektsperre aus.
+
** Standardaufbewahrungsmodus und Objektaufbewahrungsmodus mit Buckets: Governance oder Compliance, sofern vom Grid-Administrator zugelassen.
** Standardaufbewahrungszeitraum für Bucket und Objektaufbewahrung bis Datum: Muss kleiner oder gleich dem sein, was durch den vom Grid-Administrator festgelegten maximalen Aufbewahrungszeitraum zulässig ist.


* Verbesserte Unterstützung von `aws-chunked` Kodierungs- und Streaming-Werten für Inhalte `x-amz-content-sha256`. Einschränkungen:
+
** Falls vorhanden, `chunk-signature` ist optional und nicht validiert
** Wenn vorhanden, `x-amz-trailer` wird der Inhalt ignoriert






 a| 
11,8
 a| 
Die Namen der S3-Vorgänge wurden aktualisiert, um sie mit den in der verwendeten Namen http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Amazon Web Services (AWS) Dokumentation: Amazon Simple Storage Service API Reference"^] zu vergleichen.



 a| 
11,7
 a| 
* Hinzugefügt link:quick-reference-support-for-aws-apis.html["Schnelle Referenz: Unterstützte S3-API-Anforderungen"].
* Zusätzliche Unterstützung für die Verwendung DES GOVERNANCE-Modus mit S3 Object Lock.
* Unterstützung für den StorageGRID-spezifischen Antwortheader für GET Object- und HEAD-Objektanforderungen wurde hinzugefügt `x-ntap-sg-cgr-replication-status`. Dieser Header stellt den Replikationsstatus eines Objekts für die Grid-übergreifende Replikation bereit.
* SelectObjectContent Requests unterstützen nun Parkett-Objekte.




 a| 
11,6
 a| 
* Unterstützung für die Verwendung des Anforderungsparameters in GET Object und HEAD Object Requests hinzugefügt `partNumber`.
* Zusätzliche Unterstützung für einen Standardaufbewahrungsmodus und einen Standardaufbewahrungszeitraum auf Bucket-Ebene für S3 Object Lock.
* Unterstützung für den Richtlinienzustandsschlüssel hinzugefügt `s3:object-lock-remaining-retention-days`, um den Bereich der zulässigen Aufbewahrungsfristen für Ihre Objekte festzulegen.
* Die maximale _recommended_-Größe für einen einzelnen PUT-Objekt-Vorgang wurde auf 5 gib (5,368,709,120 Bytes) geändert. Wenn Sie über Objekte mit einer Größe von mehr als 5 gib verfügen, verwenden Sie stattdessen mehrteilige Uploads.




 a| 
11,5
 a| 
* Zusätzliche Unterstützung für das Management der Bucket-Verschlüsselung
* Unterstützung für S3 Object Lock und veraltete ältere Compliance-Anforderungen wurde hinzugefügt.
* Zusätzliche Unterstützung beim LÖSCHEN mehrerer Objekte in versionierten Buckets.
* Der `Content-MD5` Anforderungskopf wird jetzt korrekt unterstützt.




 a| 
11,4
 a| 
* Unterstützung für DELETE Bucket-Tagging, GET Bucket-Tagging und PUT Bucket-Tagging. Kostenzuordnungstags werden nicht unterstützt.
* Bei in StorageGRID 11.4 erstellten Buckets ist keine Beschränkung der Objektschlüsselnamen auf Performance-Best-Practices mehr erforderlich.
* Unterstützung für Bucket-Benachrichtigungen für den Ereignistyp hinzugefügt `s3:ObjectRestore:Post`.
* Die Größenbeschränkungen von AWS für mehrere Teile werden nun durchgesetzt. Jedes Teil eines mehrteiligen Uploads muss zwischen 5 MiB und 5 gib liegen. Der letzte Teil kann kleiner als 5 MiB sein.
* Unterstützung für TLS 1.3 hinzugefügt




 a| 
11,3
 a| 
* Zusätzliche Unterstützung für serverseitige Verschlüsselung von Objektdaten mit vom Kunden bereitgestellten Schlüsseln (SSE-C).
* Unterstützung für DIE Lebenszyklusoperationen „DELETE“, „GET“ und „PUT“ (nur Ablaufaktion) und für den Antwortheader hinzugefügt `x-amz-expiration`.
* Aktualisiertes PUT-Objekt, PUT-Objekt – Copy und Multipart-Upload, um die Auswirkungen von ILM-Regeln zu beschreiben, die synchrone Platzierung bei der Aufnahme verwenden.
* TLS 1.1-Chiffren werden nicht mehr unterstützt.




 a| 
11,2
 a| 
Unterstützung für DIE WIEDERHERSTELLUNG NACH Objekten wurde hinzugefügt und kann in Cloud-Storage-Pools verwendet werden. Unterstützung für die Verwendung der AWS-Syntax für ARN, Richtlinienzustandsschlüssel und Richtlinienvariablen in Gruppen- und Bucket-Richtlinien Vorhandene Gruppen- und Bucket-Richtlinien, die die StorageGRID-Syntax verwenden, werden weiterhin unterstützt.

*Hinweis:* die Verwendung von ARN/URN in anderen Konfigurationen JSON/XML, einschließlich derjenigen, die in benutzerdefinierten StorageGRID-Funktionen verwendet werden, hat sich nicht geändert.



 a| 
11,1
 a| 
Zusätzliche Unterstützung für die Cross-Origin Resource Sharing (CORS), HTTP für S3-Clientverbindungen zu Grid-Nodes und Compliance-Einstellungen für Buckets.



 a| 
11,0
 a| 
Unterstützung für die Konfiguration von Plattform-Services (CloudMirror Replizierung, Benachrichtigungen und Elasticsearch-Integration) für Buckets. Außerdem wurden die Unterstützung für Objekt-Tagging-Speicherortbeschränkungen für Buckets und die verfügbare Konsistenz hinzugefügt.



 a| 
10,4
 a| 
Unterstützung für ILM-Scanning-Änderungen an Versionierung, Seitenaktualisierungen von Endpoint Domain-Namen, Bedingungen und Variablen in Richtlinien, Richtlinienbeispiele und die Berechtigung PutOverwriteObject.



 a| 
10,3
 a| 
Zusätzliche Unterstützung für Versionierung



 a| 
10,2
 a| 
Unterstützung für Gruppen- und Bucket-Zugriffsrichtlinien und für mehrteilige Kopien (Upload Part - Copy) hinzugefügt



 a| 
10,1
 a| 
Unterstützung für mehrteilige Uploads, virtuelle Hosted-Style-Anforderungen und v4 Authentifizierung



 a| 
10,0
 a| 
Erste Unterstützung der S3 REST API durch das StorageGRID -System.  Die derzeit unterstützte Version der _Simple Storage Service API Reference_ ist 2006-03-01.

|===