---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: Der Vorgang UploadPart lädt ein Teil in einem mehrteiligen Upload für ein Objekt hoch. 
---
= Unterstützte und nicht unterstützte Anforderungsheader für S3 UploadPart-Operationen in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Vorgang UploadPart lädt ein Teil in einem mehrteiligen Upload für ein Objekt hoch.



[[supported-request-headers]]
== Unterstützte Anfrageheader

Die folgenden Anfragezeilen werden unterstützt:

* Prüfsummen-Anforderungsheader:
+
--
** `x-amz-checksum-crc32`
** `x-amz-checksum-crc32c`
** `x-amz-checksum-crc64nvme`
** `x-amz-checksum-sha256`


--
+
Wenn Sie während der CreateMultipartUpload-Anfrage eine CRC-32-, CRC-32C-, CRC-64/NVME- oder SHA-256-Prüfsumme angegeben haben, muss der Prüfsumme-Anforderungsheader auch in jede UploadPart-Anfrage aufgenommen werden.

+

NOTE: Wenn in einer CreateMultipartUpload-Anfrage keine Prüfsumme angegeben wird, berechnet StorageGRID keine Standard-CRC-64/NVME-Prüfsumme für ein Objekt.

* `Content-Length`
* `Content-MD5`




[[request-headers-for-server-side-encryption]]
== Anforderungsheader für serverseitige Verschlüsselung

Wenn Sie die SSE-C-Verschlüsselung für die CreateMultipartUpload-Anforderung angegeben haben, müssen Sie auch die folgenden Anforderungsheader in jede UploadPart-Anforderung einschließen:

* `x-amz-server-side-encryption-customer-algorithm`: Spezifizieren `AES256`.
* `x-amz-server-side-encryption-customer-key`: Geben Sie den gleichen Verschlüsselungsschlüssel an, den Sie in der CreateMultipartUpload-Anforderung angegeben haben.
* `x-amz-server-side-encryption-customer-key-MD5`: Geben Sie den gleichen MD5-Digest an, den Sie in der CreateMultipartUpload-Anfrage angegeben haben.



CAUTION: Die von Ihnen zur Verfügung gelegten Schlüssel werden niemals gespeichert. Wenn Sie einen Verschlüsselungsschlüssel verlieren, verlieren Sie das entsprechende Objekt. Bevor Sie vom Kunden bereitgestellte Schlüssel zum Schutz von Objektdaten verwenden, lesen Sie die Überlegungen in link:using-server-side-encryption.html["Serverseitige Verschlüsselung"].



[[unsupported-request-headers]]
== Nicht unterstützte Anforderungsheader

Die folgenden Anforderungsheader werden nicht unterstützt:

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`
* `x-amz-checksum-md5`
* `x-amz-checksum-sha1`
* `x-amz-checksum-sha512`
* `x-amz-checksum-xxhash3`
* `x-amz-checksum-xxhash64`
* `x-amz-checksum-xxhash128`




[[versioning]]
== Versionierung

Mehrteilige Uploads bestehen aus separaten Vorgängen zum Initiieren des Uploads, Auflisten von Uploads, Hochladen von Teilen, Zusammenbauen der hochgeladenen Teile und Abschließen des Uploads. Objekte werden erstellt (und ggf. versioniert), wenn der CompleteMultipartUpload-Vorgang ausgeführt wird.
