---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: MIB-Dateien enthalten Definitionen und Informationen über die Eigenschaften der verwalteten Ressourcen und Dienste für die Knoten in der Tabelle. Sie können auf MIB-Dateien zugreifen, die die Objekte und Benachrichtigungen für StorageGRID definieren. Diese Dateien können für die Überwachung Ihres Grids nützlich sein. 
---
= Zugriff auf MIB-Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MIB-Dateien enthalten Definitionen und Informationen über die Eigenschaften der verwalteten Ressourcen und Dienste für die Knoten in der Tabelle. Sie können auf MIB-Dateien zugreifen, die die Objekte und Benachrichtigungen für StorageGRID definieren. Diese Dateien können für die Überwachung Ihres Grids nützlich sein.

Weitere Informationen zu SNMP- und MIB-Dateien finden Sie unterlink:using-snmp-monitoring.html["Verwenden Sie SNMP-Überwachung"].



== Zugriff auf MIB-Dateien

Gehen Sie wie folgt vor, um auf die MIB-Dateien zuzugreifen.

.Schritte
. Wählen Sie *KONFIGURATION* > *Überwachung* > *SNMP-Agent*.
. Wählen Sie auf der Seite des SNMP-Agenten die Datei aus, die Sie herunterladen möchten:
+
** *NETAPP-STORAGEGRID-MIB.txt*: Definiert die Alarmtabelle und Benachrichtigungen (Traps), auf die auf allen Admin-Knoten zugegriffen werden kann.
** *Es-NETAPP-06-MIB.mib*: Definiert Objekte und Benachrichtigungen für E-Series-basierte Appliances.
** *MIB_1_10.zip*: Definiert Objekte und Benachrichtigungen für Geräte mit BMC-Schnittstelle.
+
[]
====

TIP: Sie können auch auf MIB-Dateien am folgenden Speicherort auf jedem StorageGRID-Knoten zugreifen: `/usr/share/snmp/mibs`

====


. So extrahieren Sie die StorageGRID-OIDs aus der MIB-Datei:
+
.. Erhalten Sie die OID des Stamms der StorageGRID MIB:
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
Ergebnis: `.1.3.6.1.4.1.789.28669` (`28669` Ist immer die OID für StorageGRID)

.. Grep für die StorageGRID-OID in der gesamten Struktur (zum verbinden von Linien verwenden `paste`):
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`






TIP: Der `snmptranslate` Befehl hat viele Optionen, die nützlich sind, um die MIB zu erforschen. Dieser Befehl ist auf jedem StorageGRID-Node verfügbar.



== MIB-Dateiinhalte

Alle Objekte befinden sich unter der StorageGRID-OID.

[cols="1a,1a,2a"]
|===
| Objektname | Objekt-ID (OID) | Beschreibung 


| .iso.org.dod.internet. + private.Unternehmen. + netapp.storagegrid | .1.3.6.1.4.1.789.28669  a| 
Das MIB-Modul für NetApp StorageGRID-Einheiten.

|===


== MIB-Objekte

[cols="1a,1a,2a"]
|===
| Objektname | Objekt-ID (OID) | Beschreibung 


| ActiveAlertCount | .1.3.6.1.4.1. + 789.28669.1.3  a| 
Die Anzahl der aktiven Warnungen in der activeAlertTable.



| ActiveAlertTable | .1.3.6.1.4.1. + 789.28669.1.4  a| 
Eine Tabelle mit aktiven Warnmeldungen in StorageGRID.



| ActiveAlertId | .1.3.6.1.4.1. + 789.28669.1.4.1.1  a| 
Die ID der Warnmeldung. Nur im aktuellen Satz aktiver Warnungen eindeutig.



| ActiveAlertName | .1.3.6.1.4.1. + 789.28669.1.4.1.2  a| 
Der Name der Warnmeldung.



| ActiveAlertInstance | .1.3.6.1.4.1. + 789.28669.1.4.1.3  a| 
Der Name der Entität, die die Warnmeldung generiert hat, normalerweise der Knotenname.



| ActiveAlertSchweregrad | .1.3.6.1.4.1. + 789.28669.1.4.1.4  a| 
Der Schweregrad der Meldung.



| ActiveAlertStartTime | .1.3.6.1.4.1. + 789.28669.1.4.1.5  a| 
Das Datum und die Uhrzeit, zu der die Warnmeldung ausgelöst wurde.

|===


== Benachrichtigungstypen (Traps)

Alle Benachrichtigungen enthalten die folgenden Variablen als varbindes:

* ActiveAlertId
* ActiveAlertName
* ActiveAlertInstance
* ActiveAlertSchweregrad
* ActiveAlertStartTime


[cols="1a,1a,2a"]
|===
| Benachrichtigungstyp | Objekt-ID (OID) | Beschreibung 


| ActiveMinorAlert | .1.3.6.1.4.1. + 789.28669.0.6  a| 
Ein Alarm mit geringem Schweregrad



| ActiveMajorAlert | .1.3.6.1.4.1. + 789.28669.0.7  a| 
Ein Alarm mit dem Hauptschweregrad



| ActiveCriticalAlert | .1.3.6.1.4.1. + 789.28669.0.8  a| 
Eine Meldung mit dem Schweregrad „kritisch“

|===