---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Sie können StorageGRID-Protokolldateien und Systemdaten einschließlich Konfigurationsdaten abrufen und an den technischen Support senden. 
---
= Erfassen von Protokolldateien und Systemdaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können StorageGRID-Protokolldateien und Systemdaten einschließlich Konfigurationsdaten abrufen und an den technischen Support senden.

.Bevor Sie beginnen
* Sie sind auf dem primären Admin-Knoten mit einem beim Grid-Manager angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben link:../admin/admin-group-permissions.html["Bestimmte Zugriffsberechtigungen"].
* Sie haben die Provisionierungs-Passphrase.


.Über diese Aufgabe
Verwenden Sie den Grid Manager, um link:logs-files-reference.html["Log-Dateien"]Systemdaten und Konfigurationsdaten von einem beliebigen Grid-Knoten für den ausgewählten Zeitraum zu erfassen. Die Daten werden in einer Datei gesammelt und archiviert `.tar.gz`, die Sie dann auf Ihren lokalen Computer herunterladen oder an den technischen Support senden können.

Optional können Sie das Ziel der Audit-Protokolle ändern und Audit-Informationen an einen externen Syslog-Server senden. Lokale Protokolle von Audit-Datensätzen werden weiterhin generiert und gespeichert, wenn ein externer Syslog-Server konfiguriert ist. Siehe link:../monitor/configure-audit-messages.html["Konfigurieren von Audit-Meldungen und externem Syslog-Server"].

.Schritte
. Wählen Sie *SUPPORT* > *Extras* > *Protokolle*. Eine Tabelle mit Knoten wird angezeigt.
. Wählen Sie die Grid-Knoten aus, für die Sie Protokolldateien sammeln möchten.
+
Sie können nach Node-Namen, Standort und Node-Typ sortieren. Die Spalten Standort und Knotentyp enthalten Filter zur Auswahl nach einzelnen Standorten und Knotentypen.

. Wählen Sie *Weiter*.
. Wählen Sie das Datum und den Zeitraum der Daten aus, die in die Protokolldateien aufgenommen werden sollen.
+
Wenn Sie einen sehr langen Zeitraum auswählen oder Protokolle von allen Knoten in einem großen Raster sammeln, könnte das Protokollarchiv zu groß werden, um auf einem Knoten gespeichert zu werden, oder zu groß, um zum Download an den primären Admin-Knoten gesammelt zu werden. Wenn eines der Szenarien eintritt, starten Sie die Protokollerfassung mit einem kleineren Datensatz neu.

. Wählen Sie die Protokolltypen aus, die Sie sammeln möchten.
+
** *Anwendungsprotokolle*: Anwendungsspezifische Protokolle, die der technische Support am häufigsten für die Fehlerbehebung verwendet. Die gesammelten Protokolle sind eine Teilmenge der verfügbaren Anwendungsprotokolle.
** *Audit-Protokolle*: Protokolle, die die während des normalen Systembetriebs generierten Audit-Nachrichten enthalten.
** *Network Trace*: Protokolle für das Netzwerk-Debugging.
** *Prometheus-Datenbank*: Zeitreihenmetriken aus den Diensten auf allen Knoten.


. Verwenden Sie optional das Textfeld *Hinweise*, um Notizen zu den Protokolldateien einzugeben, die Sie sammeln.
+
Mithilfe dieser Hinweise können Sie Informationen zum technischen Support über das Problem geben, das Sie zum Erfassen der Protokolldateien aufgefordert hat. Ihre Notizen werden zu einer Datei mit dem Namen, zusammen mit anderen Informationen über die Log-Datei-Sammlung hinzugefügt `info.txt`. Die `info.txt` Datei wird im Archivpaket der Protokolldatei gespeichert.

. Geben Sie im Textfeld *Provisionierungs-Passphrase* die Provisionierungs-Passphrase für Ihr StorageGRID-System ein.
. Wählen Sie *Protokolle sammeln*.
+
Auf der Seite „Protokolle“ können Sie den Fortschritt der Sammlung von Protokolldateien für jeden Grid-Knoten überwachen.

+
Wenn Sie eine Fehlermeldung über die Protokollgröße erhalten, versuchen Sie, Protokolle für einen kürzeren Zeitraum oder für weniger Nodes zu sammeln.

. Wenn die Protokollerfassung fehlschlägt:
+
** Wenn die Meldung „Log Collection failed“ angezeigt wird, können Sie die Protokollsammlung erneut versuchen oder die Sitzung beenden, ohne erneut zu versuchen.
** Wenn die Meldung „Log Collection partially failed“ angezeigt wird, können Sie die Protokollsammlung erneut versuchen, die Sitzung beenden, die teilweise Protokolldatei herunterladen oder die teilweise Protokolldatei an AutoSupport senden.


. Wenn die Sammlung der Protokolldatei abgeschlossen ist:
+
** Wählen Sie *Download*, um die Datei herunterzuladen `.tar.gz`.
** Wählen Sie *an AutoSupport senden*, um die Datei an den technischen Support zu senden `.tar.gz`.
+
Die `.tar.gz` Datei enthält alle Protokolldateien von allen Grid-Nodes, auf denen die Protokollerfassung erfolgreich war. Die kombinierte `.tar.gz` Datei enthält ein Protokolldateiarchiv für jeden Grid-Knoten.

+
Gegenstand des AutoSupport-Pakets ist `USER_TRIGGERED_SUPPORT_BUNDLE`.



. Wählen Sie *Fertig*.
+

CAUTION: Die `.tar.gz` Datei wird gelöscht, wenn Sie *Finish* auswählen. Stellen Sie sicher, dass Sie die Datei zuerst herunterladen oder senden.


