---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Sie können StorageGRID -Protokolldateien und Systemdaten, einschließlich Konfigurationsdaten, abrufen und an den technischen Support senden. 
---
= Erfassen von Protokolldateien und Systemdaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können StorageGRID -Protokolldateien und Systemdaten, einschließlich Konfigurationsdaten, abrufen und an den technischen Support senden.

.Bevor Sie beginnen
* Sie sind beim Grid Manager auf einem beliebigen Admin-Knoten mit einemlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"] .
* Sie haben link:../admin/admin-group-permissions.html["Bestimmte Zugriffsberechtigungen"].
* Sie haben die Provisionierungs-Passphrase.


.Über diese Aufgabe
Verwenden Sie den Grid Manager, umlink:logs-files-reference.html["Log-Dateien"] , Systemdaten und Konfigurationsdaten von jedem Grid-Knoten für den von Ihnen ausgewählten Zeitraum.  Die Daten werden gesammelt und archiviert in einem `.tar.gz` Datei, die Sie dann auf Ihren lokalen Computer herunterladen oder an den technischen Support senden können.

Optional können Sie das Ziel der Überwachungsprotokolle ändern und Überwachungsinformationen an einen externen Syslog-Server senden.  Wenn ein externer Syslog-Server konfiguriert ist, werden weiterhin lokale Protokolle von Prüfdatensätzen generiert und gespeichert. Sehen link:../monitor/configure-log-management.html["Konfigurieren Sie die Protokollverwaltung und den externen Syslog-Server"] .

.Schritte
. Wählen Sie *Support* > *Tools* > *Protokollsammlung*.  Es wird eine Tabelle mit Knoten angezeigt.
. Wählen Sie die Grid-Knoten aus, für die Sie Protokolldateien sammeln möchten.
+
Sie können nach Knotenname, Site und Knotentyp sortieren.  Die Spalten „Site“ und „Knotentyp“ enthalten Filter zur Auswahl nach einzelnen Sites und Knotentypen.

. Wählen Sie *Weiter*.
. Wählen Sie den Datums- und Zeitbereich der Daten aus, die in die Protokolldateien aufgenommen werden sollen.
+
Wenn Sie einen sehr langen Zeitraum auswählen oder Protokolle von allen Knoten in einem großen Raster sammeln, kann das Protokollarchiv zu groß werden, um auf einem Knoten gespeichert zu werden, oder zu groß, um von einem Admin-Knoten zum Download abgerufen zu werden.  Wenn eines dieser Szenarien eintritt, starten Sie die Protokollerfassung mit einem kleineren Datensatz neu.

. Wählen Sie die Protokolltypen aus, die Sie sammeln möchten.
+
** *Anwendungsprotokolle*: Anwendungsspezifische Protokolle, die der technische Support am häufigsten zur Fehlerbehebung verwendet.  Die gesammelten Protokolle sind eine Teilmenge der verfügbaren Anwendungsprotokolle.
** *Audit-Protokolle*: Protokolle mit den während des normalen Systembetriebs generierten Audit-Meldungen.
** *Netzwerkverfolgung*: Protokolle, die zum Debuggen des Netzwerks verwendet werden.
** *Prometheus-Datenbank*: Zeitreihenmetriken von den Diensten auf allen Knoten.


. Optional können Sie im Textfeld *Notizen* Notizen zu den Protokolldateien eingeben, die Sie erfassen.
+
Mithilfe dieser Hinweise können Sie Informationen zum technischen Support über das Problem geben, das Sie zum Erfassen der Protokolldateien aufgefordert hat. Ihre Notizen werden zu einer Datei mit dem Namen, zusammen mit anderen Informationen über die Log-Datei-Sammlung hinzugefügt `info.txt`. Die `info.txt` Datei wird im Archivpaket der Protokolldatei gespeichert.

. Geben Sie im Textfeld *Bereitstellungspassphrase* die Bereitstellungspassphrase für Ihr StorageGRID -System ein.
. Wählen Sie *Protokolle sammeln*.
+
Auf der Seite „Protokollsammlung“ können Sie den Fortschritt der Protokolldateisammlung für jeden Grid-Knoten überwachen.

+
Wenn Sie eine Fehlermeldung über die Protokollgröße erhalten, versuchen Sie, Protokolle für einen kürzeren Zeitraum oder für weniger Nodes zu sammeln.

. Wenn die Protokollerfassung fehlschlägt:
+
** Wenn die Meldung „Protokollerfassung fehlgeschlagen“ angezeigt wird, können Sie die Protokollerfassung erneut versuchen oder die Sitzung ohne erneuten Versuch beenden.
** Wenn die Meldung „Protokollerfassung teilweise fehlgeschlagen“ angezeigt wird, können Sie die Protokollerfassung erneut versuchen, die Sitzung beenden, die teilweise Protokolldatei herunterladen oder die teilweise Protokolldatei an AutoSupport senden.


. Wenn die Protokolldateierfassung abgeschlossen ist:
+
** Wählen Sie *Herunterladen*, um die `.tar.gz` Datei.
** Wählen Sie *An AutoSupport senden*, um die `.tar.gz` Datei an den technischen Support.
+
Der `.tar.gz` Die Datei enthält alle Protokolldateien aller Grid-Knoten, bei denen die Protokollerfassung erfolgreich war.  Die kombinierte `.tar.gz` Die Datei enthält ein Protokolldateiarchiv für jeden Grid-Knoten.

+
Gegenstand des AutoSupport Pakets ist `USER_TRIGGERED_SUPPORT_BUNDLE` .



. Wählen Sie *Fertig*.
+

CAUTION: Der `.tar.gz` Die Datei wird gelöscht, wenn Sie *Fertig* auswählen.  Stellen Sie sicher, dass Sie die Datei zuerst herunterladen oder senden.


