---
permalink: monitor/configure-autosupport-grid-manager.html 
sidebar: sidebar 
keywords: how to configure autosupport, what is autosupport-on-demand 
summary: Die AutoSupport-Funktion ermöglicht es Ihrem StorageGRID System, regelmäßige und ereignisgesteuerte Health- und Statusmeldungen an den technischen Support zu senden, um eine proaktive Überwachung und Fehlerbehebung zu ermöglichen. StorageGRID AutoSupport ermöglicht zudem die Nutzung von Digital Advisor für prädiktive Empfehlungen. 
---
= Konfigurieren Sie AutoSupport in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die AutoSupport-Funktion ermöglicht es Ihrem StorageGRID System, regelmäßige und ereignisgesteuerte Health- und Statusmeldungen an den technischen Support zu senden, um eine proaktive Überwachung und Fehlerbehebung zu ermöglichen. StorageGRID AutoSupport ermöglicht zudem die Nutzung von Digital Advisor für prädiktive Empfehlungen.

Standardmäßig sind die wöchentlichen und ereignisgesteuerten AutoSupport-Funktionen für softwarebasierte StorageGRID Systeme bei der Erstinstallation von StorageGRID aktiviert. Jedoch muss <<autosupport-for-appliances,Hardware-AutoSupport konfigurieren>> auf jedem Appliance-Gerät erfolgen. Bei Bedarf kann die AutoSupport-Konfiguration geändert werden.


NOTE: Wenn Sie die Konfiguration von StorageGRID AutoSupport ändern möchten, sollten Änderungen ausschließlich auf dem primären Admin-Knoten vorgenommen werden.

.Bevor Sie beginnen
* Sie sind beim Grid Manager auf dem primären Admin-Node mit einem link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"] angemeldet.
* Sie haben die link:../admin/admin-group-permissions.html["Root-Zugriffsberechtigung"].
* Wenn Sie HTTPS zum Senden von AutoSupport-Paketen verwenden, wurde dem primären Admin-Node ausgehender Internetzugriff gewährt, entweder direkt oder link:../admin/configuring-admin-proxy-settings.html["Verwenden eines Proxy-Servers"] (eingehende Verbindungen sind nicht erforderlich).
* Wenn auf der StorageGRID AutoSupport-Seite HTTP ausgewählt ist, haben Sie link:../admin/configuring-admin-proxy-settings.html["Proxy-Server konfiguriert"], um AutoSupport-Pakete als HTTPS weiterzuleiten. Die AutoSupport-Server von NetApp lehnen über HTTP gesendete Pakete ab.
* Wenn Sie SMTP als Protokoll für AutoSupport-Pakete verwenden, haben Sie link:../monitor/configure-email-server.html["einen E-Mail-Server konfiguriert"].


.Über diese Aufgabe
Sie können eine beliebige Kombination der folgenden Optionen verwenden, um AutoSupport-Pakete an den technischen Support zu senden:

* *Wöchentlich*: Verschicken Sie AutoSupport-Pakete automatisch einmal pro Woche. Standardeinstellung: Aktiviert.
* *Event-Triggered*: Sendet automatisch AutoSupport-Pakete jede Stunde oder wenn bedeutende Systemereignisse auftreten. Standardeinstellung: Aktiviert.
* *On Demand*: Lassen Sie technischen Support verlangen, dass Ihr StorageGRID-System AutoSupport-Pakete automatisch sendet, was nützlich ist, wenn sie aktiv an einem Problem arbeiten (erfordert HTTPS AutoSupport Übertragungsprotokoll). Standardeinstellung: Deaktiviert.
* *Vom Benutzer ausgelöst*: AutoSupport-Pakete jederzeit manuell senden.
* *Protokollsammlung*:link:../monitor/collecting-log-files-and-system-data.html["Sammeln Sie manuell Protokolldateien und Systemdaten und senden Sie ein AutoSupport Paket"] .




[[configure-autosupportconfigure-autosupport]]
== [[configure-autosupport]]AutoSupport konfigurieren

Um die Standardinstallationskonfiguration für AutoSupport zu ändern oder die Hardware-AutoSupport auf jedem StorageGRID Gerät zu konfigurieren:

.Schritte
. Wählen Sie *Support* > *Tools* > * AutoSupport* > *Einstellungen*.
. Wählen Sie das Protokoll aus, das zum Senden von AutoSupport-Paketen verwendet werden soll.
+
** *HTTPS*: Dies ist die Standard-Einstellung und wird für Neuinstallationen empfohlen. Dieses Protokoll verwendet Port 443. Wenn Sie möchten<<AutoSupport-on-Demand aktivieren,Aktivieren Sie die Funktion „AutoSupport On Demand“>>, müssen Sie HTTPS verwenden.
** *HTTP*: Wenn Sie HTTP auswählen, müssen Sie link:../admin/configuring-admin-proxy-settings.html["Konfiguration eines Proxyservers"], um AutoSupport Pakete als HTTPS weiterzuleiten. Die AutoSupport Server von NetApp lehnen Pakete ab, die über HTTP gesendet werden. Dieses Protokoll verwendet Port 80.
** *SMTP*: Diese Option ist zu wählen, wenn AutoSupport-Pakete per E-Mail versendet werden sollen. Zunächst muss link:../monitor/configure-email-server.html["einen E-Mail-Server konfigurieren"].


+
Das festgelegte Protokoll wird für das Senden aller AutoSupport-Pakete verwendet, mit Ausnahme von AutoSupport on Demand, das das HTTPS-Protokoll erfordert.

. Wenn Sie *HTTPS* ausgewählt haben, wählen Sie aus, ob Sie ein NetApp-Support-Zertifikat (TLS-Zertifikat) verwenden möchten, um die Verbindung zum technischen Support-Server zu sichern.
+
** *Zertifikat prüfen* (Standard): Stellt sicher, dass die Übertragung von AutoSupport-Paketen sicher ist. Das NetApp Supportzertifikat ist bereits mit der StorageGRID Software installiert.
** *Zertifikat nicht überprüfen*: Wählen Sie diese Option nur aus, wenn Sie einen guten Grund haben, keine Zertifikatvalidierung zu verwenden, z.B. wenn es ein vorübergehendes Problem mit einem Zertifikat gibt.


. Wenn Sie *SMTP* ausgewählt haben, verwenden Sie das Feld *Absender*, um die Adresse des E-Mail-Servers einzugeben, den Sie zuvor konfiguriert haben.
. Wählen Sie *Speichern*. Alle wöchentlichen, vom Benutzer ausgelösten und vom Ereignis ausgelösten Pakete werden mit dem ausgewählten Protokoll gesendet.




[[disable-weekly-autosupport]]
== Wöchentliche AutoSupport deaktivieren

Standardmäßig ist das StorageGRID-System so konfiguriert, dass einmal pro Woche ein AutoSupport-Paket an den technischen Support gesendet wird.

Um zu bestimmen, wann das wöchentliche AutoSupport-Paket gesendet wird, gehen Sie auf die Registerkarte *AutoSupport* > *Results*. Im Abschnitt *Weekly AutoSupport* sehen Sie sich den Wert für *Next Scheduled Time* an.

Sie können das automatische Senden von wöchentlichen AutoSupport-Paketen jederzeit deaktivieren.

.Schritte
. Wählen Sie *Support* > *Tools* > * AutoSupport* > *Einstellungen*.
. Deaktivieren Sie das Kontrollkästchen *Weekly AutoSupport* aktivieren.
. Wählen Sie *Speichern*.




[[disable-event-triggered-autosupport]]
== Deaktivieren Sie ereignisgesteuerte AutoSupport

Standardmäßig ist das StorageGRID System so konfiguriert, dass jede Stunde ein AutoSupport-Paket an den technischen Support gesendet wird.

Sie können ereignisgesteuerte AutoSupport jederzeit deaktivieren.

.Schritte
. Wählen Sie *Support* > *Tools* > * AutoSupport* > *Einstellungen*.
. Deaktivieren Sie das Kontrollkästchen *Event-Triggered AutoSupport* aktivieren.
. Wählen Sie *Speichern*.




[[enable-autosupport-on-demand]]
== AutoSupport-on-Demand aktivieren

AutoSupport On Demand kann Ihnen bei der Lösung von Problemen helfen, an denen der technische Support aktiv arbeitet.

AutoSupport-on-Demand ist standardmäßig deaktiviert. Wenn Sie diese Funktion aktivieren, kann der technische Support von Ihrem StorageGRID-System verlangen, dass AutoSupport-Pakete automatisch gesendet werden. Der technische Support kann auch das Abfrageintervall für AutoSupport-on-Demand-Abfragen festlegen.

Der technische Support kann AutoSupport On Demand nicht aktivieren oder deaktivieren.

.Schritte
. Wählen Sie *Support* > *Tools* > * AutoSupport* > *Einstellungen*.
. Wählen Sie *HTTPS* für das Protokoll aus.
. Aktivieren Sie das Kontrollkästchen *Weekly AutoSupport* aktivieren.
. Aktivieren Sie das Kontrollkästchen *AutoSupport on Demand aktivieren*.
. Wählen Sie *Speichern*.
+
AutoSupport-on-Demand ist aktiviert, und der technische Support kann AutoSupport-on-Demand-Anfragen an StorageGRID senden.





[[disable-checks-for-software-updates]]
== Deaktivieren Sie die Prüfung auf Softwareupdates

Standardmäßig wendet sich StorageGRID an NetApp, um zu ermitteln, ob Software-Updates für Ihr System verfügbar sind. Wenn ein StorageGRID-Hotfix oder eine neue Version verfügbar ist, wird die neue Version auf der Seite StorageGRID-Aktualisierung angezeigt.

Bei Bedarf können Sie optional die Prüfung auf Softwareupdates deaktivieren. Wenn Ihr System beispielsweise keinen WAN-Zugriff hat, sollten Sie die Prüfung deaktivieren, um Download-Fehler zu vermeiden.

.Schritte
. Wählen Sie *Support* > *Tools* > * AutoSupport* > *Einstellungen*.
. Deaktivieren Sie das Kontrollkästchen *nach Softwareupdates suchen*.
. Wählen Sie *Speichern*.




[[add-an-additional-autosupport-destination]]
== Fügen Sie ein weiteres AutoSupport Ziel hinzu

Wenn Sie AutoSupport aktivieren, werden Health- und Statuspakete an den technischen Support gesendet. Sie können ein zusätzliches Ziel für alle AutoSupport-Pakete angeben.

Informationen zur Überprüfung oder Änderung des zum Senden von AutoSupport-Paketen verwendeten Protokolls finden Sie in den Anweisungen unter <<configure-autosupport,AutoSupport konfigurieren>>.


NOTE: Sie können das SMTP-Protokoll nicht verwenden, um AutoSupport-Pakete an ein zusätzliches Ziel zu senden.

.Schritte
. Wählen Sie *Support* > *Tools* > * AutoSupport* > *Einstellungen*.
. Wählen Sie *Zusätzliches AutoSupport-Ziel aktivieren*.
. Geben Sie Folgendes an:
+
Hostname:: Der Hostname oder die IP-Adresse des Servers eines zusätzlichen AutoSupport-Zielservers.
+
--

NOTE: Sie können nur ein weiteres Ziel eingeben.

--
Port:: Der Port, über den eine Verbindung zu einem zusätzlichen AutoSupport-Zielserver hergestellt wird. Der Standardwert ist Port 80 für HTTP oder Port 443 für HTTPS.
Zertifikatvalidierung:: Ob ein TLS-Zertifikat verwendet wird, um die Verbindung zum zusätzlichen Ziel zu sichern.
+
--
** Wählen Sie *Zertifikat überprüfen*, um die Zertifikatvalidierung zu verwenden.
** Wählen Sie *Zertifikat nicht verifizieren*, um Ihre AutoSupport-Pakete ohne Zertifikatvalidierung zu senden.
+
Wählen Sie diese Option nur aus, wenn Sie einen guten Grund haben, die Zertifikatvalidierung nicht zu verwenden, z. B. wenn ein vorübergehendes Problem mit einem Zertifikat vorliegt.



--


. Wenn Sie *Zertifikat überprüfen* ausgewählt haben, gehen Sie wie folgt vor:
+
.. Navigieren Sie zum Speicherort des Zertifizierungsstellenzertifikats.
.. Laden Sie die CA-Zertifikatdatei hoch.
+
Die Metadaten des CA-Zertifikats werden angezeigt.



. Wählen Sie *Speichern*.
+
Alle zukünftigen wöchentlichen, ereignisgetriggerten und vom Benutzer ausgelösten AutoSupport Pakete werden an das zusätzliche Ziel gesendet.





[[autosupport-for-appliancesconfigure-autosupport-for-appliances]]
== [[AutoSupport für Appliances]]Konfigurieren von AutoSupport für Appliances

AutoSupport für Appliances meldet StorageGRID Hardwareprobleme und StorageGRID AutoSupport meldet StorageGRID Softwareprobleme. Mit einer Ausnahme meldet StorageGRID AutoSupport sowohl Hardware- als auch Softwareprobleme. Sie müssen AutoSupport auf jeder Appliance konfigurieren, mit Ausnahme der SGF6112, die keine zusätzliche Konfiguration erfordert. AutoSupport wird für Service-Appliances und Storage Appliances anders implementiert.

Sie verwenden SANtricity, um AutoSupport für jede Storage Appliance zu aktivieren. Sie können SANtricity AutoSupport während der ersten Appliance-Einrichtung oder nach der Installation einer Appliance konfigurieren:

* Für SG6000 und SG5700 Appliances, https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/accessing-and-configuring-santricity-system-manager.html["Konfigurieren Sie AutoSupport in SANtricity System Manager"^]


AutoSupport-Pakete von E-Series Appliances können in StorageGRID AutoSupport einbezogen werden, wenn die AutoSupport-Zustellung per Proxy in link:sending-eseries-autosupport-messages-through-storagegrid.html["SANtricity System Manager"] konfiguriert wird.

StorageGRID AutoSupport meldet keine Hardwareprobleme, z. B. DIMM- oder HIC-Fehler (Host Interface Card). Einige Komponentenfehler können jedoch auslösenlink:../monitor/alerts-reference.html["Warnmeldungen zu Hardware"]. Bei StorageGRID Appliances mit einem Baseboard Management Controller (BMC) können Sie E-Mail und SNMP Traps konfigurieren, um Hardwarefehler zu melden:

* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/setting-up-email-notifications-for-alerts.html["E-Mail-Benachrichtigungen für BMC-Warnungen einrichten"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/configuring-snmp-settings-for-bmc.html["Konfigurieren Sie die SNMP-Einstellungen für BMC"^]


.Verwandte Informationen
* link:../network/external-communications.html["Anschlüsse für externe Kommunikation"]
* https://mysupport.netapp.com/site/global/dashboard["NetApp Support"^]

