---
permalink: monitor/configure-log-management.html 
sidebar: sidebar 
keywords: log management, audit level, external syslog server, log destinations 
summary: Konfigurieren Sie nach Bedarf Prüfebenen, Protokollheader und den Speicherort von Prüfmeldungen und -protokollen. 
---
= Protokollverwaltung in StorageGRID konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Bedarf können Audit-Stufen, Protokoll-Header, der Speicherort von Audit-Meldungen und Protokollen sowie die Protokollaufbewahrung konfiguriert werden.

Alle StorageGRID -Knoten generieren Prüfmeldungen und Protokolle, um Systemaktivitäten und Ereignisse zu verfolgen.  Prüfmeldungen und -protokolle sind wichtige Tools zur Überwachung und Fehlerbehebung.

Optional können Sie link:../monitor/considerations-for-external-syslog-server.html["Konfigurieren Sie einen externen Syslog-Server"] verwenden, um Auditinformationen remote zu speichern. Die Leistungsbeeinträchtigung durch die Protokollierung von Auditmeldungen lässt sich minimieren, ohne die Vollständigkeit der Auditdaten zu reduzieren, wenn ein externer Server verwendet wird. Ein externer Syslog Server ist besonders nützlich, wenn ein großes Grid vorhanden ist, mehrere Typen von S3-Anwendungen genutzt werden oder alle Auditdaten aufbewahrt werden sollen.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:../admin/admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Wenn Sie planen, einen externen Syslog-Server zu konfigurieren, haben Sie die folgenden Schritte überprüft und befolgtlink:../monitor/considerations-for-external-syslog-server.html["Überlegungen zur Verwendung eines externen Syslog-Servers"] .
* Wenn Sie einen externen Syslog-Server mit TLS- oder RELP/TLS-Protokoll konfigurieren möchten, verfügen Sie über die erforderlichen Server-CA- und Client-Zertifikate und den privaten Client-Schlüssel.




[[change-audit-message-levels]]
== Meldungsebenen ändern

Sie können für jede der folgenden Meldungskategorien im Prüfprotokoll eine andere Überwachungsstufe festlegen:

[cols="1a,1a,1a"]
|===
| Audit-Kategorie | Standardeinstellung | Weitere Informationen 


 a| 
System
 a| 
Normal
 a| 
link:../audit/system-audit-messages.html["Systemaudits Meldungen"]



 a| 
Storage
 a| 
Fehler
 a| 
link:../audit/object-storage-audit-messages.html["Audit-Meldungen zu Objekt-Storage"]



 a| 
Vereinfachtes
 a| 
Normal
 a| 
link:../audit/management-audit-message.html["Management-Audit-Nachricht"]



 a| 
Client-Lesevorgänge
 a| 
Normal
 a| 
link:../audit/client-read-audit-messages.html["Client liest Audit-Meldungen"]



 a| 
Client-Schreibvorgänge
 a| 
Normal
 a| 
link:../audit/client-write-audit-messages.html["Audit-Meldungen des Clients schreiben"]



 a| 
ILM
 a| 
Normal
 a| 
link:../audit/ilm-audit-messages.html["ILM-Prüfmeldungen"]



 a| 
Grid-übergreifende Replizierung
 a| 
Fehler
 a| 
link:../audit/cgrr-cross-grid-replication-request.html["CGRR: Grid-übergreifende Replikationsanforderung"]

|===

NOTE: Bei Upgrades werden Konfigurationen auf Audit-Ebene nicht sofort wirksam.

.Schritte
. Wählen Sie *Konfiguration* > *Überwachung* > *Protokollverwaltung*.
. Wählen Sie für jede Kategorie der Überwachungsmeldung eine Überwachungsstufe aus der Dropdown-Liste aus:
+
[cols="1a,3a"]
|===
| Audit-Level | Beschreibung 


 a| 
Aus
 a| 
Es werden keine Überwachungsmeldungen aus der Kategorie protokolliert.



 a| 
Fehler
 a| 
Es werden nur Fehlermeldungen protokolliert – Prüfmeldungen, deren Ergebniscode nicht „erfolgreich“ (SUCS) war.



 a| 
Normal
 a| 
Standardtransaktionsmeldungen werden protokolliert – die in diesen Anweisungen für die Kategorie aufgeführten Nachrichten.



 a| 
Debuggen
 a| 
Veraltet. Dieser Level verhält sich mit dem normalen Prüfstand.

|===
+
Die Meldungen, die für eine bestimmte Ebene enthalten sind, enthalten diejenigen, die auf den höheren Ebenen protokolliert werden würden. Die normale Ebene umfasst beispielsweise alle Fehlermeldungen.

+

NOTE: Wenn Sie keine detaillierte Aufzeichnung der Client-Lesevorgänge für Ihre S3-Anwendungen benötigen, ändern Sie optional die Einstellung *Client Reads* in *Error*, um die Anzahl der im Audit-Protokoll aufgezeichneten Audit-Meldungen zu verringern.

. Wählen Sie *Speichern*.




[[define-http-request-headers]]
== Definieren Sie HTTP-Anforderungsheader

Sie können optional alle HTTP-Anforderungsheader definieren, die Sie in die Prüfnachrichten zum Lesen und Schreiben des Clients aufnehmen möchten.

.Schritte
. Definieren Sie im Abschnitt *Audit Protocol headers* die HTTP-Anforderungsheader, die Sie in die Audit-Nachrichten des Clients aufnehmen möchten.
+
Verwenden Sie ein Sternchen (\*) als Platzhalter, um Null oder mehr Zeichen zu entsprechen. Verwenden Sie die Escape-Sequenz (\*), um mit einem wortwörtliche Sternchen überein.

. Wählen Sie *Einen anderen Header hinzufügen* aus, um ggf. zusätzliche Header zu erstellen.
+
Wenn StorageGRID HTTP-Header in einer Anfrage findet, werden diese im Prüfprotokoll unter dem Feld HTRH aufgeführt.

+

NOTE: Anforderungsheader des Prüfprotokolls werden nur protokolliert, wenn die Prüfebene für *Client-Lesevorgänge* oder *Client-Schreibvorgänge* nicht *Aus* ist.

. Wählen Sie *Speichern*




[[configure-log-location]]
== Konfigurieren des Protokollspeicherorts

Standardmäßig werden Audit-Meldungen und Protokolle auf den Knoten gespeichert, auf denen sie generiert werden. StorageGRID rotiert und löscht Audit-Meldungen und Protokolle regelmäßig, um zu verhindern, dass sie übermäßig viel Speicherplatz belegen. Um Audit-Meldungen und eine Teilmenge der Protokolle extern zu speichern, <<use-external-syslog-server,Verwenden Sie einen externen Syslog-Server>>.

Wenn Sie die Protokolldateien intern speichern möchten, wählen Sie einen Mandanten und einen Bucket für die Protokollspeicherung aus und aktivieren Sie die Protokollarchivierung.



[[use-external-syslog-serveruse-an-external-syslog-server]]
=== [[use-external-syslog-Server]]Verwenden Sie einen externen syslog-Server

Optional können Sie einen externen Syslog-Server konfigurieren, um Audit-Protokolle, Anwendungsprotokolle und Sicherheitsereignisprotokolle an einem Ort außerhalb des Grids zu speichern.


NOTE: Wenn Sie keinen externen Syslog-Server verwenden möchten, überspringen Sie diesen Schritt und gehen Sie zu<<select-log-location,Protokollspeicherort auswählen>> .


TIP: Wenn die in diesem Verfahren verfügbaren Konfigurationsoptionen nicht flexibel genug sind, um Ihre Anforderungen zu erfüllen, können zusätzliche Konfigurationsoptionen über die Endpunkte angewendet werden `audit-destinations`, die sich im Abschnitt Private API des befindenlink:../admin/using-grid-management-api.html["Grid Management API"]. Sie können beispielsweise die API verwenden, wenn Sie unterschiedliche Syslog-Server für verschiedene Knotengruppen verwenden möchten.



==== Geben Sie Syslog-Informationen ein

Greifen Sie auf den Assistenten zum Konfigurieren des externen Syslog-Servers zu und geben Sie die Informationen an, die StorageGRID für den Zugriff auf den externen Syslog-Server benötigt.

.Schritte
. Wählen Sie auf der Registerkarte „Lokaler Knoten und externer Server“ die Option „Externen Syslog-Server konfigurieren“ aus.  Oder wählen Sie *Externen Syslog-Server bearbeiten*, wenn Sie zuvor einen externen Syslog-Server konfiguriert haben.
+
Der Assistent zum Konfigurieren des externen Syslog-Servers wird angezeigt.

. Geben Sie für den Schritt *Enter syslog info* des Assistenten einen gültigen vollständig qualifizierten Domänennamen oder eine IPv4- oder IPv6-Adresse für den externen Syslog-Server in das Feld *Host* ein.
. Geben Sie den Zielport auf dem externen Syslog-Server ein (muss eine Ganzzahl zwischen 1 und 65535 sein). Der Standardport ist 514.
. Wählen Sie das Protokoll aus, das zum Senden von Audit-Informationen an den externen Syslog-Server verwendet wird.
+
Die Verwendung von *TLS* oder *RELP/TLS* wird empfohlen. Sie müssen ein Serverzertifikat hochladen, um eine dieser Optionen verwenden zu können. Mithilfe von Zertifikaten lassen sich die Verbindungen zwischen dem Grid und dem externen Syslog-Server sichern. Weitere Informationen finden Sie unter link:../admin/using-storagegrid-security-certificates.html["Verwalten von Sicherheitszertifikaten"].

+
Für alle Protokolloptionen muss der externe Syslog-Server unterstützt und konfiguriert werden. Sie müssen eine Option wählen, die mit dem externen Syslog-Server kompatibel ist.

+

NOTE: Reliable Event Logging Protocol (RELP) erweitert die Funktionalität des Syslog-Protokolls für eine zuverlässige Bereitstellung von Ereignismeldungen. Mithilfe von RELP können Sie den Verlust von Audit-Informationen verhindern, wenn Ihr externer Syslog-Server neu gestartet werden muss.

. Wählen Sie *Weiter*.
. [[Attach-Certificate]]Wenn Sie *TLS* oder *RELP/TLS* ausgewählt haben, laden Sie die Server-CA-Zertifikate, das Client-Zertifikat und den privaten Client-Schlüssel hoch.
+
.. Wählen Sie *Durchsuchen* für das Zertifikat oder den Schlüssel, das Sie verwenden möchten.
.. Wählen Sie das Zertifikat oder die Schlüsseldatei aus.
.. Wählen Sie *Öffnen*, um die Datei hochzuladen.
+
Neben dem Zertifikat- oder Schlüsseldateinamen wird eine grüne Prüfung angezeigt, die Sie darüber informiert, dass das Zertifikat erfolgreich hochgeladen wurde.



. Wählen Sie *Weiter*.




==== Syslog-Inhalte managen

Sie können auswählen, welche Informationen an den externen Syslog-Server gesendet werden sollen.

.Schritte
. Wählen Sie für den Schritt *syslog-Inhalt verwalten* des Assistenten jeden Typ von Audit-Informationen aus, die Sie an den externen syslog-Server senden möchten.
+
** *Audit-Protokolle senden*: Sendet StorageGRID-Ereignisse und Systemaktivitäten
** *Sicherheitsereignisse senden*: Sendet Sicherheitsereignisse, z. B. wenn ein nicht autorisierter Benutzer versucht sich anzumelden oder sich ein Benutzer als root anmeldet
** *Senden von Anwendungsprotokollen*: Sendet link:../monitor/storagegrid-software-logs.html["Protokolldateien der StorageGRID Software"] nützliche Informationen für die Fehlersuche, einschließlich:
+
*** `bycast-err.log`
*** `bycast.log`
*** `jaeger.log`
*** `nms.log` (Nur Admin-Nodes)
*** `prometheus.log`
*** `raft.log`
*** `hagroups.log`


** *Zugriffsprotokolle senden*: Sendet HTTP-Zugriffsprotokolle für externe Anfragen an Grid Manager, Tenant Manager, konfigurierte Load Balancer-Endpunkte und Grid Federation-Anfragen von Remote-Systemen.


. Verwenden Sie die Dropdown-Menüs, um den Schweregrad und die Einrichtung (Meldungstyp) für jede zu sendende Kategorie von Audit-Informationen auszuwählen.
+
Durch das Festlegen von Schweregraden und Einrichtungswerten können Sie die Protokolle auf anpassbare Weise für eine einfachere Analyse zusammenfassen.

+
.. Wählen Sie für *Severity* *Passthrough* aus, oder wählen Sie einen Schweregrad zwischen 0 und 7 aus.
+
Wenn Sie einen Wert auswählen, wendet StorageGRID den ausgewählten Wert auf alle Nachrichten dieses Typs an. Details zu verschiedenen Schweregraden gehen verloren, wenn der Schweregrad durch einen festen Wert überschrieben wird.

+
[cols="1a,3a"]
|===
| Schweregrad | Beschreibung 


 a| 
Passthrough
 a| 
Jede an das externe Syslog gesendete Nachricht hat denselben Schweregrad wie bei der lokalen Anmeldung am Knoten:

*** Für Prüfprotokolle lautet der Schweregrad „Info“.
*** Bei Sicherheitsereignissen werden die Schweregrade von der Linux-Distribution auf den Knoten generiert.
*** Bei Anwendungsprotokollen variieren die Schweregrade zwischen „Info“ und „Hinweis“, je nachdem, was das Problem ist. Wenn beispielsweise ein NTP-Server hinzugefügt und eine HA-Gruppe konfiguriert wird, wird der Wert „Info“ angezeigt, während der SSM- oder RSM-Service absichtlich angehalten wird, wird der Wert „Hinweis“ angezeigt.
*** Für Zugriffsprotokolle lautet der Schweregrad „Info“.




 a| 
0
 a| 
Notfall: System ist unbrauchbar



 a| 
1
 a| 
Warnung: Maßnahmen müssen sofort ergriffen werden



 a| 
2
 a| 
Kritisch: Kritische Bedingungen



 a| 
3
 a| 
Fehler: Fehlerbedingungen



 a| 
4
 a| 
Warnung: Warnbedingungen



 a| 
5
 a| 
Hinweis: Normaler, aber bedeutender Zustand



 a| 
6
 a| 
Information: Informationsmeldungen



 a| 
7
 a| 
Debug: Debug-Level-Meldungen

|===
.. Wählen Sie für *Facilty* *Passthrough* aus, oder wählen Sie einen Wert zwischen 0 und 23 aus.
+
Wenn Sie einen Wert auswählen, wird dieser auf alle Nachrichten dieses Typs angewendet. Informationen zu verschiedenen Einrichtungen gehen verloren, wenn Sie die Einrichtung mit einem festen Wert überschreiben.

+
[cols="1a,3a"]
|===
| Anlage | Beschreibung 


 a| 
Passthrough
 a| 
Jede Nachricht, die an das externe Syslog gesendet wird, hat denselben Einrichtungswert wie bei der lokalen Anmeldung am Knoten:

*** Für Audit-Protokolle lautet die an den externen Syslog-Server gesendete Einrichtung „local7“.
*** Bei Sicherheitsereignissen werden die Einrichtungswerte von der linux-Distribution auf den Knoten generiert.
*** Für Anwendungsprotokolle weisen die an den externen Syslog-Server gesendeten Anwendungsprotokolle die folgenden Einrichtungswerte auf:
+
**** `bycast.log`: Benutzer oder Daemon
**** `bycast-err.log`: Benutzer, Daemon, local3 oder local4
**** `jaeger.log`: Local2
**** `nms.log`: Local3
**** `prometheus.log`: Local4
**** `raft.log`: Local5
**** `hagroups.log`: Local6


*** Für Zugriffsprotokolle lautet die an den externen Syslog-Server gesendete Einrichtung „local0“.




 a| 
0
 a| 
kern (Kernelmeldungen)



 a| 
1
 a| 
Benutzer (Meldungen auf Benutzerebene)



 a| 
2
 a| 
E-Mail



 a| 
3
 a| 
Daemon (Systemdemonen)



 a| 
4
 a| 
Auth (Sicherheits-/Autorisierungsmeldungen)



 a| 
5
 a| 
Syslog (intern erzeugte Nachrichten durch syslogd)



 a| 
6
 a| 
lpr (Liniendrucker-Subsystem)



 a| 
7
 a| 
nachrichten (Netzwerk-News-Subsystem)



 a| 
8
 a| 
UUCP



 a| 
9
 a| 
Cron (Clock Daemon)



 a| 
10
 a| 
Sicherheit (Sicherheits-/Autorisierungsmeldungen)



 a| 
11
 a| 
FTP



 a| 
12
 a| 
NTP



 a| 
13
 a| 
Logaudit (Protokollaudit)



 a| 
14
 a| 
Logalert (Protokollwarnung)



 a| 
15
 a| 
Uhr (Uhrzeitdaemon)



 a| 
16
 a| 
Local0



 a| 
17
 a| 
local1



 a| 
18
 a| 
local2



 a| 
19
 a| 
local3



 a| 
20
 a| 
local4



 a| 
21
 a| 
local5



 a| 
22
 a| 
local6



 a| 
23
 a| 
local7

|===


. Wählen Sie *Weiter*.




==== Versenden von Testmeldungen

Bevor ein externer Syslog-Server verwendet wird, sollte veranlasst werden, dass alle Knoten im Grid Testnachrichten an den externen Syslog-Server senden. Diese Testnachrichten unterstützen die Validierung der gesamten Protokollerfassungsinfrastruktur, bevor die Übertragung von Daten an den externen Syslog-Server festgelegt wird.


CAUTION: Verwenden Sie die Konfiguration des externen Syslog-Servers erst, wenn Sie bestätigen, dass der externe Syslog-Server von jedem Knoten in Ihrem Raster eine Testmeldung erhalten hat und dass die Nachricht erwartungsgemäß verarbeitet wurde.

.Schritte
. Wenn Sie keine Testnachrichten senden möchten, weil Sie sicher sind, dass Ihr externer Syslog-Server korrekt konfiguriert ist und Audit-Informationen von allen Knoten in Ihrem Raster empfangen kann, wählen Sie *Überspringen und Beenden*.
+
Ein grünes Banner zeigt an, dass die Konfiguration gespeichert wurde.

. Andernfalls wählen Sie *Testmeldungen senden* (empfohlen).
+
Die Testergebnisse werden kontinuierlich auf der Seite angezeigt, bis Sie den Test beenden. Während der Test läuft, werden Ihre Audit-Meldungen weiterhin an Ihre zuvor konfigurierten Ziele gesendet.

. Wenn Sie während der Syslog-Serverkonfiguration oder zur Laufzeit Fehler erhalten, korrigieren Sie diese und wählen Sie erneut *Testnachrichten senden*.
+
Weitere  Informationen finden Sie unter, link:../troubleshoot/troubleshooting-syslog-server.html["Fehlerbehebung für einen externen Syslog-Server"] um Sie bei der Behebung von Fehlern zu unterstützen.

. Warten Sie, bis ein grünes Banner angezeigt wird, dass alle Nodes die Tests bestanden haben.
. Überprüfen Sie den Syslog-Server, ob Testmeldungen empfangen und verarbeitet werden wie erwartet.
+

NOTE: Wenn Sie UDP verwenden, überprüfen Sie Ihre gesamte Infrastruktur zur Protokollsammlung.  Das UDP-Protokoll ermöglicht keine so strenge Fehlererkennung wie die anderen Protokolle.

. Wählen Sie *Stop and Finish*.
+
Sie gelangen zurück zur Seite *Audit und Syslog Server*. Ein grünes Banner zeigt an, dass die Syslog-Server-Konfiguration gespeichert wurde.

+

NOTE: StorageGRID Auditinformationen werden erst an den externen Syslog-Server gesendet, wenn Sie ein Ziel auswählen, das den externen Syslog-Server enthält.





[[select-log-location]]
=== Protokollspeicherort auswählen

Sie können angeben, wo Überwachungsprotokolle, Sicherheitsereignisprotokolle,link:../monitor/storagegrid-software-logs.html["StorageGRID -Anwendungsprotokolle"] , und Zugriffsprotokolle werden gesendet.

[NOTE]
====
StorageGRID verwendet standardmäßig lokale Überwachungsziele für Knoten und speichert die Audit-Informationen in `/var/local/log/localaudit.log`.

Bei Verwendung von `/var/local/log/localaudit.log` werden die Audit-Protokolleinträge für Grid Manager und Tenant Manager möglicherweise an einen Storage Node gesendet. Mit dem Befehl finden Sie den Node mit den neuesten Einträgen `run-each-node --parallel "zgrep MGAU /var/local/log/localaudit.log | tail"`.

Einige Ziele sind nur verfügbar, wenn Sie einen externen Syslog-Server konfiguriert haben.

====
.Schritte
. Wählen Sie *Protokollspeicherort* > *Lokaler Knoten und externer Server*.
. Um den Protokollspeicherort für die Protokolltypen zu ändern, wählen Sie eine andere Option.
+

TIP: *Nur lokale Knoten* und *externer Syslog-Server* bieten normalerweise eine bessere Leistung.

+
[cols="1a,2a"]
|===
| Option | Beschreibung 


 a| 
Nur lokale Knoten (Standard)
 a| 
Prüfmeldungen, Sicherheitsereignisprotokolle und Anwendungsprotokolle werden nicht an Admin-Knoten gesendet.  Stattdessen werden sie nur auf den Knoten gespeichert, die sie generiert haben („der lokale Knoten“).  Die auf jedem lokalen Knoten generierten Prüfinformationen werden gespeichert in `/var/local/log/localaudit.log` .

*Hinweis*: StorageGRID entfernt regelmäßig lokale Protokolle in einer Rotation, um Speicherplatz freizugeben.  Wenn die Protokolldatei für einen Knoten 1 GB erreicht, wird die vorhandene Datei gespeichert und eine neue Protokolldatei gestartet.  Die Rotationsgrenze für das Protokoll liegt bei 21 Dateien.  Wenn die 22. Version der Protokolldatei erstellt wird, wird die älteste Protokolldatei gelöscht.  Durchschnittlich werden auf jedem Knoten etwa 20 GB Protokolldaten gespeichert.  Um Protokolle über einen längeren Zeitraum zu speichern,<<use-bucket,Verwenden Sie einen Mandanten und einen Bucket zur Protokollspeicherung>> .



 a| 
Admin-Nodes/lokale Nodes
 a| 
Audit-Meldungen werden an das Überwachungsprotokoll auf Admin-Nodes gesendet, Sicherheitsereignisprotokolle und Anwendungsprotokolle werden auf den Knoten gespeichert, die sie generiert haben. Die Audit-Informationen werden in folgenden Dateien gespeichert:

** Admin-Knoten (primär und nicht primär): `/var/local/audit/export/audit.log`
** Alle Knoten: Die `/var/local/log/localaudit.log` Datei ist normalerweise leer oder fehlt. Sie kann sekundäre Informationen enthalten, z. B. eine zusätzliche Kopie einiger Nachrichten.




 a| 
Externer Syslog-Server
 a| 
Audit-Informationen werden an einen externen Syslog-Server gesendet und auf den lokalen Knoten gespeichert(`/var/local/log/localaudit.log` ).  Die Art der gesendeten Informationen hängt davon ab, wie Sie den externen Syslog-Server konfiguriert haben.  Diese Option wird erst aktiviert, nachdem Sie<<use-external-syslog-server,einen externen Syslog-Server konfiguriert>> .



 a| 
Admin-Knoten und externer Syslog-Server
 a| 
Audit-Meldungen werden an das Audit-Protokoll gesendet(`/var/local/audit/export/audit.log` ) auf Admin-Knoten, und Audit-Informationen werden an den externen Syslog-Server gesendet und auf dem lokalen Knoten gespeichert(`/var/local/log/localaudit.log` ).  Die Art der gesendeten Informationen hängt davon ab, wie Sie den externen Syslog-Server konfiguriert haben.  Diese Option wird erst aktiviert, nachdem Sie<<use-external-syslog-server,einen externen Syslog-Server konfiguriert>> .

|===
. Wählen Sie *Speichern*.
+
Es wird eine Warnmeldung angezeigt.

. Wählen Sie *OK*, um zu bestätigen, dass Sie das Ziel für die Audit-Informationen ändern möchten.
+
Neue Protokolle werden an die ausgewählten Ziele gesendet. Vorhandene Protokolle verbleiben an ihrem aktuellen Speicherort.





[[use-bucketuse-a-bucket]]
=== [[use-bucket]]Verwenden Sie einen Eimer

Die Protokolle werden regelmäßig rotiert.  Verwenden Sie einen S3-Bucket im selben Grid, um Protokolle über einen längeren Zeitraum zu speichern.

. Wählen Sie *Protokollspeicherort* > *Bucket verwenden*.
. Aktivieren Sie das Kontrollkästchen *Archivprotokolle aktivieren*.
. Wenn der aufgeführte Mandant und Bucket nicht die sind, die Sie verwenden möchten, wählen Sie *Mandanten und Bucket ändern* und dann entweder *Mandanten und Bucket erstellen* oder *Mandanten und Bucket auswählen*.
+
[role="tabbed-block"]
====
.Mandanten und Bucket erstellen
--
.. Geben Sie einen neuen Mandantennamen ein.
.. Geben Sie ein Kennwort für den neuen Mandanten ein und bestätigen Sie es.
.. Geben Sie einen neuen Bucket-Namen ein.
.. Wählen Sie *Erstellen und aktivieren*.


--
.Wählen Sie Mandant und Bucket aus
--
.. Wählen Sie aus dem Pulldown-Menü einen Mandantennamen aus.
.. Wählen Sie einen Bucket aus dem Pulldown-Menü aus.
.. Wählen Sie *Auswählen und aktivieren*.


--
====


. Wählen Sie *Speichern*.
+
Protokolle werden im von Ihnen angegebenen Mandanten und Bucket gespeichert.  Der Objektschlüsselname für die Protokolle hat dieses Format:

+
[listing]
----
system-logs/{node_hostname}/{absolute_path_to_log_file_on_node}--{last_modified_time}.gz
----
+
Beispiel:

+
[listing]
----
system-logs/DC1-SN1/var/local/log/localaudit.log--2025-05-12_13:41:44.gz
----




[[manage-log-retention]]
== Protokollaufbewahrung verwalten

Sie können steuern, wie lange StorageGRID Protokolle aufbewahrt, indem Sie eine ILM-Regel erstellen oder eine S3-Bucket-Lebenszyklusrichtlinie konfigurieren.

[role="tabbed-block"]
====
.ILM-Regel
--
Eine ILM-Regel für den Bucket erstellen und diese Regel zur aktiven ILM-Richtlinie hinzufügen.

.Schritte
. Wählen Sie *ILM* > *Regeln*.
. *Erstellen* auswählen. link:../ilm/create-ilm-rule-enter-details.html["Schritt 1 (Details eingeben)"]Der Assistent zum Erstellen einer ILM-Regel wird angezeigt:
+
.. Geben Sie einen eindeutigen Namen für die Regel ein. Zum Beispiel: ILM Regel für archivierte Protokolle.
.. Das S3-Mandantenkonto für die Protokollarchivierung auswählen.
.. Geben Sie den S3-Bucket für die Protokollarchivierung an.


. Weiter zu link:../ilm/create-ilm-rule-define-placements.html["Schritt 2 (Platzierungen definieren)"] und die Platzierung für die Regel für archivierte Protokolle definieren. Beispielsweise speichert die ILM-Regel im ersten Jahr eine replizierte Kopie an Standort 1 und eine replizierte Kopie an Standort 2. Nach einem Jahr wird eine 2+1-Löschcodierungskopie erstellt und nur an einem Standort gespeichert.
. Nach dem Erstellen der Regel wird sie einer aktiven ILM-Richtlinie hinzugefügt.


--
.S3 Bucket Lebenszyklus
--
Eine S3-Bucket-Lebenszyklusrichtlinie für den S3-Bucket zur Protokollarchivierung konfigurieren:

[listing]
----
{
      "Rules": [
        {
            "ID": "Retain logs forever",
            "Filter": {},
            "Status": "Enabled"，
            "Expiration": {}
        }
      ]
}
----
Wenn Sie eine S3-Bucket-Lifecycle-Richtlinie für den S3-Bucket zur Protokollarchivierung konfigurieren, überschreiben die Ablaufaktionen die ILM-Richtlinie für Objekte, die dem Bucket-Lifecycle-Filter entsprechen. Objekte, die dem Bucket-Lifecycle-Filter nicht entsprechen, verwenden die Aufbewahrungseinstellungen der ILM-Richtlinie. Wenn ein Objekt einem Bucket-Lifecycle-Filter entspricht und keine Ablaufaktionen explizit angegeben sind, werden die Aufbewahrungseinstellungen der ILM-Richtlinie nicht verwendet, und es gilt, dass Objektversionen unbegrenzt aufbewahrt werden.

--
====