---
permalink: monitor/managing-alerts.html 
sidebar: sidebar 
keywords: alert rules, managing alerts, alerts, alert notifications. edit alert rules 
summary: Das Warnsystem bietet eine benutzerfreundliche Oberfläche zum Erkennen, Bewerten und Beheben von Problemen, die während des StorageGRID-Betriebs auftreten können. 
---
= Verwalten von Meldungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Warnsystem bietet eine benutzerfreundliche Oberfläche zum Erkennen, Bewerten und Beheben von Problemen, die während des StorageGRID-Betriebs auftreten können.

Warnmeldungen werden auf bestimmten Schweregraden ausgelöst, wenn Alarmregelbedingungen als wahr bewertet werden. Wenn eine Meldung ausgelöst wird, treten die folgenden Aktionen auf:

* Im Grid Manager wird ein Symbol für den Schweregrad der Warnmeldung im Dashboard angezeigt, und die Anzahl der aktuellen Warnmeldungen wird erhöht.
* Die Warnung wird auf der Übersichtsseite *Knoten* und auf der Registerkarte *Knoten* > *_Knoten_* > *Übersicht* angezeigt.
* Es wird eine E-Mail-Benachrichtigung gesendet, vorausgesetzt, Sie haben einen SMTP-Server konfiguriert und E-Mail-Adressen für die Empfänger bereitgestellt.
* Es wird eine SNMP-Benachrichtigung (Simple Network Management Protocol) gesendet, vorausgesetzt, Sie haben den StorageGRID SNMP-Agent konfiguriert.


Sie können benutzerdefinierte Warnmeldungen erstellen, Warnmeldungen bearbeiten oder deaktivieren und Warnmeldungen verwalten.

Weitere Informationen:

* Sehen Sie sich die Videos an:
+
.Übersicht über Warnungen
video::2eea81c5-8323-417f-b0a0-b1ff008506c1[panopto]
+
.Benutzerdefinierte Benachrichtigungen
video::54af90c4-9a38-4136-9621-b1ff008604a3[panopto]
* Weitere Informationen finden Sie imlink:alerts-reference.html["Alerts Referenz"] .

