---
permalink: monitor/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, triggering autosupport, manually triggering autosupport, autosupport triggers 
summary: Um den technischen Support bei der Fehlerbehebung in Ihrem StorageGRID System zu unterstützen, können Sie manuell ein AutoSupport Paket senden. 
---
= Starten Sie manuell ein AutoSupport-Paket
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um den technischen Support bei der Fehlerbehebung in Ihrem StorageGRID System zu unterstützen, können Sie manuell ein AutoSupport Paket senden.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die Berechtigung Root-Zugriff oder andere Grid-Konfigurationen.


.Schritte
. Wählen Sie *SUPPORT* > *Werkzeuge* > *AutoSupport*.
. Wählen Sie auf der Registerkarte *Aktionen* *vom Benutzer ausgelöste AutoSupport* senden.
+
StorageGRID versucht, ein AutoSupport-Paket an die NetApp-Support-Website zu senden. Wenn der Versuch erfolgreich ist, werden die *aktuellsten Ergebnisse* und *Letzte erfolgreiche Zeit* Werte auf der Registerkarte *Ergebnisse* aktualisiert. Wenn es ein Problem gibt, wird der Wert *Letzte Ergebnisse* auf „fehlgeschlagen“ aktualisiert, und StorageGRID versucht nicht, das AutoSupport-Paket erneut zu senden.

. Aktualisieren Sie nach 1 Minute die Seite „AutoSupport“ in Ihrem Browser, um die aktuellsten Ergebnisse anzuzeigen.



TIP: Darüber hinaus können link:../monitor/collecting-log-files-and-system-data.html["Sammeln Sie umfangreichere Protokolldateien und Systemdaten"] Sie sie an die NetApp Support-Website senden.
