---
permalink: monitor/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: how to review audit messages, how to view audit messages 
summary: Audit-Meldungen helfen Ihnen, die detaillierten Vorgänge Ihres StorageGRID Systems besser zu verstehen. Sie können mithilfe von Audit-Protokollen Probleme beheben und die Performance bewerten. 
---
= Audit-Meldungen prüfen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Audit-Meldungen helfen Ihnen, die detaillierten Vorgänge Ihres StorageGRID Systems besser zu verstehen. Sie können mithilfe von Audit-Protokollen Probleme beheben und die Performance bewerten.

Während des normalen Systembetriebs generieren alle StorageGRID Services wie folgt Audit-Meldungen:

* Systemaudits-Meldungen betreffen das Auditing des Systems selbst, den Status von Grid-Nodes, systemweite Task-Aktivitäten und Service-Backup-Vorgänge.
* Audit-Nachrichten zum Objekt-Storage beziehen sich auf die Storage- und das Management von Objekten in StorageGRID, einschließlich Objekt-Storage und -Abruf, Grid-Node- zu Grid-Node-Transfers und Verifizierungen.
* Audit-Meldungen zu Lese- und Schreibzugriffen von Clients werden protokolliert, wenn eine S3-Client-Applikation zum Erstellen, Ändern oder Abrufen eines Objekts fordert.
* Managementaudits protokollieren Benutzeranfragen an die Management-API.


Jeder Admin-Knoten speichert Audit-Meldungen in Textdateien. Die Revisionsfreigabe enthält die aktive Datei (Audit.log) sowie komprimierte Audit-Protokolle aus früheren Tagen. Jeder Node im Raster speichert auch eine Kopie der auf dem Node generierten Audit-Informationen.

Sie können über die Befehlszeile des Admin-Knotens direkt auf Audit-Log-Dateien zugreifen.

StorageGRID kann standardmäßig Audit-Informationen senden oder das Ziel ändern:

* StorageGRID ist standardmäßig auf lokale Node-Überwachungsziele eingestellt.
* Die Audit-Protokolleinträge von Grid Manager und Tenant Manager können an einen Storage Node gesendet werden.
* Optional können Sie das Ziel der Audit-Protokolle ändern und Audit-Informationen an einen externen Syslog-Server senden. Lokale Protokolle von Audit-Datensätzen werden weiterhin generiert und gespeichert, wenn ein externer Syslog-Server konfiguriert ist.
* link:../monitor/configure-log-management.html["Informationen zum Konfigurieren der Protokollverwaltung"] .


Details zur Audit-Log-Datei, zum Format der Audit-Meldungen, zu den Typen der Audit-Meldungen und zu den verfügbaren Tools zur Analyse von Audit-Meldungen finden Sie unter link:../audit/index.html["Prüfung von Audit-Protokollen"].
