---
permalink: maintain/all-node-types-replacing-linux-node.html 
sidebar: sidebar 
keywords: replace linux node 
summary: Wenn ein Fehler erfordert, dass Sie einen oder mehrere neue physische oder virtuelle Hosts bereitstellen oder Linux auf einem vorhandenen Host neu installieren, stellen Sie den Ersatz-Host bereit und konfigurieren Sie ihn, bevor Sie den Grid-Node wiederherstellen können. Dieses Verfahren ist ein Schritt der Wiederherstellung des Grid-Nodes für alle Arten von Grid-Nodes. 
---
= Ersetzen Sie einen Linux-Knoten in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Fehler erfordert, dass Sie einen oder mehrere neue physische oder virtuelle Hosts bereitstellen oder Linux auf einem vorhandenen Host neu installieren, stellen Sie den Ersatz-Host bereit und konfigurieren Sie ihn, bevor Sie den Grid-Node wiederherstellen können. Dieses Verfahren ist ein Schritt der Wiederherstellung des Grid-Nodes für alle Arten von Grid-Nodes.

„Linux“ bezieht sich auf eine Bereitstellung von Red Hat® Enterprise Linux® (RHEL), Ubuntu® oder Debian®.  Eine Liste der unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool (IMT)"^] .

Dieses Verfahren wird nur als ein Schritt bei der Wiederherstellung von softwarebasierten Storage-Nodes, primären oder nicht primären Admin-Nodes oder Gateway-Nodes durchgeführt. Die Schritte sind unabhängig vom Typ des wiederherenden Grid-Node identisch.

Wenn mehr als ein Grid-Knoten auf einem physischen oder virtuellen Linux-Host gehostet wird, ist die Wiederherstellung der Grid-Knoten in beliebiger Reihenfolge möglich. Ist jedoch der primäre Admin Node vorhanden, muss dieser zuerst wiederhergestellt werden, um zu verhindern, dass die Wiederherstellung anderer Grid-Knoten ins Stocken gerät, wenn diese versuchen, den primären Admin Node zu kontaktieren. Falls der primäre Admin Node nicht zuerst wiederhergestellt werden kann und ein nicht-primärer Admin Node verfügbar ist, kann ein nicht-primärer Admin Node verwendet werden, um die Knoten in beliebiger Reihenfolge wiederherzustellen.
