---
permalink: maintain/assess-hotfix-requirement-during-primary-admin-node-recovery-using-npan.html 
sidebar: sidebar 
keywords: storagegrid, hotfix, primary admin node recovery 
summary: Feststellen, ob ein Hotfix erforderlich ist, wenn ein primärer Admin-Knoten mithilfe eines nicht-primären Admin-Knotens wiederhergestellt wird. 
---
= StorageGRID Hotfix-Anforderung für den primären Admin-Node ermitteln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Wiederherstellung eines primären Admin-Knotens sollte festgestellt werden, ob ein Hotfix angewendet werden muss.

.Bevor Sie beginnen
Die Wiederherstellung des primären Admin Node ist abgeschlossen.

.Schritte
. Melden Sie sich mit einem beim Grid-Manager anlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
. Wählen Sie *Knoten* aus.
. Wählen Sie in der Liste links den primären Admin-Node aus.
. Notieren Sie sich auf der Registerkarte Übersicht die Version, die im Feld *Softwareversion* angezeigt wird.
. Wählen Sie einen beliebigen anderen Grid-Knoten aus.
. Auf der Registerkarte „Übersicht“ sind die im Feld *Softwareversion* angezeigten Versionen zu beachten.
+
** Wenn die in den Feldern *Software Version* angezeigten Versionen identisch sind, müssen Sie keinen Hotfix anwenden.
** Wenn die in den Feldern *Softwareversion* angezeigten Versionen unterschiedlich sind, müssen Sie link:storagegrid-hotfix-procedure.html["Installieren Sie einen Hotfix"]den wiederhergestellten primären Admin-Knoten auf dieselbe Version aktualisieren.



