---
permalink: maintain/checking-storage-state-after-recovering-storage-volumes.html 
sidebar: sidebar 
keywords: storagegrid, storage volume recovery, storage state, storage volume 
summary: Nach der Wiederherstellung von Speichervolumes müssen Sie überprüfen, ob der gewünschte Status des Speicherknoten auf „Online“ gesetzt ist, und sicherstellen, dass der Status beim Neustart des Speicherknotenservers standardmäßig online ist. 
---
= Überprüfen Sie den Speicherstatus nach der Wiederherstellung von Storage Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Wiederherstellung von Speichervolumes müssen Sie überprüfen, ob der gewünschte Status des Speicherknoten auf „Online“ gesetzt ist, und sicherstellen, dass der Status beim Neustart des Speicherknotenservers standardmäßig online ist.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Der Speicherknoten wurde wiederhergestellt und die Datenwiederherstellung ist abgeschlossen.


.Schritte
. Wählen Sie *Knoten* > *_Speicherknoten_* > *Aufgaben*.
. Wenn die Dropdown-Liste *Speicherstatus* auf „Schreibgeschützt“ oder „Offline“ eingestellt ist, wählen Sie „Online“ aus.
. Wählen Sie *Speichern*.

