---
permalink: maintain/checking-storage-state-after-recovering-storage-node-system-drive.html 
sidebar: sidebar 
keywords: storagegrid, storage node recovery, system drive, storage state 
summary: Nach der Wiederherstellung des Systemlaufwerks für einen Speicherknoten müssen Sie überprüfen, ob der gewünschte Status des Speicherknoten auf Online gesetzt ist, und vergewissern Sie sich, dass der Status beim Neustart des Speicherknotenservers standardmäßig online ist. 
---
= Überprüfen Sie den Speicherstatus nach der Wiederherstellung des Speicherknoten-Systemlaufwerks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Wiederherstellung des Systemlaufwerks für einen Speicherknoten müssen Sie überprüfen, ob der gewünschte Status des Speicherknoten auf Online gesetzt ist, und vergewissern Sie sich, dass der Status beim Neustart des Speicherknotenservers standardmäßig online ist.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Der Speicherknoten wurde wiederhergestellt und die Datenwiederherstellung ist abgeschlossen.


.Schritte
. Wählen Sie *NODES* > *_Storage Node_* > *Tasks* aus.
. Wenn die Dropdown-Liste *Speicherstatus* auf Schreibgeschützt oder Offline eingestellt ist, wählen Sie *Online* aus.
. Wählen Sie *Speichern*.

