---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: Bevor Sie einen Grid-Node außer Betrieb nehmen, müssen Sie bestätigen, dass keine Datenreparatur-Jobs aktiv sind. Wenn Reparaturen fehlgeschlagen sind, müssen Sie sie neu starten und vor der Außerbetriebnahme abschließen lassen. 
---
= Überprüfen Sie Datenreparaturjobs in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie einen Grid-Knoten außer Betrieb nehmen oder erweitern, müssen Sie bestätigen, dass keine Datenreparaturjobs aktiv sind.  Wenn Reparaturen fehlgeschlagen sind, müssen Sie diese neu starten und abschließen lassen, bevor Sie die Außerbetriebnahme durchführen.

* Siehelink:../expand/index.html["Erweiterungsarten"] für Details zum Erweitern eines Rasterknotens.
* Mit dem Grid Manager können laufende Wiederherstellungsprozesse überwacht und eine Wiederherstellungshistorie angezeigt werden. Dazu stehen folgende Verfahren zur Verfügung:
+
** link:../maintain/restoring-object-data-to-storage-volume-for-appliance.html["Wiederherstellung von Objektdaten auf Storage Volumes für die Appliance"]
** link:../maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Wiederherstellung von Objektdaten auf dem Storage Volume, auf dem das Systemlaufwerk intakt ist"]
** link:../maintain/restoring-object-data-to-storage-volume.html["Wiederherstellung von Objektdaten auf einem Storage-Volume (Systemausfall)"]



