---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: Nach der Wiederherstellung eines Appliance Storage Node müssen Sie überprüfen, ob der gewünschte Status des Appliance Storage Node auf „Online“ gesetzt ist, und vergewissern Sie sich, dass der Status bei jedem Neustart des Storage Node-Servers standardmäßig online ist. 
---
= Überprüfen Sie den Speicherstatus nach der Wiederherstellung des Appliance-Speicherknoten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Wiederherstellung eines Appliance Storage Node müssen Sie überprüfen, ob der gewünschte Status des Appliance Storage Node auf „Online“ gesetzt ist, und vergewissern Sie sich, dass der Status bei jedem Neustart des Storage Node-Servers standardmäßig online ist.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Der Speicherknoten wurde wiederhergestellt und die Datenwiederherstellung ist abgeschlossen.


.Schritte
. Wählen Sie *NODES* > *_Storage Node_* > *Tasks* aus.
. Wenn die Dropdown-Liste *Speicherstatus* auf Schreibgeschützt oder Offline eingestellt ist, wählen Sie *Online* aus.
. Wählen Sie *Speichern*.

