---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: Um die Leistung zu steigern, können Sie langsamere Storage Nodes ohne ADC in reine Storage-Nodes umwandeln. 
---
= Umwandeln eines Storage-Node in einen rein datenbasierten Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Leistung zu steigern, können Sie langsamere Storage Nodes ohne ADC in reine Storage-Nodes umwandeln.

Ein Storage-Node ausschließlich für Daten ist sinnvoll, wenn Ihre Storage-Nodes unterschiedliche Performance-Merkmale aufweisen. Um beispielsweise die Performance potenziell zu steigern, können Sie reine Daten-Storage-Nodes mit einer hohen Kapazität und gleichzeitig hochperformante Storage-Nodes mit Metadaten verwenden.

Darüber hinaus können Sie mehr Metadaten-Kapazität erhalten, indem Sie Cassandra Nodes mit niedrigem RAM entfernen, wodurch sich die maximal zulässige Metadatenkapazität pro Node erhöht. Siehe link:../admin/managing-object-metadata-storage.html["Management von Objekt-Metadaten-Storage"].

Bei der Installation von reinen Datenknoten muss das Grid Folgendes enthalten:

* Mindestens zwei kombinierte oder rein datengeschützte Storage-Nodes pro Grid
* Mindestens ein kombinierter oder nur-Daten-Storage-Node pro Standort
* Mindestens drei kombinierte oder nur Metadaten-Storage-Nodes pro Standort


.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Der zu konvertierende Speicher-Node enthält weder den ADC-Dienst noch link:../maintain/move-adc-service.html["ADC-Dienst verschoben"]einen anderen Knoten.
* Der Storage-Node ist kein metadatenbasierter Node oder ein rein datenbasierter Node.
* Auf anderen Knoten am Standort ist genügend Metadatenspeicher vorhanden, um die Metadaten aufzunehmen, die vom zu konvertierenden Speicher-Node migriert werden.


.Über diese Aufgabe
Verwenden Sie dieses Verfahren, um einen oder mehrere kombinierte oder nur-Metadaten-Speicher-Nodes, die den ADC-Dienst nicht enthalten, in reine Datenknoten zu konvertieren. Die Storage-Nodes müssen sich am selben Standort befinden.

Zusätzlich zum Konvertieren des Storage-Knotens wird Cassandra vom Knoten dekomprimiert. Alle Metadaten werden zu kombinierten oder nur Metadaten-Storage-Nodes migriert. Je nach Menge der zu migrierenden Metadaten kann dieses Verfahren bis zu mehrere Tage pro Node dauern.


TIP: Im Allgemeinen können Sie bis zu 10 Nodes gleichzeitig konvertieren, wenn die Metadatennutzung pro Node weniger als 1 TB beträgt. Wenn die Metadatennutzung pro Knoten mehr als 1 TB beträgt, konvertieren Sie stattdessen bis zu 5 Knoten pro Prozedur.

.Schritte
. Notieren Sie die Knoten-IDs der nicht-ADC-Speicherknoten, die Sie konvertieren möchten.
. Wählen Sie oben im Grid Manager das Hilfesymbol aus und wählen Sie *API-Dokumentation*.
. Wählen Sie *Gehe zu privater API-Dokumentation*.
. Wählen Sie den `POST /private/convert-to-data-only-node/start` Vorgang aus. Weitere Informationen finden Sie unter link:../admin/using-grid-management-api.html#issue-api-requests["API-Anforderungen ausgeben"] .
+
Während des Verfahrens wird jeder Node neu gebootet.

. Mit können Sie `GET /private/convert-to-data-only-node` den Vorgang überwachen. Wenn Fehler auftreten, wählen Sie, `POST /private/convert-to-data-only-node/retry` um den Vorgang erneut zu versuchen.
. link:../maintain/downloading-recovery-package.html["Laden Sie ein Wiederherstellungspaket herunter"] Nach Abschluss dieses Verfahrens.

