---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: Mit der Wiederherstellungspaketdatei können Sie das StorageGRID-System bei einem Ausfall wiederherstellen. 
---
= Wiederherstellungspaket herunterladen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Wiederherstellungspaketdatei können Sie das StorageGRID-System bei einem Ausfall wiederherstellen.

.Bevor Sie beginnen
* Vom primären Admin-Knoten aus werden Sie mit einem beim Grid-Manager angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die Provisionierungs-Passphrase.
* Sie haben link:../admin/admin-group-permissions.html["Bestimmte Zugriffsberechtigungen"].


Laden Sie die aktuelle Wiederherstellungspaket-Datei herunter, bevor Sie Änderungen an der Grid-Topologie am StorageGRID-System vornehmen oder bevor Sie die Software aktualisieren. Laden Sie anschließend eine neue Kopie des Wiederherstellungspakets herunter, nachdem Sie Änderungen an der Grid-Topologie vorgenommen oder die Software aktualisiert haben.

.Schritte
. Wählen Sie *WARTUNG* > *System* > *Wiederherstellungspaket*.
. Geben Sie die Provisionierungs-Passphrase ein, und wählen Sie *Download starten*.
+
Der Download startet sofort.

. Öffnen Sie nach Abschluss des Downloads die `.zip` Datei, und bestätigen Sie, dass Sie auf den Inhalt einschließlich der Datei zugreifen können `Passwords.txt`.
. Kopieren Sie die heruntergeladene Wiederherstellungspaket-Datei (`.zip`) in zwei sichere und separate Speicherorte.
+

CAUTION: Die Wiederherstellungspaket-Datei muss gesichert werden, da sie Verschlüsselungsschlüssel und Passwörter enthält, die verwendet werden können, um Daten vom StorageGRID-System zu erhalten.


