---
permalink: maintain/gathering-required-materials-site-decom.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: Bevor Sie eine Website ausmustern, sind die folgenden Unterlagen erforderlich. 
---
= Sammeln Sie die erforderlichen Materialien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine Website ausmustern, sind die folgenden Unterlagen erforderlich.

[cols="1a,2a"]
|===
| Element | Hinweise 


 a| 
Recovery-Paketdatei `.zip`
 a| 
Sie müssen die neueste Recovery-Paket-Datei herunterladen `.zip`(`sgws-recovery-package-id-revision.zip` ). Sie können die Wiederherstellungspaket-Datei verwenden, um das System bei einem Fehler wiederherzustellen.

link:downloading-recovery-package.html["Laden Sie das Wiederherstellungspaket herunter"]



 a| 
`Passwords.txt` Datei
 a| 
Diese Datei enthält die Passwörter, die für den Zugriff auf Grid-Nodes auf der Befehlszeile erforderlich sind und ist im Wiederherstellungspaket enthalten.



 a| 
Provisioning-Passphrase
 a| 
Die Passphrase wird erstellt und dokumentiert, wenn das StorageGRID-System zum ersten Mal installiert wird. Die Provisionierungs-Passphrase ist nicht in der `Passwords.txt` Datei enthalten.



 a| 
Beschreibung der Topologie des StorageGRID Systems vor der Stilllegung
 a| 
Falls verfügbar, finden Sie eine Dokumentation, die die aktuelle Topologie des Systems beschreibt.

|===
.Verwandte Informationen
link:../admin/web-browser-requirements.html["Anforderungen an einen Webbrowser"]
