---
permalink: maintain/grid-node-procedures.html 
sidebar: sidebar 
keywords: storagegrid, grid node procedure 
summary: Möglicherweise müssen Sie Wartungsverfahren für bestimmte Grid-Nodes oder Node-Services durchführen. 
---
= Node-Wartungsverfahren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie Wartungsverfahren für bestimmte Grid-Nodes oder Node-Services durchführen.

ADC verschieben:: Derlink:../maintain/understanding-adc-service-quorum.html["ADC-Dienst"] befindet sich auf einigen Speicherknoten.  Unter bestimmten Umständen der Außerbetriebnahme und Knotenkonvertierung müssen Sie den ADC-Dienst auf einen anderen Speicherknoten am selben Standort verschieben.
Konvertieren Sie den Speicherknoten in einen Nur-Datenknoten:: Sie können Speicherknoten, die den ADC-Dienst nicht enthalten, in reine Datenspeicherknoten umwandeln.
Knoten neu starten, herunterfahren und einschalten:: Mit diesen Verfahren starten Sie einen oder mehrere Knoten neu, fahren die Knoten herunter und starten sie neu oder schalten die Knoten aus und wieder ein.
Port-Neuzuordnung:: Sie können die Portzuordnungsverfahren verwenden, um die Portzuordnungen von einem Node zu entfernen, z. B. wenn Sie einen Load Balancer-Endpunkt mit einem zuvor neu zugeordneten Port konfigurieren möchten.
Server-Manager:: Server Manager wird auf jedem Grid-Knoten ausgeführt, um das Starten und Beenden von Diensten zu überwachen und sicherzustellen, dass Dienste problemlos dem StorageGRID-System beitreten und das System verlassen. Server Manager überwacht auch die Dienste auf jedem Grid-Knoten und versucht automatisch, alle Services, die Fehler melden, neu zu starten.
+
--
Um Server Manager-Verfahren auszuführen, müssen Sie normalerweise auf die Befehlszeile des Knotens zugreifen.


CAUTION: Sie sollten auf Server Manager zugreifen, wenn Sie von technischem Support dazu aufgefordert wurden.

--

