---
permalink: maintain/modifying-dns-configuration-for-single-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, dns, modify dns 
summary: Anstatt den DNS global für die gesamte Bereitstellung zu konfigurieren, können Sie ein Skript ausführen, um DNS für jeden Grid-Knoten anders zu konfigurieren. 
---
= Ändern der DNS-Konfiguration für einen einzelnen Grid-Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anstatt den DNS global für die gesamte Bereitstellung zu konfigurieren, können Sie ein Skript ausführen, um DNS für jeden Grid-Knoten anders zu konfigurieren.

Im Allgemeinen sollten Sie zum Konfigurieren von DNS-Servern die Option *Wartung* > *Netzwerk* > *DNS-Server* im Grid Manager verwenden.  Verwenden Sie das folgende Skript nur, wenn Sie für verschiedene Grid-Knoten unterschiedliche DNS-Server verwenden müssen.

.Schritte
. Der externe SSH-Zugriff ist standardmäßig blockiert.  Falls erforderlich,link:../admin/manage-external-ssh-access.html["Zugriff vorübergehend erlauben"] .
. Melden Sie sich beim primären Admin-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.

.. Fügen Sie den SSH-privaten Schlüssel zum SSH-Agenten hinzu. Eingabe: `ssh-add`
.. Geben Sie das in der Datei aufgeführte SSH-Zugriffspasswort ein `Passwords.txt`.


. [[log_in_to_Node]]Melden Sie sich an dem Knoten an, den Sie mit einer benutzerdefinierten DNS-Konfiguration aktualisieren möchten: `ssh _node_IP_address_`
. Führen Sie das DNS-Setup-Skript aus: `setup_resolv.rb.`
+
Das Skript antwortet mit der Liste der unterstützten Befehle.

+
[listing]
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [`add search <domain>|remove search <domain>|add nameserver <ip>`]
              [`remove nameserver <ip>|remove nameserver all|save|abort|help`]
----
. Fügen Sie die IPv4-Adresse eines Servers hinzu, der Domänennamendienst für Ihr Netzwerk bereitstellt: `add <nameserver IP_address>`
. Wiederholen Sie den `add nameserver` Befehl, um Namensserver hinzuzufügen.
. Befolgen Sie die Anweisungen, wenn Sie dazu aufgefordert werden, weitere Befehle einzugeben.
. Speichern Sie Ihre Änderungen und beenden Sie die Anwendung: `save`
. [[close_cmd_Shell]]Schließen Sie die Befehlsshell auf dem Server: `exit`
. Wiederholen Sie für jeden Rasterknoten die Schritte von <<log_in_to_node,Anmeldung beim Node>> bis <<close_cmd_shell,Schließen der Befehlsshell>>.
. Wenn Sie keinen passwortlosen Zugriff auf andere Server mehr benötigen, entfernen Sie den privaten Schlüssel vom SSH-Agent. Eingabe: `ssh-add -D`
. Wenn Sie externen SSH-Zugriff zugelassen haben,link:../admin/manage-external-ssh-access.html["Zugriff blockieren"] wenn Sie mit der Änderung der DNS-Konfiguration fertig sind.

