---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'Sie können den Status von Reparaturjobs mit dem Skript von der Befehlszeile aus überwachen `repair-data`.' 
---
= Überwachen Sie Jobs mit Reparaturdaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Status von Reparaturjobs mit dem Skript von der Befehlszeile aus überwachen `repair-data`.

Dazu gehören Jobs, die Sie manuell initiiert haben, oder Jobs, die StorageGRID automatisch im Rahmen einer Stilllegung initiiert hat.


NOTE: Wenn Sie stattdessen Volume-Wiederherstellungsjobs ausführenlink:../maintain/restoring-volume.html["Überwachen Sie den Fortschritt und zeigen Sie einen Verlauf dieser Jobs im Grid Manager an"].

Überwachen Sie den Status von `repair-data` Jobs, je nachdem, ob Sie *replizierte Daten*, *Erasure-coded(EC)-Daten* oder beides verwenden.

[role="tabbed-block"]
====
.Replizierte Daten
--
* Um einen geschätzten Fertigstellungsgrad für die replizierte Reparatur zu erhalten, fügen Sie die Option zum Befehl Repair-Data hinzu `show-replicated-repair-status`.
+
`repair-data show-replicated-repair-status`

* So stellen Sie fest, ob Reparaturen abgeschlossen sind:
+
.. Wählen Sie *NODES* > *_Storage Node wird repariert_* > *ILM*.
.. Prüfen Sie die Attribute im Abschnitt Bewertung. Wenn die Reparaturen abgeschlossen sind, weist das Attribut *wartet - Alle* 0 Objekte an.


* So überwachen Sie die Reparatur genauer:
+
.. Wählen Sie *KNOTEN*.
.. Wählen Sie *_Grid Name_* > *ILM* aus.
.. Setzen Sie den Mauszeiger über das ILM-Warteschlangendiagramm, um den Wert des Attributs *Scan Rate (Objects/sec)* anzuzeigen. Dies ist die Rate, mit der Objekte im Raster gescannt und für ILM in die Warteschlange eingereiht werden.
.. Sehen Sie sich im Abschnitt ILM-Warteschlange die folgenden Attribute an:
+
*** *Scan-Zeitraum - geschätzt*: Die geschätzte Zeit, um einen vollständigen ILM-Scan aller Objekte durchzuführen.
+
Ein vollständiger Scan kann nicht garantieren, dass ILM auf alle Objekte angewendet wurde.

*** *Reparaturversuche*: Die Gesamtzahl der Objektreparaturoperationen für replizierte Daten, die versucht wurden. Diese Zählung erhöht sich jedes Mal, wenn ein Storage-Node versucht, ein Objekt mit hohem Risiko zu reparieren. Risikobehaftete ILM-Reparaturen werden priorisiert, wenn das Grid besetzt wird.
+
Die Reparatur desselben Objekts erhöht sich möglicherweise erneut, wenn die Replikation nach der Reparatur fehlgeschlagen ist. + Diese Attribute können nützlich sein, wenn Sie den Fortschritt der Storage Node Volume Recovery überwachen. Wenn die Anzahl der versuchten Reparaturen nicht mehr steigt und ein vollständiger Scan abgeschlossen wurde, ist die Reparatur wahrscheinlich abgeschlossen.



.. Alternativ können Sie auch eine Prometheus-Abfrage für und `storagegrid_ilm_repairs_attempted` einreichen `storagegrid_ilm_scan_period_estimated_minutes`.




--
.EC-Daten (Erasure Coded)
--
So überwachen Sie die Reparatur von Daten mit Verfahren zur Einhaltung von Datenkonsistenz und versuchen Sie es erneut, eventuell fehlgeschlagene Anfragen zu senden:

. Status von Datenreparaturen mit Löschungscode ermitteln:
+
** Wählen Sie *SUPPORT* > *Tools* > *Metrics*, um die geschätzte Zeit bis zum Abschluss und den Fertigstellungsgrad für den aktuellen Job anzuzeigen. Wählen Sie dann im Abschnitt Grafana die Option *EC Übersicht* aus. Sehen Sie sich die Dashboards *Grid EC Job Estimated Time to Completion* und *Grid EC Job prozentual Completed* an.
** Mit diesem Befehl können Sie den Status einer bestimmten Operation anzeigen `repair-data`:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Verwenden Sie diesen Befehl, um alle Reparaturen aufzulisten:
+
`repair-data show-ec-repair-status`

+
Die Ausgabe listet Informationen auf, einschließlich `repair ID`, für alle zuvor ausgeführten und aktuell laufenden Reparaturen.



. Wenn die Ausgabe zeigt, dass der Reparaturvorgang fehlgeschlagen ist, verwenden Sie `--repair-id` die Option, um die Reparatur erneut zu versuchen.
+
Mit diesem Befehl wird eine fehlerhafte Node-Reparatur mithilfe der Reparatur-ID 6949309319275667690 erneut versucht:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Mit diesem Befehl wird eine fehlerhafte Volume-Reparatur mithilfe der Reparatur-ID 6949309319275667690 wiederholt:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====