---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Sie können den ADC-Dienst auf einen anderen Speicherknoten am selben Standort verschieben. 
---
= Verschieben Sie den ADC-Dienst in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den ADC-Dienst auf einen anderen Speicherknoten am selben Standort verschieben.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Du hastlink:../admin/admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"] .
* Der Quellknoten enthält den ADC-Dienst.
* Der Zielknoten enthält nicht den ADC-Dienst.
* Der Zielknoten ist entweder ein reiner Metadatenknoten oder ein kombinierter Knoten (Metadaten und Objektdaten).
* Der Quellknoten und der Zielknoten befinden sich am selben Standort.


.Über diese Aufgabe
Mit dem Verfahren „ADC verschieben“ lässt sich der ADC-Dienst manuell zwischen Storage Nodes verschieben. Zum Beispiel kann eine Umverteilung der ADC-Dienste auf verschiedene Nodes oder das Verschieben des ADC-Dienstes auf einen leistungsfähigeren Node erforderlich sein.

Bei diesem Verfahren werden die Dienste ADC, IDNT, ACCT und RSM von einem Speicherknoten zu einem anderen am selben Standort verschoben.  Die RSM-, IDNT- und ACCT-Dienste sind vom ADC-Dienst abhängig und werden daher automatisch verschoben, wenn der ADC-Dienst verschoben wird.

[NOTE]
====
* Sie müssen den ADC-Dienst vor link:../maintain/convert-to-data-only-node.html["Umwandlung eines Storage Node in einen reinen Datenknoten"] oder der Außerbetriebnahme eines Storage Node nicht manuell verschieben. Diese Verfahren verschieben den ADC-Dienst bei Bedarf automatisch. Weitere Informationen zu den Anforderungen finden sich unter link:../maintain/understanding-adc-service-quorum.html["Was ist das ADC Quorum?"].
* StorageGRID verschiebt den ADC-Dienst auf die neuesten Storage Nodes, die die Anforderungen für das Hosting des Dienstes erfüllen.


====
.Schritte
. Notieren Sie die Knoten-IDs der Quell- und Zielknoten.
+
In der Grid Management API wird die Quellknoten-ID bezeichnet als `sourceNodeId` .  Die Zielknoten-ID wird bezeichnet als `targetNodeId` .

. Wählen Sie oben im Grid Manager das Hilfesymbol aus und wählen Sie *API-Dokumentation*.
. Wählen Sie *Gehe zu privater API-Dokumentation*.
. Wählen Sie die `POST /private/move-adc/start` Betrieb. Weitere Informationen finden Sie unter link:../admin/using-grid-management-api.html#issue-api-requests["API-Anforderungen ausgeben"] für weitere Informationen.
+
Während des Vorgangs werden die beiden Knoten nacheinander neu gestartet.  Zuerst wird der Quellknoten neu gestartet, gefolgt vom Zielknoten.

. Sie können `GET /private/move-adc` um den Vorgang zu überwachen.  Wenn Fehler auftreten, wählen Sie `POST /private/move-adc/retry` um den Vorgang zu wiederholen.
. link:../maintain/downloading-recovery-package.html["Laden Sie ein Wiederherstellungspaket herunter"]nach Abschluss dieses Vorgangs.

