---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Sie können den ADC-Dienst auf einen anderen Storage Node am selben Standort verschieben. 
---
= Den ADC-Dienst verschieben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den ADC-Dienst auf einen anderen Storage Node am selben Standort verschieben.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben link:admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Der Quellknoten enthält den ADC-Dienst.
* Der Zielknoten enthält keinen ADC-Dienst.
* Der Ziel-Node ist entweder ein nur-Metadaten-Node oder ein kombinierter Node (Metadaten und Objektdaten).
* Der Quell- und Zielknoten befinden sich am selben Standort.


.Über diese Aufgabe
Verwenden Sie das Verfahren ADC verschieben, wenn Sie:

* Deaktivieren Sie einen Speicher-Node, der den ADC-Dienst enthält
* Konvertieren eines ADC-Knotens in einen reinen Datenknoten
* Fügen Sie einen Knoten hinzu, um ADC-bezogene Aufgaben auszuführen


Wenn Sie einen Speicher-Node oder dekomprimieren möchtenlink:../maintain/convert-to-data-only-node.html["Umwandeln eines Storage-Node in einen rein datenbasierten Node"], müssen Sie möglicherweise zuerst das Verfahren zum Verschieben von ADC verwenden. Sie müssen sicherstellen, dass die link:../maintain/understanding-adc-service-quorum.html["Das ADC-Quorum bleibt erhalten"].

Mit diesem Verfahren werden die ADC-, IDNT-, ACCT- und RSM-Dienste von einem Storage Node zu einem anderen am selben Standort verschoben. Die RSM- und ACCT-Dienste sind vom ADC-Dienst abhängig, sodass sie sich automatisch bewegen, wenn sich der ADC-Dienst bewegt.

.Schritte
. Notieren Sie die Knoten-IDs der Quell- und Zielknoten.
+
In der Grid-Management-API wird die Quell-Node-ID als bezeichnet `sourceNodeId`. Die ID des Zielknotens wird als bezeichnet `targetNodeId`.

. Wählen Sie oben im Grid Manager das Hilfesymbol aus und wählen Sie *API-Dokumentation*.
. Wählen Sie *Gehe zu privater API-Dokumentation*.
. Wählen Sie den `POST /private/move-adc/start` Vorgang aus. Weitere Informationen finden Sie unter link:../admin/using-grid-management-api.html#issue-api-requests["API-Anforderungen ausgeben"] .
+
Während des Verfahrens wird jeder Node neu gebootet.

. Mit können Sie `GET /private/move-adc` den Vorgang überwachen. Wenn Fehler auftreten, wählen Sie, `POST /private/move-adc/retry` um den Vorgang erneut zu versuchen.
. link:../maintain/downloading-recovery-package.html["Laden Sie ein Wiederherstellungspaket herunter"] Nach Abschluss dieses Verfahrens.

