---
permalink: maintain/powering-down-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: Bevor Sie einen Host herunterfahren, müssen Sie Dienste auf allen Grid-Nodes auf diesem Host anhalten. 
---
= Schalten Sie den Host aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie einen Host herunterfahren, müssen Sie Dienste auf allen Grid-Nodes auf diesem Host anhalten.

.Schritte
. Melden Sie sich beim Grid-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.


+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.

. Beenden Sie alle auf dem Knoten ausgeführten Dienste: `service servermanager stop`
+
Die Dienste können bis zu 15 Minuten zum Herunterfahren dauern. Außerdem können Sie sich möglicherweise per Remote-Zugriff beim System anmelden, um den Shutdown-Prozess zu überwachen.

. Wiederholen Sie die Schritte 1 und 2 für jeden Knoten auf dem Host.
. Wenn Sie einen Linux-Host haben:
+
.. Melden Sie sich beim Host-Betriebssystem an.
.. Stoppen Sie den Knoten: `storagegrid node stop`
.. Fahren Sie das Host-Betriebssystem herunter.


. Wenn der Node auf einer virtuellen VMware-Maschine ausgeführt wird oder es sich um einen Appliance-Node handelt, geben Sie den Befehl shutdown ein: `shutdown -h now`
+
Führen Sie diesen Schritt unabhängig vom Ergebnis des `service servermanager stop` Befehls aus.

+

NOTE: Nachdem Sie den Befehl an einem Appliance-Node ausgegeben `shutdown -h now` haben, müssen Sie die Appliance aus- und wieder einschalten, um den Node neu zu starten.

+
Bei diesem Befehl wird der Controller heruntergefahren, das Gerät ist jedoch weiterhin eingeschaltet. Sie müssen den nächsten Schritt abschließen.

. Wenn Sie einen Appliance-Node herunterfahren, befolgen Sie die Schritte für Ihre Appliance.
+
[role="tabbed-block"]
====
.SG6160
--
.. Schalten Sie den SG6100-CN-Speicher-Controller aus.
.. Warten Sie, bis die blaue LED-Betriebsanzeige am SG6100-CN-Speicher-Controller ausgeschaltet ist.


--
.SGF6112
--
.. Schalten Sie das Gerät aus.
.. Warten Sie, bis die blaue Betriebs-LED erlischt.


--
.SG6000
--
.. Warten Sie, bis die grüne LED Cache Active auf der Rückseite der Storage Controller ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

.. Schalten Sie das Gerät aus und warten Sie, bis die blaue Strom-LED ausgeschaltet ist.


--
.SG5800
--
.. Warten Sie, bis die grüne LED Cache Active auf der Rückseite des Storage Controllers ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

.. Wählen Sie auf der Startseite des SANtricity System Managers die Option *Vorgänge in Bearbeitung anzeigen*.
.. Bestätigen Sie, dass alle Vorgänge abgeschlossen wurden, bevor Sie mit dem nächsten Schritt fortfahren.
.. Schalten Sie beide Netzschalter am Controller Shelf aus und warten Sie, bis alle LEDs am Controller Shelf ausgeschaltet sind.


--
.SG5700
--
.. Warten Sie, bis die grüne LED Cache Active auf der Rückseite des Storage Controllers ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

.. Schalten Sie das Gerät aus und warten Sie, bis alle LED- und siebensegmentreichen Anzeigeaktivitäten angehalten sind.


--
.SG110 oder SG1100
--
.. Schalten Sie das Gerät aus.
.. Warten Sie, bis die blaue Betriebs-LED erlischt.


--
.SG100 oder SG1000
--
.. Schalten Sie das Gerät aus.
.. Warten Sie, bis die blaue Betriebs-LED erlischt.


--
====
. Melden Sie sich von der Befehls-Shell ab: `exit`


.Verwandte Informationen
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112 und SG6160 Storage Appliances"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["Storage Appliances der SG6000"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["Storage Appliances der SG5700"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["Storage Appliances der SG5800"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["Service Appliances für SG110 und SG1100"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100- und SG1000-Services-Appliances"^]

