---
permalink: maintain/recovering-from-admin-node-failures.html 
sidebar: sidebar 
keywords: recover, admin node failure, workflow 
summary: Der Wiederherstellungsprozess für einen Admin-Knoten hängt davon ab, ob es sich um den primären Admin-Knoten oder einen nicht-primären Admin-Knoten handelt. 
---
= Recovery des primären oder nicht primären Admin-Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Wiederherstellungsprozess für einen Admin-Knoten hängt davon ab, ob es sich um den primären Admin-Knoten oder einen nicht-primären Admin-Knoten handelt.

Die Schritte für die Wiederherstellung eines primären oder nicht primären Admin-Knotens auf hoher Ebene sind identisch, wobei sich die Details der einzelnen Schritte unterscheiden.

Befolgen Sie immer den richtigen Wiederherstellungsvorgang für den Admin-Knoten, den Sie wiederherstellen. Die Verfahren sehen auf hohem Niveau gleich aus, unterscheiden sich aber in den Details.

.Wahlmöglichkeiten
* link:recovering-from-primary-admin-node-failures.html["Wiederherstellung nach Ausfällen des primären Admin-Nodes"]
* link:recovering-from-non-primary-admin-node-failures.html["Wiederherstellung nach Ausfällen von Admin-Nodes außerhalb des primären Standorts"]

