---
permalink: maintain/recovering-storagegrid-appliance-storage-node.html 
sidebar: sidebar 
keywords: recover, appliance storage node failure, workflow 
summary: Das Verfahren zur Wiederherstellung eines fehlerhaften StorageGRID-Appliance-Speicherknoten ist dieselbe, egal ob Sie eine Wiederherstellung nach dem Verlust des Systemlaufwerks oder nach dem Verlust von Storage-Volumes durchführen. 
---
= Warnungen zum Wiederherstellen von Appliance Storage Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Verfahren zur Wiederherstellung eines fehlerhaften StorageGRID-Appliance-Speicherknoten ist dieselbe, egal ob Sie eine Wiederherstellung nach dem Verlust des Systemlaufwerks oder nach dem Verlust von Storage-Volumes durchführen.


CAUTION: Wenn mehrere Speicherknoten ausgefallen sind (oder offline ist), wenden Sie sich an den technischen Support. Führen Sie den folgenden Wiederherstellungsvorgang nicht durch. Es kann zu Datenverlusten kommen. Weitere Informationen finden Sie unter link:how-site-recovery-is-performed-by-technical-support.html["Wie der technische Support eine Site wiederherstellt"].


CAUTION: Wenn ILM-Regeln so konfiguriert sind, dass nur eine replizierte Kopie gespeichert wird und sich die Kopie auf einem ausgefallenen Storage Volume befindet, können Sie das Objekt nicht wiederherstellen.


NOTE: Informationen zu Hardware-Wartungsverfahren, z. B. Anweisungen zum Austauschen eines Controllers oder zum Neuinstallieren von SANtricity OS, finden Sie unter https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/index.html["Wartungsanweisungen für Ihr Lagergerät"^].
