---
permalink: maintain/replacing-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace non-primary admin node, replacing non-primary admin node, non-primary admin node 
summary: Um einen nicht-primären Admin-Node wiederherzustellen, müssen Sie zuerst die physische oder virtuelle Hardware ersetzen. 
---
= Nicht-primärer Admin-Node ersetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um einen nicht-primären Admin-Node wiederherzustellen, müssen Sie zuerst die physische oder virtuelle Hardware ersetzen.

Sie können einen nicht primären Admin-Node durch einen nicht-primären Admin-Node ersetzen, der auf derselben Plattform ausgeführt wird, oder Sie können einen nicht-primären Admin-Node, der auf VMware oder einem Linux-Host ausgeführt wird, durch einen nicht-primären Admin-Node ersetzen, der auf einer Services Appliance gehostet wird.

Verwenden Sie das Verfahren, das der für den Node ausgewählten Ersatzplattform entspricht. Nachdem Sie den Knotenaustausch abgeschlossen haben (der für alle Node-Typen geeignet ist), werden Sie durch dieses Verfahren zum nächsten Schritt für die Wiederherstellung eines nicht-primären Admin-Knotens geleitet.

[cols="1a,2a"]
|===
| Austauschplattform | Verfahren 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Einen VMware-Knoten ersetzen"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Ersetzen Sie einen Linux-Knoten"]



 a| 
Service-Appliances
 a| 
link:replacing-failed-node-with-services-appliance.html["Ersetzen Sie eine Service Appliance"]



 a| 
OpenStack
 a| 
Die von NetApp bereitgestellten Festplattendateien und Skripte für Virtual Machines von OpenStack werden für Recovery-Vorgänge nicht mehr unterstützt. Wenn Sie einen Knoten wiederherstellen müssen, der in einer OpenStack-Implementierung ausgeführt wird, laden Sie die Dateien für Ihr Linux-Betriebssystem herunter. Dann folgen Sie dem Verfahren für link:all-node-types-replacing-linux-node.html["Ersetzen eines Linux-Knotens"].

|===