---
permalink: maintain/restarting-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, restart server manager 
summary: Möglicherweise müssen Sie den Server-Manager und alle Dienste, die auf einem Grid-Knoten ausgeführt werden, neu starten. 
---
= Starten Sie Server Manager und alle Services neu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie den Server-Manager und alle Dienste, die auf einem Grid-Knoten ausgeführt werden, neu starten.

.Bevor Sie beginnen
Sie haben die `Passwords.txt` Datei.

.Schritte
. Melden Sie sich beim Grid-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.


+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.

. Starten Sie Server Manager und alle Dienste auf dem Grid-Knoten neu: `service servermanager restart`
+
Server Manager und alle Dienste auf dem Grid-Knoten werden angehalten und dann neu gestartet.

+

NOTE: Die Verwendung des `restart` Befehls entspricht der Verwendung des Befehls gefolgt vom `stop` Befehl `start`.

. Melden Sie sich von der Befehls-Shell ab: `exit`

