---
permalink: maintain/restoring-audit-log-on-recovered-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore audit log, primary admin node 
summary: Wenn Sie das Revisionsprotokoll vom fehlgeschlagenen primären Admin-Knoten erhalten konnten, können Sie es in den primären Admin-Knoten kopieren, den Sie wiederherstellen. 
---
= Prüfprotokoll auf wiederhergestellten primären Admin-Knoten wiederherstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie das Revisionsprotokoll vom fehlgeschlagenen primären Admin-Knoten erhalten konnten, können Sie es in den primären Admin-Knoten kopieren, den Sie wiederherstellen.

.Bevor Sie beginnen
* Der wiederhergestellte Admin-Knoten wird installiert und ausgeführt.
* Sie haben die Überwachungsprotokolle an einen anderen Speicherort kopiert, nachdem der ursprüngliche Admin-Node fehlgeschlagen ist.


.Über diese Aufgabe
Wenn ein Admin-Knoten ausfällt, gehen in diesem Admin-Knoten gespeicherte Prüfprotokolle möglicherweise verloren. Es könnte möglich sein, Daten vor Verlust durch Kopieren von Prüfprotokollen aus dem fehlgeschlagenen Admin-Knoten und dann die Wiederherstellung dieser Prüfprotokolle auf den wiederhergestellten Admin-Knoten. Je nach Ausfall ist es möglicherweise nicht möglich, Prüfprotokolle vom fehlgeschlagenen Admin-Node zu kopieren. Wenn die Bereitstellung mehr als einen Admin-Node hat, können Sie in diesem Fall Audit-Protokolle von einem anderen Admin-Node wiederherstellen, da Audit-Protokolle auf allen Admin-Nodes repliziert werden.

Wenn nur ein Admin-Knoten vorhanden ist und das Audit-Protokoll nicht vom fehlgeschlagenen Knoten kopiert werden kann, beginnt der wiederhergestellte Admin-Knoten, Ereignisse im Auditprotokoll zu erfassen, als ob die Installation neu ist.

Sie müssen einen Admin-Knoten so schnell wie möglich wiederherstellen, um die Protokollierungsfunktion wiederherzustellen.

[NOTE]
====
Standardmäßig werden Audit-Informationen an das Audit-Protokoll auf Admin-Knoten gesendet. Sie können diese Schritte überspringen, wenn eine der folgenden Maßnahmen zutrifft:

* Sie haben einen externen Syslog-Server konfiguriert und Audit-Protokolle werden jetzt an den Syslog-Server anstatt an Admin-Knoten gesendet.
* Sie haben ausdrücklich angegeben, dass Audit-Meldungen nur auf den lokalen Knoten gespeichert werden sollten, die sie generiert haben.


Weitere Informationen finden Sie unter link:../monitor/configure-audit-messages.html["Konfigurieren von Überwachungsmeldungen und Protokollzielen"] .

====
.Schritte
. Melden Sie sich beim wiederhergestellten Admin-Knoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@recovery_Admin_Node_IP`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.


+
Nachdem Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.

. Prüfen Sie, welche Audit-Dateien erhalten wurden: `cd /var/local/log`
. Kopieren Sie die erhaltenen Audit-Log-Dateien in den wiederhergestellten Admin-Node: `scp admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs/YYYY* .`
+
Geben Sie bei der entsprechenden Eingabeaufforderung das Passwort für den Administrator ein.

. Löschen Sie aus Sicherheitsgründen die Prüfprotokolle vom fehlgeschlagenen Grid-Knoten, nachdem Sie überprüft haben, ob sie erfolgreich auf den wiederhergestellten Admin-Node kopiert wurden.
. Aktualisieren Sie die Benutzer- und Gruppeneinstellungen der Audit-Log-Dateien auf dem wiederhergestellten Admin-Knoten: `chown ams-user: bycast *`
. Melden Sie sich als root ab: `exit`

