---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: Lesen Sie vor der Wiederherstellung eines ausgefallenen Systemlaufwerks eines Storage-Knotens die allgemeinen Warnungen und Überlegungen zur Wiederherstellung des Grid-Knotens sowie die folgenden spezifischen Warnungen durch. 
---
= Warnungen für die Wiederherstellung des Storage Node-Systemlaufwerks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lesen Sie vor der Wiederherstellung eines fehlerhaften Systemlaufwerks eines Storage-Knotens die allgemeinen link:warnings-and-considerations-for-grid-node-recovery.html["Warnungen und Überlegungen zur Wiederherstellung des Grid Node"] und die folgenden spezifischen Warnungen durch.

Storage-Nodes verfügen über eine Cassandra Datenbank mit Objekt-Metadaten. Die Cassandra-Datenbank kann neu erstellt werden, wenn:

* Ein Speicher-Volume fällt aus und wird wiederhergestellt.
* Das Systemlaufwerk und ein oder mehrere Storage-Volumes ausfallen und werden wiederhergestellt.


Nach dem Rebuilt von Cassandra verwendet das System Informationen von anderen Speicherknoten. Falls Cassandra vor Kurzem neu aufgebaut wurde, sind Cassandra-Daten möglicherweise noch nicht konsistent im gesamten Grid. Wenn zu viele Storage-Nodes offline sind:

* Einige Cassandra-Daten sind möglicherweise nicht verfügbar.
* Es kann zu Datenverlusten kommen.



CAUTION: Wenn mehrere Speicherknoten ausgefallen sind (oder offline ist), wenden Sie sich an den technischen Support. Führen Sie das folgende Wiederherstellungsverfahren nicht durch. Es kann zu Datenverlusten kommen. Weitere Informationen finden Sie unter link:how-site-recovery-is-performed-by-technical-support.html["Wie der technische Support eine Site wiederherstellt"].


CAUTION: Wenn sich dieser Speicherknoten im schreibgeschützten Wartungsmodus befindet, um das Abrufen von Objekten durch einen anderen Speicherknoten mit ausgefallenen Speichervolumes zu ermöglichen, stellen Sie Volumes auf dem Speicherknoten mit fehlerhaften Speicher-Volumes wieder her, bevor Sie diesen fehlgeschlagenen Speicherknoten wiederherstellen. Siehe die Anweisungen zu link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["Wiederherstellung nach einem Ausfall des Speicher-Volumes bei intakt des Systemlaufwerks"].


CAUTION: Wenn ILM-Regeln so konfiguriert sind, dass nur eine replizierte Kopie gespeichert wird und sich die Kopie auf einem ausgefallenen Storage Volume befindet, können Sie das Objekt nicht wiederherstellen.
