---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: Lesen Sie vor der Wiederherstellung eines ausgefallenen Systemlaufwerks eines Storage-Knotens die allgemeinen Warnungen und Überlegungen zur Wiederherstellung des Grid-Knotens sowie die folgenden spezifischen Warnungen durch. 
---
= Warnungen für die Wiederherstellung des Storage Node-Systemlaufwerks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lesen Sie vor der Wiederherstellung eines fehlerhaften Systemlaufwerks eines Storage-Knotens die allgemeinen link:warnings-and-considerations-for-grid-node-recovery.html["Warnungen und Überlegungen zur Wiederherstellung des Grid Node"] und die folgenden spezifischen Warnungen durch.

Speicherknoten verfügen über eine Cassandra-Datenbank, die Objektmetadaten enthält.  Die Cassandra-Datenbank kann in folgenden Fällen neu erstellt werden:

* Ein Speichervolume fällt aus und wird wiederhergestellt.
* Das Systemlaufwerk und ein oder mehrere Storage-Volumes ausfallen und werden wiederhergestellt.


Beim Neuaufbau von Cassandra verwendet das System Informationen von anderen Speicherknoten.  Wenn Cassandra vor Kurzem neu erstellt wurde, sind die Cassandra-Daten im gesamten Grid möglicherweise noch nicht konsistent.  Wenn zu viele Speicherknoten offline sind:

* Einige Cassandra-Daten sind möglicherweise nicht verfügbar.
* Es könnte zu Datenverlust kommen.



CAUTION: Wenn mehr als ein Speicherknoten ausgefallen ist (oder offline ist), wenden Sie sich an den technischen Support.  Führen Sie das folgende Wiederherstellungsverfahren nicht durch.  Es könnte zu Datenverlust kommen. Weitere Informationen finden Sie unter link:how-site-recovery-is-performed-by-technical-support.html["Wie der technische Support eine Site wiederherstellt"] .


CAUTION: Wenn sich dieser Speicherknoten im schreibgeschützten Wartungsmodus befindet, um das Abrufen von Objekten durch einen anderen Speicherknoten mit ausgefallenen Speichervolumes zu ermöglichen, stellen Sie Volumes auf dem Speicherknoten mit fehlerhaften Speicher-Volumes wieder her, bevor Sie diesen fehlgeschlagenen Speicherknoten wiederherstellen. Siehe die Anweisungen zu link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["Wiederherstellung nach einem Ausfall des Speicher-Volumes bei intakt des Systemlaufwerks"].


CAUTION: Wenn ILM-Regeln so konfiguriert sind, dass nur eine replizierte Kopie gespeichert wird und sich die Kopie auf einem ausgefallenen Storage Volume befindet, können Sie das Objekt nicht wiederherstellen.
