---
permalink: maintain/selecting-node-recovery-procedure.html 
sidebar: sidebar 
keywords: storagegrid, recover, procedure 
summary: Das richtige Wiederherstellungsverfahren für den Typ des ausgefallenen Knotens auswählen. 
---
= Wählen Sie das StorageGRID-Knoten-Wiederherstellungsverfahren aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das richtige Wiederherstellungsverfahren für den Typ des ausgefallenen Knotens auswählen.

[cols="1a,2a"]
|===
| Grid-Node | Wiederherstellungsvorgang 


 a| 
Storage-Node
 a| 
Das Wiederherstellungsverfahren für den Storage Node hängt von der Art des Fehlers ab.

link:recovering-from-storage-node-failures.html["Wiederherstellung nach Ausfällen der Storage-Nodes"]



 a| 
Admin-Node
 a| 
Das Verfahren Admin-Knoten hängt davon ab, ob Sie den primären Admin-Knoten oder einen nicht-primären Admin-Knoten wiederherstellen müssen.

link:recovering-from-admin-node-failures.html["Wiederherstellung bei Ausfällen des Admin-Nodes"]



 a| 
Gateway-Node
 a| 
link:replacing-gateway-node.html["Wiederherstellung nach Gateway-Node-Ausfällen"]



 a| 
Archiv-Node
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/recovering-from-archive-node-failures.html["Wiederherstellung nach Ausfällen des Archivierungs-Nodes (StorageGRID 11.8-Dokumentstandort)"^]

|===

NOTE: Fällt ein Server mit mehreren Grid-Knoten aus, können die Knoten in beliebiger Reihenfolge wiederhergestellt werden. Ist der ausgefallene Server jedoch der primäre Admin-Knoten und es existieren keine nicht-primären Admin-Knoten, muss der primäre Admin-Knoten zuerst wiederhergestellt werden. Die Wiederherstellung des primären Admin-Knotens zuerst verhindert, dass die Wiederherstellung anderer Knoten ins Stocken gerät, wenn diese versuchen, den primären Admin-Knoten zu kontaktieren. Ist ein nicht-primärer Admin-Knoten verfügbar, kann dieser auch zur Wiederherstellung anderer Knoten verwendet werden, sodass diese Wiederherstellungen ohne Kontaktaufnahme mit dem primären Admin-Knoten fortgesetzt werden können.
