---
permalink: maintain/selecting-start-recovery-to-configure-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage node 
summary: Nachdem Sie einen Speicherknoten ersetzt haben, müssen Sie im Grid Manager die Option Wiederherstellung starten auswählen, um den neuen Knoten als Ersatz für den ausgefallenen Knoten zu konfigurieren. 
---
= Wählen Sie „Wiederherstellung starten“, um den StorageGRID-Speicherknoten zu konfigurieren.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie einen Speicherknoten ersetzt haben, müssen Sie im Grid Manager die Option Wiederherstellung starten auswählen, um den neuen Knoten als Ersatz für den ausgefallenen Knoten zu konfigurieren.

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:../admin/admin-group-permissions.html["Berechtigung für Wartung oder Root-Zugriff"].
* Sie haben die Provisionierungs-Passphrase.
* Sie haben den Ersatzknoten bereitgestellt und konfiguriert.
* Sie haben das Startdatum aller Reparaturaufträge für Daten, die mit dem Verfahren zur Fehlerkorrektur codiert wurden.


.Über diese Aufgabe
Wenn der Storage-Node als Container auf einem Linux-Host installiert ist, müssen Sie diesen Schritt nur ausführen, wenn einer dieser Schritte zutrifft:

* Sie mussten das Flag zum Importieren des Knotens verwenden `--force`, oder Sie haben es ausgegeben `storagegrid node force-recovery _node-name_`
* Sie mussten eine vollständige Neuinstallation des Knotens durchführen oder /var/local wiederherstellen.


.Schritte
. Melden Sie sich am primären Admin-Knoten an. Falls der primäre Admin-Knoten nicht verfügbar ist, kann ein nicht-primärer Admin-Knoten verwendet werden, sofern einer vorhanden ist.
. Im Grid Manager *Wartung* > *Aufgaben* > *Knotenwiederherstellung* auswählen.
. Wählen Sie in der Liste Ausstehende Knoten den Rasterknoten aus, den Sie wiederherstellen möchten.
+
Nodes werden in der Liste angezeigt, wenn sie fehlschlagen. Sie können jedoch keinen Node auswählen, bis er neu installiert wurde und für die Wiederherstellung bereit ist.

. Die *Bereitstellungs-Passphrase* eingeben.
. Auf *Wiederherstellung starten* klicken.
. Der Fortschritt der Wiederherstellung lässt sich unter *Wartung* > *Aufgaben* > *Knotenwiederherstellung* einsehen.
+
** Wenn der Grid-Knoten den Status „Warten auf manuelle Schritte“ erreicht, ist es erforderlich, link:../maintain/remounting-and-reformatting-storage-volumes-manual-steps.html["Speichervolumes manuell neu einbinden und formatieren"]. Nach Abschluss der manuellen Schritte erfolgt die Fortsetzung mit link:../maintain/restoring-object-data-to-storage-volume.html["Objektdaten auf den Volumes wiederherstellen"].
** Wenn die Wiederherstellung des Grid-Knotens von *In Bearbeitung* auf *Wiederhergestellt* übergegangen ist, ohne die Phase „Warten auf manuelle Schritte“ durchlaufen zu haben, sind keine weiteren Maßnahmen erforderlich.
+
[NOTE]
====
Während der Wiederherstellung kann jederzeit *Zurücksetzen* ausgewählt werden, um eine neue Wiederherstellung zu starten. Ein Dialogfeld erscheint, das darauf hinweist, dass der Node in einem undefinierten Zustand verbleibt, wenn der Vorgang zurückgesetzt wird.

Wenn Sie die Wiederherstellung nach dem Zurücksetzen des Vorgangs erneut versuchen möchten, muss der Geräteknoten wie folgt in einen Zustand vor der Installation versetzt werden:

*** *VMware*: Den bereitgestellten virtuellen Grid-Knoten löschen. Wenn Sie bereit sind, die Recovery neu zu starten, implementieren Sie den Node erneut.
*** *Linux*: Starten Sie den Knoten neu, indem Sie diesen Befehl auf dem Linux-Host ausführen: `storagegrid node force-recovery _node-name_`


====



