---
permalink: maintain/stopping-services-and-shutting-down-grid-nodes.html 
sidebar: sidebar 
keywords: recover, stop services, shut down nodes, node shutdown 
summary: Bevor Sie ein StorageGRID System ausschalten können, müssen Sie alle Services, die auf jedem Grid-Node ausgeführt werden, anhalten und anschließend alle VMware Virtual Machines, Container-Engines und StorageGRID Appliances herunterfahren. 
---
= Stoppen Sie Services und fahren Sie die Grid-Nodes herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie ein StorageGRID System ausschalten können, müssen Sie alle Services, die auf jedem Grid-Node ausgeführt werden, anhalten und anschließend alle VMware Virtual Machines, Container-Engines und StorageGRID Appliances herunterfahren.

.Über diese Aufgabe
Beenden Sie zuerst Dienste auf Admin-Nodes und Gateway-Nodes, und beenden Sie dann Dienste auf Storage-Nodes.

Dieser Ansatz ermöglicht Ihnen, den primären Admin-Knoten so lange wie möglich zu verwenden, um den Status der anderen Grid-Knoten zu überwachen.


NOTE: Wenn ein einzelner Host mehr als einen Grid-Node enthält, fahren Sie den Host erst herunter, wenn Sie alle Nodes auf diesem Host angehalten haben. Wenn der Host den primären Admin-Node enthält, fahren Sie diesen Host zuletzt herunter.


NOTE: Bei Bedarf können Sie link:linux-migrating-grid-node-to-new-host.html["Migrieren Sie Nodes von einem Linux-Host zu einem anderen"]die Hostwartung durchführen, ohne die Funktionalität oder Verfügbarkeit Ihres Grids zu beeinträchtigen.

.Schritte
. Beenden Sie alle Client-Applikationen vom Zugriff auf das Grid.
. [[log_in_to_gn]]Melden Sie sich bei jedem Gateway-Knoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.



. [[stop_all_Services]]Beenden Sie alle Dienste, die auf dem Knoten ausgeführt werden: `service servermanager stop`
+
Die Dienste können bis zu 15 Minuten zum Herunterfahren dauern. Außerdem können Sie sich möglicherweise per Remote-Zugriff beim System anmelden, um den Shutdown-Prozess zu überwachen.



. Wiederholen Sie die beiden vorherigen Schritte, um die Services auf allen Speicher-Nodes und nicht-primären Admin-Nodes anzuhalten.
+
Sie können die Dienste auf diesen Knoten in beliebiger Reihenfolge anhalten.

+

NOTE: Wenn Sie den Befehl zum Anhalten der Dienste auf einem Appliance-Storage-Node ausgeben `service servermanager stop`, müssen Sie die Appliance aus- und wieder einschalten, um den Node neu zu starten.

. Wiederholen Sie für den primären Admin-Knoten die Schritte für <<log_in_to_gn,Anmeldung beim Node>> und <<stop_all_services,Anhalten aller Dienste auf dem Knoten>>.
. Für Knoten, die auf Linux-Hosts ausgeführt werden:
+
.. Melden Sie sich beim Host-Betriebssystem an.
.. Stoppen Sie den Knoten: `storagegrid node stop`
.. Fahren Sie das Host-Betriebssystem herunter.


. Geben Sie für Knoten, die auf virtuellen VMware-Maschinen ausgeführt werden, und für Appliance Storage Nodes den Befehl shutdown ein: `shutdown -h now`
+
Führen Sie diesen Schritt unabhängig vom Ergebnis des `service servermanager stop` Befehls aus.

+
Bei diesem Befehl wird der Compute-Controller heruntergefahren, das Gerät ist jedoch weiterhin eingeschaltet. Sie müssen den nächsten Schritt abschließen.

. Wenn Sie Appliance-Nodes haben:
+
** Für Service-Appliances oder SGF6112-Appliances
+
... Schalten Sie das Gerät aus.
... Warten Sie, bis die blaue Betriebs-LED erlischt.


** Für die SG6160 Appliance
+
... Schalten Sie den SG6100-CN-Speicher-Controller aus.
... Warten Sie, bis die blaue LED-Betriebsanzeige am SG6100-CN-Speicher-Controller ausgeschaltet ist.


** Für das SG6000-Gerät
+
... Warten Sie, bis die grüne LED Cache Active auf der Rückseite der Storage Controller ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

... Schalten Sie das Gerät aus und warten Sie, bis die blaue Strom-LED ausgeschaltet ist.


** Für die SG5800 Appliance
+
... Warten Sie, bis die grüne LED Cache Active auf der Rückseite des Storage Controllers ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

... Wählen Sie auf der Startseite des SANtricity System Managers die Option *Vorgänge in Bearbeitung anzeigen*.
... Bestätigen Sie, dass alle Vorgänge abgeschlossen wurden, bevor Sie mit dem nächsten Schritt fortfahren.
... Schalten Sie beide Netzschalter am Controller Shelf aus und warten Sie, bis alle LEDs am Controller Shelf ausgeschaltet sind.


** Für die SG5700 Appliance
+
... Warten Sie, bis die grüne LED Cache Active auf der Rückseite des Storage Controllers ausgeschaltet ist.
+
Diese LED leuchtet, wenn zwischengespeicherte Daten auf die Laufwerke geschrieben werden müssen. Sie müssen warten, bis diese LED ausgeschaltet ist, bevor Sie den Strom ausschalten.

... Schalten Sie das Gerät aus und warten Sie, bis alle LED- und siebensegmentreichen Anzeigeaktivitäten angehalten sind.




. Melden Sie sich bei Bedarf von der Command Shell ab: `exit`
+
Das StorageGRID-Grid wurde jetzt heruntergefahren.



.Verwandte Informationen
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112 und SG6160 Storage Appliances"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["Storage Appliances der SG6000"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["Storage Appliances der SG5800"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["Storage Appliances der SG5700"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["Service Appliances für SG110 und SG1100"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100- und SG1000-Services-Appliances"^]

