---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: Möglicherweise müssen Sie einen Hotfix auf Ihr StorageGRID-System anwenden, wenn Probleme mit der Software zwischen Funktionsversionen erkannt und behoben werden. 
---
= StorageGRID Hotfix Verfahren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie einen Hotfix auf Ihr StorageGRID-System anwenden, wenn Probleme mit der Software zwischen Funktionsversionen erkannt und behoben werden.

StorageGRID Hotfixes enthalten Software-Änderungen, die außerhalb einer Feature- oder Patch-Freigabe verfügbar gemacht werden. Die gleichen Änderungen sind in einer zukünftigen Version enthalten. Darüber hinaus enthält jede Hotfix-Version eine Roll-up aller früheren Hotfixes innerhalb der Funktion oder Patch-Freigabe.



[[considerations-for-applying-a-hotfix]]
== Überlegungen für die Anwendung eines Hotfix

Ein StorageGRID-Hotfix kann nicht angewendet werden, wenn ein anderer Wartungsvorgang ausgeführt wird. Sie können beispielsweise keinen Hotfix anwenden, während eine Stilllegung, Erweiterung oder Wiederherstellung ausgeführt wird.


NOTE: Wenn ein Knoten oder ein Standort stillgelegt wird, können Sie sicher einen Hotfix anwenden. Darüber hinaus können Sie in der Lage sein, einen Hotfix in den letzten Phasen eines StorageGRID-Upgrade-Verfahrens anzuwenden. Weitere Informationen finden Sie in der Anleitung zum Aktualisieren der StorageGRID-Software.

Nachdem Sie den Hotfix im Grid Manager hochgeladen haben, wird der Hotfix automatisch auf den primären Admin-Knoten angewendet. Anschließend können Sie die Anwendung des Hotfix für die übrigen Knoten in Ihrem StorageGRID-System genehmigen.

Wenn ein Hotfix nicht auf einen oder mehrere Knoten angewendet wird, wird der Grund für den Fehler in der Spalte Details der Hotfix-Fortschrittstabelle angezeigt. Sie müssen alle Fehler beheben und den gesamten Prozess wiederholen. Knoten mit einer zuvor erfolgreichen Anwendung des Hotfix werden in nachfolgenden Anwendungen übersprungen. Sie können den Hotfix-Prozess so oft wie erforderlich sicher wiederholen, bis alle Knoten aktualisiert wurden. Der Hotfix muss erfolgreich auf allen Grid-Knoten installiert werden, damit die Anwendung abgeschlossen werden kann.

Während die Grid-Knoten mit der neuen Hotfix-Version aktualisiert werden, können die tatsächlichen Änderungen in einem Hotfix nur bestimmte Dienste auf bestimmte Node-Typen beeinflussen. Ein Hotfix wirkt sich beispielsweise nur auf den LDR-Service auf Storage Nodes aus.



[[how-hotfixes-are-applied-for-recovery-and-expansion]]
== Wie Hotfixes für die Wiederherstellung und Erweiterung eingesetzt werden

Nachdem ein Hotfix auf Ihr Grid angewendet wurde, installiert der primäre Admin-Node oder ein nicht-primärer Admin-Node automatisch dieselbe Hotfix-Version auf allen Nodes, die durch Wiederherstellungsvorgänge wiederhergestellt oder in einer Erweiterung hinzugefügt wurden. Eine Wiederherstellung jedes beliebigen Nodes (einschließlich des primären Admin-Nodes) ist möglich, wenn eine Anmeldung an einem nicht-primären Admin-Node erfolgt ist. Wird ein Node von einem nicht-primären Admin-Node aus wiederhergestellt, wendet dieser Admin-Node den Hotfix auf den wiederhergestellten Node an.

Wenn Sie den primären Admin Node von seinem eigenen StorageGRID Installer wiederherstellen müssen, muss die korrekte StorageGRID Version manuell installiert und anschließend der Hotfix angewendet werden. Die endgültige StorageGRID Version des primären Admin Node muss mit der Version der anderen Nodes im Grid übereinstimmen.

Das folgende Beispiel veranschaulicht, wie ein Hotfix angewendet wird, wenn der primäre Admin-Knoten wiederhergestellt wird, während Sie am nicht-primären Admin-Knoten angemeldet sind:

. Angenommen, auf dem Grid wird eine StorageGRID 11._A.B_-Version mit dem neuesten Hotfix ausgeführt. Die "Grid Version" ist 11._A.B.y_.
. Der primäre Admin-Node schlägt fehl.
. Sie stellen den primären Admin-Node mit StorageGRID 11._A.B_ neu bereit und führen das Recovery-Verfahren durch.
+

NOTE: Wie zur Anpassung an die Grid-Version erforderlich, können Sie bei der Implementierung des Node eine untergeordnete Version verwenden. Sie müssen nicht zuerst die Hauptversion implementieren.

. Anschließend wenden Sie Hotfix 11._A.B.y_ auf den primären Admin-Node an.

