---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'Das ADC-Quorum stellt sicher, dass an jedem Standort eine Mindestanzahl von Administrative Domain Controller (ADC)-Diensten verfügbar bleibt. StorageGRID verschiebt den ADC-Dienst bei Bedarf während der Außerbetriebnahme automatisch.' 
---
= Was ist das StorageGRID ADC-Quorum?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das ADC-Quorum stellt sicher, dass an jedem Standort eine Mindestanzahl von Administrative Domain Controller (ADC)-Diensten verfügbar bleibt. StorageGRID verschiebt den ADC-Dienst bei Bedarf während der Außerbetriebnahme automatisch.

Der ADC-Dienst, der auf einigen Storage Nodes zu finden ist, verwaltet Informationen zur Grid-Topologie und stellt Konfigurationsdienste für das Grid bereit. Das StorageGRID System erfordert, dass an jedem Standort und zu jeder Zeit ein Quorum von ADC-Services verfügbar ist.

Sie können einen Speicher-Node nicht stilllegen, wenn das Entfernen des Knotens dazu führen würde, dass das ADC-Quorum nicht mehr erfüllt wird. Um das ADC-Quorum während einer Stilllegung zu erfüllen, müssen mindestens drei Storage Nodes an jedem Standort über den ADC-Service verfügen. Wenn ein Standort über mehr als drei Storage Nodes mit dem ADC-Dienst verfügt, muss eine einfache Mehrheit dieser Nodes nach der Stilllegung verfügbar bleiben: `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: Gehen Sie mit Vorsicht vor, wenn Sie Storage-Nodes in einem Grid stilllegen, das rein softwarebasierte Metadaten-Nodes enthält. Wenn Sie alle Knoten außer Betrieb nehmen, die für den Speicher _sowohl_ Objekte als auch Metadaten konfiguriert sind, wird die Fähigkeit zum Speichern von Objekten aus dem Raster entfernt. Weitere Informationen zu nur Metadaten-Storage-Nodes finden Sie unterlink:../primer/what-storage-node-is.html#types-of-storage-nodes["Typen von Storage-Nodes"].

Angenommen, ein Standort umfasst derzeit sechs Storage Nodes mit ADC-Diensten und Sie möchten drei Storage Nodes stilllegen. Aufgrund der Quorum-Anforderung des ADC müssen Sie zwei Verfahren zur Deaktivierung durchführen:

* Bei der ersten Stilllegung müssen Sie sicherstellen, dass vier Speicher-Nodes mit ADC-Diensten verfügbar bleiben: `((0.5 * 6) + 1)`. Das bedeutet, dass Sie zunächst nur zwei Storage-Nodes außer Betrieb nehmen können.
* Im zweiten Außerbetriebnahmeverfahren können Sie den dritten Speicherknoten entfernen, da das ADC-Quorum jetzt nur noch drei ADC-Dienste erfordert, um verfügbar zu bleiben: `((0.5 * 4) + 1)` .


Wenn ein Speicherknoten mit dem ADC-Dienst außer Betrieb genommen wird, verschiebt StorageGRID den ADC-Dienst automatisch auf einen anderen Speicherknoten am selben Standort, falls die Außerbetriebnahme die Anzahl der ADC-Knoten am Standort unter das Quorum senken würde. Die automatische Verschiebung setzt voraus, dass alle Knoten im Grid verbunden sind und dass am selben Standort Speicherknoten ohne ADC-Dienst verfügbar sind, die den Dienst übernehmen können. Das Außerbetriebnahmeverfahren stellt sicher, dass pro Standort mindestens drei ADC-Speicherknoten vorhanden sind. Wenn beispielsweise vier oder sechs ADC-Knoten an einem Standort außer Betrieb genommen werden, bleiben nach dem Verfahren drei ADC-Speicherknoten übrig, vorausgesetzt, es sind noch Speicherknoten ohne ADC-Dienst am selben Standort verfügbar.

Kann der ADC-Dienst nicht automatisch verschoben werden, besteht die Möglichkeit, link:move-adc-service.html["Den ADC Service manuell verschieben"] auf einen anderen Storage Node am selben Standort zu verschieben oder link:../expand/index.html["einen neuen Storage Node in einer Erweiterung hinzufügen"] und anzugeben, dass dieser einen ADC-Dienst haben soll. Danach kann der bestehende Storage Node außer Betrieb genommen werden, ohne das Quorum zu beeinträchtigen.
