---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'Sie können bestimmte Speicher-Nodes an einem Standort möglicherweise nicht stilllegen, wenn nach der Stilllegung zu wenige Dienste des Administrative Domain Controller \(ADC\) verbleiben würden.' 
---
= Was ist das ADC-Quorum?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise können Sie bestimmte Speicher-Nodes an einem Standort nicht stilllegen, wenn nach der Stilllegung zu wenige ADC-Dienste (Administrative Domain Controller) verbleiben würden.

Der ADC-Dienst, der auf einigen Storage Nodes zu finden ist, verwaltet Informationen zur Grid-Topologie und stellt Konfigurationsdienste für das Grid bereit. Das StorageGRID System erfordert, dass an jedem Standort und zu jeder Zeit ein Quorum von ADC-Services verfügbar ist.

Sie können einen Speicher-Node nicht stilllegen, wenn das Entfernen des Knotens dazu führen würde, dass das ADC-Quorum nicht mehr erfüllt wird. Um das ADC-Quorum während einer Stilllegung zu erfüllen, müssen mindestens drei Storage Nodes an jedem Standort über den ADC-Service verfügen. Wenn ein Standort über mehr als drei Storage Nodes mit dem ADC-Dienst verfügt, muss eine einfache Mehrheit dieser Nodes nach der Stilllegung verfügbar bleiben: `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: Gehen Sie mit Vorsicht vor, wenn Sie Storage-Nodes in einem Grid stilllegen, das rein softwarebasierte Metadaten-Nodes enthält. Wenn Sie alle Knoten außer Betrieb nehmen, die für den Speicher _sowohl_ Objekte als auch Metadaten konfiguriert sind, wird die Fähigkeit zum Speichern von Objekten aus dem Raster entfernt. Weitere Informationen zu nur Metadaten-Storage-Nodes finden Sie unterlink:../primer/what-storage-node-is.html#types-of-storage-nodes["Typen von Storage-Nodes"].

Angenommen, ein Standort umfasst derzeit sechs Storage Nodes mit ADC-Diensten und Sie möchten drei Storage Nodes stilllegen. Aufgrund der Quorum-Anforderung des ADC müssen Sie zwei Verfahren zur Deaktivierung durchführen:

* Bei der ersten Stilllegung müssen Sie sicherstellen, dass vier Speicher-Nodes mit ADC-Diensten verfügbar bleiben: `((0.5 * 6) + 1)`. Das bedeutet, dass Sie zunächst nur zwei Storage-Nodes außer Betrieb nehmen können.
* Im zweiten Außerbetriebnahmeverfahren können Sie den dritten Speicherknoten entfernen, da das ADC-Quorum jetzt nur noch drei ADC-Dienste erfordert, um verfügbar zu bleiben: `((0.5 * 4) + 1)` .


Wenn Sie einen Speicherknoten außer Betrieb nehmen müssen, können Sie die ADC-Quorum-Anforderung weiterhin erfüllen, indem Sielink:../upgrade/changes-to-grid-management-api.html#new-private-endpoints-for-move-adc["Verschieben des ADC-Dienstes auf einen anderen Speicherknoten am selben Standort"] oder Hinzufügen eines neuen Speicherknotens in einemlink:../expand/index.html["Expansion"] und angeben, dass es einen ADC-Dienst haben soll.  Anschließend können Sie den vorhandenen Speicherknoten außer Betrieb nehmen, ohne das Quorum zu beeinträchtigen.
