---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: StorageGRID, what is a storage node, how many storage nodes 
summary: Storage-Nodes managen und speichern Objektdaten und Metadaten. Storage-Nodes umfassen die Services und Prozesse, die zum Speichern, Verschieben, Überprüfen und Abrufen von Objektdaten und Metadaten auf der Festplatte erforderlich sind. 
---
= Was ist ein StorageGRID Storage Node?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage-Nodes managen und speichern Objektdaten und Metadaten. Storage-Nodes umfassen die Services und Prozesse, die zum Speichern, Verschieben, Überprüfen und Abrufen von Objektdaten und Metadaten auf der Festplatte erforderlich sind.

Jeder Standort im StorageGRID-System muss über mindestens drei Storage-Nodes verfügen.



== Typen von Storage-Nodes

Während der Installation können Sie den Typ des Storage-Node auswählen, den Sie installieren möchten. Diese Typen sind für softwarebasierte Storage Nodes und Appliance-basierte Storage Nodes verfügbar, die die Funktion unterstützen:

* Storage-Node für Daten und Metadaten kombiniert
* Storage-Node nur für Metadaten
* Rein datenrein Storage-Node


Sie können den Typ des Storage-Node in folgenden Situationen auswählen:

* Bei der Erstinstallation eines Storage Node
* Wenn Sie während der StorageGRID-Systemerweiterung einen Speicher-Node hinzufügen




=== Storage Node für Daten und Metadaten (kombiniert)

Standardmäßig werden auf allen neuen Storage-Nodes sowohl Objektdaten als auch Metadaten gespeichert. Dieser Typ von Storage Node wird als _Combined_ Storage Node bezeichnet.



=== Storage-Node nur für Metadaten

Die ausschließliche Verwendung eines Storage-Knotens für Metadaten kann sinnvoll sein, wenn Ihr Grid eine sehr große Anzahl kleiner Objekte speichert. Die Installation von dedizierten Metadaten bietet ein besseres Gleichgewicht zwischen dem für eine große Anzahl an kleinen Objekten erforderlichen Speicherplatz und dem für diese Objekte erforderlichen Speicherplatz. Darüber hinaus können Storage-Nodes, die auf hochperformanten Appliances gehostet werden, auf nur Metadaten ausgerichtet sind, die Performance steigern.

Storage-Nodes, die nur Metadaten enthalten, erfüllen spezifische Hardwareanforderungen:

* Bei Verwendung von StorageGRID Appliances können nur Nodes mit Metadaten auf SGF6112-Appliances mit zwölf 1.9-TB- oder zwölf 3.8-TB-Laufwerken konfiguriert werden.
* Bei der Verwendung von softwarebasierten Nodes müssen die auf Metadaten auslaufenden Node-Ressourcen mit den vorhandenen Storage-Nodes übereinstimmen. Beispiel:
+
** Wenn der bestehende StorageGRID Standort SG6000 oder SG6100 Appliances verwendet, müssen die rein softwarebasierten Nodes mit Metadaten die folgenden Mindestanforderungen erfüllen:
+
*** 128 GB RAM
*** 8-Core-CPU
*** 8 TB SSD oder äquivalenter Storage für die Cassandra-Datenbank (rangedb/0)


** Wenn die vorhandene StorageGRID Site virtuelle Speicherknoten mit 24 GB RAM, 8-Kern-CPU und 3 TB oder 4 TB Metadatenspeicher verwendet, sollten die softwarebasierten Nur-Metadaten-Knoten ähnliche Ressourcen verwenden (24 GB RAM, 8-Kern-CPU und 4 TB Metadatenspeicher (rangedb/0)).


* Beim Hinzufügen einer neuen StorageGRID -Site sollte die Gesamtmetadatenkapazität der neuen Site mindestens der vorhandener Sites entsprechen.  Die Ressourcen an einem neuen Standort sollten mit den Speicherknoten an vorhandenen Standorten übereinstimmen.



NOTE: Obwohl reine Metadaten-Storage-Nodes S3-Client-Anforderungen enthalten <<ldr-service,LDR-Service>>und verarbeiten können, erhöht sich die StorageGRID-Performance möglicherweise nicht.



=== Rein datenrein Storage-Node

Ein Storage-Node ausschließlich für Daten ist sinnvoll, wenn Ihre Storage-Nodes unterschiedliche Performance-Merkmale aufweisen. Um beispielsweise die Performance potenziell zu steigern, können Sie reine Daten-Storage-Nodes mit einer hohen Kapazität und gleichzeitig hochperformante Storage-Nodes mit Metadaten verwenden.

Darüber hinaus können Sie mehr Metadatenkapazität erhalten, indem Sie Knoten mit wenig RAM aus Cassandra entfernen, wodurch sich das Metadatenkapazitätslimit pro Knoten erhöht. Weitere Informationen finden Sie unter link:../admin/managing-object-metadata-storage.html["Management von Objekt-Metadaten-Storage"] .

Sie können einen Storage Node konvertieren, der nicht die<<adc-service,ADC-Dienst>> zu einem reinen Datenspeicherknoten. Weitere Informationen finden Sie unter link:../maintain/convert-to-data-only-node.html["Konvertieren eines Speicherknotens in einen Nur-Datenknoten"] .



== Erforderliche Speicherknoten pro Grid und pro Site

Beachten Sie bei der Auswahl der in Ihrer Topologie zu verwendenden Speicherknoten, dass das Raster bzw. jeder Standort im Raster Folgendes enthalten muss:

* Pro Site (in einem Single- oder Multi-Site-Raster): Drei<<adc-service,ADC>> Speicherknoten (kann eine beliebige Kombination aus kombinierten und reinen Metadaten-Speicherknoten sein)
* Single-Site-Grid: Mindestens zwei Objektspeicherknoten (kann eine beliebige Kombination aus kombinierten und Nur-Daten-Knoten sein)
* Multi-Site-Raster: Mindestens ein Objektspeicherknoten pro Site (kann entweder kombiniert oder nur für Daten sein)




== Primäre Services für Storage-Nodes

Die folgende Tabelle enthält die primären Services für Storage-Nodes. In dieser Tabelle werden jedoch nicht alle Node-Services aufgeführt.


NOTE: Einige Services, wie z. B. der ADC-Service und der RSM-Service, bestehen in der Regel nur auf drei Storage-Nodes an jedem Standort.

[cols="1a,3a"]
|===
| Service | Tastenfunktion 


 a| 
Konto (Konto)
 a| 
Management von Mandantenkonten.

Dieser Dienst wird nicht von reinen Datenspeicherknoten gehostet.



 a| 
[[adc-service]]Administrativer Domänencontroller (ADC)
 a| 
Aufrechterhaltung der Topologie und Grid-Konfiguration

Dieser Dienst wird nicht von reinen Datenspeicherknoten gehostet.

.Details
[%collapsible]
====
Der Dienst Administrative Domain Controller (ADC) authentifiziert Grid-Knoten und ihre Verbindungen miteinander. Der ADC-Dienst wird auf mindestens drei Storage Nodes an einem Standort gehostet.

Der ADC-Dienst verwaltet Topologiedaten, einschließlich Standort und Verfügbarkeit von Diensten. Wenn ein Grid-Knoten Informationen von einem anderen Grid-Knoten benötigt oder eine Aktion von einem anderen Grid-Knoten ausgeführt werden muss, kontaktiert er einen ADC-Service, um den besten Grid-Knoten für die Bearbeitung seiner Anforderung zu finden. Darüber hinaus behält der ADC-Service eine Kopie der Konfigurationspakete der StorageGRID-Bereitstellung bei, sodass jeder Grid-Node aktuelle Konfigurationsinformationen abrufen kann.

Zur Erleichterung von verteilten und isanded-Operationen synchronisiert jeder ADC-Dienst Zertifikate, Konfigurationspakete und Informationen über Services und Topologie mit den anderen ADC-Diensten im StorageGRID-System.

Im Allgemeinen unterhalten alle Rasterknoten eine Verbindung zu mindestens einem ADC-Dienst. So wird sichergestellt, dass die Grid-Nodes immer auf die neuesten Informationen zugreifen. Wenn sich Grid-Nodes verbinden, werden die Zertifikate anderer Grid-Nodes zwischengespeichert, sodass die Systeme mit bekannten Grid-Nodes weiterarbeiten können, selbst wenn ein ADC-Dienst nicht verfügbar ist. Neue Grid-Knoten können nur Verbindungen über einen ADC-Dienst herstellen.

Durch die Verbindung jedes Grid-Knotens kann der ADC-Service Topologiedaten erfassen. Die Informationen zu diesem Grid-Node umfassen die CPU-Last, den verfügbaren Festplattenspeicher (wenn der Storage vorhanden ist), unterstützte Services und die Standort-ID des Grid-Node. Andere Dienste fragen den ADC-Service nach Topologiedaten durch Topologieabfragen. Der ADC-Dienst reagiert auf jede Abfrage mit den neuesten Informationen, die vom StorageGRID-System empfangen wurden.

====


 a| 
Cassandra
 a| 
Speichert und sichert Objekt-Metadaten.

Dieser Dienst wird nicht von reinen Datenspeicherknoten gehostet.



 a| 
Cassandra Reaper
 a| 
Führt automatische Reparaturen von Objektmetadaten durch.

Dieser Dienst wird nicht von reinen Datenspeicherknoten gehostet.



 a| 
Chunk
 a| 
Verwaltet Erasure-codierte Daten und Paritätsfragmente.



 a| 
Data Mover (dmv)
 a| 
Verschiebt Daten in Cloud-Storage-Pools



 a| 
Verteilter Datenspeicher (DDS)
 a| 
Überwacht Objekt-Metadaten-Storage

.Details
[%collapsible]
====
Jeder Storage Node umfasst den Distributed Data Store (DDS)-Service. Dieser Service ist mit der Cassandra-Datenbank verbunden, um Hintergrundaufgaben für die im StorageGRID-System gespeicherten Objektmetadaten auszuführen.

Der DDS-Service verfolgt die Gesamtanzahl der im StorageGRID-System aufgenommenen Objekte sowie die Gesamtanzahl der über die unterstützten Schnittstellen (S3) des Systems aufgenommenen Objekte.

====


 a| 
Identität (idnt)
 a| 
Föderiert Benutzeridentitäten von LDAP und Active Directory

Dieser Dienst wird nicht von reinen Datenspeicherknoten gehostet.



 a| 
[[ldr-Service]]Local Distribution Router (LDR)
 a| 
Verarbeitet Protokollanfragen von Objekt-Storage und managt Objektdaten auf der Festplatte.

.Details
[%collapsible]
====
Jeder _kombinierte_, _nur Daten_ und _nur Metadaten_ Speicher-Node enthält den Local Distribution Router (LDR)-Service. Dieser Service übernimmt Funktionen für den Content-Transport, einschließlich Datenspeicherung, Routing und Bearbeitung von Anfragen. Der LDR-Dienst erledigt die meiste harte Arbeit des StorageGRID-Systems durch die Verarbeitung von Datenübertragungslasten und Datenverkehrsfunktionen.

Der LDR-Service übernimmt folgende Aufgaben:

* Abfragen
* Information Lifecycle Management-Aktivitäten (ILM
* Löschen von Objekten
* Objekt-Storage
* Objektdatenübertragung von einem anderen LDR-Service (Storage Node)
* Datenspeicher-Management
* S3 Protokollschnittstelle


Der LDR-Service ordnet jedes S3-Objekt seiner eindeutigen UUID zu.

Objektspeicher:: Der zugrunde liegende Datenspeicher eines LDR-Service wird in eine feste Anzahl an Objektspeichern (auch Storage-Volumes genannt) unterteilt. Jeder Objektspeicher ist ein separater Bereitstellungspunkt.
+
--
Das Objekt speichert in einem Storage-Node werden durch eine Hexadezimalzahl zwischen 0000 und 002F identifiziert, die als Volume-ID bezeichnet wird. Der Speicherplatz ist im ersten Objektspeicher (Volume 0) für Objekt-Metadaten in einer Cassandra-Datenbank reserviert. Für Objektdaten werden alle verbleibenden Speicherplatz auf diesem Volume verwendet. Alle anderen Objektspeichern werden ausschließlich für Objektdaten verwendet, zu denen replizierte Kopien und nach dem Erasure-Coding-Verfahren Fragmente gehören.

Um sicherzustellen, dass selbst der Speicherplatz für replizierte Kopien genutzt wird, werden Objektdaten für ein bestimmtes Objekt auf Basis des verfügbaren Storage in einem Objektspeicher gespeichert. Wenn ein Objektspeicher voll ist, speichern die übrigen Objektspeicher weiterhin Objekte, bis kein Speicherplatz mehr auf dem Storage-Node vorhanden ist.

--
Metadatensicherung:: StorageGRID speichert Objekt-Metadaten in einer Cassandra-Datenbank, die über eine Schnittstelle zum LDR-Service verfügt.
+
--
Um Redundanz sicherzustellen und so vor Verlust zu schützen, werden an jedem Standort drei Kopien von Objekt-Metadaten aufbewahrt. Diese Replikation ist nicht konfigurierbar und wird automatisch ausgeführt. Weitere Informationen finden Sie unter link:../admin/managing-object-metadata-storage.html["Management von Objekt-Metadaten-Storage"].

--


====


 a| 
Replicated State Machine (RSM)
 a| 
Stellt sicher, dass Serviceanfragen der S3-Plattform an ihre jeweiligen Endpunkte gesendet werden.

Dieser Dienst wird nicht von reinen Datenspeicherknoten gehostet.



 a| 
Server Status Monitor (SSM)
 a| 
Überwachung des Betriebssystems und der zugrunde liegenden Hardware

|===