---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines, StorageGRID 
summary: Sie können Ihr StorageGRID System durch Hinzufügen eines neuen Standorts erweitern. 
---
= Richtlinien zum Hinzufügen eines neuen Standorts in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihr StorageGRID System durch Hinzufügen eines neuen Standorts erweitern.



[[guidelines-for-adding-a-site]]
== Richtlinien zum Hinzufügen eines Standorts

Überprüfen Sie vor dem Hinzufügen eines Standorts die folgenden Anforderungen und Einschränkungen:

* Sie können nur einen Standort pro Erweiterungsvorgang hinzufügen.
* Sie können einem vorhandenen Standort keine Grid-Nodes im Rahmen derselben Erweiterung hinzufügen.
* Alle Standorte müssen mindestens drei Speicherknoten umfassen. Diese können beliebige Kombinationen aus kombinierten und ausschließlich Metadaten-Speicherknoten sein. Wenn mehr als drei Speicherknoten vorhanden sind, sind beliebige Kombinationen aus kombinierten, ausschließlich Metadaten- und ausschließlich Daten-Speicherknoten möglich, sofern drei ADC-Services verfügbar sind. Weitere Informationen finden sich unter link:../primer/what-storage-node-is.html#required-storage-nodes-per-grid-and-per-site["Erforderliche Speicherknoten pro Grid und pro Site"].
* Beim Hinzufügen eines neuen Standorts erhöht sich die Anzahl der Objekte, die Sie speichern können, nicht automatisch. Die gesamte Objektkapazität eines Grids hängt von der verfügbaren Speicherkapazität, der ILM-Richtlinie und der Metadatenkapazität an jedem Standort ab.
* Bei der Dimensionierung eines neuen Standorts müssen Sie sicherstellen, dass dieser genügend Metadaten enthält.
+
StorageGRID speichert an jedem Standort eine Kopie aller Objektmetadaten. Beim Hinzufügen eines neuen Standorts ist darauf zu achten, dass ausreichend Metadatenkapazität sowohl für die vorhandenen Objektmetadaten als auch für Wachstum vorhanden ist.

+
Weitere Informationen sind unter den folgenden Quellen zu finden:

+
** link:../admin/managing-object-metadata-storage.html["Management von Objekt-Metadaten-Storage"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["Überwachen der Objekt-Metadaten-Kapazität für jeden Storage Node"]


* Dabei muss die verfügbare Netzwerkbandbreite zwischen Standorten und das Maß der Netzwerklatenz berücksichtigt werden. Metadatenaktualisierungen werden kontinuierlich zwischen Standorten repliziert, selbst wenn alle Objekte nur am Standort gespeichert werden, an dem sie aufgenommen werden.
+
Um Leistungseinbußen aufgrund von Latenz zu vermeiden:

+
** Erasure Coding wird zwischen Standorten mit einer Latenz von mehr als 100 ms nicht empfohlen.
** Die Standorte in Ihrem StorageGRID System sollten sich nicht über große geografische Entfernungen erstrecken, beispielsweise über mehrere Kontinente.


* Da Ihr StorageGRID System während der Erweiterung betriebsbereit bleibt, müssen Sie ILM-Regeln prüfen, bevor Sie mit dem Erweiterungsverfahren beginnen. Sie müssen sicherstellen, dass Objektkopien erst am neuen Standort gespeichert werden, wenn der Erweiterungsvorgang abgeschlossen ist.
+
Beispielsweise sollte vor Beginn der Erweiterung geprüft werden, ob Regeln den Standard-Speicherpool (All Storage Nodes) verwenden. Falls dies der Fall ist, kann ein neuer Speicherpool mit den vorhandenen Storage Nodes erstellt und die ILM-Regeln so aktualisiert werden, dass sie den neuen Speicherpool verwenden. Andernfalls werden Objekte an den neuen Standort kopiert, sobald der erste Knoten an diesem Standort aktiv ist.

+
Weitere Informationen zum Ändern einer ILM-Richtlinie beim Hinzufügen eines neuen Standorts sind in der link:../ilm/example-6-changing-ilm-policy.html["Beispiel zum Ändern einer ILM-Richtlinie"] zu finden.


