---
sidebar: sidebar 
permalink: expand/copying-audit-logs.html 
keywords: copy audit log, Admin Node expansion, StorageGRID 
summary: Wenn Sie über ein Erweiterungsverfahren einen neuen Admin-Knoten hinzufügen, protokolliert sein AMS-Dienst nur Ereignisse und Aktionen, die nach dem Beitritt zum System auftreten.  Bei Bedarf können Sie Prüfprotokolle von einem zuvor installierten Admin-Knoten auf den neuen Erweiterungs-Admin-Knoten kopieren, sodass dieser mit dem Rest des StorageGRID -Systems synchronisiert ist. 
---
= Kopieren Sie die Audit-Protokolle auf neue Admin-Knoten in StorageGRID.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie über ein Erweiterungsverfahren einen neuen Admin-Knoten hinzufügen, protokolliert sein AMS-Dienst nur Ereignisse und Aktionen, die nach dem Beitritt zum System auftreten.  Bei Bedarf können Sie Prüfprotokolle von einem zuvor installierten Admin-Knoten auf den neuen Erweiterungs-Admin-Knoten kopieren, sodass dieser mit dem Rest des StorageGRID -Systems synchronisiert ist.

.Bevor Sie beginnen
* Sie haben die erforderlichen Erweiterungsschritte zum Hinzufügen eines Admin-Knotens abgeschlossen.
* Sie haben die `Passwords.txt` Datei.


.Über diese Aufgabe
Um historische Audit-Meldungen auf einem neuen Admin-Knoten verfügbar zu machen, müssen Sie die Audit-Log-Dateien manuell von einem vorhandenen Admin-Knoten in den Erweiterungs-Admin-Knoten kopieren.

[NOTE]
====
Standardmäßig werden Audit-Informationen an die `localaudit` Melden Sie sich bei jedem Knoten an.  Um dieses Verfahren zu verwenden, müssen Sie die Admin-Knoten wie folgt als Prüfziel konfiguriert haben:

* Sie haben *Admin-Knoten/lokale Knoten* als Protokollziel konfiguriert.
* Sie haben *Admin-Knoten und externen Syslog-Server* als Protokollziel konfiguriert.


Siehelink:../monitor/configure-audit-messages.html["Konfigurieren von Audit-Meldungen und externem Syslog-Server"] für Details.

====
.Schritte
. Melden Sie sich beim primären Admin-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh _admin@_primary_Admin_Node_IP_`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.



. Beenden Sie den AMS-Dienst, um zu verhindern, dass er eine neue Datei erstellt: `service ams stop`
. Navigieren Sie zum Verzeichnis für den Audit-Export:
+
`cd /var/local/audit/export/`

. Benennen Sie die Quelle um `audit.log` Datei, um sicherzustellen, dass die Datei auf dem Erweiterungs-Admin-Knoten, auf den Sie sie kopieren, nicht überschrieben wird:
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. Kopieren Sie alle Audit-Log-Dateien in den Zielspeicherort auf dem Erweiterungs-Admin-Node:
+
`scp -p * _IP_address_:/var/local/audit/export/`

. Wenn Sie zur Eingabe der Passphrase für aufgefordert `/root/.ssh/id_rsa` werden, geben Sie das SSH-Zugriffspasswort für den in der Datei aufgeführten primären Admin-Knoten ein `Passwords.txt`.
. Originaldatei wiederherstellen `audit.log`:
+
`mv _new_name_.txt audit.log`

. AMS-Dienst starten:
+
`service ams start`

. Melden Sie sich vom Server ab:
+
`exit`

. Melden Sie sich beim Erweiterungs-Admin-Knoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_expansion_Admin_Node_IP_`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
.. Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
.. Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.



. Benutzer- und Gruppeneinstellungen für die Audit-Log-Dateien aktualisieren:
+
`cd /var/local/audit/export/`

+
`chown ams-user:bycast *`

. Melden Sie sich vom Server ab:
+
`exit`


