---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion, StorageGRID 
summary: Beim Hinzufügen von Admin-Nodes durch ein Erweiterungsverfahren können Sie optional die Datenbank vom primären Admin-Node zum neuen Admin-Node kopieren. Durch das Kopieren der Datenbank können Sie historische Informationen über Attribute, Warnmeldungen und Warnmeldungen aufbewahren. 
---
= Kopieren Sie die Admin-Knotendatenbank auf neue Admin-Knoten in StorageGRID.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Hinzufügen von Admin-Nodes durch ein Erweiterungsverfahren können Sie optional die Datenbank vom primären Admin-Node zum neuen Admin-Node kopieren. Durch das Kopieren der Datenbank können Sie historische Informationen über Attribute, Warnmeldungen und Warnmeldungen aufbewahren.

.Bevor Sie beginnen
* Sie haben die erforderlichen Erweiterungsschritte zum Hinzufügen eines Admin-Knotens abgeschlossen.
* Sie haben die `Passwords.txt` Datei.
* Sie haben die Provisionierungs-Passphrase.


.Über diese Aufgabe
Der StorageGRID-Softwareaktivierungsprozess erstellt eine leere Datenbank für den NMS-Dienst auf dem Erweiterungs-Admin-Knoten. Wenn der NMS-Dienst auf dem Erweiterungs-Admin-Knoten startet, zeichnet er Informationen für Server und Dienste auf, die derzeit Teil des Systems sind oder später hinzugefügt werden. Diese Admin-Knoten-Datenbank enthält die folgenden Informationen:

* Meldungsverlauf
* Historische Attributdaten, die in Diagrammen im Legacy-Stil auf der Seite Knoten verwendet werden


Um sicherzustellen, dass die Admin-Node-Datenbank zwischen den Knoten konsistent ist, können Sie die Datenbank vom primären Admin-Node auf den Erweiterungs-Admin-Node kopieren.


NOTE: Das Kopieren der Datenbank vom primären Admin-Node (der__Source Admin-Node_) zu einem Erweiterungs-Admin-Node kann bis zu mehrere Stunden dauern. In diesem Zeitraum ist der Grid Manager nicht zugänglich.

Führen Sie diese Schritte aus, um den MI-Dienst und den Management-API-Dienst sowohl auf dem primären Admin-Node als auch auf dem Erweiterungs-Admin-Node zu beenden, bevor Sie die Datenbank kopieren.

.Schritte
. Führen Sie die folgenden Schritte auf dem primären Admin-Knoten aus:
+
.. Melden Sie sich beim Admin-Knoten an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
... Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.


.. Führen Sie den folgenden Befehl aus: `recover-access-points`
.. Geben Sie die Provisionierungs-Passphrase ein.
.. Halten Sie den MI-Dienst an: `service mi stop`
.. Beenden Sie den Management Application Program Interface (Management API)-Service: `service mgmt-api stop`


. Führen Sie die folgenden Schritte auf dem Erweiterungs-Admin-Knoten aus:
+
.. Melden Sie sich beim Erweiterungs-Admin-Knoten an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
... Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.


.. Halten Sie den MI-Dienst an: `service mi stop`
.. Stoppen Sie den Management-API-Service: `service mgmt-api stop`
.. Fügen Sie den SSH-privaten Schlüssel zum SSH-Agenten hinzu. Eingabe:``ssh-add``
.. Geben Sie das in der Datei aufgeführte SSH-Zugriffspasswort ein `Passwords.txt`.
.. Kopieren Sie die Datenbank vom Quell-Admin-Node auf den Erweiterungs-Admin-Node: `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. Wenn Sie dazu aufgefordert werden, bestätigen Sie, dass Sie die MI-Datenbank auf dem Erweiterungs-Admin-Node überschreiben möchten.
+
Die Datenbank und ihre historischen Daten werden auf den Erweiterungs-Admin-Knoten kopiert. Wenn der Kopiervorgang abgeschlossen ist, startet das Skript den Erweiterungs-Admin-Knoten.

.. Wenn Sie keinen passwortlosen Zugriff auf andere Server mehr benötigen, entfernen Sie den privaten Schlüssel vom SSH-Agent. Eingabe:``ssh-add -D``


. Starten Sie die Dienste auf dem primären Admin-Node neu: `service servermanager start`

