---
permalink: expand/gather-required-materials.html 
sidebar: sidebar 
keywords: expand, expansion, planning, storagrid files 
summary: Bevor Sie eine Erweiterung durchführen, sammeln Sie die Materialien und installieren und konfigurieren Sie neue Hardware und Netzwerke. 
---
= Sammeln Sie die erforderlichen Materialien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine Erweiterung durchführen, sammeln Sie die Materialien und installieren und konfigurieren Sie neue Hardware und Netzwerke.

[cols="1a,2a"]
|===
| Element | Hinweise 


 a| 
StorageGRID Installationsarchiv
 a| 
Wenn Sie neue Grid-Nodes oder einen neuen Standort hinzufügen, müssen Sie das StorageGRID Installationsarchiv herunterladen und extrahieren. Sie müssen dieselbe Version verwenden, die derzeit im Raster ausgeführt wird.

Weitere Informationen finden Sie in den Anweisungen für <<download-and-extract-install-files,Herunterladen und Extrahieren der StorageGRID-Installationsdateien>>.

*Hinweis:* Sie müssen keine Dateien herunterladen, wenn Sie neue Speichervolumes zu vorhandenen Speicherknoten hinzufügen oder eine neue StorageGRID-Appliance installieren.



 a| 
Service-Laptop
 a| 
Der Service-Laptop verfügt über Folgendes:

* Netzwerkport
* SSH-Client (z. B. PuTTY)
* link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"]




 a| 
`Passwords.txt` Datei
 a| 
Enthält die Passwörter, die für den Zugriff auf Grid-Nodes in der Befehlszeile erforderlich sind. Im Wiederherstellungspaket enthalten.



 a| 
Provisioning-Passphrase
 a| 
Die Passphrase wird erstellt und dokumentiert, wenn das StorageGRID-System zum ersten Mal installiert wird. Die Provisionierungs-Passphrase ist nicht in der `Passwords.txt` Datei enthalten.



 a| 
StorageGRID-Dokumentation
 a| 
* link:../admin/index.html["StorageGRID verwalten"]
* link:../release-notes/index.html["Versionshinweise"]
* Installationsanweisungen für Ihre Plattform
+
** link:../rhel/index.html["Installieren Sie StorageGRID unter Red hat Enterprise Linux"]
** link:../ubuntu/index.html["Installieren Sie StorageGRID auf Ubuntu oder Debian"]
** link:../vmware/index.html["Installieren Sie StorageGRID auf VMware"]






 a| 
Aktuelle Dokumentation für Ihre Plattform
 a| 
Informationen zu unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["Interoperabilitäts-Matrix-Tool (IMT)"^].

|===


== Laden Sie die StorageGRID Installationsdateien herunter und extrahieren Sie sie

.[[Download-and-Extract-install-files]]
Bevor Sie neue Grid-Nodes oder einen neuen Standort hinzufügen können, müssen Sie das entsprechende StorageGRID-Installationsarchiv herunterladen und die Dateien extrahieren.

.Über diese Aufgabe
Sie müssen Erweiterungsvorgänge mit der Version von StorageGRID durchführen, die derzeit im Grid ausgeführt wird.

.Schritte
. Gehen Sie zu https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^].
. Wählen Sie die Version von StorageGRID aus, die derzeit im Grid ausgeführt wird.
. Melden Sie sich mit Ihrem Benutzernamen und Passwort für Ihr NetApp Konto an.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung, aktivieren Sie das Kontrollkästchen und wählen Sie dann *Akzeptieren und fortfahren* aus.
. Wählen Sie in der Spalte *Install StorageGRID* der Download-Seite die Datei oder `.zip` für Ihre Plattform aus `.tgz`.
+
Die in der Archivdatei der Installation angezeigte Version muss mit der Version der derzeit installierten Software übereinstimmen.

+
Verwenden Sie die `.zip` Datei, wenn Sie Windows auf dem Service-Laptop ausführen.

+
[cols="1a,2a"]
|===
| Plattform | Installationsarchiv 


 a| 
Red Hat Enterprise Linux
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu oder Debian oder Appliances
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 


 a| 
OpenStack/anderer Hypervisor
 a| 
Um eine vorhandene Implementierung auf OpenStack zu erweitern, müssen Sie eine Virtual Machine mit einer der oben aufgeführten unterstützten Linux-Distributionen implementieren und die entsprechenden Anweisungen für Linux befolgen.

|===
. Laden Sie die Archivdatei herunter und extrahieren Sie sie.
. Führen Sie den entsprechenden Schritt für Ihre Plattform aus, um die benötigten Dateien basierend auf Ihrer Plattform, der geplanten Grid-Topologie und der Erweiterung des StorageGRID Systems auszuwählen.
+
Die im Schritt für jede Plattform aufgeführten Pfade beziehen sich auf das von der Archivdatei installierte Verzeichnis auf der obersten Ebene.

. Wenn Sie ein Red hat Enterprise Linux-System erweitern, wählen Sie die entsprechenden Dateien aus.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./Effektivwert/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./Effektivwert/NLF000000.txt  a| 
Eine kostenlose Lizenz, die keinen Support-Anspruch auf das Produkt bietet.



| ./Effektivwert/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RPM-Paket für die Installation der StorageGRID-Node-Images auf Ihren RHEL-Hosts.



| ./Effektivwert/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RPM-Paket für die Installation des StorageGRID-Hostdienstes auf Ihren RHEL-Hosts.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./Effektivwert/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./Effektivwert/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./rpms/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript.



| ./Effektivwert/storagegrid-ssoauth.py  a| 
Ein Beispiel-Python-Skript, mit dem Sie sich bei aktivierter Single-Sign-On-Funktion bei der Grid-Management-API anmelden können. Sie können dieses Skript auch für die Ping Federate-Integration verwenden.



| ./rpms/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei zur Verwendung mit dem `configure-storagegrid.py` Skript.



| ./rpms/Extras/ansible  a| 
Ansible-Beispielrolle und -Playbook zur Konfiguration von RHEL-Hosts für die Bereitstellung von StorageGRID-Containern. Die Rolle oder das Playbook können Sie nach Bedarf anpassen.



| ./eff/storagegrid-ssoauth-azure.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) mithilfe von Active Directory oder Ping Federate aktiviert ist.



| ./RMS/storagegrid-ssoauth-Azure.js  a| 
Ein Hilfsskript, das vom zugehörigen Python-Skript aufgerufen `storagegrid-ssoauth-azure.py` wird, um SSO-Interaktionen mit Azure durchzuführen.



| ./rpms/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie diese Schemas verwenden, um zu bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung für Upgrade-Kompatibilitätstests haben.

|===
. Wenn Sie ein Ubuntu oder Debian-System erweitern, wählen Sie die entsprechenden Dateien aus.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./DES/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./Debs/NLF000000.txt  a| 
Eine NetApp Lizenzdatei, die nicht in der Produktionsumgebung enthalten ist und für Tests und Proof of Concept-Implementierungen genutzt werden kann



| ./Debs/storagegrid-webscale-images-version-SHA.deb  a| 
DEB-Paket zum Installieren der StorageGRID-Knoten-Images auf Ubuntu oder Debian-Hosts.



| ./Debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5-Prüfsumme für die Datei `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./Debs/storagegrid-webscale-service-version-SHA.deb  a| 
DEB-Paket zur Installation des StorageGRID-Hostdienstes auf Ubuntu oder Debian-Hosts.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./Debs/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./Debs/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./Debs/storagegrid-ssoauth.py  a| 
Ein Beispiel-Python-Skript, mit dem Sie sich bei aktivierter Single-Sign-On-Funktion bei der Grid-Management-API anmelden können. Sie können dieses Skript auch für die Ping Federate-Integration verwenden.



| ./debs/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript.



| ./debs/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei zur Verwendung mit dem `configure-storagegrid.py` Skript.



| ./Debs/Extras/ansible  a| 
Beispiel-Rolle und Playbook für Ansible zur Konfiguration von Ubuntu oder Debian-Hosts für die Implementierung von StorageGRID-Containern Die Rolle oder das Playbook können Sie nach Bedarf anpassen.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) mithilfe von Active Directory oder Ping Federate aktiviert ist.



| ./debs/storagegrid-ssoauth-Azure.js  a| 
Ein Hilfsskript, das vom zugehörigen Python-Skript aufgerufen `storagegrid-ssoauth-azure.py` wird, um SSO-Interaktionen mit Azure durchzuführen.



| ./debs/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie diese Schemas verwenden, um zu bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung für Upgrade-Kompatibilitätstests haben.

|===
. Wenn Sie ein VMware-System erweitern, wählen Sie die entsprechenden Dateien aus.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./vsphere/README  a| 
Eine Textdatei, die alle in der StorageGRID-Download-Datei enthaltenen Dateien beschreibt.



| ./vsphere/NLF000000.txt  a| 
Eine kostenlose Lizenz, die keinen Support-Anspruch auf das Produkt bietet.



| ./vsphere/NetApp-SG-Version-SHA.vmdk  a| 
Die Festplattendatei für Virtual Machines, die als Vorlage für die Erstellung von Grid-Node-Virtual Machines verwendet wird.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
Die Datei Open Virtualization Format template (`.ovf`) und Manifest file (`.mf`) zur Bereitstellung des primären Admin-Knotens.



| ./vsphere/vsphere-nicht-primäre-admin.ovf ./vsphere/vsphere-nicht-primäre-admin.mf  a| 
Die Vorlagendatei (`.ovf`) und die Manifestdatei (`.mf`) für die Bereitstellung von nicht-primären Admin-Knoten.



| ./vsphere/vsphere-Gateway.ovf ./vsphere/vsphere-Gateway.mf  a| 
Die Vorlagendatei (`.ovf`) und die Manifestdatei (`.mf`) für die Bereitstellung von Gateway-Knoten.



| ./vsphere/vsphere-Storage.ovf ./vsphere/vsphere-Storage.mf  a| 
Die Vorlagendatei (`.ovf`) und Manifest-Datei (`.mf`) für die Bereitstellung von virtuellen Machine-basierten Speicher-Nodes.



| Tool zur Implementierung von Skripten | Beschreibung 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Ein Bash Shell-Skript, das zur Automatisierung der Implementierung virtueller Grid-Nodes verwendet wird.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `deploy-vsphere-ovftool.sh` Skript.



| ./vsphere/configure-storagegrid.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration eines StorageGRID Systems.



| ./vsphere/configure-sga.py  a| 
Ein Python-Skript zur Automatisierung der Konfiguration von StorageGRID Appliances



| ./vsphere/storagegrid-ssoauth.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) aktiviert ist. Sie können dieses Skript auch für die Ping Federate-Integration verwenden.



| ./vsphere/configure-storagegrid.sample.json  a| 
Eine Beispielkonfigurationsdatei für die Verwendung mit dem `configure-storagegrid.py` Skript.



| ./vsphere/configure-storagegrid.blank.json  a| 
Eine leere Konfigurationsdatei zur Verwendung mit dem `configure-storagegrid.py` Skript.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Ein Beispiel für ein Python-Skript, mit dem Sie sich bei der Grid Management API anmelden können, wenn Single Sign-On (SSO) mithilfe von Active Directory oder Ping Federate aktiviert ist.



| ./vsphere/storagegrid-ssoauth-Azure.js  a| 
Ein Hilfsskript, das vom zugehörigen Python-Skript aufgerufen `storagegrid-ssoauth-azure.py` wird, um SSO-Interaktionen mit Azure durchzuführen.



| ./vsphere/Extras/API-Schemata  a| 
API-Schemata für StorageGRID:

*Hinweis*: Bevor Sie ein Upgrade durchführen, können Sie diese Schemas verwenden, um zu bestätigen, dass jeder Code, den Sie zur Verwendung von StorageGRID Management APIs geschrieben haben, mit der neuen StorageGRID-Version kompatibel ist, wenn Sie keine StorageGRID-Umgebung außerhalb der Produktionsumgebung für Upgrade-Kompatibilitätstests haben.

|===
. Wenn Sie ein Appliance-basiertes StorageGRID System erweitern, wählen Sie die entsprechenden Dateien aus.


[cols="1a,1a"]
|===
| Pfad und Dateiname | Beschreibung 


| ./Debs/storagegrid-webscale-images-version-SHA.deb  a| 
DEB-Paket zum Installieren der StorageGRID Node Images auf den Geräten.



| ./Debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5-Prüfsumme für die Datei `/debs/storagegridwebscale-
images-version-SHA.deb`.

|===

NOTE: Für die Installation der Appliance sind diese Dateien nur erforderlich, wenn Sie den Netzwerkverkehr vermeiden müssen. Die Appliance kann die erforderlichen Dateien vom primären Admin-Knoten herunterladen.



== Überprüfung der Hardware und des Netzwerks

Stellen Sie vor Beginn der Erweiterung Ihres StorageGRID-Systems Folgendes sicher:

* Die zur Unterstützung der neuen Grid-Nodes erforderliche Hardware oder der neue Standort wurde installiert und konfiguriert.
* Alle neuen Nodes verfügen über bidirektionale Kommunikationspfade zu allen vorhandenen und neuen Nodes (Voraussetzung für das Grid Network). Vergewissern Sie sich insbesondere, dass die folgenden TCP-Ports zwischen den neuen Nodes, die Sie in der Erweiterung hinzufügen, und dem primären Admin-Node geöffnet sind:
+
** 1055
** 7443
** 8011
** 10342


+
Siehe link:../network/internal-grid-node-communications.html["Interne Kommunikation mit Grid-Nodes"].

* Der primäre Admin-Knoten kann mit allen Erweiterungsservern kommunizieren, die das StorageGRID-System hosten sollen.
* Wenn einer der neuen Knoten eine Grid-Netzwerk-IP-Adresse in einem Subnetz hat, das zuvor nicht verwendet wurde, haben Sie bereits link:updating-subnets-for-grid-network.html["Das neue Subnetz wurde hinzugefügt"]die Liste Grid Network Subnetz. Andernfalls müssen Sie die Erweiterung abbrechen, das neue Subnetz hinzufügen und den Vorgang erneut starten.
* Sie verwenden keine Network Address Translation (NAT) im Grid-Netzwerk zwischen Grid-Knoten oder zwischen StorageGRID-Standorten. Wenn Sie private IPv4-Adressen für das Grid-Netzwerk verwenden, müssen diese Adressen von jedem Grid-Knoten an jedem Standort direkt routingfähig sein. Die Verwendung von NAT zur Brücke des Grid-Netzwerks über ein öffentliches Netzwerksegment wird nur unterstützt, wenn Sie eine Tunneling-Anwendung verwenden, die für alle Knoten im Netz transparent ist, was bedeutet, dass die Grid-Knoten keine Kenntnisse über öffentliche IP-Adressen benötigen.
+
Diese NAT-Einschränkung gilt für Grid-Knoten und Grid-Netzwerk. Sie können NAT je nach Bedarf zwischen externen Clients und Grid-Nodes verwenden, beispielsweise um eine öffentliche IP-Adresse für einen Gateway-Node bereitzustellen.


