---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active, StorageGRID 
summary: Nachdem ein Erweiterungsvorgang abgeschlossen ist, der neue Speicherknoten hinzugefügt hat, sollte das StorageGRID-System automatisch mit den neuen Speicherknoten beginnen. Sie müssen das StorageGRID-System verwenden, um sicherzustellen, dass der neue Speicherknoten aktiv ist. 
---
= Überprüfen Sie, ob die Speicherknoten nach einer StorageGRID Erweiterung aktiv sind.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem ein Erweiterungsvorgang abgeschlossen ist, der neue Speicherknoten hinzugefügt hat, sollte das StorageGRID-System automatisch mit den neuen Speicherknoten beginnen. Sie müssen das StorageGRID-System verwenden, um sicherzustellen, dass der neue Speicherknoten aktiv ist.

.Schritte
. Melden Sie sich mit einem beim Grid-Manager anlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
. Wählen Sie *Knoten* > *_Erweiterungsspeicherknoten_* > *Speicher*.
. Bewegen Sie den Cursor über die Grafik *verwendeter Speicher - Objektdaten*, um den Wert für *Used* anzuzeigen, der die Menge des gesamten nutzbaren Speicherplatzes ist, der für Objektdaten verwendet wurde.
. Vergewissern Sie sich, dass der Wert von *verwendet* erhöht wird, wenn Sie den Cursor nach rechts auf dem Diagramm bewegen.

