---
permalink: troubleshoot/searching-for-and-restoring-potentially-lost-objects.html 
sidebar: sidebar 
keywords: how to search lost object, how to restore lost object, how to find lost object 
summary: 'Es kann möglich sein, Objekte zu finden und wiederherzustellen, die eine Warnung * Objekt VERLOREN * und einen Legacy VERLOREN Objekte (VERLOREN) Alarm ausgelöst haben und die Sie als potenziell verloren identifiziert haben.' 
---
= Suche nach potenziell verlorenen Objekten und Wiederherstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es kann möglich sein, Objekte zu finden und wiederherzustellen, die eine Warnung * Objekt VERLOREN * und einen Legacy VERLOREN Objekte (VERLOREN) Alarm ausgelöst haben und die Sie als potenziell verloren identifiziert haben.

.Bevor Sie beginnen
* Sie haben die UUID eines verlorenen Objekts, wie in angegebenlink:../troubleshoot/investigating-lost-objects.html["Untersuchen Sie verlorene Objekte"].
* Sie haben die `Passwords.txt` Datei.


.Über diese Aufgabe
Im Anschluss an dieses Verfahren können Sie sich nach replizierten Kopien des verlorenen Objekts an einer anderen Stelle im Grid suchen. In den meisten Fällen wird das verlorene Objekt nicht gefunden. In einigen Fällen können Sie jedoch ein verlorenes repliziertes Objekt finden und wiederherstellen, wenn Sie umgehend Maßnahmen ergreifen.


CAUTION: Wenden Sie sich an den technischen Support, wenn Sie Hilfe bei diesem Verfahren benötigen.

.Schritte
. Suchen Sie in einem Admin-Knoten die Prüfprotokolle nach möglichen Objektspeichern:
+
.. Melden Sie sich beim Grid-Node an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@grid_node_IP`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
... Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`. Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.


.. [[substep-1b]]Wechseln Sie in das Verzeichnis, in dem sich die Überwachungsprotokolle befinden.
+
--
Das Verzeichnis der Überwachungsprotokolle und die entsprechenden Knoten hängen von den Einstellungen des Überwachungsziels ab.

[cols="1a,2a"]
|===
| Option | Ziel 


 a| 
Lokale Knoten (Standard)
 a| 
`/var/local/log/localaudit.log`



 a| 
Admin-Nodes/lokale Nodes
 a| 
*** Admin-Nodes (primär und nicht primär): `/var/local/audit/export/audit.log`
*** Alle Knoten: Die `/var/local/log/localaudit.log` Datei ist in der Regel leer oder fehlt in diesem Modus.




 a| 
Externer Syslog-Server
 a| 
`/var/local/log/localaudit.log`

|===
Geben Sie je nach den Einstellungen des Überwachungsziels Folgendes ein: `cd /var/local/log` Oder `/var/local/audit/export/`

Weitere Informationen finden Sie unter link:../monitor/configure-audit-messages.html#select-audit-information-destinations["Wählen Sie Ziele für Audit-Informationen aus"].

--
.. Verwenden Sie grep, um den  zu extrahieren link:../audit/object-ingest-transactions.html["Überwachungsmeldungen, die mit dem potenziell verlorenen Objekt verknüpft sind"]und an eine Ausgabedatei zu senden. Eingabe: `grep uuid-value audit_file_name > output_file_name`
+
Beispiel:

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_lost_object.txt
----
.. Verwenden Sie grep, um die Meldungen zum Lost Location (LLST) aus dieser Ausgabedatei zu extrahieren. Eingabe: `grep LLST output_file_name`
+
Beispiel:

+
[listing]
----
Admin: # grep LLST /var/local/tmp/messages_about_lost_objects.txt
----
+
Eine LLST-Überwachungsmeldung sieht wie in dieser Beispielnachricht aus.

+
[listing]
----
[AUDT:[NOID(UI32):12448208][CBIL(UI64):0x38186FE53E3C49A5]
[UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"][LTYP(FC32):CLDI]
[PCLD(CSTR):"/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA#3tN6"]
[TSRC(FC32):SYST][RSLT(FC32):NONE][AVER(UI32):10][ATIM(UI64):1581535134379225]
[ATYP(FC32):LLST][ANID(UI32):12448208][AMID(FC32):CLSM][ATID(UI64):7086871083190743409]]
----
.. Suchen Sie in der LLST-Meldung das Feld PCLD und das Feld NOID.
+
Falls vorhanden, ist der Wert von PCLD der vollständige Pfad auf der Festplatte zur fehlenden replizierten Objektkopie. Der Wert von NOID ist die Knoten-id des LDR, wo eine Kopie des Objekts gefunden werden kann.

+
Wenn Sie einen Speicherort für ein Objekt finden, kann das Objekt möglicherweise wiederhergestellt werden.

.. Suchen Sie den Storage Node, der dieser LDR-Node-ID zugeordnet ist. Wählen Sie im Grid Manager *SUPPORT* > *Tools* > *Grid-Topologie* aus. Wählen Sie dann *_Data Center_* > *_Storage Node_* > *LDR* aus.
+
Die Knoten-ID für den LDR-Dienst befindet sich in der Tabelle Node Information. Überprüfen Sie die Informationen für jeden Speicherknoten, bis Sie den gefunden haben, der dieses LDR hostet.



. Stellen Sie fest, ob das Objekt auf dem in der Meldung „Audit“ angegebenen Speicherknoten vorhanden ist:
+
.. Melden Sie sich beim Grid-Node an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@grid_node_IP`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
... Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
+
Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.



.. Stellen Sie fest, ob der Dateipfad für das Objekt vorhanden ist.
+
Verwenden Sie für den Dateipfad des Objekts den Wert von PCLD aus der LLST-Überwachungsmeldung.

+
Geben Sie beispielsweise Folgendes ein:

+
[listing]
----
ls '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+

NOTE: Schließen Sie den Pfad der Objektdatei immer in einzelne Anführungszeichen ein, um Sonderzeichen zu umgehen.

+
*** Wenn der Objektpfad nicht gefunden wird, geht das Objekt verloren und kann mit diesem Verfahren nicht wiederhergestellt werden. Wenden Sie sich an den technischen Support.
*** Wenn der Objektpfad gefunden wird, fahren Sie mit dem nächsten Schritt fort. Sie können versuchen, das gefundene Objekt wieder in StorageGRID wiederherzustellen.




. Wenn der Objektpfad gefunden wurde, versuchen Sie, das Objekt in StorageGRID wiederherzustellen:
+
.. Ändern Sie vom gleichen Speicherknoten aus die Eigentumsrechte an der Objektdatei, so dass sie von StorageGRID gemanagt werden kann. Eingabe: `chown ldr-user:bycast 'file_path_of_object'`
.. Telnet für localhost 1402 für den Zugriff auf die LDR-Konsole. Eingabe: `telnet 0 1402`
.. Eingabe: `cd /proc/STOR`
.. Eingabe: `Object_Found 'file_path_of_object'`
+
Geben Sie beispielsweise Folgendes ein:

+
[listing]
----
Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
Mit dem `Object_Found` Befehl wird das Raster über den Standort des Objekts informiert. Zudem werden die aktiven ILM-Richtlinien ausgelöst. Anhand dieser Richtlinien werden zusätzliche Kopien erstellt, die in jeder Richtlinie angegeben sind.

+

NOTE: Wenn der Speicher-Node, auf dem Sie das Objekt gefunden haben, offline ist, können Sie das Objekt auf jeden Online-Speicher-Node kopieren. Platzieren Sie das Objekt in einem beliebigen /var/local/rangedb-Verzeichnis des Online-Storage-Node. Geben Sie dann den `Object_Found` Befehl mit diesem Dateipfad zum Objekt aus.

+
*** Wenn das Objekt nicht wiederhergestellt werden kann, schlägt der `Object_Found` Befehl fehl. Wenden Sie sich an den technischen Support.
*** Wenn das Objekt erfolgreich in StorageGRID wiederhergestellt wurde, wird eine Erfolgsmeldung angezeigt. Beispiel:
+
[listing]
----
ade 12448208: /proc/STOR > Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'

ade 12448208: /proc/STOR > Object found succeeded.
First packet of file was valid. Extracted key: 38186FE53E3C49A5
Renamed '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6' to '/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila#3udu'
----
+
Fahren Sie mit dem nächsten Schritt fort.





. Wenn das Objekt erfolgreich in StorageGRID wiederhergestellt wurde, überprüfen Sie, ob die neuen Speicherorte erstellt wurden:
+
.. Melden Sie sich mit einem beim Grid-Manager anlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
.. Wählen Sie *ILM* > *Object Metadata Lookup*.
.. Geben Sie die UUID ein, und wählen Sie *Look Up*.
.. Überprüfen Sie die Metadaten, und überprüfen Sie die neuen Speicherorte.


. Durchsuchen Sie von einem Admin-Node aus die Prüfprotokolle für die ORLM-Überwachungsmeldung für dieses Objekt, um zu bestätigen, dass Information Lifecycle Management (ILM) Kopien nach Bedarf platziert hat.
+
.. Melden Sie sich beim Grid-Node an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@grid_node_IP`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`.
... Geben Sie den folgenden Befehl ein, um zu root zu wechseln: `su -`
... Geben Sie das in der Datei aufgeführte Passwort ein `Passwords.txt`. Wenn Sie als root angemeldet sind, wechselt die Eingabeaufforderung von `$` zu `#`.


.. Wechseln Sie in das Verzeichnis, in dem sich die Audit-Protokolle befinden. Siehe <<substep-1b,Teilschritt 1, b>> .
.. Verwenden Sie grep, um die mit dem Objekt verknüpften Überwachungsmeldungen in eine Ausgabedatei zu extrahieren. Eingabe: `grep uuid-value audit_file_name > output_file_name`
+
Beispiel:

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_restored_object.txt
----
.. Verwenden Sie grep, um die ORLM-Audit-Meldungen (Object Rules met) aus dieser Ausgabedatei zu extrahieren. Eingabe: `grep ORLM output_file_name`
+
Beispiel:

+
[listing]
----
Admin: # grep ORLM /var/local/tmp/messages_about_restored_object.txt
----
+
Eine ORLM-Überwachungsmeldung sieht wie in dieser Beispielnachricht aus.

+
[listing]
----
[AUDT:[CBID(UI64):0x38186FE53E3C49A5][RULE(CSTR):"Make 2 Copies"]
[STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[LOCS(CSTR):"**CLDI 12828634 2148730112**, CLDI 12745543 2147552014"]
[RSLT(FC32):SUCS][AVER(UI32):10][ATYP(FC32):ORLM][ATIM(UI64):1563398230669]
[ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
.. Suchen Sie das FELD LOKS in der Überwachungsmeldung.
+
Wenn vorhanden, ist der Wert von CLDI in LOCS die Node-ID und die Volume-ID, in der eine Objektkopie erstellt wurde. Diese Meldung zeigt, dass das ILM angewendet wurde und dass an zwei Standorten im Grid zwei Objektkopien erstellt wurden.



. link:resetting-lost-and-missing-object-counts.html["Setzt die Anzahl der verlorenen und fehlenden Objekte zurück"] Im Grid-Manager.

