---
permalink: ilm/enabling-s3-object-lock.html 
sidebar: sidebar 
keywords: enable s3 object lock, object lock 
summary: Falls ein S3-Mandantenkonto Vorschriften beim Speichern von Objektdaten einhalten muss, muss die S3-Objektsperre für Ihr gesamtes StorageGRID System aktiviert werden. Wenn Sie die globale S3-Objektsperre aktivieren, können alle S3-Mandantenbenutzer Buckets und Objekte mit S3 Object Lock erstellen und verwalten. 
---
= S3 Object Lock in StorageGRID aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls ein S3-Mandantenkonto Vorschriften beim Speichern von Objektdaten einhalten muss, muss die S3-Objektsperre für Ihr gesamtes StorageGRID System aktiviert werden. Wenn Sie die globale S3-Objektsperre aktivieren, können alle S3-Mandantenbenutzer Buckets und Objekte mit S3 Object Lock erstellen und verwalten.

.Bevor Sie beginnen
* Sie haben die link:../admin/admin-group-permissions.html["Root-Zugriffsberechtigung"].
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben den S3-Objektsperrworkflow überprüft und die Überlegungen verstanden.
* Sie haben bestätigt, dass die Standardregel in der aktiven ILM-Richtlinie konform ist. Weitere Informationen finden Sie unter link:creating-default-ilm-rule.html["Erstellen einer Standard-ILM-Regel"].


.Über diese Aufgabe
Ein Grid-Administrator muss die globale S3-Objektsperre aktivieren, damit Mandantenbenutzer neue Buckets erstellen können, für die S3-Objektsperre aktiviert ist. Nachdem diese Einstellung aktiviert ist, kann sie nicht deaktiviert werden.

Nach der Aktivierung der S3 Object Lock kann ein Grid-Administrator Mandantenbenutzern auch die Möglichkeit geben, die S3 Object Lock für einen bestehenden Bucket zu aktivieren. Nachdem ein Grid-Administrator diese Einstellung aktiviert hat, kann sie wieder deaktiviert werden. Weitere Informationen finden sich unter link:requirements-for-s3-object-lock.html#s3-object-lock-existing-buckets["Anforderungen an die S3-Objektsperre"].

Überprüfen Sie die Compliance-Einstellungen vorhandener Mandanten, nachdem Sie die globale S3 Object Lock-Einstellung aktiviert haben. Wenn Sie diese Einstellung aktivieren, hängen die Einstellungen für die S3-Objektsperrung pro Mandant vom StorageGRID-Release zum Zeitpunkt der Erstellung des Mandanten ab.


NOTE: Die globale Compliance-Einstellung ist veraltet. Wenn diese Einstellung in einer früheren Version von StorageGRID aktiviert wurde, wird die S3 Object Lock-Einstellung automatisch aktiviert. Die Verwaltung der Einstellungen bestehender konformer Buckets mit StorageGRID ist weiterhin möglich, das Erstellen neuer konformer Buckets jedoch nicht. Weitere Informationen finden sich unter  https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp Knowledge Base: Management älterer, konformer Buckets für StorageGRID 11.5"^].

.Schritte
. Wählen Sie *Konfiguration* > *System* > *S3-Objektsperre*.
+
Die Seite Einstellungen für die S3-Objektsperre wird angezeigt.

. *S3-Objektsperre aktivieren* auswählen, um die S3-Objektsperre für das gesamte StorageGRID System zu aktivieren.
. Optional kann *S3 Object Lock für bestehende Buckets aktiviert werden* ausgewählt werden.
+

CAUTION: Die Aktivierung der S3 Object Lock-Funktion für einen bestehenden Bucket kann abhängig von Ihren ILM-Regeln eine unbeabsichtigte Datenmigration von einem Cloud Storage Pool zurück zu StorageGRID verursachen. Diese Migration kann nach ihrem Start nicht mehr gestoppt werden. Weitere Informationen finden sich unter link:requirements-for-s3-object-lock.html#s3-object-lock-existing-buckets["Anforderungen an die S3-Objektsperre"].

. Wählen Sie *Anwenden*.
+
Ein Bestätigungsdialogfeld wird angezeigt, in dem Sie daran erinnert werden, dass Sie die S3-Objektsperre nicht deaktivieren können, nachdem sie aktiviert wurde.

. Wenn Sie sicher sind, dass Sie die S3-Objektsperre für Ihr gesamtes System dauerhaft aktivieren möchten, wählen Sie *OK*.
+
Wenn Sie *OK* wählen:

+
** Wenn die Standardregel in der aktiven ILM-Richtlinie konform ist, ist S3 Object Lock jetzt für das gesamte Grid aktiviert und kann nicht deaktiviert werden.
** Wenn die Standardregel nicht konform ist, wird ein Fehler angezeigt. Es ist erforderlich, eine neue ILM-Richtlinie zu erstellen und zu aktivieren, die eine konforme Regel als Standardregel enthält. *OK* auswählen. Anschließend eine neue Richtlinie erstellen, sie simulieren und aktivieren. Weitere Anweisungen sind unter link:creating-ilm-policy.html["ILM-Richtlinie erstellen"] zu finden.



