---
permalink: ilm/example-9-delete-noncurrent-versions-and-expired-delete-markers.html 
sidebar: sidebar 
keywords: retention priority, example S3 bucket lifecycle, example ILM policy 
summary: Je nach Lifecycle-Konfiguration folgen Objekte den Aufbewahrungseinstellungen entweder des S3 Bucket-Lebenszyklus oder einer ILM-Richtlinie. 
---
= Nicht mehr aktuelle Versionen und abgelaufene Löschmarkierungen in StorageGRID löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die Versionierung eines Buckets ausgesetzt wird, muss der Bucket-Lebenszyklus so konfiguriert werden, dass nicht aktuelle Versionen und abgelaufene Löschmarkierungen mit Nullversion verarbeitet werden.

Beispiel einer Bucket Lifecycle-Konfiguration, die nicht aktuelle Versionen und abgelaufene Löschmarkierungen verarbeitet:: Diese Schritte werden für einen Bucket mit einer aktiven ILM-Richtlinie durchgeführt:
+
--
. Versionierung aktivieren. Wenn Objekte mit demselben Namen aufgenommen werden, bleiben frühere Versionen als nicht aktuelle Versionen verfügbar und Löschanforderungen erzeugen Löschmarkierungen. Nicht aktuelle Versionen sind zugänglich, belegen jedoch Speicherplatz.
. Die Versionsverwaltung wird ausgesetzt, da die gewünschte Konfiguration darin besteht, nur eine Version beizubehalten und den von nicht aktuellen Versionen belegten Speicherplatz freizugeben. Dies wird im nächsten Schritt konfiguriert.
. Ein Bucket-Lebenszyklus kann so konfiguriert werden, dass nicht aktuelle Versionen und Löschmarkierungen verarbeitet werden, die nach der Aussetzung der Versionierung verbleiben.


--
ILM-Richtlinie::
+
--
Regel basierend auf Referenz zur Aufnahmezeit (Standard): An Tag 0, X Kopien für immer aufbewahren

--
Bucket-Lebenszyklus::
+
--
`"Filter": {}, "Expiration": {"ExpiredObjectDeleteMarker": true}, "NoncurrentVersionExpiration": {"NoncurrentDays": 1}`

--
Ergebnis:: Der Bucket-Lebenszyklus ist so konfiguriert, dass nicht aktuelle Versionen und abgelaufene Löschmarkierungen verarbeitet werden:
+
--
. Versionen, die länger als einen Tag nicht mehr aktuell sind, werden gelöscht. Nur die aktuelle Version bleibt dauerhaft erhalten.
. Ein Objekt mit dem Namen  `draftdoc` wird aufgenommen und hat die Versions-ID  `NULL`.
. Wenn ein anderes Objekt mit demselben Namen (`draftdoc`) eingelesen wird, wird die Null-Version überschrieben und ersetzt und die vorherige Version sofort gelöscht.
. Wenn eine Löschanforderung an `draftdoc` gestellt wird, ohne eine Versions-ID anzugeben, wird ein Löschmarker mit Nullversion erstellt, der das Objekt mit der Nullversion ersetzt und löscht.
. Der null-versionierte Löschmarker ist abgelaufen, da keine nicht aktuellen Versionen vorhanden sind.
. Kurz darauf wird der abgelaufene Löschmarker mit Null-Version gelöscht.


--

