---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: Sie können die Uhrzeit des letzten Zugriffs als Referenzzeit in einer ILM-Regel verwenden. Sie möchten beispielsweise Objekte, die in den letzten drei Monaten auf lokalen Speicherknoten angezeigt wurden, während Sie Objekte verschieben, die noch nicht in letzter Zeit an einen externen Standort betrachtet wurden. Sie können die Uhrzeit des letzten Zugriffs auch als erweiterten Filter verwenden, wenn eine ILM-Regel nur auf Objekte angewendet werden soll, auf die an einem bestimmten Datum zuletzt zugegriffen wurde. 
---
= Verwenden Sie die letzte Zugriffszeit in ILM-Regeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Uhrzeit des letzten Zugriffs als Referenzzeit in einer ILM-Regel verwenden. Sie möchten beispielsweise Objekte, die in den letzten drei Monaten auf lokalen Speicherknoten angezeigt wurden, während Sie Objekte verschieben, die noch nicht in letzter Zeit an einen externen Standort betrachtet wurden. Sie können die Uhrzeit des letzten Zugriffs auch als erweiterten Filter verwenden, wenn eine ILM-Regel nur auf Objekte angewendet werden soll, auf die an einem bestimmten Datum zuletzt zugegriffen wurde.

.Über diese Aufgabe
Bevor Sie die letzte Zugriffszeit in einer ILM-Regel verwenden, sollten Sie die folgenden Überlegungen durchgehen:

* Wenn Sie die Uhrzeit des letzten Zugriffs als Referenzzeit verwenden, beachten Sie, dass die Änderung der Uhrzeit des letzten Zugriffs für ein Objekt keine sofortige ILM-Bewertung auslöst. Stattdessen werden die Platzierungen des Objekts bewertet und das Objekt nach Bedarf verschoben, wenn im Hintergrund ILM das Objekt bewertet wird. Dies kann zwei Wochen oder länger dauern, nachdem auf das Objekt zugegriffen wurde.
+
Berücksichtigen Sie diese Latenz bei der Erstellung von ILM-Regeln auf der Grundlage der letzten Zugriffszeit und vermeiden Sie Platzierungen, die kurze Zeiträume (weniger als einen Monat) verwenden.

* Wenn Sie die letzte Zugriffszeit als erweiterten Filter oder als Referenzzeit verwenden, müssen Sie die Updates der letzten Zugriffszeit für S3-Buckets aktivieren. Sie können die  oder die verwendenlink:../tenant/enabling-or-disabling-last-access-time-updates.html["Mandanten-Manager"]link:../s3/put-bucket-last-access-time-request.html["Mandantenmanagement-API"].
+

NOTE: Updates der Uhrzeit des letzten Zugriffs sind für S3 Buckets standardmäßig deaktiviert.

+

NOTE: Beachten Sie, dass eine Aktualisierung der letzten Zugriffszeit die Performance beeinträchtigen kann, insbesondere bei Systemen mit kleinen Objekten. Die Auswirkungen auf die Performance werden dadurch erzielt, dass StorageGRID die Objekte bei jedem Abruf mit neuen Zeitstempel aktualisieren muss.



In der folgenden Tabelle wird zusammengefasst, ob die Uhrzeit des letzten Zugriffs für alle Objekte im Bucket für verschiedene Arten von Anforderungen aktualisiert wird.

[cols="1a,1a,1a"]
|===
| Art der Anfrage | Gibt an, ob die letzte Zugriffszeit aktualisiert wird, wenn die Updates der letzten Zugriffszeit deaktiviert sind | Gibt an, ob die letzte Zugriffszeit aktualisiert wird, wenn die Updates der letzten Zugriffszeit aktiviert sind 


 a| 
Anforderung zum Abrufen eines Objekts, seiner Zugriffssteuerungsliste oder seiner Metadaten
 a| 
Nein
 a| 
Ja.



 a| 
Anforderung zum Aktualisieren der Metadaten eines Objekts
 a| 
Ja.
 a| 
Ja.



 a| 
Anforderung zum Kopieren eines Objekts von einem Bucket in einen anderen
 a| 
* Nein, für die Quellkopie
* Ja, für die Zielkopie

 a| 
* Ja, für die Quellkopie
* Ja, für die Zielkopie




 a| 
Anforderung zum Abschließen eines mehrteiligen Uploads
 a| 
Ja, für das zusammengesetzte Objekt
 a| 
Ja, für das zusammengesetzte Objekt

|===