---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: Ein Cloud Storage Pool ermöglicht die Nutzung von ILM, um Objektdaten außerhalb Ihres StorageGRID Systems zu verschieben. Beispielsweise kann es sinnvoll sein, selten genutzte Objekte in kostengünstigeren Cloud Storage wie Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud oder die Archive-Zugriffsebene in Microsoft Azure Blob Storage zu verschieben. Ebenso kann eine Cloud-Sicherung der StorageGRID Objekte zur Verbesserung der Disaster Recovery erhalten bleiben. 
---
= Erfahren Sie mehr über Cloud Storage Pools in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Cloud Storage Pool ermöglicht die Nutzung von ILM, um Objektdaten außerhalb Ihres StorageGRID Systems zu verschieben. Beispielsweise kann es sinnvoll sein, selten genutzte Objekte in kostengünstigeren Cloud Storage wie Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud oder die Archive-Zugriffsebene in Microsoft Azure Blob Storage zu verschieben. Ebenso kann eine Cloud-Sicherung der StorageGRID Objekte zur Verbesserung der Disaster Recovery erhalten bleiben.

Aus ILM-Sicht ähnelt ein Cloud-Speicherpool einem Speicherpool. Zum Speichern von Objekten an einem der beiden Speicherorte wird der Pool beim Erstellen der Platzierungsanweisungen für eine ILM-Regel ausgewählt. Während Speicherpools jedoch aus Storage Nodes innerhalb des StorageGRID Systems bestehen, besteht ein Cloud-Speicherpool aus einem externen Bucket (S3) oder Container (Azure Blob Storage).

Die Tabelle vergleicht Speicherpools mit Cloud-Speicherpools und zeigt die grundlegenden Ähnlichkeiten und Unterschiede.

[cols="1a,2a,5a"]
|===
|  | Storage-Pool | Cloud-Storage-Pool 


 a| 
Wie wird sie erstellt?
 a| 
Verwenden der Option *ILM* > *Storage Pools* im Grid Manager.
 a| 
Verwenden der Option *ILM* > *Speicherpools* > *Cloud-Speicherpools* im Grid Manager.

Sie müssen den externen Bucket oder Container einrichten, bevor Sie den Cloud Storage-Pool erstellen können.



 a| 
Wie viele Pools können Sie erstellen?
 a| 
Unbegrenzt.
 a| 
Bis zu 10.



 a| 
Wo werden Objekte gespeichert?
 a| 
Auf einem oder mehreren Storage-Nodes innerhalb von StorageGRID.
 a| 
In einem Amazon S3 Bucket, einem Azure Blob Storage Container oder einer Google Cloud, die sich außerhalb des StorageGRID Systems befindet.

Wenn der Cloud Storage Pool ein Amazon S3-Bucket ist:

* Optional kann ein Bucket-Lebenszyklus konfiguriert werden, um Objekte auf kostengünstigen Langzeit-Storage wie Amazon S3 Glacier oder S3 Glacier Deep Archive zu verschieben. Das externe Speichersystem muss die Glacier Storage-Klasse und die S3 RestoreObject API unterstützen.
* Sie können Cloud-Storage-Pools zur Verwendung mit AWS Commercial Cloud Services (C2S) erstellen, die die AWS Secret Region unterstützen.


Wenn es sich bei dem Cloud Storage Pool um einen Azure Blob Storage Container handelt, verschiebt StorageGRID das Objekt in die Archivschicht.

*Hinweis:* Im Allgemeinen sollte die Azure Blob Storage Lebenszyklusverwaltung nicht für den Container konfiguriert werden, der für einen Cloud Storage Pool verwendet wird. RestoreObject-Vorgänge an Objekten im Cloud Storage Pool können durch den konfigurierten Lebenszyklus beeinträchtigt werden.



 a| 
Welche Kontrollen steuern die Objektplatzierung?
 a| 
Eine ILM-Regel in den aktiven ILM-Richtlinien.
 a| 
Eine ILM-Regel in den aktiven ILM-Richtlinien.



 a| 
Welche Datenschutzmethode wird verwendet?
 a| 
Replizierung oder Erasure Coding:
 a| 
Replizierung:



 a| 
Wie viele Kopien jedes Objekts sind erlaubt?
 a| 
Mehrere:
 a| 
Eine Kopie im Cloud-Storage-Pool und optional eine oder mehrere Kopien in StorageGRID.

*Hinweis:* ein Objekt kann zu keinem Zeitpunkt in mehr als einem Cloud-Speicherpool gespeichert werden.



 a| 
Worin liegen die Vorteile?
 a| 
Objekte sind jederzeit schnell abrufbar.
 a| 
Kostengünstiger Storage:

*Hinweis*: FabricPool-Daten können nicht in Cloud-Speicherpools verschoben werden.

|===