---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Ein Speicherpool ist eine logische Gruppierung von Storage-Nodes. 
---
= Was ist ein Speicherpool?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Speicherpool ist eine logische Gruppierung von Storage-Nodes.

Bei der Installation von StorageGRID wird automatisch ein Speicherpool pro Standort erstellt. Sie können zusätzliche Speicherpools je nach Bedarf konfigurieren.


NOTE: Speicherknoten können während der Installation so konfiguriert werden, dass sie Objektdaten und Metadaten („kombinierter“ Speicherknoten), nur Objektmetadaten oder nur Objektdaten enthalten.  Nur-Metadaten-Speicherknoten können nicht in Speicherpools verwendet werden. Weitere Informationen finden Sie unter link:../primer/what-storage-node-is.html#types-of-storage-nodes["Typen von Storage-Nodes"] .

Storage-Pools haben zwei Attribute:

* *Speicherklasse*: Für Storage-Nodes, die relative Performance beim Sichern von Speicher.
* *Standort*: Das Rechenzentrum, in dem Objekte gespeichert werden.


Storage-Pools werden in ILM-Regeln verwendet, um zu bestimmen, wo Objektdaten gespeichert werden und welcher Storage-Typ verwendet wird. Wenn Sie ILM-Regeln für die Replikation konfigurieren, wählen Sie einen oder mehrere Speicherpools aus.
