---
permalink: release-notes/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.1 verwendet Version 4 der Grid Management API. Version 4 ersetzt Version 3. Die Versionen 1, 2 und 3 werden jedoch weiterhin unterstützt. 
---
= Änderungen an der Grid Management API in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 verwendet Version 4 der Grid Management API. Version 4 setzt Version 3 außer Kraft, jedoch werden die Versionen 1, 2 und 3 weiterhin unterstützt.


NOTE: Sie können veraltete Versionen der Management-API weiterhin mit StorageGRID verwenden, jedoch wird die Unterstützung für diese Versionen der API in einer zukünftigen Version von StorageGRID entfernt. Nach dem Upgrade auf StorageGRID 12.0 oder höher kann die Deaktivierung der veralteten APIs mithilfe der  `PUT /grid/config/management` API erfolgen.

Weitere Informationen finden Sie unter link:../admin/using-grid-management-api.html["Verwenden Sie die Grid-Management-API"].



[[new-endpoints-for-changing-the-bmc-password-and-lan-ip-settings]]
== Neue Endpunkte zum Ändern des BMC Passworts und der LAN IP-Einstellungen

Der folgende Endpunkt wurde hinzugefügt, um Ihnen zu ermöglichen, link:../harden/hardening-guidelines-for-storagegrid-nodes.html#change-appliance-bmc-password["Ändern eines Appliance BMC Passworts"].

`PUT /bmc-configuration/root-password`

Die folgenden Endpunkte wurden hinzugefügt, damit Sie link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["Ändern oder Anzeigen der BMC LAN IP Einstellungen"] können.

`PUT /grid/bmc/{node-id}/lan-ip-config`

`GET /grid/bmc/{node-id}/lan-ip-config`
