---
permalink: release-notes/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 12.1 verwendet Version 4 der Tenant Management API. Version 4 ersetzt Version 3. Die Versionen 1, 2 und 3 werden jedoch weiterhin unterstützt. 
---
= Änderungen an der Tenant Management API in StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 verwendet Version 4 der Tenant Management API. Version 4 ersetzt Version 3, jedoch werden die Versionen 1, 2 und 3 weiterhin unterstützt.


NOTE: Sie können veraltete Versionen der Tenant Management API weiterhin mit StorageGRID verwenden, jedoch wird die Unterstützung für diese API-Versionen in einer zukünftigen Version von StorageGRID entfernt. Nach dem Upgrade auf StorageGRID 12.0 oder höher können die veralteten APIs mithilfe der  `PUT /grid/config/management` API deaktiviert werden.

Weitere Informationen finden Sie unter link:../tenant/understanding-tenant-management-api.html["Mandantenmanagement-API verstehen"].



[[new-api-for-object-replication]]
== Neue API für die Objektreplikation

Sie können die `/org/cross-grid-replication/{versionId}/replicate` API zum manuellen Replizieren von Objekten in einem vorhandenen Bucket, für den die Cross-Grid-Replikation neu konfiguriert wurde.
