---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.1 
summary: Diese Version von StorageGRID enthält die folgenden Funktionen und funktionalen Änderungen. 
---
= Neues in StorageGRID 12.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 führt die folgenden Funktionen und funktionalen Änderungen ein.

Einzelheiten zu behobenen und bekannten Problemen in den aktuellen StorageGRID 12.1-Versionen finden Sie in den  https://library.netapp.com/ecm/ecm_download_file/ECMLP3373065["StorageGRID 12.1 Versionshinweise"^]. Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.



[[capacity]]
== Kapazität



[[ec-rebalance-now-uses-free-space]]
=== EC Rebalancing verwendet jetzt freien Speicherplatz

EC-Rebalancing verwendet nun freien Speicherplatz anstelle von belegtem Speicherplatz. Siehe link:../expand/considerations-for-rebalancing-erasure-coded-data.html#what-is-ec-rebalancing["Erfahren Sie mehr über EC-Rebalancing nach der Erweiterung in StorageGRID."].



[[metadata-allowed-space]]
=== Für Metadaten erlaubter Speicherplatz

Sie können den maximal zulässigen Metadatenwert nun von 3,96 TB auf 7,92 TB erhöhen. Weitere Informationen finden Sie unter link:../admin/managing-object-metadata-storage.html#allowed-metadata-space["Zulässiger Metadatenspeicherplatz"].



[[control-access]]
== Zugriff steuern



[[sso-using-oidc]]
=== SSO mit OIDC

Sie können jetzt link:../admin/learn-about-setting-up-sso-oidc.html["Single Sign-On (SSO) in StorageGRID mit OpenID Connect (OIDC) einrichten"].



[[federation]]
== Föderation



[[global-namespace]]
=== Globaler Namensraum

Sie können nun einen globalen Namensraum einrichten, um Mandanten den Zugriff auf Buckets über mehrere StorageGRID Systeme hinweg zu ermöglichen. Siehe link:../admin/learn-about-global-namespace.html["Informationen zum globalen Namensraum"].



[[manageability]]
== Verwaltbarkeit



[[auto-move-adc-service]]
=== Auto-Move ADC Service

link:../maintain/understanding-adc-service-quorum.html["Wenn dies erforderlich ist, um das ADC Quorum zu erreichen"], der ADC-Dienst wird nun automatisch verschoben, wenn Sie link:../maintain/convert-to-data-only-node.html["Umwandlung eines Storage Node in einen reinen Datenknoten"] oder link:../maintain/considerations-for-decommissioning-storage-nodes.html["Außerbetriebnahme eines Storage Node"].



[[primary-admin-node-recovery]]
=== Wiederherstellung des primären Administratorknotens

Sie können nun jeden Knoten von einem nicht-primären Admin Node wiederherstellen. Weitere Informationen finden Sie unter link:../maintain/recovering-from-primary-admin-node-failures.html["Wiederherstellung nach Ausfällen des primären Admin Node"].



[[s3]]
== S3



[[enable-s3-object-lock-on-existing-buckets]]
=== S3 Object Lock für bestehende Buckets aktivieren

Wenn die Einstellung „S3 Object Lock für bestehende Buckets zulassen“ aktiviert ist, kann ein S3-Mandantenkonto S3 Object Lock für einen bestehenden Bucket aktivieren. Nachdem ein S3-Mandantenkonto S3 Object Lock für einen bestehenden Bucket aktiviert hat, kann diese Einstellung nicht mehr deaktiviert werden.



[[replication-allowed-for-s3-object-lock-enabled-buckets]]
=== Replikation für S3 Object Lock-aktivierte Buckets zulässig

Sie können nun CloudMirror verwenden, um Objekte in S3 Object Lock-aktivierten Buckets zu replizieren. Siehe link:../tenant/considerations-for-platform-services.html["Informationen zu Plattformdiensten"].



[[enable-cross-grid-replication-for-non-empty-buckets]]
=== Gridübergreifende Replikation für nicht leere Buckets aktivieren

Sie können nun die netzübergreifende Replikation für Buckets, die nicht leer sind, aktivieren. Siehe link:../admin/grid-federation-what-is-cross-grid-replication.html#requirements-for-cross-grid-replication["Anforderungen für die Grid-übergreifende Replizierung"].



[[s3-batch-operations-fpvr-only]]
=== S3 Batch operations (nur FPVR)

Sie können S3-Batch-Operationen verwenden, um vorhandene Objekte in einem versioning-fähigen Bucket zu replizieren, den Sie für die Cross-Grid-Replikation konfigurieren möchten.

Diese Funktion erfordert die FPVR-Genehmigung für StorageGRID 12.1. Für die Nutzung dieser Funktion ist die Kontaktaufnahme mit Ihrem Kundenbetreuer erforderlich.



[[non-functional-s3-rest-api-headers]]
=== Nicht-funktionale S3 REST API Header

Die  `If-Match` und  `If-None-Match` Header werden zwar akzeptiert, sind aber für die S3 REST API link:../s3/put-object.html["PutObject"], link:../s3/complete-multipart-upload.html["CompleteMultipartUpload"], link:../s3/put-object-copy.html["CopyObject"] und link:../s3/operations-on-objects.html["DeleteObject"] nicht funktionsfähig.

Weitere Informationen sind unter link:../release-notes/changes-to-s3-rest-api.html["Änderungen an StorageGRID S3 REST API Unterstützung"] zu finden.



[[support-for-pre-calculated-checksum-values]]
=== Unterstützung für vorab berechnete Prüfsummenwerte

Die S3 REST SPI bietet jetzt Unterstützung für vorab berechnete Prüfsummenwerte und den  `x-amz-checksum-type`-Anforderungsheader. Siehe link:../s3/index.html#updates-to-rest-api-support["Aktualisierungen der REST API-Unterstützung"].



[[security]]
== Sicherheit



[[multi-admin-verification]]
=== Multi-Admin-Verifizierung

Die Multi-Admin-Verifizierung (MAV) hilft, versehentliche oder unautorisierte Änderungen an Ihrem StorageGRID System zu verhindern. Siehe link:../admin/about-multi-admin-verify.html["Informationen zur Multi-Admin-Verifizierung von StorageGRID"].



[[security-policy-updates-for-fips]]
=== Aktualisierungen der Sicherheitsrichtlinien für FIPS

Die strengen Richtlinienkriterien von FIPS wurden aktualisiert. Siehe link:../admin/manage-tls-ssh-policy.html#select-a-security-policy["Eine Sicherheitsrichtlinie in „TLS- und SSH-Richtlinie verwalten“ auswählen"].



[[tenants]]
== Mandanten



[[account-sync]]
=== Kontosynchronisierung

Die Funktion _Konto klonen_ bezieht sich nun auf eine einmalige Kopie bestimmter Mandantenkontoinformationen.

_Kontosynchronisierung_ ist eine neue Funktion, die es ermöglicht, Mandantenkonten, Mandantengruppen, Mandantenbenutzer und S3-Zugriffsschlüssel automatisch und kontinuierlich zwischen den StorageGRID Systemen in einer oder mehreren Grid Federation-Verbindungen zu replizieren. Siehe link:../admin/grid-federation-what-is-account-sync.html["Informationen zur Kontosynchronisierung in StorageGRID"].



[[kafka-endpoints-and-mtls-authentication]]
=== Kafka Endpunkte und mTLS-Authentifizierung

Mutual Transport Layer Security (mTLS) wird jetzt für Kafka-Endpunkte unterstützt. Siehe link:../tenant/configuring-platform-services-endpoints.html["Plattform-Services-Endpunkte konfigurieren"].



[[maximum-number-of-buckets]]
=== Maximale Anzahl an Buckets

Ein StorageGRID System unterstützt jetzt maximal 20.000 Buckets für jedes S3-Mandantenkonto.



[[upgrade]]
== Upgrade



[[time-to-enable-features-is-increased]]
=== Die Zeit zum Aktivieren von Funktionen ist erhöht

Während des StorageGRID Upgrades auf Version 12.1 hat sich die Zeit zum Aktivieren von Funktionen von unter fünf Minuten auf eine Stunde erhöht. Siehe link:../upgrade/estimating-time-to-complete-upgrade.html#estimate-time-to-upgrade["Schätzen Sie die Zeit für die Durchführung eines StorageGRID Upgrades"].



[[user-interface]]
== Benutzeroberfläche



[[bmc-settings-page]]
=== BMC-Einstellungsseite

Eine neue Registerkarte „BMC Settings“ wurde auf der Seite „Nodes“ im Grid Manager hinzugefügt, um das Zurücksetzen des BMC-Passworts und Änderungen an den BMC-LAN-IP-Einstellungen zu ermöglichen. Siehe link:../harden/hardening-guidelines-for-storagegrid-nodes.html["BMC-Passwort des Geräts ändern"] und link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["BMC LAN-IP-Einstellungen des Appliance-Knotens ändern"]. Neue API-Endpunkte wurden ebenfalls hinzugefügt, um diese Funktionen zu unterstützen. Siehe link:../release-notes/changes-to-grid-management-api.html["Neue Endpunkte zum Ändern des BMC Passworts und der LAN IP-Einstellungen"].



[[email-notifications]]
=== E-Mail-Benachrichtigungen

Der Grid Manager verfügt nun über eine gemeinsame E-Mail-Seite zur Konfiguration und Verwaltung von E-Mail-Benachrichtigungen für Warnmeldungen, AutoSupport und Multi-Admin-Verifizierung (MAV). Siehe link:../monitor/configure-email-server.html["E-Mail-Server konfigurieren"].



[[link-cost-page-update]]
=== Aktualisierung der Link cost Seite

StorageGRID 12.1 bietet detailliertere Informationen und Einstellungen zu den Verbindungskosten. Siehe link:../admin/manage-link-costs.html["Verwalten Sie Verbindungskosten"].



[[usb-port-control]]
=== USB-Port-Steuerung

Sie können jetzt USB-Anschlüsse über den Grid Manager aktivieren oder deaktivieren. Siehe link:../harden/hardening-guidelines-for-storagegrid-nodes.html#control-remote-access-through-usb-ports["Remotezugriff über USB-Ports kontrollieren"].
