---
permalink: fabricpool/creating-load-balancer-endpoint-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, create, creating, certificate 
summary: StorageGRID verwendet einen Load Balancer zum Managen des Workloads von Client-Applikationen wie FabricPool. Load Balancing maximiert Geschwindigkeit und Verbindungskapazität über mehrere Storage Nodes hinweg. 
---
= Erstellen eines Load Balancer-Endpunkts für FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID verwendet einen Load Balancer zum Managen des Workloads von Client-Applikationen wie FabricPool. Load Balancing maximiert Geschwindigkeit und Verbindungskapazität über mehrere Storage Nodes hinweg.

Wenn Sie StorageGRID für die Verwendung mit FabricPool konfigurieren, müssen Sie einen Load Balancer-Endpunkt konfigurieren und ein Load Balancer-Endpunktzertifikat hochladen oder generieren, das zum Sichern der Verbindung zwischen ONTAP und StorageGRID verwendet wird.

Um diese Aufgabe mithilfe des FabricPool-Setup-Assistenten abzuschließen, gehen Sie zu link:use-fabricpool-setup-wizard-steps.html["Öffnen und Abschließen des FabricPool Setup-Assistenten"].

.Bevor Sie beginnen
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:../admin/admin-group-permissions.html["Root-Zugriffsberechtigung"].
* Sie haben die allgemeinen link:../admin/managing-load-balancing.html["Überlegungen zum Lastausgleich"]sowie die link:best-practices-for-load-balancing.html["Best Practices für Lastausgleich für FabricPool"].


.Schritte
. Wählen Sie *Konfiguration* > *Netzwerk* > *Load Balancer-Endpunkte*.
. Wählen Sie *Erstellen*.
. Füllen Sie für den Schritt *Enter Endpoint Details* die folgenden Felder aus.
+
[cols="1a,2a"]
|===
| Feld | Beschreibung 


 a| 
Name
 a| 
Ein beschreibender Name für den Endpunkt.



 a| 
Port
 a| 
Der StorageGRID-Port, den Sie für den Lastausgleich verwenden möchten. Dieses Feld ist für den ersten erstellten Endpunkt standardmäßig auf 10433 eingestellt, Sie können jedoch jeden nicht verwendeten externen Port eingeben. Wenn Sie 80 oder 443 eingeben, wird der Endpunkt nur auf Gateway-Nodes konfiguriert. Diese Ports sind für Admin-Nodes reserviert.

*Hinweis:* von anderen Netzdiensten verwendete Ports sind nicht erlaubt. Siehe link:../network/internal-grid-node-communications.html["Referenz für Netzwerk-Ports"].

Sie geben diese Nummer an ONTAP an, wenn Sie StorageGRID als FabricPool-Cloud-Tier hinzufügen.



 a| 
Client-Typ
 a| 
Wählen Sie *S3*.



 a| 
Netzwerkprotokoll
 a| 
Wählen Sie *HTTPS*.

*Hinweis*: Die Kommunikation mit StorageGRID ohne TLS-Verschlüsselung wird unterstützt, aber nicht empfohlen.

|===
. Geben Sie für den Schritt *Bindungsmodus auswählen* den Bindungsmodus an. Der Bindungsmodus steuert, wie der Zugriff auf den Endpunkt über eine beliebige IP-Adresse oder über spezifische IP-Adressen und Netzwerkschnittstellen erfolgt.
+
[cols="1a,3a"]
|===
| Modus | Beschreibung 


 a| 
Global (Standard)
 a| 
Clients können über die IP-Adresse eines beliebigen Gateway-Node oder Admin-Node, die virtuelle IP-Adresse (VIP) einer beliebigen HA-Gruppe in einem beliebigen Netzwerk oder einen entsprechenden FQDN auf den Endpunkt zugreifen.

Verwenden Sie die *Global*-Einstellung (Standard), es sei denn, Sie müssen die Zugriffsmöglichkeiten dieses Endpunkts einschränken.



 a| 
Virtuelle IPs von HA-Gruppen
 a| 
Clients müssen eine virtuelle IP-Adresse (oder einen entsprechenden FQDN) einer HA-Gruppe verwenden, um auf diesen Endpunkt zuzugreifen.

Endpunkte mit diesem Bindungsmodus können alle dieselbe Portnummer verwenden, solange sich die für die Endpunkte ausgewählten HA-Gruppen nicht überlappen.



 a| 
Node-Schnittstellen
 a| 
Clients müssen die IP-Adressen (oder entsprechende FQDNs) der ausgewählten Knotenschnittstellen verwenden, um auf diesen Endpunkt zuzugreifen.



 a| 
Node-Typ
 a| 
Basierend auf dem von Ihnen ausgewählten Knotentyp müssen Clients entweder die IP-Adresse (oder den entsprechenden FQDN) eines beliebigen Admin-Knotens oder die IP-Adresse (oder den entsprechenden FQDN) eines beliebigen Gateway-Knotens verwenden, um auf diesen Endpunkt zuzugreifen.

|===
. Wählen Sie für den Schritt *Tenant Access* eine der folgenden Optionen aus:
+
[cols="1a,2a"]
|===
| Feld | Beschreibung 


 a| 
Alle Mandanten zulassen (Standard)
 a| 
Alle Mandantenkonten können diesen Endpunkt verwenden, um auf ihre Buckets zuzugreifen.

*Alle Mandanten zulassen* ist fast immer die geeignete Option für den für FabricPool verwendeten Load Balancer Endpunkt.

Sie müssen diese Option auswählen, wenn Sie noch keine Mandantenkonten erstellt haben.



 a| 
Ausgewählte Mandanten zulassen
 a| 
Nur die ausgewählten Mandantenkonten können diesen Endpunkt für den Zugriff auf ihre Buckets verwenden.



 a| 
Ausgewählte Mandanten blockieren
 a| 
Die ausgewählten Mandantenkonten können diesen Endpunkt nicht für den Zugriff auf ihre Buckets verwenden. Dieser Endpunkt kann von allen anderen Mandanten verwendet werden.

|===
. Wählen Sie für den Schritt *Zertifikat anhängen* eine der folgenden Optionen aus:
+
[cols="1a,2a"]
|===
| Feld | Beschreibung 


 a| 
Zertifikat hochladen (empfohlen)
 a| 
Verwenden Sie diese Option, um ein CA-signiertes Serverzertifikat, einen privaten Zertifikatschlüssel und ein optionales CA-Paket hochzuladen.



 a| 
Zertifikat wird generiert
 a| 
Verwenden Sie diese Option, um ein selbstsigniertes Zertifikat zu generieren. Einzelheiten dazu finden Sie unterlink:../admin/configuring-load-balancer-endpoints.html["Konfigurieren von Load Balancer-Endpunkten"].



 a| 
StorageGRID S3-Zertifikat verwenden
 a| 
Diese Option ist nur verfügbar, wenn Sie bereits eine benutzerdefinierte Version des globalen StorageGRID-Zertifikats hochgeladen oder generiert haben. Weitere Informationen finden Sie unter link:../admin/configuring-custom-server-certificate-for-storage-node.html["Konfigurieren Sie S3-API-Zertifikate"] .

|===
. Wählen Sie *Erstellen*.



NOTE: Änderungen an einem Endpunktzertifikat können bis zu 15 Minuten dauern, bis sie auf alle Knoten angewendet werden können.
