---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, StorageGRID, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure coding, replication, cloud storage pool, glacier 
summary: Sie können diese einfache Beispielrichtlinie als Ausgangspunkt für Ihre eigenen ILM-Regeln und -Richtlinien verwenden. 
---
= StorageGRID ILM für FabricPool-Daten konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können diese einfache Beispielrichtlinie als Ausgangspunkt für Ihre eigenen ILM-Regeln und -Richtlinien verwenden.

Das Beispiel geht davon aus, dass Sie die ILM-Regeln und eine ILM-Richtlinie für ein StorageGRID System mit vier Storage-Nodes in einem einzelnen Datacenter in Denver, Colorado, entwerfen. Die FabricPool-Daten in diesem Beispiel verwenden einen Bucket mit dem Namen `fabricpool-bucket`.


CAUTION: Die folgenden ILM-Regeln und -Richtlinien sind nur Beispiele. Es gibt viele Möglichkeiten zur Konfiguration von ILM-Regeln. Simulieren Sie vor der Aktivierung einer neuen Richtlinie, um zu bestätigen, dass sie so funktioniert, wie sie zum Schutz von Inhalten vor Verlust vorgesehen ist. Weitere Informationen finden Sie unter link:../ilm/index.html["Objektmanagement mit ILM"].


CAUTION: Verwenden Sie zur Vermeidung von Datenverlust keine ILM-Regel, die ausläuft oder die Cloud-Tiering-Daten von FabricPool löscht. Setzen Sie die Aufbewahrungsfrist auf *Forever*, um sicherzustellen, dass FabricPool-Objekte nicht durch StorageGRID ILM gelöscht werden.

.Bevor Sie beginnen
* Sie haben die überprüftlink:best-practices-ilm.html["Best Practices für die Verwendung von ILM mit FabricPool-Daten"].
* Sie sind im Grid Manager mit einem angemeldetlink:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben die link:../admin/admin-group-permissions.html["ILM oder Root-Zugriffsberechtigung"].
* Wenn Sie von einer StorageGRID -Version vor 11.7 auf StorageGRID 12.0 aktualisiert haben, haben Sie den zu verwendenden Speicherpool konfiguriert.  Im Allgemeinen sollten Sie für jede StorageGRID -Site, die Sie zum Speichern von Daten verwenden, einen Speicherpool erstellen.  (Ab Version 11.7 werden Speicherpools automatisch für jeden Standort erstellt.)
+

NOTE: Diese Voraussetzung gilt nicht, wenn Sie zunächst StorageGRID 11.7 oder 11.8 installiert haben. Wenn Sie eine dieser Versionen zuerst installieren, werden Speicherpools automatisch für jeden Standort erstellt.



.Schritte
. Erstellen Sie eine ILM-Regel, die nur auf die Daten in zutrifft `fabricpool-bucket`. Diese Beispielregel erstellt Kopien, die nach der Löschung codiert wurden.
+
[cols="1a,2a"]
|===
| Regeldefinition | Beispielwert 


 a| 
Regelname
 a| 
2 + 1 Erasure Coding für FabricPool-Daten



 a| 
Bucket-Name
 a| 
`fabricpool-bucket`

Sie könnten auch nach dem FabricPool-Mandantenkonto filtern.



 a| 
Erweiterte Filter
 a| 
Objektgröße größer als 0.2 MB.

*Hinweis:* FabricPool schreibt nur 4 MB Objekte, aber Sie müssen einen Objektgrößenfilter hinzufügen, da diese Regel Erasure Coding verwendet.



 a| 
Referenzzeit
 a| 
Aufnahmezeit



 a| 
Zeitraum und Platzierungen
 a| 
Ab Tag 0 für immer speichern

Speichern Sie Objekte durch Erasure Coding mit dem 2+1-EC-Schema in Denver und bewahren Sie diese Objekte für immer in StorageGRID auf.


CAUTION: Verwenden Sie zur Vermeidung von Datenverlust keine ILM-Regel, die ausläuft oder die Cloud-Tiering-Daten von FabricPool löscht.



 a| 
Aufnahmeverhalten
 a| 
Ausgeglichen

|===
. Erstellen Sie eine standardmäßige ILM-Regel, die zwei replizierte Kopien von Objekten erstellt, die der ersten Regel nicht zugeordnet sind. Wählen Sie keinen einfachen Filter (Mandantenkonto oder Bucket-Name) oder keine erweiterten Filter aus.
+
[cols="1a,2a"]
|===
| Regeldefinition | Beispielwert 


 a| 
Regelname
 a| 
Zwei replizierte Kopien



 a| 
Bucket-Name
 a| 
_None_



 a| 
Erweiterte Filter
 a| 
_None_



 a| 
Referenzzeit
 a| 
Aufnahmezeit



 a| 
Zeitraum und Platzierungen
 a| 
Ab Tag 0 für immer speichern

Speichern Sie Objekte, indem Sie 2 Kopien in Denver replizieren.



 a| 
Aufnahmeverhalten
 a| 
Ausgeglichen

|===
. Erstellen Sie eine ILM-Richtlinie und wählen Sie die beiden Regeln aus. Da die Replikationsregel keine Filter verwendet, kann es sich um die Standardregel (letzte) für die Richtlinie handelt.
. Aufnahme von Testobjekten in das Raster
. Simulieren Sie die Richtlinie mit den Testobjekten, um das Verhalten zu überprüfen.
. Aktivieren Sie die Richtlinie.


Wenn diese Richtlinie aktiviert ist, speichert StorageGRID Objektdaten wie folgt:

* Die Daten-Tiering von FabricPool in `fabricpool-bucket` wird mit dem Erasure Coding-Schema 2+1 codiert. Zwei Datenfragmente und ein Paritätsfragment werden auf drei verschiedenen Storage Nodes platziert.
* Alle Objekte in allen anderen Buckets werden repliziert. Es werden zwei Kopien erstellt und auf zwei verschiedenen Speicherknoten platziert.
* Die Kopien werden für immer in StorageGRID aufbewahrt. StorageGRID ILM wird diese Objekte nicht löschen.

